### ISSUE TITLE
Export Connection Profile does not replace existing file

### ISSUE THREAD

**Issue by ericmvaughn** [IBM-Blockchain/blockchain-vscode-extension#1001]
## Description
When exporting a connection profile to the same location as an existing file you get a pop-up warning you that file already exists and gives you the option to cancel or replace the file.  When I select replace everything appears to work and you get a success message back from IBP but on closer inspection the file has not changed.

## Expected Behavior
The previous file should be overwritten with the new connection profile.

## Actual Behavior
The old file was unchanged.

## Steps to Reproduce

1.  Place and old file in the location you want the new connection profile to be
2.  Run the IBP Export Connection Profile command
3. Use the pop-up window to navigate to the file in step one and hit the export button
4. You'll get a pop-up warning that the file already exists, select the export option
5. Look at the file and see if it has changed

## Existing issues
Didn't find any matching issues.

## Log File

[5/24/2019 12:35:38 PM] [INFO] exportConnectionProfileCommand
[5/24/2019 12:35:57 PM] [SUCCESS] Successfully exported connection profile to /Users/eric/Documents/projects/poe-sample/config/network/connection.json

## Your Environment

* IBM Blockchain Platform Extension Version: 1.0.1
* Visual Studio Code version: 1.34.0
* Environment name and version (e.g. Node.js v8.12.0, npm v6.4.1): Node v8.12.0, npm v6.4.1
* Operating System and version:  MacOS 10.13.6 (17G7024)
* Link to your project: https://github.com/blocledger/poe-sample

**Comment by heatherlp** [comment]
Yep, this is completely correct - I'll fix it today

**Comment by heatherlp** [comment]
Fixed under #1006 - this will be in the next release

**Comment by ericmvaughn** [comment]
Thanks so much for quick resolution to this issue
