### ISSUE TITLE
Connect to Cloud: Refactor to support multiple peers, channels, orgs etc 

### ISSUE THREAD

**Issue by heatherlp** [IBM-Blockchain/blockchain-vscode-extension#1008]
And possibly multiple CAs

things already work
- [x] choosing a single peer to install on when have multiple
- [x] choosing a single channel to instantiate on when have multiple channels but single peer

list of things todo
- [x] enable selecting multiple peers at once to install on
- [x] stop same installed contract appearing multiple times in the instantiate list
- [x] enroll identities with remote CA
- [ ] export connection profile
- [x] instantiate with all peers installed on

things not doing for now
- specify endorsement policy #430 
- remote debug 

questions
- [x] signing of instantiate transaction peer is done by the first peer is this ok? yes this is ok
- [x] querying instantiated contracts is always done with the first peer, is this correct? yes thats ok
- [x] channel events uses first peer, is this correct? yes because they all get the event
- [x] getting channel orderer uses first peer, is this correct? yes this is ok

**Comment by cazfletch** [comment]
closing and creating a new issue for exporting the connection profile as it can't be done yet until we allow you to create a gateway from a devops connection
