### ISSUE TITLE
Javascript Test Runner has been deprecated

### ISSUE THREAD

**Issue by heatherlp** [IBM-Blockchain/blockchain-vscode-extension#1026]
We need to find another to bundle with - this should be fixed for the next release

Alternatives to explore:
https://marketplace.visualstudio.com/items?itemName=nilobarp.javascript-test-runner
https://marketplace.visualstudio.com/items?itemName=hbenl.vscode-mocha-test-adapter

**Comment by Jakeeyturner** [comment]
Decision made was to use https://marketplace.visualstudio.com/items?itemName=oshri6688.javascript-test-runner
