### ISSUE TITLE
Tutorial words need updates for no longer selecting single peer, channel etc

### ISSUE THREAD

**Issue by heatherlp** [IBM-Blockchain/blockchain-vscode-extension#1048]
Since v1.0.2 - you no longer get asked for what peer to install on (for example) because currently there is only one, there are some null steps now in the tutorials - these need updating. 

e.g. Step 5.2 in tutorial 1

**Comment by cazfletch** [comment]
Also need to update tutorial 2 step 1 as not free beta anymore
