### ISSUE TITLE
Spinner on channel whilst contract is starting, instead of spinner on contract

### ISSUE THREAD

**Issue by sstone1** [IBM-Blockchain/blockchain-vscode-extension#1061]
When you connect to a gateway and try to expand a channel that has one or more contracts deployed that are not started, the channel has a spinning icon and will not expand until all of the contracts are started. The spinner should really be on the contracts, not on the channel, as it would be a lot more obvious what is going on (and allow you to interact with the contracts that are started).

**Comment by heatherlp** [comment]
Done in #1129 so closing
