### ISSUE TITLE
Eclipse Che compatibility

### ISSUE THREAD

**Issue by sstone1** [IBM-Blockchain/blockchain-vscode-extension#1071]
Eclipse Che, along with Eclipse Theia, allow users to run our VS Code extension within a web browser. This epic will track the work required to support this configuration.

### Extension issues

- The activation events cannot be changed after first activation
- gRPC is constantly rebuilt every time you open or refresh the browser
- Extension directory cannot be stored in the home directory
- Console logging spam makes it difficult to diagnose issues
https://github.com/IBM-Blockchain/blockchain-vscode-extension/issues/1072
- Local Fabric runtime needs a _lot_ of work

### Known Eclipse Che or Eclipse Theia issues

- No action buttons available in the packages/ops/gateways/wallets views:
https://github.com/theia-ide/theia/issues/4174
- Welcome page and tutorials do not render correctly:
https://github.com/theia-ide/theia/issues/5518
- No homepage button in the top right of an editor:
https://github.com/theia-ide/theia/issues/5515
- Extension fails to activate after refreshing the browser:
https://github.com/theia-ide/theia/issues/5514
- No IBM Blockchain logo on the left bar
https://github.com/eclipse/che-theia/issues/277

**Comment by cazfletch** [comment]
done so closing
