### ISSUE TITLE
Cannot create package - invalid package.json name

### ISSUE THREAD

**Issue by rolivieri** [IBM-Blockchain/blockchain-vscode-extension#1076]
For a TypeScript chaincode component, we are getting the following error when trying to package it: 

`"Invalid package.json name. Name can only include alphanumeric, "_" and "-" characters.”`

However, the package name is valid because it needs to have a scope... hence, the need to have the `@` symbol in the name, as documented in the npm [docs](https://docs.npmjs.com/misc/scope). For some reason, the packaging action fails when the `@` symbol is present in the package name (e.g.  `"name": "@scope/cc-name"`)

Is this a known limitation that will be addressed soon? Not sure if the problem is in the fabric tooling itself or in the VSCode extension.
## Steps to Reproduce
1. Just create a TypeScript of JS chaincode component and use a scope in the package name in the `package.json` file -> `"name": "@scope/cc-name"`
2. Then try to package it in VSCode.

## Your Environment
* IBM Blockchain Platform Extension Version: 1.0.3
* Visual Studio Code version: 1.35.1
* Environment name and version (e.g. Node.js v8.12.0, npm v6.4.1): node v8.9.4, npm 6.9.0
* Operating System and version: macOS (Mojave 10.14.5)

**Comment by Jakeeyturner** [comment]
Hi @rolivieri,

When you package a smart contract, due to the Fabric packaging API, the name can only include alphanumeric, "_" and "-" characters.
However, with npm packages, you're completely correct that the name `@scope/cc-name` would be valid.

I think we should change the error message to make that clearer.
Perhaps something like: `Invalid package name. Name can only include alphanumeric, "_" and "-" characters` would be better.

**Comment by rolivieri** [comment]
@Jakeeyturner Thanks for following up. Not sure I understand the solution other than asking the the developer to manually remove the scope from the package name in the `package.json` file, which is not quite the solution I was hoping for. : )

 The only way I was able to package the chaincode component was to manually edit `package.json` and change the name entry from `"name": "@scope/mycc"` to `"name": "mycc"`. 

If the limitation for not allowing `@` exists in the Fabric packaging API (as opposed to the vscode extension), could not the extension then get the package name from the `package.json` file, parse it to remove the scope, and then feed the parsed name to the Fabric packaging API? 

Or did I miss something?

**Comment by cazfletch** [comment]
@rolivieri I think the solution is to raise an issue with the packaging api. Closing this issue as it isn't a problem with the extension. If the scope problem is fixed in the api then we will allow it in the extension

**Comment by rolivieri** [comment]
@cazfletch Got it. Where can we open an issue against the packaging api? Can you points us to the right place for doing so?

**Comment by cazfletch** [comment]
Reopening as we should parse the package name from the `package.json`.

**Comment by cazfletch** [comment]
done so closing
