### ISSUE TITLE
Cannot debug chaincode created not using vscode extension

### ISSUE THREAD

**Issue by rolivieri** [IBM-Blockchain/blockchain-vscode-extension#1079]
There are probably two related but separate issues in the description below.

We wrote a chaincode component in TypeScript from scratch, meaning we did **not** use the capability provided by the vscode extension to generate the scaffolding code.

Though we are able to use the vscode extension to package, install, and instantiate this chaincode component, we cannot debug it. If you go to the debug panel in vscode, you do not get the `Debug Smart Contract` option. Instead, you see the `No Configurations` option and the option to add a new configuration. Choosing the option for adding a new configuration offers then several options for Fabric smart contracts. However, choosing the option for Fabric node generates a `launch.json` file that does not yield the desired outcome... meaning, you cannot still debug the chaincode component.

We then decided to copy the `launch.json` file that was created in another chaincode project (one that was generated using the vscode extension) and brought that `launch.json` file over to the chaincode project that was written from scratch (please note that this chaincode component happens to use the low level chaincode api). After that, then we can see `Debug Smart Contract` configuration/option in the debugger view... but starting it fails because it attempts to find `fabric-contract-api` module. Therefore, it looks like we need a different debug configuration that does not depend on the `fabric-contract-api` module so that we can debug chaincode written using the low level api.

## Your Environment
* IBM Blockchain Platform Extension Version: 1.0.3
* Visual Studio Code version: 1.35.1
* Environment name and version (e.g. Node.js v8.12.0, npm v6.4.1): node v8.9.4, npm 6.9.0
* Operating System and version: macOS (Mojave 10.14.5)

**Comment by heatherlp** [comment]
Hi @rolivieri, I'm reading that you have two problems

1) adding your own launch.json configuration doesn't work. I've defined a new typescript configuration which adds the `preLaunchTask` and `outFiles` attributes, #1101 - do you think that would solve this problem?
2) debug fails because it can't find `fabric-contract-api`, which I'll tackle next :)

**Comment by lehors** [comment]
I think the first problem is that the launch.json file that gets automatically created doesn't work if one starts with just adding an existing contract folder to the workspace and starting the debugger, as opposed to creating a whole project from the extension via "Create a smart contract project".

**Comment by heatherlp** [comment]
Ok, update:

1. #1101 wasn't right - as I couldn't get breakpoints to hit, I need to investigate that further. Can you tell me why adding a configuration yourself didn't work - what did you see happen?
2. I've figured out this one, after recreating it. You need to add the following attribute to the configuration: `"program": "${workspaceFolder}/<path_to_start.js>/start.js"` where `start.js` is the file that contains the `Shim.start(new Chaincode());` line. This stopped me from seeing the fabric-contract-api problem, so I'm going to update the readMe to reflect this. Let me know how you get on

**Comment by heatherlp** [comment]
Unassigning - I think we need more information from @rolivieri

**Comment by cazfletch** [comment]
@rolivieri can you try this with the latest version of the extension and say if this is still an issue please

**Comment by cazfletch** [comment]
closing as no response

**Comment by rolivieri** [comment]
@cazfletch @heatherlp The email notifications to my inbox got lost in the high number of emails from GHE... unfortunately, today using the latest version of the extension, we are still seeing the first issue we reported here back in June:

```
We wrote a chaincode component in TypeScript from scratch, meaning we did not use the capability provided by the vscode extension to generate the scaffolding code.

Though we are able to use the vscode extension to package, install, and instantiate this chaincode component we implemeted from scratch, we cannot debug it. If you go to the debug panel in vscode, you do not get the Debug Smart Contract option. Instead, you see the No Configurations option and the option to add a new configuration. Choosing the option for adding a new configuration offers then several options for Fabric smart contracts. However, choosing the option for Fabric node generates a launch.json file that does not yield the desired outcome... meaning, you cannot still debug the chaincode component.
```

Can the vscode extension generate the corresponding launch.json file? Having to copy the launch.json file that was created in another chaincode project (one that was generated using the vscode extension) and bringing it over is not a great user experience.
