### ISSUE TITLE
Update the Welcome page so users are more likely to find what they need on it

### ISSUE THREAD

**Issue by cazfletch** [IBM-Blockchain/blockchain-vscode-extension#1080]
Some suggestions we've received:

- Add a "magic link" from the readme to the tutorials (i.e. people have been reading the ReadMe, seeing the mention of tutorials and then pinging us to ask where they are - clearly folks are finding the mention of them in the ReadMe, but not finding the tutorials themselves! So, when we mention them in the readme, we could construct a link that opens VS Code, installs the extension, and launches the first tutorial to get folks started perhaps)

- Improve the "Welcome" screen so it's less likely to be insta-closed by new users! Too many people seem unaware that it exists, and the few times we've asked follow-up questions, it turns out they think "this is just one of those release-notes things that I never bother to read, I'll close it and then get started!". We've certainly observed this with some folks from the Garage that Jake got to see using the extension.

**Comment by EdMoffatt** [comment]
Did a bit of playing around with the "welcome screen" today - not sure if it's any good, just posting it here so I don't forget I did it and see if anyone has thoughts :)

![image](https://user-images.githubusercontent.com/7454304/60736417-cf8e8480-9f4e-11e9-8714-bc218ba7105e.png)

**Comment by EdMoffatt** [comment]
Pulling in some of the feedback Jake heard at the Garage related to this, in preparation for assigning Charlotte this work!

> In terms of the tutorials, they weren't even aware that they existed which could be due to a couple of reasons. In our GitHub and Marketplace README, we don't make a big deal about them which we should! Imagine finding the GitHub README and pressing a button which says 'View Tutorials'. This could use a magic link, which if the extension is installed, opens up the extension to the Tutorial Gallery. We could even magic link to install the extension, assuming they have VS Code installed.
Another reason they weren't aware of the tutorials is that they think some of the Home page is too passive.  When the Home page opens, they just think it's another splash screen (like the VS Code Welcome screen) which they close instinctively. They made the comments that words like 'Welcome' are a reason for habit. One suggestion was to change some of the language like 'Get Started' to 'Tutorials', and even to have the action in the panel in the form of a large and eye-catching button.

**Comment by EdMoffatt** [comment]
One further quick exploration whilst I happened to have the Sketch file open...
![image](https://user-images.githubusercontent.com/7454304/60893774-70d05000-a259-11e9-8c46-d00b5ce64c45.png)

**Comment by EdMoffatt** [comment]
One further quick exploration whilst I happened to have the Sketch file open...
![image](https://user-images.githubusercontent.com/7454304/60893925-aaa15680-a259-11e9-9eb6-2d17c4c0a74e.png)

**Comment by EdMoffatt** [comment]
Extra re-affirmation of some of the feedback from Anthony and Matthew's follow-up Garage visit today:

"some of the wording on homepage could be more directive, or at least consistent to avoid read-through, whereby users ignore valuable content due to "weak" words - - e.g. replace Welcome! with  Smart contract development,  replace Get Started with Tutorials, keep Samples, keep Help and Support.  All minor stuff, but helps users see what's there."

**Comment by cazfletch** [comment]
We also had the feedback from the garage that you should be able to find the tutorials from google

**Comment by EdMoffatt** [comment]
TODO: Identify any places where we talk about "you should follow this tutorial in VSCode", which would be places that we could look to pick the massively-overly-grandly-named "magic links".

I suspect some good places to look are:

- Horea's tutorial on IBM Developer that is a copy of tutorial 1 in the dev tools
- The ReadMe?
- Other tutorials cross-referencing each other?
- Other places???

A good first step would be to identify all the places it would be useful to make use of these "magic links", and where they would link to (e.g. the tutorials gallery page, or an individual tutorial etc.).

@Charlotte8699 - can you have a dig around and compile such a list for us, please?

**Comment by Charlotte8699** [comment]
An update on the welcome page
Very nearly finished, waiting on the creation of an SDK icon. 
Video will be planned and made in the coming weeks. 

<img width="1680" alt="Screenshot 2019-08-06 at 14 46 43" src="https://user-images.githubusercontent.com/52786879/62545206-2e4e6300-b859-11e9-806d-9d64f1673a3d.png">
<img width="1680" alt="Screenshot 2019-08-06 at 14 46 32" src="https://user-images.githubusercontent.com/52786879/62545212-31495380-b859-11e9-8f1e-36261ddd1bdc.png">

**Comment by Charlotte8699** [comment]
Magic Links - hopefully i'm on the right lines with this but these are the areas i've found that could benefit from a link to the tutorials.

1. Read the documentation - "access our Beginner Tutorial"
General link to tutorials in introduction
Throughout, it states what you can do with the extension - reference relevant tutorial for carrying these tasks out.

2. E-book
Could introduce e-book with something along the lines of "should you want to learn more outside the tutorials, download this e-book" with the tutorials highlighted as a link

3. IBM Cloud/ IBM Cloud private link
Although this has been removed from the tutorial page, when this page appears from other sources, the link on said page should be made clickable. Presently, the link given under "getting started" is not active 

4. Extension install page
Same as point 1 above ^^^

5. Link on Google so the tutorials can be searched for in a search engine?

6. All tutorials could start/end with a link to the previous/next tutorial. If there are any critical steps/recurring issues with users that are solved by other tutorials, these can be linked throughout.

**Comment by cazfletch** [comment]
Another place we could put a magic link is in the IBP docs, i had a call with Pam and Nick earlier and they liked the idea

**Comment by EdMoffatt** [comment]
Created #1258 to separately track the "magic links" work, and leave this one as just being the Welcome page updates

**Comment by Charlotte8699** [comment]
Final design for the welcome page, will need to find out from @Jakeeyturner  what he needs regarding how the page will minimise and any other important page details for the hand over.

<img width="1313" alt="Screenshot 2019-09-30 at 10 27 48" src="https://user-images.githubusercontent.com/52786879/65866615-049f4d00-e36d-11e9-9762-c34f2e081196.png">

**Comment by EdMoffatt** [comment]
Closing as part of a clean-out for Welcome+Tutorials updates. Will be replaced with new issues.
