### ISSUE TITLE
as a user i can associate an identity with a node

### ISSUE THREAD

**Issue by cazfletch** [IBM-Blockchain/blockchain-vscode-extension#1088]

**Comment by EdMoffatt** [comment]
Done by clicking peers during the setup phase:

![image](https://user-images.githubusercontent.com/7454304/60734302-66574300-9f47-11e9-8739-3ec3f32594f2.png)

Then they are asked a set of questions:
![image](https://user-images.githubusercontent.com/7454304/60734657-8d624480-9f48-11e9-8939-2151656dd03d.png)

(and then if there are other nodes yet to associate the ID for, #1089 applies!)

**Comment by cazfletch** [comment]
done so closing
