### ISSUE TITLE
as a user i can associate an identity with multiple nodes

### ISSUE THREAD

**Issue by cazfletch** [IBM-Blockchain/blockchain-vscode-extension#1089]
when associating identities with nodes you should be able to associate other nodes with the same identity

**Comment by EdMoffatt** [comment]
Here's the flow. If there are multiple nodes to associate IDs for, we'll ask whether to use the same ID for other nodes after it's associated with one:

![image](https://user-images.githubusercontent.com/7454304/60734269-4d4e9200-9f47-11e9-811b-3d061e5f3ec9.png)
