### ISSUE TITLE
as a user i can skip associating an identity and do it later

### ISSUE THREAD

**Issue by cazfletch** [IBM-Blockchain/blockchain-vscode-extension#1090]

**Comment by EdMoffatt** [comment]
Achieved by hitting the "skip this step" link during setup:

![image](https://user-images.githubusercontent.com/7454304/60734227-24c69800-9f47-11e9-9433-944f20b86539.png)

**Comment by cazfletch** [comment]
closing as you can always delete nodes you don't want to assign
