### ISSUE TITLE
as a user i can associate a wallet with a environment

### ISSUE THREAD

**Issue by cazfletch** [IBM-Blockchain/blockchain-vscode-extension#1094]

**Comment by EdMoffatt** [comment]
Accessed via right-click on the environment, like so:
![image](https://user-images.githubusercontent.com/7454304/60733930-33607f80-9f46-11e9-9ba8-f27dda24b672.png)

We use this to skip a question during the setup phase (associating admin IDs with peers) the first time an Environment is used:
![image](https://user-images.githubusercontent.com/7454304/60733995-58ed8900-9f46-11e9-9697-4c4099bfd1bb.png)

**Comment by cazfletch** [comment]
closing as this doesn't make sense anymore
