### ISSUE TITLE
as a user my fabric is migrated to the new environment

### ISSUE THREAD

**Issue by cazfletch** [IBM-Blockchain/blockchain-vscode-extension#1103]

**Comment by EdMoffatt** [comment]
Can't figure out what this one means :)

Are we talking about moving "Local Fabric Ops" content across to live under "Local Fabric" in the new "Fabric Environments" panel?

Or possibly about exacting Fabric samples that include a runtime config providing the node JSON files that would be needed to add them as an Environment in VS Code?

**Comment by cazfletch** [comment]
This one is for migrating the local fabric runtime to the new environments stuff as where the config for it is has moved

**Comment by cazfletch** [comment]
done so closing
