### ISSUE TITLE
A developer should not be able to use a HSM configuration

### ISSUE THREAD

**Issue by jt-nti** [IBM-Blockchain/blockchain-vscode-extension#111]
The Fabric network capabilities integrated with the vscode extension are meant for simple testing and debugging, and are not intended to support production use. Hardware security modules are beyond the scope of a simple development environment and should therefore not be supported.

There are two related Fabric issues:

- [FABN-626 make pkcs11 dependency optional](https://jira.hyperledger.org/browse/FABN-626) this is a native module so it won't work on Windows currently, see also #72 
- [FABN-928 HSM connection profile section](https://jira.hyperledger.org/browse/FABN-928) would allow the vscode extension to notify users that HSM is not supported

**Comment by caroline-church** [comment]
blocked until HSM not supported thing has gone in

**Comment by caroline-church** [comment]
closing
