### ISSUE TITLE
Local Fabric 

### ISSUE THREAD

**Issue by pancaldi** [IBM-Blockchain/blockchain-vscode-extension#1111]
Issue Type: <b>Bug</b>

Hi,
I experienced a Local Fabric runtime stop by getting the following error:
Failed to start local_fabric: Failed to execute command "cmd" with arguments "/c, start.cmd" return code 1

How can I solve this error?
Thanks,
Jacques

Extension version: 1.0.3
VS Code version: Code 1.35.1 (c7d83e57cd18f18026a8162d042843bda1bcf21f, 2019-06-12T14:30:02.622Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i3-8145U CPU @ 2.10GHz (4 x 2304)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.82GB (2.10GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>

**Comment by cazfletch** [comment]
Hi where there any other errors in the log or any other information?

**Comment by pancaldi** [comment]
Hi,There were no other errors. This was the first error I encountered as I was following the tutorial. I need to get over this error in order to continue. Thanks Sent from my T-Mobile 4G LTE Device
-------- Original message --------From: Caroline Fletcher <notifications@github.com> Date: 7/2/19  04:07  (GMT-05:00) To: IBM-Blockchain/blockchain-vscode-extension <blockchain-vscode-extension@noreply.github.com> Cc: Jacques Bikoundou <jaqo59@gmail.com>, State change <state_change@noreply.github.com> Subject: Re: [IBM-Blockchain/blockchain-vscode-extension] Local Fabric  (#1111) Hi where there any other errors in the log or any other information?

—You are receiving this because you modified the open/close state.Reply to this email directly, view it on GitHub, or mute the thread.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/IBM-Blockchain/blockchain-vscode-extension/issues/1111?email_source=notifications\u0026email_token=AGT6O2HDT45BXQWKTRJNIN3P5MECVA5CNFSM4H4WWM2KYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGODZAOEGY#issuecomment-507568667",
"url": "https://github.com/IBM-Blockchain/blockchain-vscode-extension/issues/1111?email_source=notifications\u0026email_token=AGT6O2HDT45BXQWKTRJNIN3P5MECVA5CNFSM4H4WWM2KYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGODZAOEGY#issuecomment-507568667",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by cazfletch** [comment]
Can you send all the output from the blockchain output channel please

**Comment by pancaldi** [comment]
Attached is the output screen!Sent from my T-Mobile 4G LTE Device
-------- Original message --------From: Caroline Fletcher <notifications@github.com> Date: 7/2/19  11:12  (GMT-05:00) To: IBM-Blockchain/blockchain-vscode-extension <blockchain-vscode-extension@noreply.github.com> Cc: Jacques Bikoundou <jaqo59@gmail.com>, State change <state_change@noreply.github.com> Subject: Re: [IBM-Blockchain/blockchain-vscode-extension] Local Fabric  (#1111) Can you send all the output from the blockchain output channel please

—You are receiving this because you modified the open/close state.Reply to this email directly, view it on GitHub, or mute the thread.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/IBM-Blockchain/blockchain-vscode-extension/issues/1111?email_source=notifications\u0026email_token=AGT6O2DNAAOQCCN6J5JXFOLP5NV7NA5CNFSM4H4WWM2KYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGODZBTLBA#issuecomment-507721092",
"url": "https://github.com/IBM-Blockchain/blockchain-vscode-extension/issues/1111?email_source=notifications\u0026email_token=AGT6O2DNAAOQCCN6J5JXFOLP5NV7NA5CNFSM4H4WWM2KYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGODZBTLBA#issuecomment-507721092",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by cazfletch** [comment]
I cant see a screen shot, i need all the logs from when the extension was activated to you trying to start the local fabric. Can you also check what files are in the <extension directory>\runtime please. The extension directory will be in your home dir\.fabric-vscode

**Comment by pancaldi** [comment]
Hi,Please check these attachments. I guess this is the info you asked?Sent from my T-Mobile 4G LTE Device
-------- Original message --------From: Caroline Fletcher <notifications@github.com> Date: 7/3/19  05:05  (GMT-05:00) To: IBM-Blockchain/blockchain-vscode-extension <blockchain-vscode-extension@noreply.github.com> Cc: Jacques Bikoundou <jaqo59@gmail.com>, State change <state_change@noreply.github.com> Subject: Re: [IBM-Blockchain/blockchain-vscode-extension] Local Fabric  (#1111) I cant see a screen shot, i need all the logs from when the extension was activated to you trying to start the local fabric. Can you also check what files are in the \runtime please. The extension directory will be in your home dir.fabric-vscode

—You are receiving this because you modified the open/close state.Reply to this email directly, view it on GitHub, or mute the thread.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/IBM-Blockchain/blockchain-vscode-extension/issues/1111?email_source=notifications\u0026email_token=AGT6O2G3TZJCAYAKR5GLMETP5RTW5A5CNFSM4H4WWM2KYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGODZDZSNA#issuecomment-508008756",
"url": "https://github.com/IBM-Blockchain/blockchain-vscode-extension/issues/1111?email_source=notifications\u0026email_token=AGT6O2G3TZJCAYAKR5GLMETP5RTW5A5CNFSM4H4WWM2KYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGODZDZSNA#issuecomment-508008756",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by sstone1** [comment]
@pancaldi you need to reply to this thread using the GitHub website, not by using email.

**Comment by juanitodur** [comment]
Hello,
I experience the same issue. When I try to run the local frabric I get the error. Here is the log file.
[blockchain vs extension logs.txt](https://github.com/IBM-Blockchain/blockchain-vscode-extension/files/3359343/blockchain.vs.extension.logs.txt)
I could create the project but I don't get to make the fabric run. I've read somewhere this could be related to the need to have docker shared drives (I am using a Windows machine) but when I try to share it I get prompted credentials, which I am not sure I own (I am an IBM employee)
![image](https://user-images.githubusercontent.com/21688815/60668500-818c5a80-9e42-11e9-9ae0-a2c662c75d9f.png)
Thanks

**Comment by pancaldi** [comment]
My local fabric ops started and ended with a set of expandable/collapsible sections (smart contracts, channels, nodes, and organizations). 
But there's an error at the end stating: identity 'admin' isn't enrolled or loaded. How can this be dealt with?

**Comment by cazfletch** [comment]
Were there any errors previously like when the fabric was starting? Do you
see anything in the expandable sections?

**Comment by pancaldi** [comment]
Hi, they were no errors when the fabric was starting. All of the expandables have sections except the **Channels** expandable which gave the error: admin isn't enrolled or loaded.

**Comment by cazfletch** [comment]
can you try tearing down and restarting

**Comment by cazfletch** [comment]
closing as no response
