### ISSUE TITLE
Investigate TreeViewSelectionChangeEvent in vscode api

### ISSUE THREAD

**Issue by heatherlp** [IBM-Blockchain/blockchain-vscode-extension#1119]
Noticed this: https://code.visualstudio.com/api/references/vscode-api#TreeViewSelectionChangeEvent%3CT%3E

earlier. Will it allow us to select multiple stuff in our tree?
Needs investigation

**Comment by cazfletch** [comment]
closing as although you can select multiple you still can't use that to do an action
