### ISSUE TITLE
When packaging a smart contract, it should exclude non necessary folders

### ISSUE THREAD

**Issue by floriancastelain** [IBM-Blockchain/blockchain-vscode-extension#1125]
When packaging a smart contract, not necessary folders are included, increasing the size of the .cds archive.

## Description

When building a smart contract, the first cds file was 2 kb.

When updating my code, rebuilding it, the size is more than 9k times bigger. (18,925kb)
This is due to me adding folders with scripts to invoke chaincode (and thus node-modules). These folders are included into the package, but they should not:

For example:

![image](https://user-images.githubusercontent.com/10050024/60707783-cc72a480-9f0c-11e9-96d3-9fd5d37fe834.png)

## Expected Behavior
Include only required files into the package.

## Actual Behavior
Only the following are explicitly not included (``.npmignore``)
```
# don't package the connection details
local_fabric

# don't package the tests
test
functionalTests

# don't package config files
.vscode
.editorconfig
.eslintignore
.eslintrc.js
.gitignore
.npmignore
.nyc_output
coverage
```

## Steps to Reproduce

1. Add a folder with unrelated data
2. Create the package
3. Export the package
4. The non necessary data will be in the cds archive.

## Existing issues
None. But similar discussion happened on fabric rocket chat : https://chat.hyperledger.org/channel/fabric-chaincode-dev?msg=9wAmTF3vrck3EFTdH

## Your Environment
* IBM Blockchain Platform Extension Version: 1.0.4
* Visual Studio Code version: 1.36.0
* Environment name and version: Node.js v10.15.1, npm v6.9.0
* Operating System and version: Windows 10
* Link to your project: none

**Comment by cazfletch** [comment]
Hi @floriancastelain, it will exclude the node_modules directory automatically without it being added to the `.npmIgnore` file, but only the top level node_modules directory. I see from your screen shot you have a `profile` sub-directory in your smart contract. This dir should be added to the `.npmIgnore` file as it is not needed for your smart contract..

Closing this issue as not a problem with the extension. Please reopen if you find it is a problem
