### ISSUE TITLE
Not able to start the local fabric runtime : Windows 10 Enterprise password

### ISSUE THREAD

**Issue by paritoshranjan** [IBM-Blockchain/blockchain-vscode-extension#1131]
I am not able to start the local fabric runtime because the extension asks for Windows 10 system password which I am not aware of as I use IPIN to log into my IBM laptop and there is no option to use or change password.

## Description
I don't think its a defect on the VSCode extension side. However, I had a discussion with IBM IT and passwords are not allowed in their opinion on Windows 10 laptops.

Any idea on how can this be solved? If not, then Windows 10 users might not be able to use the system.

## Expected Behavior
Can the Windows IPIN be used instead of password when starting the local runtime?

## Actual Behavior
There is a windows popup saying Docker needs your windows password(which is not available for IBM Windows 10 users, AFAIK).

## Possible Fix
Use Windoes IPIN instead or some other way of authentication.

## Steps to Reproduce
Start Local Runtime on a IBM Windows 10 Enterprise system. Share C: when Windows asks then wait for the popup. The process to start the local runtime never ends. I have waited for hours.

## Existing issues
Could not find any similar issue.

## Your Environment
Windows 10
IBM Blockchain VSCode extension v1.0.4

**Comment by davidkel** [comment]
Unfortunately due to restrictions in the way your Windows 10 Enterprise setup you aren't going to be able to run the local fabric easily because docker uses SMB to share files between your windows environment and the Hyper-v linux VM it uses to run the linux containers and unless you can provide the required authority for that to happen then the local fabric won't be able to run.

**Comment by paritoshranjan** [comment]
Ok. I will open an issue with Docker Desktop(Windows) to provide a way to authenticate via IPIN also while asking for disk sharing on Windows 10 Enterprise. 

For other Windows 10 Enterprise users who might face the same problem, the solution for me was to move my development environment to a Hyper-V Linux VM in Windows 10 where the extension worked as expected. I was able to connect to local as well as IBM Blockchain platform from the extension installed on Linux VM.

**Comment by bfagalde** [comment]
HI, I have tried many options and all of them fails in somehow; Could you please provide more details about your soultion?
- I have tried Windows 10 + Docker Desktop -> I faced the same problem with enterprise user, I do not have any password set and I cannot set a new one, so docker desktop does not allow me to share drive.
- I have also tried in the same Windows 10 machine, but with a new local user, but extension is not installed.
- I have also tried ubuntu + docker -> Here the extension does not install, I get an error (already reported, regarding grpc).

Could someone who has been succesfull provide me information about versions and SO used?
- Which Linux distributions/versions?
- npm and node exact version?
- Is using Windows 10, what docker installation/version are using?

Thank you very much!!!

**Comment by paritoshranjan** [comment]
Created following issue in docker desktop to address this problem: https://github.com/docker/for-win/issues/4259

**Comment by paritoshranjan** [comment]
@bfagalde I use following script to install node, docker and other components.

```
curl -O https://hyperledger.github.io/composer/latest/prereqs-ubuntu.sh
chmod u+x prereqs-ubuntu.sh
./prereqs-ubuntu.sh
```

For Linux VM setup, I use the Quick Create Feature of Hyper V on Windows.

**Comment by cazfletch** [comment]
closing
