### ISSUE TITLE
Welcome page not opening after installing extension

### ISSUE THREAD

**Issue by Charlotte8699** [IBM-Blockchain/blockchain-vscode-extension#1141]
After installing the extension, the welcome page doesn't open automatically as it should. 

## Description
This page should open to give the user guidance on what to do next after installation. It contains important information on getting started which is not provided otherwise. 

## Expected Behavior
Automatically open the welcome page after installation.

## Actual Behavior
Instal page remains open after installation with no additional pages opening.
<img width="1680" alt="Screenshot 2019-07-12 at 11 07 46" src="https://user-images.githubusercontent.com/52786879/61121485-4075f500-a497-11e9-8371-7eacccf7580a.png">

## Steps to Reproduce
1. Install all requirements (e.g. docker, node)
2. Click install

**Comment by cazfletch** [comment]
It will only ever show the home page the first time you install it or after upgrade. If you uninstall it and reinstall it then the home page won't show.
