### ISSUE TITLE
Cannot connect to gateway without admin access to peer

### ISSUE THREAD

**Issue by sstone1** [IBM-Blockchain/blockchain-vscode-extension#1142]
If you connect to a peer, when your identity is part of an MSP that is different to the peers MSP, then you cannot view any channels on the peer. This is because we ask the peer for a list of all of its channels, and it comes back with `access denied`.

We should ignore this error if, and only if, the user has provided a list of channels in the connection profile that can be used instead.

**Comment by cazfletch** [comment]
done so closing
