### ISSUE TITLE
Failed to register chaincode

### ISSUE THREAD

**Issue by christ0089** [IBM-Blockchain/blockchain-vscode-extension#1144]
When trying to initianate a contract in the chain get the following errors from the peers. 

I must also point out that during installing the cds is never installed on the peer nor was I asked the channel I wanted to add the .cds from the vscode extension. 

Entry chaincode: name:"lscc" 
2019-07-12 17:59:07.251 UTC [endorser] callChaincode -> INFO 0ad [mychannel][0085354b] Exit chaincode: name:"lscc"  (2137ms)
2019-07-12 17:59:07.251 UTC [endorser] SimulateProposal -> ERRO 0ae [mychannel][0085354b] failed to invoke chaincode name:"lscc" , error: container exited with 1
github.com/hyperledger/fabric/core/chaincode.(*RuntimeLauncher).Launch.func1
	/opt/gopath/src/github.com/hyperledger/fabric/core/chaincode/runtime_launcher.go:63
runtime.goexit
	/opt/go/src/runtime/asm_amd64.s:1333
chaincode registration failed

**Comment by cazfletch** [comment]
Can you see the installed package in the local fabric ops view? It doesn’t ask which channel as there is only one

**Comment by paparent** [comment]
I have the same issue following the tutorial! :(

**Comment by paparent** [comment]
I was able to get it working. Was a DNS issue on my side. I followed this guide https://development.robinwinslow.uk/2016/06/23/fix-docker-networking-dns/ , putting only 8.8.8.8 in the config and it's working.

Dunno if it's the same problem, hope it helps!

**Comment by cazfletch** [comment]
@christ0089 is this still a problem?

**Comment by cazfletch** [comment]
closing as no response
