### ISSUE TITLE
Add a delete all button for packages

### ISSUE THREAD

**Issue by cazfletch** [IBM-Blockchain/blockchain-vscode-extension#1153]
Add a delete all button to the package explorer view

**Comment by cazfletch** [comment]
@EdMoffatt thoughts?

**Comment by EdMoffatt** [comment]
Yeah, this one would definitely be useful. I'd like to word it as "A user is able to delete many packages from the "SMART CONTRACTS" view at one time" :) I wonder if there's something we could do with checkboxes meaning that we could let them also achieve "I want to delete 29 of these 30 packages". Like maybe "Delete multiple packages" as an action which then gives you a command-prompt ticky-box list of your packages and asks you to select all the ones you want to delete?

Assigning this one to Charlotte to take a look at next week!

(A good use case for this btw is someone who is using debug, and ending up with many many packages cluttering up that view such that they just want to clean them out!)

**Comment by cazfletch** [comment]
We already have being able to select ones you want to delete, actually thinking about it, the selecting which ones you want to delete has a button at the top to select all. Closing this one then as not needed
