### ISSUE TITLE
Update tutorial to show short cut for instantiate

### ISSUE THREAD

**Issue by cazfletch** [IBM-Blockchain/blockchain-vscode-extension#1154]
Update first tutorial to use short cut way of instantiating and say you can also do it the long way

**Comment by EdMoffatt** [comment]
Adding this to the current sprint (I'll make the changes and submit a PR for this one!)

**Comment by EdMoffatt** [comment]
Had a chat with MGK and here's the planned set of updates to the tutorial:

1. Replace 3 step process with the "quick" method
2. Add a step that has them make a minor change to the smart contract and package.json
3. Show an upgrade, using the "slow" method

That way we show both but we don't offer 2 ways of doing the same thing (which MGK reckons is highly likely to confuse people in labs!)

**Comment by cazfletch** [comment]
done so closing
