### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by babaryasin** [IBM-Blockchain/blockchain-vscode-extension#1163]
- Issue Type: `Performance`
- Extension Name: `ibm-blockchain-platform`
- Extension Version: `1.0.3`
- OS Version: `Windows_NT x64 10.0.17134`
- VSCode version: `1.35.1`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`C:\Users\Dell\IBMBlockchain.ibm-blockchain-platform-unresponsive.cpuprofile.txt`

Find more details here: https://github.com/Microsoft/vscode/wiki/Explain:-extension-causes-high-cpu-load

**Comment by cazfletch** [comment]
@babaryasin do you have anymore info?

**Comment by cazfletch** [comment]
closing as no response
