### ISSUE TITLE
CDS file is not packaged properly if main file is not in project root

### ISSUE THREAD

**Issue by caveman7** [IBM-Blockchain/blockchain-vscode-extension#1168]
## Description

My chaincode is structured in such a way that the `main.go` (the entrypoint) is inside `cmd` subfolder, not the chaincode root folder. I used the extension to create CDS file and deploy to IBM Blockchain Platform, but I received error during instantiation. If I move `main.go` to the chaincode root folder, the instantiation succeeds.

## Expected Behavior
CDS file should be created correctly even if the project entrypoint file is not in the root folder of the chaincode

## Actual Behavior
When I deploy in IBM Blockchain Platform on Cloud, I cannot instantiate the chaincode and the `fluentd` container shows the following logs

```
2019-07-23 06:45:37.000000000 +0000 3ca364d309b0: {"log":"can't load package: package github.com/cuscal/digitalid-chaincode: no Go files in /chaincode/input/src/github.com/cuscal/digitalid-chaincode","container_id":"3ca364d309b053fb17669fb832aa41b78a6063af7d516b77fe3f1be250b0978a","container_name":"/heuristic_banach","source":"stderr"}
```

## Your Environment

* IBM Blockchain Platform Extension Version: 1.0.5
* Visual Studio Code version: 1.36.1
* Environment name and version (e.g. Node.js v8.12.0, npm v6.4.1): node 8.11.4 npm 6.9.0
* Operating System and version: MacOS Mojave
* Link to your project:

**Comment by cazfletch** [comment]
This isn't a problem with the extension, the problem is with the SDK so can you raise a jira here please https://jira.hyperledger.org/projects/FABN/issues/FABN-1314?filter=allopenissues
