### ISSUE TITLE
Connecting from Windows 10 VS Code to Fabric Runtime running on Linux

### ISSUE THREAD

**Issue by ashishchandr70** [IBM-Blockchain/blockchain-vscode-extension#1174]
I am currently working in a very severely restricted environment at a client location. We are trying to stand up a fabric runtime on a RHEL 7 Linux VM using the Hyperledger Fabric GitHub repo using their installation script https://raw.githubusercontent.com/hyperledger/fabric/master/scripts/bootstrap.sh.

We only have a command line interface to the Linux VM so our thinking was to develop on a Windows 10 machine in VS Code use the IBM Blockchain Platform extension to connect to the Linux VM. The thinking was to develop locally but package and deploy on the Linux VM.

It sounds like it should be doable but are there any instructions available, especially on how to configure the local_fabric runtime in IBM Blockchain Platform extension, to use the Linux VM's runtime, instead of spinning one up on the Windows 10 machine.

Here is some environment info:

Docker: 18.09
Docker-compose: 1.24.1
Linux: RHEL 7.6
Windows 10
IBM Blockchain Platform Extension: 1.0.5
HLF: 1.4.1

Appreciate someone taking the time to address this question.

Thank you.

**Comment by cazfletch** [comment]
You can't at the moment but we are currently working on being able to deploy to any fabric not just the local one. You can connect to another fabric and submit transactions though by adding a gateway you just need to have a connection profile and an identity

**Comment by mpraturi** [comment]
I have created a connection profile and an identity; it connects but it gives a TCP Read failure as follows:
Could not connect to gateway: Error creating channel map: 14 UNAVAILABLE: TCP Read failed. What does that mean?

**Comment by ashishchandr70** [comment]
@mpraturi probably better to start a new issue as this one has been closed. I will follow the issue you create so I can also figure this out.

**Comment by mpraturi** [comment]
Yes I did, issue #1182
