### ISSUE TITLE
Evaluate tree structure via testing

### ISSUE THREAD

**Issue by EdMoffatt** [IBM-Blockchain/blockchain-vscode-extension#118]
How usable is the tree structure?  Would it be more or less usable with different headings or icons?  Discussion around this in show 'n' tell, lets see what we get out of testing!

**Comment by EdMoffatt** [comment]
Very low-fi design:
![image](https://user-images.githubusercontent.com/7454304/47219092-bb492e00-d3a5-11e8-8fdd-cab40d4bcda4.png)

(Note the [ ]s will be icons, to match Ops Tools)

**Comment by EdMoffatt** [comment]
Adding in the latest thoughts - showing the suggestion of adding icons, and an example with some more _stuff_ in there, but basically the structure in unchanged.

![image](https://user-images.githubusercontent.com/7454304/47861813-8f896780-ddeb-11e8-94d1-86e3ef50f7bc.png)

So, I reckon we go ahead with this navigation structure, and look to add the icons in later, as whilst everyone seems to like them, we want to differentiate between installed and instantiated smart contracts, so icons need a bit more work before we finalise them and add 'em in.

**Comment by caroline-church** [comment]
created issue https://github.com/IBM-Blockchain/blockchain-vscode-extension/issues/295 for the icons so we can now work on this issue
