### ISSUE TITLE
As a user, I want to know what APIs I can use to create contracts and applications

### ISSUE THREAD

**Issue by Jakeeyturner** [IBM-Blockchain/blockchain-vscode-extension#1180]
## Description

At the moment we make it really easy for people to get started with a basic smart contract.
After this, we do not help our user's by telling them what APIs they can use to write their smart contract code.

Additionally, we do not provide help for users in writing applications.
## Expected Behavior

We should help users to find the Contract and SDK docs, enabling them to create their smart contracts and applications

## Actual Behavior

We don't help users to write contracts and application!
## Possible Fix

One suggestion would be to create a command which opens up the Contract and SDK docs.
Another suggestion could be to insert some links on the home page.

**Comment by EdMoffatt** [comment]
I reckon the plan of attack on this one should be:

1. Sort out a "homepage" for Fabric, which does a good job at pointing developers off to the various resources they'll need and then

2. Add a link to _that_ somewhere obvious like the extension homepage!

**Comment by cazfletch** [comment]
blocked until homepage updated

**Comment by cazfletch** [comment]
the homepage is updated so we should do this now

**Comment by jt-nti** [comment]
This is a very old issue and the home page does link to tutorials and the Fabric documentation
