### ISSUE TITLE
Modify initial command logging message

### ISSUE THREAD

**Issue by Jakeeyturner** [IBM-Blockchain/blockchain-vscode-extension#1186]
In our code, when we run a function the user is presented with a message such as:
`outputAdapter.log(LogType.INFO, undefined, 'addWalletIdentity');`
`outputAdapter.log(LogType.INFO, undefined, 'instantiateSmartContract');`, etc.

## Description

We log these messages for development purposes and to help figure out what problems a user has run into.
Although these messages are useful, it can sometimes be misleading from a user perspective. There has been several cases of where a user has run a command, seen this message, and then has thought that the command has completed.
In some cases the user has actually hit an error but still thinks the command has run successfully. In other cases an input/selection has appeared but the user hasn't spotted it (as they're not expecting it).

We should change something about the way we are logging to indicate that this is for dev/debugging purposes.
## Expected Behavior

"I know that this command has started"
## Actual Behavior

`outputAdapter.log(LogType.INFO, undefined, 'addWalletIdentity');`
## Possible Fix

One possible fix could be to change `LogType.INFO` to something else such as `LogType.DEV`.

Another fix could be to change `addWalletIdentity` to something like:
`Starting addWalletIdentity command`

We should have a discussion on what changes we should make in order to stop users from getting confused.

**Comment by giacomofiorindo** [comment]
I'd like to pick it up.
I think we could incorporate both the solutions.
We might have a flag to activate dev logging + clarify some of the log messages.

**Comment by Jakeeyturner** [comment]
Hey @giacomofiorindo, how is the issue going?

**Comment by giacomofiorindo** [comment]
Hi @Jakeeyturner, sorry if I reply only now, but I've been really busy with work.
Anyway, sadly vs doesn't allow you to set custom flags, it'd have been nice to have one to run the program in dev mode. So, I've started going through the entire code and improve the logging. Not sure if it's worth adding a new log flag because I wouldn't really know which messages are meant for dev and which for users.

Hopefully, I'll be able to finish soon.

TL;RL I'm improving all the system's log

**Comment by Jakeeyturner** [comment]
> Hi @Jakeeyturner, sorry if I reply only now, but I've been really busy with work.
> Anyway, sadly vs doesn't allow you to set custom flags, it'd have been nice to have one to run the program in dev mode. So, I've started going through the entire code and improve the logging. Not sure if it's worth adding a new log flag because I wouldn't really know which messages are meant for dev and which for users.
> 
> Hopefully, I'll be able to finish soon.
> 
> TL;RL I'm improving all the system's log

No worries!
Yeah it's quite annoying that it's not possible to use debug flags, and we didn't think it was worth adding another output channel to write these dev messages to.
I believe most of the dev messages are the one's outputted when we first run a command, e.g. `outputAdapter.log(LogType.INFO, undefined, 'addWalletIdentity');`
So I guess if you make a start there, we can always update other dev messages in the codebase when we come across them!

Let me know if you need any help! 😄 

Thanks!
