### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by marcosbaima** [IBM-Blockchain/blockchain-vscode-extension#1192]
- Issue Type: `Performance`
- Extension Name: `ibm-blockchain-platform`
- Extension Version: `1.0.5`
- OS Version: `Linux x64 4.19.0-5-amd64`
- VSCode version: `1.36.1`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`/home/maratona-btc/IBMBlockchain.ibm-blockchain-platform-unresponsive.cpuprofile.txt`

Find more details here: https://github.com/Microsoft/vscode/wiki/Explain:-extension-causes-high-cpu-load

**Comment by cazfletch** [comment]
@marcosbaima what were you doing when this happened?

**Comment by greg2git** [comment]
CPU went into an overdrive on my Windows 10 machine as well.

**Comment by cazfletch** [comment]
@marcosbaima, @greg2git  is this still happening?

**Comment by cazfletch** [comment]
closing as no response
