### ISSUE TITLE
As a developer I need to find more advanced tutorials

### ISSUE THREAD

**Issue by rachel-elizabeth-radulovich** [IBM-Blockchain/blockchain-vscode-extension#1196]
- Enhance experience of tutorials; add tutorials for the more advanced user 
    - Tutorials gallery page for choosing the right tutorial based on difficulty

**Comment by EdMoffatt** [comment]
Noting down some of the things that have been suggested as tutorial content...
Please add to this list, folks!

1. Once you've got a gateway to an instantiated smart contract, how do you go about writing a client app that transacts on that network?
2. How do you use the debugger to debug smart contracts? _(v1 already written by @cazfletch )_
3. How do you issue new identities and why is this useful? _(v1 already written by @toggle007 )_
4. How can I set up a CI pipeline between my dev environment and my deployment environment?
5. How do I add Fabric Environments, and what can I do once I've added them? _(v1 already written by @cazfletch )_
6. How to test your smart contracts (note: could we include perf test in this?)
7. "Teach me about Sample X" < tutorials to accompany samples that talk you through exploring them in VS Code
8. How to export a connection profile for your local_fabric (and use it as part of client app dev?)
9. Go version of the initial tutorial (check how this is scaling out now that we have multiple languages in there)
10. Something about how to take an old low-level-programming-model smart contract and package it up using the dev tools?

So, then just picking out the ones we already have in-flight, namely:
- Debugging your smart contract
- Issuing & using new identities from the local CA 
- Adding a "Fabric Environment" connection to an IBP instance
We should probably start by adding a new "topic" in to the tutorials gallery that will contain these 3, and also figure out what other tutorials we need to complete that "topic" :)
