### ISSUE TITLE
A developer of any skill level can follow tutorials to learn IBP and Fabric, with clear rewards and incentives

### ISSUE THREAD

**Issue by rachel-elizabeth-radulovich** [IBM-Blockchain/blockchain-vscode-extension#1197]
Key design experience: Enhance tutorial and samples experiences to teach developers concepts and techniques beyond ‘getting started’

- Enhance experience of users discovering relevant samples contributed by IBM or business partners. 
    - Samples gallery with search capability (search by tags, description, code language, contributor, git stars)
- Enhance experience of business partners submitting samples.
    - How does a user learn they can contribute a sample? How can a user learn what is required in submitting a sample? How can a user successfully submit a sample and also adhere to any legal bindings around supporting that sample?
- Enhance experience of tutorials; add tutorials for the more advanced user 
    - Tutorials gallery page for choosing the right tutorial based on difficulty

**Comment by EdMoffatt** [comment]
Some early designs to help with the sizing of this...

![image](https://user-images.githubusercontent.com/7454304/74723844-2c675280-5233-11ea-938a-2d1b576e1b95.png)

**Comment by cazfletch** [comment]
done so closing
