### ISSUE TITLE
A developer can install/instantiate on a channel in one action

### ISSUE THREAD

**Issue by caroline-church** [IBM-Blockchain/blockchain-vscode-extension#12]
Pick from packages in package view
Automatically do install on any peers they own
Then do the instantiate on the channel

Leave til Phase 2 - needs more thought

**Comment by EdMoffatt** [comment]
Here's what we'll do on this one:

![image](https://user-images.githubusercontent.com/7454304/47219042-9785e800-d3a5-11e8-97d1-7eaa31383a98.png)

(Note that the [ ]s represent "insert icon here"!)
