### ISSUE TITLE
Parameter names not accessible in  debug mode for Java

### ISSUE THREAD

**Issue by awjh-ibm** [IBM-Blockchain/blockchain-vscode-extension#1216]
Java allows access to the names of parameters for functions only when the -parameters flag is passed to the compiler. Currently the gradle build created by the yo generator is configured to provide this flag.

https://blog.javabien.net/2014/04/24/get-parameter-names-in-java-8/

When running a Java contract created by this generator it is possible to access the names of parameters only when instantiating the chaincode not in debug mode. When run in debug mode the values returned for parameter names are of the format arg0, arg1, ..., argN. The yo generator should therefore be updated to provide the additional required gradle and vscode settings to ensure the names are retrievable in debug mode.

Fix for me:
Option 2 from here -> https://github.com/redhat-developer/vscode-java/issues/666

**Comment by awjh-ibm** [comment]
When handling submodules that need to be compiled with the parameter option they also need in their build.gradle the solution in the link above and the build gradle of the parent and its settings.gradle need to reference these projects. Probably not an issue for VSCode but handy as a reference guide for others.

https://docs.gradle.org/current/userguide/multi_project_builds.html

**Comment by cazfletch** [comment]
we should not do option 2 we should do option 1 so that we don't have to run the build task everytime we run debug. Not sure if option 1 works though this needs to be tested
