### ISSUE TITLE
Implement new tutorials 

### ISSUE THREAD

**Issue by rachel-elizabeth-radulovich** [IBM-Blockchain/blockchain-vscode-extension#1232]
Before re-design of tutorials/samples pages, we need to implement the newly written tutorials in current page.

Notes:
* with consideration around the direction we plan to go when tutorials scale out further
* answer for what we call non introductory tutorials overall 

Design:
* Provide wire-frames for feedback 
* Provide hi-fidelity visual mock ups to be developed into vscode extension at end of sprint 

@EdMoffatt @cazfletch (does this cover what we talked about?)

**Comment by EdMoffatt** [comment]
This is a good summary! So I think in out next incremental release of the Tutorials page, we will have...

- The existing set of Introduction tutorials (3 of them, follow one after the other)
- Some new, standalone tutorials that cover the following topics:
   - Adding a new "Fabric Environment" (i.e. a connection to some or all of the nodes in a runtime - such as one created in the IBP Ops Tools for example - that allows a developer to perform install and instantiate operations in that environment without leaving VS Code)
   - Debugging a smart contract
   - Issuing a new ID with attributes for the Local Fabric environment

These 3 aren't really any particularly logical set, they're just bits that are either new functionality in the dev tools (Fabric Environment addition) OR existing functionality that users seem unaware of but would find useful (e.g. we've had folks ask to be able to do the things that debug and ID-issuing allow them to achieve, so evidently they're not aware that they can use these things to achieve their goals, hence the team have written tutorials to draw attention to them!).

**Comment by rachel-elizabeth-radulovich** [comment]
Would love your feedback on these @EdMoffatt @cazfletch 
Initial iteration of wires for this issue: 

1. Additional tutorials look with collapsed intro tutorials. Still open to naming of that second section (if we think it should be a separate section); I have a little list in the left column
![Lofi- Tutorials Gallery Copy 8](https://user-images.githubusercontent.com/37701387/62571175-bbe08180-b85e-11e9-8351-191afdca0b22.png)

2. Same as 1 with expanded into tutorials (pushes down rest of content).  I figured we could keep the same interaction (expand/collapse) for any tutorials that are hefty enough to be broken down that way, and others can be a taller tile that simply opens in another page instead of expanding at all.
![Lofi- Tutorials Gallery Copy 10](https://user-images.githubusercontent.com/37701387/62571176-bbe08180-b85e-11e9-8686-c12ba8eacfc6.png)

3. Selected and opened tutorial from the 'additional concepts' section. Same interaction also, just wanted to iterate that (for now) it won't expand or collapse, just open on click. 
![Lofi- Tutorials Gallery Copy 11](https://user-images.githubusercontent.com/37701387/62571178-bbe08180-b85e-11e9-9641-69e1fb32054e.png)

**Comment by cazfletch** [comment]
Looks good - on the naming i quite like additional concepts

**Comment by EdMoffatt** [comment]
Naming is excellent - and I like having that Additional section down below the Introduction. Going forward that means we could leave the tutorials most will want to start with at the top and start to add search/filter to the Additional Concepts if it grows large enough to need that.

The expand/collapse behaviour and defaults are also all good with me!

The one thing I spot is that our copy could do with an update, namely the paragraphs below each of the headings. Here's my bash at re-writing those...

### Introduction

**Now:** The introduction series of tutorials will teach you step by step to develop smart contracts locally, then deploy into an IBM Blockchain Platform cloud environment. You'll get to see how recommended sample code can help you learn about Hyperledger Fabric development, and how client applications transact on deployed contracts.

**Suggested:** Get started with a series of tutorials that show you how to develop a Hyperledger Fabric smart contract locally, then deploy it into an IBM Blockchain Platform cloud environment. You'll also create a gateway to the cloud environment and see how client applications submit and evaluate transactions against a ledger.

### Additional Concepts

**Now:** These tutorials expand past the basic concepts to give step by step instructions for achieving other functionalities of the VSCode Extension for the IBM Blockchain Platform.

**Suggested:** These tutorials expand past the basic concepts to give step by step instructions for achieving other common development tasks using the IBM Blockchain Platform extension for VS Code.

**Comment by rachel-elizabeth-radulovich** [comment]
I am a fan of these updated word changes ^

**Comment by cazfletch** [comment]
done so closing
