### ISSUE TITLE
Failed to start Local Fabric in VSCode

### ISSUE THREAD

**Issue by deanzaka** [IBM-Blockchain/blockchain-vscode-extension#1233]
Having the same issue with this:
https://github.com/IBM-Blockchain/blockchain-vscode-extension/issues/1127#issuecomment-518483835_

Failed to start local fabric in IBP Blockchain VSCode extension. When I tried to troubleshoot it, I found out that the peer failed to start due to a failed couchdb connection request. But, the couchdb is running well when I tried to check it using Project Fauxton after getting this error.

<img width="776" alt="Screen Shot 2019-08-06 at 10 28 32" src="https://user-images.githubusercontent.com/5698173/62509354-0fd67080-b835-11e9-9bf2-686ba52764d1.png">
<img width="1049" alt="Screen Shot 2019-08-06 at 10 25 28" src="https://user-images.githubusercontent.com/5698173/62509272-bc642280-b834-11e9-8477-624cef3969e3.png">

My suspicion is that the peer is looking for couchdb container that hasn't started yet. Since I can't seem to find the compose file, I'm not sure if peer container has depends_on property to couchdb container or not.

Clean up docker containers, removed ~/.fabric-vscode. Still having no luck.
Any help will be much appreciated.

**Comment by cazfletch** [comment]
Hi @deanzaka, I think you might have hit a known problem, can yuo try the work around in this issue please https://github.com/IBM-Blockchain/blockchain-vscode-extension/issues/1201

**Comment by deanzaka** [comment]
@cazfletch Just realized that I haven't replied to this. Confirmed the work around is good for now. Thanks a lot
