### ISSUE TITLE
Investigate status bar icons

### ISSUE THREAD

**Issue by cazfletch** [IBM-Blockchain/blockchain-vscode-extension#1240]
Look into putting the home page button on the status bar. What sort of things can you do with the status bar. Do some investigation and find out then we can decide what to do with the home page button

**Comment by cazfletch** [comment]
Part of the design for submitting transactions using the transactions view has a button on the status bar

**Comment by Jakeeyturner** [comment]
You should be able to add icons into the status bar label - https://code.visualstudio.com/api/references/icons-in-labels

For the home page, we might want to use the 'home' icon for example.

**Comment by cazfletch** [comment]
done so closing
