### ISSUE TITLE
As a user i can approve my 2.0 smart contract

### ISSUE THREAD

**Issue by cazfletch** [IBM-Blockchain/blockchain-vscode-extension#1246]
I should be able to somehow approve a smart contract. This depends on how seeing which smart contracts is achieved i.e. #1248. 

If i do it from the command i should only see smart contracts that haven't been approved to choose from

It should also let you choose which orgs you want to approve it for

An endorsement policy is needed for the approval stage - question should we just provide a default one or should we let the user set one?

Question - install and approve at the same time?

**Comment by cazfletch** [comment]
If you just want to update endorsement policy this needs to be approved with a new sequence number but doesn't need an install. Need to support this

**Comment by EdMoffatt** [comment]
Replaced with #1902
