### ISSUE TITLE
Magic Links to VS Code integrated tutorials

### ISSUE THREAD

**Issue by rachel-elizabeth-radulovich** [IBM-Blockchain/blockchain-vscode-extension#1258]
Separating out from #1080 (which will be re-named to just cover making updates to the Welcome page).

> **Magic Link**
> A link from outside VS Code (e.g. on a web page) which can be clicked to open up VS Code _and_ navigate to a relevant page e.g. the marketplace page to install our extension, or a particular tutorial within the extension.

Here was Charlotte's list of possible places to use these "magic links":
https://github.com/IBM-Blockchain/blockchain-vscode-extension/issues/1080#issuecomment-518694021

**Comment by EdMoffatt** [comment]
Ugh, link doesn't actually show the comment in this issue! Ok, here was Charlotte's comment...

Magic Links - hopefully i'm on the right lines with this but these are the areas i've found that could benefit from a link to the tutorials.

1. Read the documentation - "access our Beginner Tutorial"
General link to tutorials in introduction
Throughout, it states what you can do with the extension - reference relevant tutorial for carrying these tasks out.

2. E-book
Could introduce e-book with something along the lines of "should you want to learn more outside the tutorials, download this e-book" with the tutorials highlighted as a link

3. IBM Cloud/ IBM Cloud private link
Although this has been removed from the tutorial page, when this page appears from other sources, the link on said page should be made clickable. Presently, the link given under "getting started" is not active 

4. Extension install page
Same as point 1 above ^^^

5. Link on Google so the tutorials can be searched for in a search engine?

6. All tutorials could start/end with a link to the previous/next tutorial. If there are any critical steps/recurring issues with users that are solved by other tutorials, these can be linked throughout. 

And then a response from Caroline:

> Another place we could put a magic link is in the IBP docs, i had a call with Pam and Nick earlier and they liked the idea

**Comment by EdMoffatt** [comment]
Closing as part of a clean-out for Welcome+Tutorials updates. Will be replaced with new issues.
