### ISSUE TITLE
private data collection configuration file faild

### ISSUE THREAD

**Issue by pgzbc001** [IBM-Blockchain/blockchain-vscode-extension#1260]
input the private data collection configuration file, but it is failed
## Description

when I init the channel

## Expected Behavior

When I initialize the chain code, I prompt "do you want to provide a private data collection configuration file", I select "yes", and then I prompt the error message "Error instantiating smart contract: Invalid policy, missing the "identities" property"

the jsonfile like it :
[
 {
    "name": "collectionMarblePrivateDetails",
    "policy": "OR('Org1MSP.member')",
    "requiredPeerCount": 0,
    "maxPeerCount": 3,
    "blockToLive":3,
    "memberOnlyRead": true
 }
]

**Comment by cazfletch** [comment]
Hi @pgzbc001, the issue is that the Node SDK takes one format and the cli takes another this tutorial has the format you need for using private data with the extension

https://fabric-sdk-node.github.io/release-1.4/tutorial-private-data.html

**Comment by pgzbc001** [comment]
thank you very much
