### ISSUE TITLE
Recycle Icon for FABRIC ENVIRONMENTS refers to Local Fabric

### ISSUE THREAD

**Issue by rthatcher** [IBM-Blockchain/blockchain-vscode-extension#1262]
Using a pre-release v1.0.7 

The recycle arrow for FABRIC ENVIRONMENTS shows "Refresh Local Fabric Ops" when hovered over which is not appropriate when there are multiple environments - perhaps "Refresh Environments" would work?

**Comment by cazfletch** [comment]
This is fixed in pr https://github.com/IBM-Blockchain/blockchain-vscode-extension/pull/1238

**Comment by cazfletch** [comment]
done so lcoisng
