### ISSUE TITLE
Windows 10 Docker errors 

### ISSUE THREAD

**Issue by greg2git** [IBM-Blockchain/blockchain-vscode-extension#1273]
Checking docker version in Windows

docker -v

## Description
Vscode extension instructions assume no Windows environment issues after failed deployments of VirtualBox

## Expected Behavior
docker should start and run

## Actual Behavior
docker fails to run

## Possible Fix
Microsoft should issue a patch to make docker work in all Windows 10 versions.

## Steps to Reproduce
run command in Windows 10: docker --version
response: could not read CA certificate "C:\\Users\\user\\.docker\\machine\\machines\\hyperledger\\hyperledger;C:\\Users\\user\\.docker\\machine\\certs;\\ca.pem

**Comment by cazfletch** [comment]
closing as this is not an issue with the extension

**Comment by greg2git** [comment]
this should be made more prominent for any Windows users:

Windows 10 Enterprise, Pro, or Education with 1607 Anniversary Update or **LATER**
