### ISSUE TITLE
Remove duplicate README.md files

### ISSUE THREAD

**Issue by sstone1** [IBM-Blockchain/blockchain-vscode-extension#1284]
Currently the extension has a top level `client` directory which contains the code that gets built into a VSIX and published to the marketplace. There is a `README.md` inside the `client` directory that gets packaged into the VSIX, and a nearly identical `README.md` at the top level which gets used by the Visual Studio Code marketplace.

Maintaining and forcing contributors to update two copies of the `README.md` is just silly; if we need two, we should have one master copy and create the other copy at build time.

**Comment by cazfletch** [comment]
done so closing
