### ISSUE TITLE
Improve error message when no smart contract project to package

### ISSUE THREAD

**Issue by davidkel** [IBM-Blockchain/blockchain-vscode-extension#130]
![image](https://user-images.githubusercontent.com/25582377/46468211-bb530680-c7c7-11e8-8e64-a2c1d3620342.png)

ok, can't show the plus button. But when I am in the extension view with the smart contract packages, I press the + button to create a smart contract package (with a naive assumption that it will get me started on my smart contract journey). However It appears to do nothing except some cryptic messages in the corner

![image](https://user-images.githubusercontent.com/25582377/46468385-2b618c80-c7c8-11e8-8a96-86d0b4141f51.png)

From a beginners perspective, not sure what it is talking about, so went back and added a folder to my workspace and then went back and pressed the + again and got

![image](https://user-images.githubusercontent.com/25582377/46468523-914e1400-c7c8-11e8-807d-f88563c8ba60.png)

Would say this is low priority, cause just trying to play dumb here.

**Comment by caroline-church** [comment]
Need to imporve the error messages

**Comment by EdMoffatt** [comment]
Note that the original ask of this one is now covered by #432 - do we want to repurpose this issue to specifically improve the error messages on package creation, or should we replace it with the newer issue?
