### ISSUE TITLE
local_fabric error - contect deadline exceeded

### ISSUE THREAD

**Issue by lesleyannjordan** [IBM-Blockchain/blockchain-vscode-extension#131]
Steps
Installed VSCode
Added blockchain-vscode-extension
Clicked 'local_fabric' under Blockchain connections (assumed this would be my first step based on the repo README

Seem to install stuff, and then had a long wait, then error under 'join peer to channel'

# Create the channel
docker exec -e "CORE_PEER_LOCALMSPID=Org1MSP" -e "CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/msp/users/Admin@org1.example.com/msp" ${COMPOSE_PROJECT_NAME}_peer0.org1.example.com_1 peer channel create -o orderer.example.com:7050 -c mychannel -f /etc/hyperledger/configtx/channel.tx

2018-10-04 10:24:16.660 UTC [channelCmd] InitCmdFactory -> INFO 001 Endorser and orderer connections initialized
2018-10-04 10:24:16.819 UTC [cli/common] readBlock -> INFO 002 Received block: 0

# Join peer0.org1.example.com to the channel.
docker exec -e "CORE_PEER_LOCALMSPID=Org1MSP" -e "CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/msp/users/Admin@org1.example.com/msp" ${COMPOSE_PROJECT_NAME}_peer0.org1.example.com_1 peer channel join -b mychannel.block

**Error:** error getting endorser client for channel: endorser client failed to connect to peer0.org1.example.com:7051: failed to create new connection: context deadline exceeded
 
Details of VM:
VMWare
Ubunto 16.06
Memory 8GB

**Comment by rthatcher** [comment]
I have the same error when joining the channel on Ubuntu VM (with VirtualBox running on Mac)

**Comment by davidkel** [comment]
There is a known problem with slow startup of couchdb which will be fixed in the official release of fabric 1.3.0

**Comment by sstone1** [comment]
This got fixed in #150 by sleeping until either the timer is reached, or the `peer channel list` command works - the latter requires the peer to be up and operational, so is a good test:

https://github.com/IBM-Blockchain/blockchain-vscode-extension/pull/150/files#diff-db6dffb5b3459c4d48b04b87ab55de2fR19

The default timeout is bumped to 30s, but in most systems it takes a couple of seconds to start.
