### ISSUE TITLE
The information for creating Node files to perform admin on a remote non ibp fabric is incomplete regarding tls ca certs

### ISSUE THREAD

**Issue by davidkel** [IBM-Blockchain/blockchain-vscode-extension#1319]
The only information in the readme I could find was this
```
Here is an example of a peer with TLS enabled, please note the pem property value has been shortened.

{
    "name": "peer0.org1.example.com",
    "api_url": "grpcs://localhost:17051",
    "type": "fabric-peer",
    "msp_id": "Org1MSP",
    "pem": "LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUNJVENDQWNpZ0F3"
 }
```
But it doesn't describe the contents of the pem field. 
The pem field is the root tls cert of the peers MSP (ie it's the TLS CA Cert for the MSP) and it has been base64 encoded from a pem file (so that if you decode it you get a valid pem file with correct newlines, not a string embedded with `\n`s for example)
Without this information it's not possible to create node files manually for fabrics using TLS

**Comment by lesleyannjordan** [comment]
Ticket result of external source - setting flag

**Comment by davidkel** [comment]
A minor typo also exists when describing a multi-node entry in a single JSON file in the read me, ie
```
[
    {
         "name": "orderer.example.com",
         "api_url": "grpc://localhost:17050",
         "type": "fabric-orderer",
         "msp_id": "OrdererMSP",
         "cluster_name": "myCluster"
     },
     {
          "name": "orderer.example.com",
          "api_url": "grpc://localhost:17050",
          "type": "fabric-orderer",
          "msp_id": "OrdererMSP",
          "cluster_name": "myCluster"
     }
]
```
But these are identical definitions so technically not valid.
