### ISSUE TITLE
Suggestion: Ideas on improving the experience of using Windows

### ISSUE THREAD

**Issue by davidkel** [IBM-Blockchain/blockchain-vscode-extension#1330]
Not sure of the feasibility, but just had some thoughts on what might improve the windows experience.

The windows experience is not quite so pleasant due to having to install the windows build tools and also a specific version of openssl for windows into a specific directory. This comes about for the following reasons
1. the fabric node sdk mandates pkcs11 which has to be compiled
2. the fabric chaincode for node requires x509 and may also require to compile grpc as a minimum. x509 requires openssl library and these need to be built natively when wanting to debug node.js chaincode.

*Possible solutions*
- If fabric node sdk made pkcs11 an optional dependency rather than mandatory then no make tools should be required. 
- if the chaincode for debug was actually built and run in a container or if WSL is installed the chaincode is built and run under WSL then both could easily have the necessary pre-reqs so no need to windows make tools and native openssl for windows.

Another thing to bear in mind is that Docker plans to move away from HyperV Client on windows to host the linux environment to run containers and go forward with WSL2.

**Comment by cazfletch** [comment]
blocked as fabric to make pkcs11 optional first

**Comment by cazfletch** [comment]
closing as moved to fabric sdk  1.4.5 and not going to do the other things
