### ISSUE TITLE
Connect to IBP Ops tool

### ISSUE THREAD

**Issue by cazfletch** [IBM-Blockchain/blockchain-vscode-extension#1333]
From the extension you should be able to create an environment by pulling the nodes from the ops console to do this you need the url of the console and an api key

to get the api key for ibm cloud https://cloud.ibm.com/apidocs/blockchain

api key for icp https://cloud.ibm.com/docs/services/blockchain?topic=blockchain-console-icp-manage#console-icp-manage-apis

**Comment by rachel-elizabeth-radulovich** [comment]
@cazfletch I have questions 
for this one I started with 2 options:
1a. adding a whole new tile for 'connecting to ops tools (wording needs help all over) I thought it would be nice for outlining where to find the API but understandable for the 1b if we just need a way for the functionality and don't want to call it out this much
![1  First page](https://user-images.githubusercontent.com/37701387/64194972-5cba6080-ce4e-11e9-959c-1b986ce612b2.png)
1b. adding it like simon had on the left column
![1  First Page 2](https://user-images.githubusercontent.com/37701387/64194979-5f1cba80-ce4e-11e9-9f0e-c2452ab72784.png)

2. Then a pop up for 'entering the api key' like this
![2  Insert API key](https://user-images.githubusercontent.com/37701387/64195148-bfabf780-ce4e-11e9-96fb-0189b2aef3be.png)

From here would it go like this: 
- user chooses from multiple instances listed to connect to 
- user choses specific nodes (peer, CA) to connect from that instance

Am i missing steps?

**Comment by cazfletch** [comment]
You would need a step before giving the api key of giving a url.

I'm not sure if having it on the homepage is the right way to go or not but if we did we would also need 1b as well to make it work like everything else.

 For 1b then the action should be on a fabric environment (you have an outdated version of the extension) as this is what you will end up with after choosing the nodes, there is a + button to add a new environment which currently adds it from just the node files that you can download from the ops tools.

i don't think you would have multiple instances in this version i think that will be on the discover from cloud part, i think you would just need to choose which nodes

**Comment by rachel-elizabeth-radulovich** [comment]
Thank you for such quick feedback! here is another rev based on that (with a couple questions again). 

1. same as above- in left column
For now- do you think there needs to be a place that explains where to find the URL and API? or should that be left for the coming tutorial to cover? 
![1  First Page 2](https://user-images.githubusercontent.com/37701387/64204536-fb04f100-ce63-11e9-9954-13776f8817ef.png)

2. Enter url (like I said- not so sure about my wording in places)
also not sure if or how the left column could change during this time of inputting 
![2  Enter ops tools url](https://user-images.githubusercontent.com/37701387/64204589-1c65dd00-ce64-11e9-9b9a-f380797867d5.png)

3. Enter API (maybe we can find a place here to link to docs for finding/generating that information)
![3  enter API](https://user-images.githubusercontent.com/37701387/64204717-5931d400-ce64-11e9-9394-9cc27c3b5286.png)

4. choosing nodes- this would be more than one screen with different node options, but i made one for now (peer, CA, orderer?, etc.) 
![4  choose nodes](https://user-images.githubusercontent.com/37701387/64204734-6058e200-ce64-11e9-8f71-955598dee97b.png)

5. To show that something populates once you do all this correctly 
![5  After choosing nodes](https://user-images.githubusercontent.com/37701387/64204801-85e5eb80-ce64-11e9-8ff2-614755be6be4.png)

Let me know your feedback

**Comment by cazfletch** [comment]
Where you add the connection to ops tools that can't be in blue - also there is a plus button to add new environments would it be better to add it to the menu you get when you press the + button so have an option to create an environment from node files and an option to create an environment from ops tools?

Remember we talked about that each time you connect we would get the nodes again, so there is the problem of we don't want to ask which nodes you want each time, but we need a way of them choosing which nodes? I think we might have said for the first version you get all the nodes and then we have a next version where you select which node?

**Comment by rachel-elizabeth-radulovich** [comment]
@cazfletch 
Yes '+' button makes lots of sense. I'll add that with those 2 options. Would the 'Create an environment from ops tools' option then have a following choice to a. connect via url and api,  b. connect by logging in to IBM Cloud? 

Right- the nodes, sorry that slipped my mind. So then once you connected the right instance, all the nodes would populate for now, without the steps of choosing. Maybe with a 'disconnect' function on individual nodes.... not sure how helpful or possible that would be but just a thought.

I'll also try to think around how you might choose others for the future state we talked about.

**Comment by cazfletch** [comment]
I don't know whether you would have a sub-menu or if you would just put all 3 options on the first one????

We are planning on adding a delete nodes function so i guess you could do that for nodes you didn't want for now???

**Comment by rachel-elizabeth-radulovich** [comment]
- I'll try out both, leaning sub-menu in my head currently
- Delete should work for now i agree

**Comment by cazfletch** [comment]
closing as the only work left is the tutorial which will be done by the engagement team
