### ISSUE TITLE
VS Code Hyperledger Platform Extension 1.0.7 is unstable

### ISSUE THREAD

**Issue by sjais789** [IBM-Blockchain/blockchain-vscode-extension#1336]
<The latest version 1.0.7 of Fabric Platform extension on VS code is unstable >

## Description

The error is  Unable to open 'Extension: IBM Blockchain Platform': Cannot read property 'focus' of null.

## Your Environment

* IBM Blockchain Platform Extension Version:1.0.7
* Visual Studio Code version:
* Environment name and version (e.g. Node.js v8.12.0, npm v6.4.1):
* Operating System and version: Mac OS Sierra

**Comment by cazfletch** [comment]
@sjais789 what actions did you take to get this error?

**Comment by sjais789** [comment]
I have just upgraded the extension to the latest version. The extension is not visible anymore after reloading to the latest version.It's showing the error mentioned above.

**Comment by cazfletch** [comment]
Have you tried uninstalling and reinstalling?

**Comment by sjais789** [comment]
I have installed and uninstalled several times within last 20 mins. I have downgraded to the version 1.0.5 (my previous version) and it's working fine.But the error persist when I update to the latest version.
