### ISSUE TITLE
As a user i can discover nodes from ibm cloud

### ISSUE THREAD

**Issue by cazfletch** [IBM-Blockchain/blockchain-vscode-extension#1338]
from the extension i can log into ibm cloud and then i can get the nodes

**Comment by rachel-elizabeth-radulovich** [comment]
First attempt at this flow- I tried to combine the work from Sim with the video from Simon. @cazfletch Let me know any feedback on feasibility or missing steps.

1. Made 'Log in to IBM Cloud' pretty obvious and kept 'api key' option on left. Might consider a way for them to share one space as separate options.
![1  First Page 2 Copy](https://user-images.githubusercontent.com/37701387/64439534-28d27b80-d098-11e9-8bfb-06f97f1656c0.png)

2. Leaves to log on to IBM Cloud in pop-up webpage
![2  leave to log in ibm cloud](https://user-images.githubusercontent.com/37701387/64439597-4bfd2b00-d098-11e9-8d2d-19a8635d2230.png)

3. Receives one-time passcode at log in
![3  one time passcode](https://user-images.githubusercontent.com/37701387/64439631-659e7280-d098-11e9-880d-27e879ff00ce.png)

4. Enters passcode in extension
![4  Enter one time passode](https://user-images.githubusercontent.com/37701387/64439645-6df6ad80-d098-11e9-94de-43391f96e821.png)

5. Chooses account from within that Cloud login
![5  choose account with cloud login](https://user-images.githubusercontent.com/37701387/64439657-7c44c980-d098-11e9-82ab-247095c779a7.png)

6. Chooses ops instance from that account
![6  choose instance](https://user-images.githubusercontent.com/37701387/64439672-8666c800-d098-11e9-926b-c143d30c4166.png)

7. Chooses nodes to connect from that instance
![7  choose nodes](https://user-images.githubusercontent.com/37701387/64439696-91b9f380-d098-11e9-9437-9c666d0aca6c.png)

8.  Populated left side 
![8  After choosing nodes](https://user-images.githubusercontent.com/37701387/64439708-9aaac500-d098-11e9-89ac-6fd87d7f0a71.png)

**Comment by cazfletch** [comment]
So you have the log into ibm cloud button on the home page but i think we need something on the fabric environments panel as well.

On the screen where you are choosing are nodes this has the same problem as connecting to ops tools in that we would want to get the nodes each time you connected but you wouldn't want to choose each time

**Comment by rachel-elizabeth-radulovich** [comment]
Agreed- could be solved with the (+) also like we're talking about in #1333

**Comment by cazfletch** [comment]
closing as only work left is tutorial which the engagement team will do
