### ISSUE TITLE
Blockchain icon has disappeared

### ISSUE THREAD

**Issue by davidkel** [IBM-Blockchain/blockchain-vscode-extension#134]
Restarted VSCode and the icon has disappeared. Looks like it has the ability to go invisible to try to fool me into not trying to break it

![image](https://user-images.githubusercontent.com/25582377/46471728-c52e3700-c7d2-11e8-8c39-47126b3f93c3.png)

Clicking on it still reacts as expected.

**Comment by Jakeeyturner** [comment]
I've seen this happen with other extensions, so I think it must be a bug with VS Code.

**Comment by caroline-church** [comment]
closing as if seen with other extensions its a bug with vscode and something we can't fix
