### ISSUE TITLE
Command Not Found on Remote Dev Machine

### ISSUE THREAD

**Issue by mattcarp** [IBM-Blockchain/blockchain-vscode-extension#1362]
[moved this here from another thread]

It seems this extension does not work using remote development via SSH on an EC2 Ubuntu server (18.04). Error messages are of the type: `command 'aPackagesExplorer.createSmartContractProjectEntry' not found` (in other words, commands from the  `activationEvents` key in package.json).

I've tried rebuilding grpc in the `~/.vscode-server/extensions/ibmblockchain.ibm-blockchain-platform-1.0.8` directory using the following:

`npm rebuild grpc --target=4.2.5 --runtime=electron --dist-url=https://atom.io/download/electron --update-binary --fallback-to-build --target_arch=x64`

But no luck. 

Works well locally on my Mac though. Would be great to have this running for remote development since it would simplify setting up dev chains in the cloud.

Thanks.

_Originally posted by @mattcarp in https://github.com/IBM-Blockchain/blockchain-vscode-extension/issues/1357#issuecomment-527180126_

**Comment by cazfletch** [comment]
closing as this issue is fixed
