### ISSUE TITLE
Add something into the empty smart contract packages view

### ISSUE THREAD

**Issue by EdMoffatt** [IBM-Blockchain/blockchain-vscode-extension#138]
We have the “Add new connection” text, but no “Add new smart contract package”.  Though it’s more “Create package from current project”.  Something like that might be useful to have in that box when there’s nothing else to display there?  I forgot the fact that list is very likely to be empty for some time when a user first starts with the extension!

**Comment by EdMoffatt** [comment]
Notes from @caroline-church when brought up on Slack:

"...the plus button lets you do that but the plus button was originally intended for import.
I think that was one of the items up for review after this phase."

**Comment by caroline-church** [comment]
Proposal: We should add an Add new smart contract package item in the package view.
In the future if we add the ability to import a smart contract we should have a quickpick that lets you import a package via a file dialog or package one from the open workspace.
