### ISSUE TITLE
FabCar example - error from application SDK

### ISSUE THREAD

**Issue by ashishchandr70** [IBM-Blockchain/blockchain-vscode-extension#1381]
## Description

I am trying to run the FabCar application example that uses Fabric application Node SDK to query instantiated chaincode. I am using the query.js script that comes with the fabric-samples/fabcar/javascript example. However, the following statement in the script throws an error:

 

```

// Get the network (channel) our contract is deployed to.

const network = await gateway.getNetwork('mychannel');

 

```

 

The error I get is

 

> Failed to evaluate transaction: Error: Unable to initialize channel. Attempted to contact 1 Peers. Last error was TypeError: Incorrectly typed arguments to startBatch

 

My modified query.js is produced below:

```

 

/*

* SPDX-License-Identifier: Apache-2.0

*/

 

'use strict';

 

const { FileSystemWallet, Gateway } = require('fabric-network');

const path = require('path');

 

let fabricconnectionprofile = "/home/ac68326/.fabric-vscode/runtime/gateways/local_fabric.json"

//const ccpPath = path.resolve(__dirname, '..', '..', 'first-network', 'connection-org1.json');

let resolvestr = path.relative(__dirname,fabricconnectionprofile);

const ccpPath = path.resolve(__dirname, resolvestr);

 

 

async function main() {

    try {

 

        // Create a new file system based wallet for managing identities.

        //const walletPath = path.join(process.cwd(), 'wallet');

        //const wallet = new FileSystemWallet(walletPath);

        const walletPath = "/home/ac68326/.fabric-vscode/wallets/local_fabric_wallet";

        const wallet = new FileSystemWallet(walletPath);

       

        console.log(`Wallet path: ${walletPath}`);

 

        // Check to see if we've already enrolled the user.

        //const userExists = await wallet.exists('user1');

        const userExists = await wallet.exists('admin');

        if (!userExists) {

            console.log('An identity for the user admin does not exist in the wallet');

            console.log('Run the registerUser.js application before retrying');

            return;

        }

 

        // Create a new gateway for connecting to our peer node.

        const gateway = new Gateway();

        //await gateway.connect(ccpPath, { wallet, identity: 'user1', discovery: { enabled: true, asLocalhost: true } });

        await gateway.connect(fabricconnectionprofile, { wallet, identity: 'admin' });

 

        // Get the network (channel) our contract is deployed to.

        const network = await gateway.getNetwork('mychannel');

 

        // Get the contract from the network.

        const contract = network.getContract('fabcar');

 

        // Evaluate the specified transaction.

        // queryCar transaction - requires 1 argument, ex: ('queryCar', 'CAR4')

        // queryAllCars transaction - requires no arguments, ex: ('queryAllCars')

        const result = await contract.evaluateTransaction('queryAllCars');

        console.log(`Transaction has been evaluated, result is: ${result.toString()}`);

 

    } catch (error) {

        console.error(`Failed to evaluate transaction: ${error}`);

        process.exit(1);

    }

}

 

main();

 

```

 

## Why Is This a Bug

I am not certain this is a bug. On my personal Ubuntu laptop, the same code works, but in our RHEL environment, I get an error, which I think is related to **grpc**.

## Expected Behavior

 

As on my Ubuntu laptop, the `gateway.getNetwork('mychannel')` statement should return the details of the "mychannel" network.

 

## Actual Behavior

The gateway.getNetwork statement throws an exception:

 

> Failed to evaluate transaction: Error: Unable to initialize channel. Attempted to contact 1 Peers. Last error was TypeError: Incorrectly typed arguments to startBatch

 

 

## Possible Fix

Not sure but sounds like it could be related to **grpc config**.

## Steps to Reproduce

1. Instantiate the FabCar smart contract.

2. Modify the query.js provided under <relative path>/fabric-samples/fabcar/javascript folder to use the wallet, connection profile json and identity (admin).

3. Run node query.js

 

## Existing issues

 

 

I have the same issue if I use the fabcar application without the IBM extension. I have asked about a possible fix on the Hyperledger chat multiple times, and have also logged an issue on HLF Jira - https://jira.hyperledger.org/browse/FAB-16502 and have had no inputs or responses.

 

I decided to try the same thing using the extension and see if I have the same issue there as well. And I do.

 

## Log File

 

On the IBM extension itself, I am able to

 

1. Instantiate the FabCar contract

2. Call the initLedger method

3. Call the queryAllCars method. Here is the log from queryAllCars method:

 

```

[9/5/2019 2:11:37 PM] [INFO] evaluateTransaction

[9/5/2019 2:11:41 PM] [INFO] evaluating transaction queryAllCars with args

[9/5/2019 2:11:41 PM] [SUCCESS] Returned value from queryAllCars: "[{\"Key\":\"CAR0\",\"Record\":{\"color\":\"blue\",\"docType\":\"car\",\"make\":\"Toyota\",\"model\":\"Prius\",\"owner\":\"Tomoko\"}},{\"Key\":\"CAR1\",\"Record\":{\"color\":\"red\",\"docType\":\"car\",\"make\":\"Ford\",\"model\":\"Mustang\",\"owner\":\"Brad\"}},{\"Key\":\"CAR2\",\"Record\":{\"color\":\"green\",\"docType\":\"car\",\"make\":\"Hyundai\",\"model\":\"Tucson\",\"owner\":\"Jin Soo\"}},{\"Key\":\"CAR3\",\"Record\":{\"color\":\"yellow\",\"docType\":\"car\",\"make\":\"Volkswagen\",\"model\":\"Passat\",\"owner\":\"Max\"}},{\"Key\":\"CAR4\",\"Record\":{\"color\":\"black\",\"docType\":\"car\",\"make\":\"Tesla\",\"model\":\"S\",\"owner\":\"Adriana\"}},{\"Key\":\"CAR5\",\"Record\":{\"color\":\"purple\",\"docType\":\"car\",\"make\":\"Peugeot\",\"model\":\"205\",\"owner\":\"Michel\"}},{\"Key\":\"CAR6\",\"Record\":{\"color\":\"white\",\"docType\":\"car\",\"make\":\"Chery\",\"model\":\"S22L\",\"owner\":\"Aarav\"}},{\"Key\":\"CAR7\",\"Record\":{\"color\":\"violet\",\"docType\":\"car\",\"make\":\"Fiat\",\"model\":\"Punto\",\"owner\":\"Pari\"}},{\"Key\":\"CAR8\",\"Record\":{\"color\":\"indigo\",\"docType\":\"car\",\"make\":\"Tata\",\"model\":\"Nano\",\"owner\":\"Valeria\"}},{\"Key\":\"CAR9\",\"Record\":{\"color\":\"brown\",\"docType\":\"car\",\"make\":\"Holden\",\"model\":\"Barina\",\"owner\":\"Shotaro\"}}]"

 

```

 

There is no other relevant log that I can think of as I have already posted the exception I get from calling `gateway.getNetwork('mychannel')` but I am happy to provide any additional info as needed.

 

 

## Your Environment

* IBM Blockchain Platform Extension Version: 1.0.5

* Visual Studio Code version: 1.36.1

* Environment name and version (e.g. Node.js v8.12.0, npm v6.4.1): Node v8.16.0, Npm 6.4.1

* Operating System and version: RHEL 7.6

* Docker: CE 18.09.7

**Comment by ashishchandr70** [comment]
Hi @cazfletch and team, I also followed this issue up with the GRPC team and here is their response:

https://github.com/grpc/grpc-node/issues/1025#issuecomment-530058096

Any ideas/suggestions? Thank you.

**Comment by cazfletch** [comment]
In the extension, if you connect to your gateway and right click on a deployed smart contract and click generate tests. Are you able to run those tests?

**Comment by ashishchandr70** [comment]
There is an error during npm install because it cannot find a matching version for fabric-client@1.4.3. Does this exist? Installing this on my laptop also results in an "npm err: extraneous" error.

Please advise.

**Comment by cazfletch** [comment]
yes it exists https://www.npmjs.com/package/fabric-client/v/1.4.3

**Comment by ashishchandr70** [comment]
Thanks @cazfletch

**Comment by ashishchandr70** [comment]
I am closing this issue because I am able to get past the startBatch related error. I have another error "Discovery error: access denied" which is apparently related to file level permissions or existence of pem files. I will debug this.

Thanks again @cazfletch
