### ISSUE TITLE
JavaScript project packages to the TypeScript folder

### ISSUE THREAD

**Issue by SamRasha** [IBM-Blockchain/blockchain-vscode-extension#139]
Packaging any JavaScript project has it package under the TypeScript directory rather than the JavaScript directory in ~/.fabric-vscode
<img width="962" alt="screen shot 2018-10-04 at 14 01 34" src="https://user-images.githubusercontent.com/10238857/46475913-b9e10880-c7de-11e8-89ac-61f722c17dbb.png">

**Comment by caroline-church** [comment]
done so closing
