### ISSUE TITLE
Cancelling selecting environment files creates an environment I can connect to

### ISSUE THREAD

**Issue by heatherlp** [IBM-Blockchain/blockchain-vscode-extension#1390]
## Description
When cancelling the dialog box for selecting node JSON files for creating an environment, the environment is created anyway. 
I see message: `Added a new environment, but some nodes could not be added`
and if I click on it, I can connect, despite giving no file

## Expected Behavior
I think the action should be cancelled and no environment created
Correct behaviour is seen on `Create Gateway` command

## Actual Behavior
Explained above

## Possible Fix
Handle the "Cancel" return value from the dialog box properly

## Steps to Reproduce
1. Create an environment, give a name
2. Cancel selecting a node file

Extension version: 1.0.10 test version

**Comment by Jakeeyturner** [comment]
@erin-hughes is assigned to this
