### ISSUE TITLE
Close/re-open required to pick up node version used

### ISSUE THREAD

**Issue by heatherlp** [IBM-Blockchain/blockchain-vscode-extension#1393]
## Description
When installing the 1.0.10 test version of the extension and using nvm version 5.something, the prerequisites page explains I need nvm 6+. Using an `nvm alias` command to use node 10/nvm 6.9.0, I clicked "check again" but it still reported that the node version was incorrect.

Reloading the vscode window did not fix this. I had to close, quit and re-open vscode before the change took affect. 

I did not know it worked because the prerequisites doesn't load again (I have no other issues to resolve). I had to open the prerequisites page again to confirm it was happy.

**Comment by Jakeeyturner** [comment]
Closing - mentioned in prereqs.
