### ISSUE TITLE
openssl prerequisite check is wrong

### ISSUE THREAD

**Issue by bigworld12** [IBM-Blockchain/blockchain-vscode-extension#1406]
Openssl prerequisite check is wrong

## Description
I have Openssl x64 bit v1.0.2t installed , but the extension still says that i need 1.0.2 or more
i also tried with v1.1.1d but still get the same warning even after detecting the version correctly 

## Expected Behavior
i don't get a warning for openssl

## Actual Behavior
![image](https://user-images.githubusercontent.com/10135395/64917502-7b472280-d791-11e9-8923-2efed6c077b3.png)

## Your Environment
VS code version : Version: 1.38.1 (system setup)
Commit: b37e54c98e1a74ba89e03073e5a3761284e3ffb0
Date: 2019-09-11T13:35:15.005Z
Electron: 4.2.10
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Windows_NT x64 10.0.18980

**Comment by davidkel** [comment]
I would suggest that it should be 1.0.2 for node 8 and 1.1 for node 10.

**Comment by Fragger5000** [comment]
I've a similar problem, in short, the extension doesn't recognize the OpenSSL installed

![image](https://user-images.githubusercontent.com/22413422/65308681-e1191d00-db8a-11e9-8f45-e6556fcf01f8.png)

![image](https://user-images.githubusercontent.com/22413422/65308708-f0986600-db8a-11e9-8209-c208057cd803.png)

**Comment by ashburnere** [comment]
Don't use OpenSSL 1.1.1 for Hyperledger Fabric. Use 1.0.2.

You will get errors when installing the fabric-shim-module. See also this comment: https://github.com/ethereumjs/ethereumjs-util/issues/43#issuecomment-363369903 (

**Comment by AishwaryJS** [comment]
I am facing the same issue. VS code not able to recognize openssl. @Fragger5000  did you find any solution ? FYI @cazfletch

**Comment by cazfletch** [comment]
@AishwaryJS which version of the extension do you have. The latest should have a fix for this

**Comment by AishwaryJS** [comment]
Hi Caroline,

I tried with open ssl 1.1.1 d which was recommended with node version 10.
I installed open ssl 1.0.2 u which resolved the issue but documentation was little misleading. Working with 1.0.2 u with node version 10 .

Regards,
Aishwary Sharma

________________________________

**Comment by NaViGatorFL** [comment]
Is there any fix to this issue, so far. I'm using 1.1.1 with node.js v10.x ?

**Comment by shoebsd31** [comment]
I tried downloading 1.0.2 u from : https://indy.fulgan.com/SSL/
didn't work for me. 
I am using node version 12
