### ISSUE TITLE
Associate identity with more nodes should use check box

### ISSUE THREAD

**Issue by cazfletch** [IBM-Blockchain/blockchain-vscode-extension#1416]
When you want to associate an identity with more than one node this should be changed to ask if you want to and then show you a list of nodes with check boxes of nodes that you can check the ones you want to associate

**Comment by toggle007** [comment]
Fix in PR.
How to test: 
When you try to associate an identity with another node, you should now see a checkbox which allows you to pick which nodes you want to delete (multiple selection) instead of picking a node one at a time.
