### ISSUE TITLE
Prereqs page take a while to load

### ISSUE THREAD

**Issue by cazfletch** [IBM-Blockchain/blockchain-vscode-extension#1437]
The prereqs page takes a while to load when using remote development. I think this is from checking the install preregs. We should add a loading spinner so that the user knows something is happening

This also happens on windows

**Comment by Jakeeyturner** [comment]
When we check the prereqs in `extension.ts`, we can pass the dependencies through to the OPEN_PRE_REQ_PAGE command if they're not all installed. We can then pass this when we create the HTML string.

**Comment by james-wallis** [comment]
I'll pick this one up.

**Comment by james-wallis** [comment]
I've just merged a PR which refactored the prereqs view by using a Promise.all to fetch the dependency versions and pass the dependencies into the page view when the extension starts up.
