### ISSUE TITLE
Duplicate packages showing in Smart Contract Packages when packaged smart contract is loaded in the workspace

### ISSUE THREAD

**Issue by heatherlp** [IBM-Blockchain/blockchain-vscode-extension#144]
Seems only to duplicate the latest packaged file, but doesn't match the file system:

<img width="665" alt="image" src="https://user-images.githubusercontent.com/40789053/46478759-8d7cba80-c7e5-11e8-8df8-9e88fae130a5.png">

**Comment by heatherlp** [comment]
Deleting one twirl@0.0.4 only removes one 🤔 from the view, and deletes the file system version and stuff gets weird when you delete the other ghost one

**Comment by heatherlp** [comment]
Ok this only happens when you have one of the packaged smart contracts open in the workspace (i.e. directly from the fabric.packages.directory specified in user settings.) It doesn't rename the package directory loaded, but understands the versions been updated, hence why we see two:

Object
collapsibleState:0
label:"twirl@0.0.256"
provider:Object
iconPath:Object
contextValue:"blockchain-package-item"
name:"twirl@0.0.256"
packageEntry:Object
path:"/Users/heatherp/test_projects/another_test/javascript/twirl@0.0.1"
chaincodeLanguage:"javascript"
name:"twirl"
version:"0.0.256"

This is low priority unless we find users consistently opening the fabric.packages.directory in their workspace and having duplicates in the view super annoying.

**Comment by caroline-church** [comment]
now we have proper packages this cant happen
