### ISSUE TITLE
Difficulty with debugging smart contracts

### ISSUE THREAD

**Issue by ashishchandr70** [IBM-Blockchain/blockchain-vscode-extension#1449]
## Description

I have a smart contract that has been successfully instantiated on local_fabric. I am successfully able to invoke the methods from the IBM extension. However, I am not able to get the breakpoints to hit.

What I did:

1. As per this [link](https://cloud.ibm.com/docs/services/blockchain/howto?topic=blockchain-develop-vscode#develop-vscode-development-mode) I looked for start.js (which has the Shim.start) statement. It was in `<extension>/node_modules/generator-fabric/generators/chaincode/templates/javascript/lib/start.js`. 
2. I set up a launch.json as per the link above and pointed to this start.js. This did not work and I got an error "cannot find module fabric-shim". So, I built the node_modules folder wherever the contract directory is, and copied over the start.js to the main contract folder. As I am testing fabcar, the chaincode folder has start,js and a node_modules directory.
3. I then start the debugger, which now starts up. But the breakpoints I have set do not hit.

I am not sure if I needed to copy over start.js from the templates folder, or whether this is auto generated (could not find documentation around this). Also, I am not certain if I need to build node_modules outside the docker container (as this is probably done within the container using a different version of node and grpc). However, building node_modules seemed to have alleviated the "fabric-shim not found" type error.

## Expected Behavior

Debug a smart contract function.

## Actual Behavior

Debugger starts up but the breakpoints do not hit. I am using the method described here https://cloud.ibm.com/docs/services/blockchain/howto?topic=blockchain-develop-vscode#develop-vscode-development-mode to start the debugger.

As per bullet 8 of this link, I am going over to the blockchain extension and submitting the evaluateTransaction on one of the methods. However, the method evaluates without stopping at the set breakpoint.

`On the debug toolbar, click the Blockchain button to submit or evaluate transactions. You also can right click on transactions in the Fabric Gateways panel to submit or evaluate them. Execution will be paused on any breakpoints you've defined.`

## Log File
No logs as such

## Your Environment

- IBM Blockchain Platform Extension Version: 1.0.5
- Visual Studio Code version: 1.36.1
- Environment name and version (e.g. Node.js v8.12.0, npm v6.4.1): Node v8.16.0, Npm 6.4.1
- Operating System and version: RHEL 7.6
- Docker: CE 18.09.7

**Comment by cazfletch** [comment]
Hi @ashishchandr70 are you using a low level chaincode or a chaincode written with the contract api?

**Comment by ashishchandr70** [comment]
Hi @cazfletch, using javascript and using the fabric contract api.

Thanks

**Comment by cazfletch** [comment]
Since you are using the contract api you don’t need to set the program property. The program property management s only needed if you aren’t using the fabric-contract-api. 

Can you try without setting that and make sure you have done an npm install on the contract.

**Comment by ashishchandr70** [comment]
Hi @cazfletch, that worked out just fine. I am able to hit the breakpoints. 

The extension documentation should be updated to reflect this.

Thanks a lot, as always!
