### ISSUE TITLE
Instantiate Hangs

### ISSUE THREAD

**Issue by caroline-church** [IBM-Blockchain/blockchain-vscode-extension#145]
When instantiating sometimes the message saying instantiating smart contract never goes away. This is due to a problem in the event handler (https://jira.hyperledger.org/browse/FABN-954?page=com.atlassian.jira.plugin.system.issuetabpanels%3Aall-tabpanel).

The instantiate does actually succeed and refreshing the blockchain connections view will show the instantiated smart contract

**Comment by rthatcher** [comment]
I see this too after Instantiating a new version of my Smart Contract - I need to Refresh the Blockchain Connections to see the new version in the tree.

**Comment by caroline-church** [comment]
closing as not seeing this anymore and event handler stuf has been rewritten
