### ISSUE TITLE
React Information

### ISSUE THREAD

**Issue by Jakeeyturner** [IBM-Blockchain/blockchain-vscode-extension#1463]
The extension now lives in the `extension` directory and the React app lives in `src`. Unless we decide to eject the react app, the react code must live in `src`.
Because of this, we now have two tsconfig files, `tsconfig.json` for the `src` react code and `tsconfig.extension.json` for the extension code.

When making any changes to the React app, `npm run build` must be run in order to transpile all the TypeScript into the `build` directory (previously `out`). This process takes a **long** time and we really need to find a way of speeding it up. This will make our builds take a long time also!

The command to open a sample page from the react app is `reactPage.open`. Currently it is disabled from the command palette.

Cypress (UI tests) tests can be run using either `npm run cypress` (GUI) or `npm run cypressCli` (CLI). The tests can be found in the `cypress/integration` directory (we can't change the config for the `integration` directory AFAIK).

Jest/Enzyme tests (more unit-y) can be run using `npm run jestTest`. The tests can be found in the `enzyme` directory (might want to change this).

Currently, the tests haven't been added to the build to run.

In the webviews (on openPanelInner), we need to run `panel.webview.postMessage('/one');` in order to tell the react app to navigate to the component where the path `/one` is registered. This tells our router in `App.tsx` which component to redirect to.
I've had to do this due to the fact that VS Code webviews require a string to build a webview. Also, we need to make sure that components can be loaded in VS Code, Cypress and Jest/Enzyme. We might be able to improve this router/redirect design, however we need to make sure it's runnable in these different environments.
As the webviews require a string (of HTML), we pass the contents of `index.html`. At the moment, we don't read in the `index.html` from the `public` directory and change the imports to use the correct URIs.

We can use the Carbon framework inside our React app which makes things a lot easier! Currently there are some _hacks_ in place to allow Carbon components to change theme when a user changes their theme in VS Code. Check `index.scss` for more information!

One current limitation is that for the React app, a user cannot `Reload Webviews` as this won't cause the component to be re-loaded.
Another limitation is that the tslint configuration _may_ be broken as VS Code doesn't seem to report unused imports, etc.
Unfortunately as we haven't ejected the React app, we cannot import files into the React app that live outside of `src`. As a workaround, we can copy files into the `src` directory on build, for example `ExtensionCommands.ts`. We copy this file into `src` so that we can reference commands.

I will update this issue as I remember more things!

---

Things to do / investigate:

- [x] Improve `npm run build` time
- [x] Improve Azure build time (related to that one ^)
- [x] Add tests to run in Azure
- [x] Investigate a better router/redirect design for loading components for different webviews
- [ ] For a webview, read from `index.html` and replace URIs (as opposed to a inline string) which we can return
- [ ] Investigate building SCSS separately and improving how we handle VS Code themes with Carbon themes
- [ ] Investigate how we can re-load a component when a user runs the `Reload Webviews` command
- [x] Get TSLint working properly

**Comment by cazfletch** [comment]
closing
