### ISSUE TITLE
Please update the extension to Node.js 12 

### ISSUE THREAD

**Issue by jessezwd** [IBM-Blockchain/blockchain-vscode-extension#1467]
Every time I open vscode, this extension reminds: Node.js 8.x or 10.x required, but Node.js current version is 12.x, not 8.x or 10.x.
Please kindly update the extension to Node.js 12.

**Comment by cazfletch** [comment]
Hi @jessezwd the Fabric sdk currently doesn't support node 12 which is why you need version 8 or 10
