### ISSUE TITLE
Unable to Import Certificate for ID under Ubuntu

### ISSUE THREAD

**Issue by rthatcher** [IBM-Blockchain/blockchain-vscode-extension#1468]
When trying to add an ID to a Wallet (a new Wallet or an existing Wallet) I select the option to supply a Certificate and Private key.  I get as far as Browsing for the Certificate file, but then the "Add ID" process just stops with no further prompts or messages.
(If the certificate file is badly formatted, then an error is generated.)

The problem occurs with v1.0.11 - with brief testing it works OK with v1.0.10

(with v1.0.9 it worked a couple of times then I had one failure, but maybe that isolated problem was user error.)

VS Code Extenstion v1.0.11
Vs Code v1.38.1  (though it happened in an earlier version before I upgraded to try to fix!)
Ubuntu Bionic 18.04

The pre-reqs check in the extension reports the following versions:
Name			Version
Node.js			10.16.3
npm				6.9.0
Docker			18.9.7
Docker Compose	1.15.0
System Req.		>4GB RAM
Go				1.12.9
Go Extension		0.11.7
Java OpenJDK 8	1.8.0
Java Language Support Extension
				0.49.0
Java Debugger Extension
				0.22.0

**Comment by Jakeeyturner** [comment]
Closing - I suspect this is no longer an issue.
