### ISSUE TITLE
Feature Request - Display peers associated with a channel.

### ISSUE THREAD

**Issue by lquintai** [IBM-Blockchain/blockchain-vscode-extension#1492]
## Description
At the moment it is not possible to find out which peers are associated with a channel in the extension. Although local fabric only has one peer and one channel, this is not necessarily the case for custom networks - it would be useful to have this information.

A possible implementation would be to display a list of peer names when hovering over Fabric Environments > Channels > channelOfInterest.

**Comment by EdMoffatt** [comment]
This just sounds like a straight-up great suggestion to me :) All you get on hover at the moment is the channel name again, so we're not using that hover state for anything, and it sounds like useful info to include.
The use case I'm imagining is that you're planning to instantiate a smart contract on the channel and need to know what peers it needs installing on for that to work.

What do you think @cazfletch ?

**Comment by cazfletch** [comment]
I agree it sounds great too!
