### ISSUE TITLE
As a user i can configure my local fabric using ansible

### ISSUE THREAD

**Issue by cazfletch** [IBM-Blockchain/blockchain-vscode-extension#1516]
We should use ansible to be able to create a local fabric with whatever peers, orgs, and channels the user wants and have this integrated into the extension

There should still only be one local fabric and you will be able to right click to configure it.

You will be able to import the directory which an ansible playbook creates. This will have the same structure as the local fabric. When you import it you will have the environment, gateways and wallets the playbook created

**Comment by EdMoffatt** [comment]
Initial design for how we want the existing Local Fabric to be configurable.
(Note that we'll cover allowing the user to achieve multiple local environments of arbitrary configurations by providing a tutorial on running Ansible playbooks and adding an option on "Add Environment" to allow "Add from directory" (to point at the directory structure created by running a playbook).

![image](https://user-images.githubusercontent.com/7454304/69542925-67375280-0f84-11ea-9c0f-ed74fe951bde.png)

**Comment by cazfletch** [comment]
done so closing

**Comment by alfalfs** [comment]
can you please mention link to tutorial, I am facing difficulty to add an Ansible  created network to add as environment. ibmblockchain.ibm-blockchain-platform v2.0.2.
