### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by yperros** [IBM-Blockchain/blockchain-vscode-extension#1527]
- Issue Type: `Performance`
- Extension Name: `ibm-blockchain-platform`
- Extension Version: `1.0.11`
- OS Version: `Windows_NT x64 10.0.18362`
- VSCode version: `1.39.0`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`C:\Users\Yiannis\IBMBlockchain.ibm-blockchain-platform-unresponsive.cpuprofile.txt`

Find more details here: https://github.com/microsoft/vscode/wiki/Explain-extension-causes-high-cpu-load

**Comment by cazfletch** [comment]
Hi @yperros what were you doing when the problem happened

**Comment by cazfletch** [comment]
closing as no response
