### ISSUE TITLE
Save a record of the nodes being used

### ISSUE THREAD

**Issue by lquintai** [IBM-Blockchain/blockchain-vscode-extension#1542]
*To be initially delivered to OpsTool feature branch*

After retrieving the Json file we excluded any node types VSCode doesn't handle. The user might also decide to not include some of the nodes.

We will write all nodes to disk, but add a new field to the json files so that we have an easily accessible record or which nodes the user added to the environment, out of all the possible nodes in the network.

This record can be used for future reference (when we attempt to reconnect, or when the user wants to add more nodes).

**Comment by cazfletch** [comment]
done so closing
