### ISSUE TITLE
Ops Tool - automatically remove node that has been deleted on the Ops tool console

### ISSUE THREAD

**Issue by lquintai** [IBM-Blockchain/blockchain-vscode-extension#1547]
*To be initially delivered to OpsTool feature branch*

When reconnecting/refreshing/editing filters/automatically pulling the json from ops tools, if there is a node present in vscode that is no longer present in ops tools, then this node should be automatically deleted.

If there are no nodes left to show, display environment as disconnected.

**Comment by cazfletch** [comment]
done so closing
