### ISSUE TITLE
"Fabric Runtime" vs "Local Fabric Environment" 

### ISSUE THREAD

**Issue by rthatcher** [IBM-Blockchain/blockchain-vscode-extension#1558]
![image](https://user-images.githubusercontent.com/29195399/66935000-47327c00-f033-11e9-8792-0bf7951fd0cb.png)

Should these commands now refer to the **Local Fabric Environment** rather than **Local Runtime** ?

**Comment by EdMoffatt** [comment]
I'm a fan of removing the additional words from the right-click, i.e. we just have:

- Restart
- Stop
- Teardown

(Although also in this screenshot those are the wrong options to be offering on a stopped Local Fabric, tho I think we have a separate issue for that).

In the commands themselves, I think our terminology is _okay_ (although admittedly a bit confusing!). A Fabric Environment is a thing (a "connection") you add in VS Code to communicate with a given Fabric network (or runtime) and pass commands like install, instantiate, or even stop, teardown etc. to it. So it's not the "Environment" you're tearing down, it's the "Network/Runtime" that the Environment provides a connection to.

That said, when you have multiple Environments offering a teardown option and you run the teardown command from the command prompt, you're then going to be asked to pick an Environment. So, perhaps updating the terminology to say "Teardown Fabric Environment" in the command prompt would be better.

I think I'd still drop it to a single word in the right-click options tho.

What do you think @cazfletch @Jakeeyturner ?

**Comment by cazfletch** [comment]
we should change to `Teardown Fabric Environment`
