### ISSUE TITLE
Update adding environment tutorial for ops tools running anywhere

### ISSUE THREAD

**Issue by heatherlp** [IBM-Blockchain/blockchain-vscode-extension#1574]
https://github.com/IBM-Blockchain/blockchain-vscode-extension/blob/master/tutorials/developer-tutorials/add-environment.md

I think this tutorial needs updating for connecting to ops tools running not on IBM Cloud

**Comment by cazfletch** [comment]
closing as we will add a tutorial on how to connect to ops tools using url etc
