### ISSUE TITLE
Images in README.md are different sizes/resolutions

### ISSUE THREAD

**Issue by sstone1** [IBM-Blockchain/blockchain-vscode-extension#159]
![screen shot 2018-10-08 at 15 47 51](https://user-images.githubusercontent.com/7118158/46616268-12334580-cb12-11e8-9553-daa71d373b80.png)

**Comment by EdMoffatt** [comment]
Will assign this to Niv when we get her added to this repo!

Steps to complete:

- Install VSCode
- Install the extension
- Re-capture any GIFS or screenshots as needed to make all consistent
(Kap is decent for GIF capture, Quicktime for video, and Mac has built in tools for screenshots)
- Replace the media files
- Update README.md with the new media files
- Pull Request that right up!
