### ISSUE TITLE
Add CHANGELOG.md file containing new features/bug fixes 

### ISSUE THREAD

**Issue by sstone1** [IBM-Blockchain/blockchain-vscode-extension#160]
Add CHANGELOG.md file containing new features/bug fixes for each release. This shows up within the marketplace and lets users know what has changed in each version:

https://github.com/Microsoft/vscode-cpptools/blob/master/Extension/CHANGELOG.md
https://github.com/Microsoft/vscode-docker/blob/master/CHANGELOG.md

**Comment by caroline-church** [comment]
done so closing
