### ISSUE TITLE
Error instantiating smart contract: Cannot read property 'CORE_CHAINCODE_ID_NAME' of undefined

### ISSUE THREAD

**Issue by siddjain** [IBM-Blockchain/blockchain-vscode-extension#1614]
## Description
We are able to install a smart contract but when we try to instantiate it we get this error: Error instantiating smart contract: Cannot read property 'CORE_CHAINCODE_ID_NAME' of undefined

## Expected Behavior
no error

## Actual Behavior
Error instantiating smart contract: Cannot read property 'CORE_CHAINCODE_ID_NAME' of undefined

## Steps to Reproduce
1. package smart contract
2. create local fabric environment
3. install smart contract
4. Try to instantiate smart contract using IBM Blockchain extension

## Log File

don't see any Blockchain.log file
```
WITSC02X6385JGH:logs sjain68$ find . -name Blockchain.log
WITSC02X6385JGH:logs sjain68$ pwd
/Users/sjain68/Library/Application Support/Code/logs
```

## Your Environment

* IBM Blockchain Platform Extension Version: 1.0.14
* Visual Studio Code version:
Version: 1.39.2
Commit: 6ab598523be7a800d7f3eb4d92d7ab9a66069390
Date: 2019-10-15T15:33:00.827Z
Electron: 4.2.10
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Darwin x64 18.6.0

**Comment by siddjain** [comment]
the peer log is just showing this:
```
2019-11-06 23:40:31.062 UTC [endorser] callChaincode -> INFO 091 [][1e1436e4] Entry chaincode: name:"cscc"
2019-11-06 23:40:31.063 UTC [endorser] callChaincode -> INFO 092 [][1e1436e4] Exit chaincode: name:"cscc"  (1ms)
2019-11-06 23:40:31.063 UTC [comm.grpc.server] 1 -> INFO 093 unary call completed grpc.service=protos.Endorser grpc.method=ProcessProposal grpc.peer_address=172.18.0.1:40120 grpc.code=OK grpc.call_duration=1.706206ms
```

**Comment by Jakeeyturner** [comment]
Hi @siddjain,

When you're trying to instantiate your smart contract do you happen to have some kind of debug task running?

**Comment by siddjain** [comment]
Yes i do. I have started fabric chaincode node and attached debugger to it

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by Jakeeyturner** [comment]
After having a look at the code, this seems to be a bug.

In instantiate/upgrade we have the following check:
```
if (!vscode.debug.activeDebugSession) {
    // Not called during debugging, ask for smart contract to instantiate
    chosenChaincode = await UserInputUtil.showChaincodeAndVersionQuickPick('Choose a smart contract and version to instantiate', channelName, peerNames);
    if (!chosenChaincode) {
        return;
    }
    data = chosenChaincode.data;
    packageToInstall = chosenChaincode.data.packageEntry;

} else {
    // called from debug session - get the chaincode ID name and folder used to debug
    smartContractName = vscode.debug.activeDebugSession.configuration.env.CORE_CHAINCODE_ID_NAME.split(':')[0];
    smartContractVersion = vscode.debug.activeDebugSession.configuration.env.CORE_CHAINCODE_ID_NAME.split(':')[1];
}
```

The problem with this (and other places in these files) occurs when the user has an active debug session, but it's not the "Debug Smart Contract" debug event. In that case, `env` won't exist on the debug session configuration, and nor will anything about the smart contract.

In order to check if the user has an active "Debug Smart Contract" we should do be doing something like:
```
if (vscode.debug.activeDebugSession && vscode.debug.activeDebugSession.configuration && vscode.debug.activeDebugSession.configuration.debugEvent === FabricDebugConfigurationProvider.debugEvent) {

...

}
```

---

For the time being @siddjain, if you're wanting to debug your smart contract you should be using the "Debug Smart Contract" configuration.
Alternatively, if you're just wanting to instantiate/upgrade your smart contract, try doing it without a debug configuration running.

**Comment by siddjain** [comment]
thanks for detailed response. is there a bug tracker you use? how can i get notified when this is fixed?
________________________________
