### ISSUE TITLE
As a Go smart contract developer, I want to generate tests and run them 

### ISSUE THREAD

**Issue by heatherlp** [IBM-Blockchain/blockchain-vscode-extension#163]
under the work I'm doing in #60, we're generating a default .js file for tests, which won't be desirable if the chaincode language is go. So when we're supporting go, we should update the extension so that we generate go test files if we detect go chaincode.

#62 covers running smart contract tests too, so this user story should cover running go tests too

**Comment by caroline-church** [comment]
closing until go support
