### ISSUE TITLE
Command to create diagnostic ZIP

### ISSUE THREAD

**Issue by Jakeeyturner** [IBM-Blockchain/blockchain-vscode-extension#1641]
We should provide a command to create a diagnostic ZIP, which as maintainers we could request if people hit problems.

This ZIP should contain the extension directory (stripping out private keys) and user settings.

This would be particularly useful in scenarios where migration has failed and we need to find out why.

**Comment by EdMoffatt** [comment]
Adding this one to the design to-do list for the current sprint.

**Comment by EdMoffatt** [comment]
As far as I can see, from me we basically just need a wording on this one?

Did a bit of googling for what other tools call a similar command and we're basically looking at some variation on `create/export/get diagnostic/support information/ZIP`.

Export sits best with our existing commands. "Diagnostic" is more descriptive of what it is, whilst "support" better implies that this is useful if you want somebody else to be able to help you.

I say let's go for: `Export diagnostic ZIP`

There ya go, I've really added value here ;)

Oh, we should also have a toast notification that tells you where VS Code has put the diagnostic ZIP (suggest we only have one at a time, and they replace each other should you run the command multiple times). So something like:

`Diagnostics exported to path/to/file/ibp_vscode_diagnostic.zip - please send this file when requesting support.`
