### ISSUE TITLE
Extension fails to load if node not installed

### ISSUE THREAD

**Issue by davidkel** [IBM-Blockchain/blockchain-vscode-extension#165]
The readme states that you only need node to start a local fabric, however the extension won't activate if node is not installed
```
extension activating
Updating native node modules
Rebuilding native node modules
Could not rebuild native dependencies spawn npm ENOENT
Failed to activate extension see previous messages for reason
```
Maybe this should also output a suggestion that perhaps node is not installed ?

**Comment by Jakeeyturner** [comment]
Implemented in #224
