### ISSUE TITLE
Fabric 2: As a user I should be able to package a Go contract outside of my GOPATH

### ISSUE THREAD

**Issue by awjh-ibm** [IBM-Blockchain/blockchain-vscode-extension#1653]
Newer version of Go allow for Go Modules which means it is no longer necessary for a Go project to be developed inside the GOPATH.

## Description
Using Go Modules Go chaincode can now define the modules it needs without having to grab them relative to the Go path. Fabric peers do not handle Go modules but using `go mod vendor` a vendor folder can be created which the peer will use to find missing modules. The peer already uses this folder since it does not have within its GOPATH all possible.

Currently when trying to package a smart contract that is not within the GOPATH an error is received which states it must be. This does not fit with how newer versions of Go are designed to be used. The benefit of implenting the updated version would mean that code from fabric samples (e.g. Fabcar) would not need to be placed in GOPATH before it could be run.

## Expected Behavior
I should be able to package my chaincode so long as a `.mod` file exists to state which imports are required.

Desirable behaviour would be that the vendor folder is generated for me and put in the packahge, but not put in my project in if I haven't already created one. <- EDIT Seems that in master this has been fixed

## Actual Behavior
An error appears saying I need to be in my GOPATH

## Possible Fix
`packageSmartContractCommand.ts -> packageSmartContract` contains an if for golang and throws an error if not in the GOPATH. 

A fix will also be required in `fabric-client` since the Go packager attempts to prefix the path given to it with the GOPATH.

## Steps to Reproduce
1. Create a new folder
2. Run `go mod init <SOME PACKAGE PATH>`
3. Open new folder in VSCode and write a simple smart contract
4. Attempt to package

## Log File
`'The Go smart contract is not a subdirectory of the path specified by the environment variable GOPATH. Please correct the environment variable GOPATH.'`

## Your Environment
* IBM Blockchain Platform Extension Version: 1.0.15
* Visual Studio Code version: 1.40.1
* Operating System and version: MacOS

**Comment by awjh-ibm** [comment]
Releated fabric-client issue->  https://jira.hyperledger.org/browse/FAB-17102

**Comment by cazfletch** [comment]
closing as this will be fixed when we support fabric 2

**Comment by jambonrose** [comment]
Hi,

Is Go module support planned for HLF 1.4 Go contracts? Or is this work limited to HLF 2.0 ? If this feature is planned to support HLF 1.4, do you have a estimate on delivery of this feature?

I note:
1. the sample project provided by the extension uses Go modules (a `go.mod` file is included in the example Go project)
2. [FAB-17102](https://jira.hyperledger.org/browse/FAB-17102) is closed, but that [the 1.4 release of `fabric-client` still expects the use of`GOPATH`](https://github.com/hyperledger/fabric-sdk-node/blob/release-1.4/fabric-client/lib/packager/Golang.js#L30). 

Related issue: https://github.com/IBM-Blockchain/blockchain-vscode-extension/issues/1799
