### ISSUE TITLE
Installing prerequisites

### ISSUE THREAD

**Issue by 2-cluster** [IBM-Blockchain/blockchain-vscode-extension#1662]
When i install the prerequisites, the extension recognizes that i have installed docker-compose and golang but does not disappear from the missing prerequisites list, the version should be oke, like shown in the picture. 

![image](https://user-images.githubusercontent.com/57709435/69184200-b0b31800-0b14-11ea-8fa9-1ce03ad57574.PNG)

**Comment by Jakeeyturner** [comment]
Hi @2-cluster,

Those pre-requisites are still displaying as your installed versions of Docker Compose and Go are less than the required versions.

You'll need to install a version of Docker Compose greater than or equal to 1.14.0 (currently you have 1.8.0) as well as a version of Go greater than or equal to 1.12.0 (currently you have 1.6.2).

Thanks,
Jake
