### ISSUE TITLE
Error instantiating Smart Contracts behind a corporate proxy

### ISSUE THREAD

**Issue by hidiego** [IBM-Blockchain/blockchain-vscode-extension#1668]
## Description
I am getting error: Error instantiating smart contract: REQUEST_TIMEOUT when trying to instantiate a Smart Contract behind a corporate proxy. 

## Expected Behavior
Get proxy variable from HTTP_PROXY environment variables or similar

## Actual Behavior
Get REQUEST_TIMEOUT because npm inside container doesn't have proxy configuration 

## Possible Fix
In a local Hyperledger network based on the first-network example, I managed to solve this by modifying the Dockerfile inside the core folder. This is my Docker file modified:

FROM hyperledger/fabric-ccenv:1.4.2

ARG HTTP_PROXY
ENV HTTP_PROXY=$HTTP_PROXY

RUN npm config set proxy $HTTP_PROXY
RUN npm config set https-proxy $HTTP_PROXY

## Steps to Reproduce

1. Connect to a network behind a corporate proxy
2. Generate new project from IBM Blockchain Platform extension in VS Code
3. Install Smart Contract
4. Instantiate Smart Contract (error here)

## Existing issues
None found

## Log File
[8-Local Fabric.log](https://github.com/IBM-Blockchain/blockchain-vscode-extension/files/3869654/8-Local.Fabric.log)

## Your Environment
* IBM Blockchain Platform Extension Version: 1.0.15
* Visual Studio Code version:  1.40.0
* Environment name and version: Node.js v10.17.0, npm v6.11.3
* Operating System and version: 18.04.1-Ubuntu

**Comment by hidiego** [comment]
?

**Comment by fabriciomind** [comment]
Hi!

I am facing this issue with the local fabric provided by the extension.

Can't find a way to fix this because I can't find the "Dockerfile in the core folder".

Help!

**Comment by cazfletch** [comment]
the docker file is in `~./.fabric-vscode/environments/Local Fabric`

**Comment by fabriciomind** [comment]
Hey Caroline,

I am probably missing something...
![folder](https://user-images.githubusercontent.com/3759002/73860511-6c353f80-481a-11ea-95fa-e655482db2bf.png)

I don't have a Dockerfile.

:sob:

**Comment by cazfletch** [comment]
The docker-compose.yml file

**Comment by cazfletch** [comment]
closing as the local fabric doesn't use a docker compose file anymore
