### ISSUE TITLE
update blockchain category

### ISSUE THREAD

**Issue by caroline-church** [IBM-Blockchain/blockchain-vscode-extension#168]
since vscode has updated they have added two new commands but they are prefixed with `IBM Blockchain Platform` this makes them different to ours so we should update ours to have the same prefix

**Comment by Jakeeyturner** [comment]
As part of this issue, did we also want to change the category for Fabric related commands such as Start Fabric, Stop Fabric, Restart Fabric?

**Comment by caroline-church** [comment]
done so closing
