### ISSUE TITLE
How to solve this problems?

### ISSUE THREAD

**Issue by GZK0329** [IBM-Blockchain/blockchain-vscode-extension#1695]
![problem](https://github.com/GZK0329/GZK0329tuchuang.github.io/raw/master/%E6%88%AA%E5%B1%8F2019-11-25%E4%B8%8B%E5%8D%887.40.41.png)

![add1](https://github.com/GZK0329/GZK0329tuchuang.github.io/raw/master/%E6%88%AA%E5%B1%8F2019-11-27%E4%B8%8B%E5%8D%882.23.29.png)

![add2](https://github.com/GZK0329/GZK0329tuchuang.github.io/raw/master/%E6%88%AA%E5%B1%8F2019-11-27%E4%B8%8B%E5%8D%882.23.40.png)

**Comment by Jakeeyturner** [comment]
Hi @GZK0329,

[Please see this issue (and comment).](https://github.com/IBM-Blockchain/blockchain-vscode-extension/issues/1621#issuecomment-552926559)

Thanks,
Jake
