### ISSUE TITLE
As a user i can see the endorsement policy that an instantiated smart contract has

### ISSUE THREAD

**Issue by cazfletch** [IBM-Blockchain/blockchain-vscode-extension#1717]
A user should be able to see the endorsement policy a smart contract has.

**Comment by EdMoffatt** [comment]
This will update the right-click options on an instantiated smart contract. So, hover information remains the same...
![image](https://user-images.githubusercontent.com/7454304/69877515-58210f00-12ba-11ea-9282-ce4580d6ef8a.png)

But then on right-click there's a new option (in addition to the existing "upgrade")...
![image](https://user-images.githubusercontent.com/7454304/69877700-ca91ef00-12ba-11ea-920a-9e87d6552bc2.png)

Endorsement policy will open as a temporary file for viewing. (Could we have it named with the Smart Contract and the Channel both appearing in the name??)

**Comment by Jakeeyturner** [comment]
We'll need to have a think about how we want to present this as when you get the endorsement policy, it's not in the exact same format as when you initially set it.

When instantiating with the policy:
```
{
   "identities": [
       { "role": { "name": "member", "mspId": "ecobankMSP" }},
       { "role": { "name": "member", "mspId": "finregMSP" }},
       { "role": { "name": "member", "mspId": "digibankMSP" }}
   ],
   "policy": {
       "2-of": [{ "signed-by": 0 }, { "signed-by": 1 }, { "signed-by": 2 }]
   }
}
```

When we try to retrieve the endorsement policy we get the following:
<img width="488" alt="Screenshot 2019-12-02 at 14 27 27" src="https://user-images.githubusercontent.com/10009752/70313569-c7908480-180d-11ea-818d-431ec7dddc28.png">

(where layouts determine the number of peers from each group which would result in successful endorsement)

**Comment by Jakeeyturner** [comment]
@sstone1 did some more investigation and found out the following:

The discovery service takes the endorsement policy and calculates all the possible plans and sends that out to the SDKs, which is what `channel.getEndorsementPlan()` returns. This is not the same as the chaincode endorsement policy that the smart contract was instantiated/upgraded with.
 
You have to send a `getccdata` transaction to the lscc chaincode (lifecycle system chaincode).
It returns a serialized [ChaincodeData object](https://godoc.org/github.com/hyperledger/fabric-protos-go/peer#ChaincodeData) which has the endorsement policy (SignaturePolicyEnvelope)

This looks something like:
```
{
    rule: {
        N: 2,
        rules: [
           { signedBy: 0 },
           { signedBy: 1 }
        ] 
    },
    identities: [ ... ]
}
```
This is not in the same format as when instantiating/upgrading a smart contract with a policy using the SDK.

We should think about how we want to address this before we continue any further.
