### ISSUE TITLE
How do I install the specific version of node.js required. 

### ISSUE THREAD

**Issue by pquodling** [IBM-Blockchain/blockchain-vscode-extension#1718]
## Description
 The installation has a mandatory requirement for an older version of node.js - either 8.* or 10.* - the current (installed) is 13.2.0 

How do I install an old version of node.js to satisfy this requirement.

**Comment by cazfletch** [comment]
Hi @pquodling you can download older versions here https://nodejs.org/en/download/releases/

**Comment by pquodling** [comment]
Finding where the releases are is easy enough - working out how to install a old version in place of a newer one, is the main concern. 

PetersLaptop  ~  node --version   SIG(127) ↵  1008  17:40:01
v10.17.0

I am now seeing this on firing up VScode. 

Failed to activate extension: Failed to execute command "npm" with  arguments "rebuild, grpc, --target=6.1.5, --runtime=electron, --update-binary, --fallback-to-build, --target_arch=x64, --dist-url=https://atom.io/download/electron" return code 1

**Comment by cazfletch** [comment]
if you use nvm https://github.com/nvm-sh/nvm that lets you easily switch between node versions. What version of vscode do you have?

**Comment by pquodling** [comment]
Hmm, went to "Code: About Visual Studio Code" and it says

**Comment by cazfletch** [comment]
you didn't add the version in your comment

**Comment by pquodling** [comment]
cut and paste did someething weird...  go to about vscode and get (and yet a terminal session with node --version says 10.17.0 )Version: 1.40.2
Commit: f359dd69833dd8800b54d458f6d37ab7c78df520
Date: 2019-11-25T14:52:45.129Z
Electron: 6.1.5
Chrome: 76.0.3809.146
Node.js: 12.4.0

**Comment by pquodling** [comment]
and I tried a brew install nvm and it says it's already up to date at 0.35.1 yet an nvm command says 

zsh: command not found: nvm

**Comment by cazfletch** [comment]
then nmv isn't in your path. I found just using the curl command it gives you to install it works fine.

**Comment by cazfletch** [comment]
rebuilding grpc is a known issue at vscode 1.40 you should downgrade to vscode 1.39 see the pinned issue
