### ISSUE TITLE
Ops Tools - Change flow: ask user for environment name *after* establishing connection

### ISSUE THREAD

**Issue by lquintai** [IBM-Blockchain/blockchain-vscode-extension#1744]
This Issue reflects the change in usability flow for connecting to an ops tools instance, in accordance with the requested flow to connect to an IBM cloud instance (future work)..

The order of events will now be:
- ask the user to select add environment method
- if ops tools, ask for URL, api key and API secret
- try to establish connection
  - ask for CA certificate chain if needed, and try again
- save CA certificate file and store key and secret
- ask user to chose a name for the environment
- ask the user to select which nodes to import

**Comment by cazfletch** [comment]
done so closing
