### ISSUE TITLE
As a developer i can configure the local fabric

### ISSUE THREAD

**Issue by caroline-church** [IBM-Blockchain/blockchain-vscode-extension#175]
Need to decide what configurations

**Comment by caroline-church** [comment]
Give this to Sim! :)

**Comment by simran-sohanpal** [comment]
Notes from meeting with Matthew:

- T-shirt sizes: S,M,L
- S: 1 peer and 1 org
- M: 2 peers and 2 orgs and 1 channel
- L: 3 peers and 3 orgs and 2 channels (to be able to test private data to see how it works) - check with Nick, Paul & Rob
- Upper limit on peers should be 7

**Comment by sstone1** [comment]
My one thing to bear in mind is - whatever configurations we pick, we'll never be able to please everyone. They will always want to adjust _something_ - most common thing will be number of organisations, number of channels, and configuration for things like Identity Mixer and private data collections.

Number of peers, number of orderer nodes, consensus algorithms (solo vs kafka vs raft) are all very much operational and we should avoid doing anything on those. One peer per org, one solo orderer - nothing more.

**Comment by caroline-church** [comment]
We should then let the user export the config for a network so that they can then edit this to suit the env they want

**Comment by EdMoffatt** [comment]
Just to concur with some of the comments here... :)

1. T-Shirt sizes sound good - also the descriptions of what's in them!
2. In terms of customisation, I think this is where we look to have a separate issue for "as a dev I can achieve a specific configuration in my local_fabric"

I like the idea of a format that describes a Fabric config, which could then be given to VSCode to spin up the local_fabric in that shape.  Say a .json file for example.  If the IBP Ops Tools could export such a thing and the IBP Dev Tools could use such a thing to configure a local fabric, we'd allow folks to easily recreate their cloud environments locally for dev/test.  Which sounds neat :)

I'd definitely like to handle that as a separate issue if we can though?

**Comment by caroline-church** [comment]
Yes agreed it should def be a separate issue. Do you want to make this an epic and add the issues separately to break it down further maybe each T-shirt size should be an issue then customising but could be an issue

**Comment by simran-sohanpal** [comment]
Will track work for choosing a configuration here, as it will apply to all the separate issues for each size.

**Comment by simran-sohanpal** [comment]
Chatting to Ed, we have a couple ideas of how a user would choose which configuration they want:
- the user right-clicks the 'local_fabric' connection and selects which config they want:
![screenshot 2018-12-17 at 12 05 15](https://user-images.githubusercontent.com/41570203/50086146-0b9d0a80-01f4-11e9-8883-420da07bc3c9.png)
(there would need to be some initial intro/explanation of what each config comprises of)
- running a command to 'choose config' + selecting option in command palette dropdown:
![screenshot 2018-12-17 at 12 09 50](https://user-images.githubusercontent.com/41570203/50086358-ac8bc580-01f4-11e9-90d7-7802cf8cc9e1.png)
(again there needs to be some kind of explanation of what each config includes)

**Comment by simran-sohanpal** [comment]
Is anything affected when you move from size-to-size i.e. is anything blown away?

**Comment by heatherlp** [comment]
it depends on whether we're planning on reusing the containers or having a separate set for each size. If it's the latter, then we wouldn't need to worry about trashing stuff on moving between them - but would the users want them all listed in the tree view so they can easily move between them?

**Comment by simran-sohanpal** [comment]
![screenshot 2018-12-18 at 10 41 11](https://user-images.githubusercontent.com/41570203/50148862-85df9480-02b1-11e9-830b-f62fffe5acda.png)

**Comment by simran-sohanpal** [comment]
One idea for switching between each size + showing which size the user is currently using:
![screenshot 2018-12-18 at 13 12 52](https://user-images.githubusercontent.com/41570203/50156398-a8c87380-02c6-11e9-9ec8-a03a0145ffb9.png)

**Comment by heatherlp** [comment]
So after a discussion on slack earlier today, we've agreed:

- one managed runtime within VSCode, with a "configure runtime" or similar command available, which allows the user to select the size of configuration they want (see command palette designs above). Docker containers need to be recreated between size change. 
- not explicitly going to show the user what size the local_fabric is in the tree view

**Comment by EdMoffatt** [comment]
To finish up on this one, I think this is the design we're going with:
![image](https://user-images.githubusercontent.com/7454304/50650482-767e6d80-0f78-11e9-8027-bc67e7374c4e.png)
We should clarify:
1) How the user gets that command prompt up
2) What descriptions we're putting against each of those
3) Confirm if we're actually having that "Custom" option and what happens if they click it (think it's shown in some of the screens above, but not sure)

Essentially, I'd like us to have a single complete step-by-step flow of designs so that we know what we're expecting from the implementation, please :)

**Comment by simran-sohanpal** [comment]
For how the user gets the command prompt up - my initial thought was a right-click menu on local_fabric:
![screenshot 2019-01-07 at 09 47 12](https://user-images.githubusercontent.com/41570203/50761095-69f06280-1261-11e9-9843-10fc18822d6b.png)

**Comment by simran-sohanpal** [comment]
For each config description - what information other than what each config consists of is needed? & would this be a wordy description? Below I've just added what was decided for each config as an initial idea:
![screenshot 2019-01-07 at 09 57 44](https://user-images.githubusercontent.com/41570203/50761644-d586ff80-1262-11e9-9319-6531a4ea7a92.png)
@heatherlp @caroline-church @sstone1 ?

**Comment by simran-sohanpal** [comment]
Confirmation of whether or not we're having the 'custom' option needed but if we decide to have the option -  my initial idea was a window appearing for the user to choose the config file from: 
![screenshot 2019-01-07 at 10 09 20](https://user-images.githubusercontent.com/41570203/50762291-70340e00-1264-11e9-9fd0-82420a74325c.png)
I wonder if there needs to be some indication in the options list of what needs to be provided to specify the custom config i.e. a (.json?) file?

**Comment by caroline-church** [comment]
closing as not doing t-shirt sizes anymore
