### ISSUE TITLE
Ops Tool - Hide node in vscode (when right click a node)

### ISSUE THREAD

**Issue by au-shah** [IBM-Blockchain/blockchain-vscode-extension#1751]
To be initially delivered to OpsTool feature branch

When a user right clicks a node, show `Hide node` option. When selected, set property of node in JSON to hidden & remove this node from the list of nodes shown.

If there are no nodes left to show, display environment as disconnected.
When connecting to an empty environment (i.e. without nodes) do not allow to connect - instead, provide a popup asking if they wish to filter nodes.. If no, don't connect. If yes, show edit filters (and if ticked atleast one node, connect to environment)

**Comment by cazfletch** [comment]
done so closing
