### ISSUE TITLE
Update output log

### ISSUE THREAD

**Issue by caroline-church** [IBM-Blockchain/blockchain-vscode-extension#176]
We should tidy up the output log to make it more "yipee" 

- [ ] make it more obvious what the thing being displayed in the log is doing
- [ ] update extension activating to include the name of the extension

**Comment by Jakeeyturner** [comment]
It might be worth creating multiple output channels to display different levels of logging information.

**Comment by Jakeeyturner** [comment]
Fixed in PR #386
