### ISSUE TITLE
Improve transaction output format

### ISSUE THREAD

**Issue by erin-hughes** [IBM-Blockchain/blockchain-vscode-extension#1770]
The output from transactions submitted in VS Code currently displays in the console, but can be difficult to read. We should come up with ways to improve how we show this to users.

Will possibly extend/modify the work done in issue #1488.

**Comment by erin-hughes** [comment]
Based on our meeting with MGK this morning, I did a bit of sleuthing to find out what we could possibly show in the output panel that would be useful to a user.

Things that we're already doing/have access to in the extension:

- The name of the transaction;
- The input arguments and transient data (the latter we could get from the input box in the transaction view);
- If the transaction was a submit or an evaluate;
- If the transaction was a success or failure;
- Any input returned from the transaction.


Things that live in the blocks (which we don't currently access in the extension):

- The transaction ID;
- The timestamp taken when the transaction was submitted (but we could just take a timestamp in the extension just before we send off the transaction);
- The read/write sets.


Things that 🤷‍♀:

- Who endorsed the transaction - this is lower level, I think you can figure it out using fabric-client? But not using fabric-network, which is what the extension uses;
- What the endorsement policy was - we talked about this earlier, but it's not possible to get the endorsement policy information back from fabric in the same format that it was input.

**Comment by erin-hughes** [comment]
Opened a separate issue for showing who signed a transaction: #1811

**Comment by erin-hughes** [comment]
Parking this issue as we're focusing on being able to submit test data files. The progress that I've made is contained in pull request #1812

**Comment by Jakeeyturner** [comment]
Done.
