### ISSUE TITLE
As a user the welcome page tells me i am now using fabric 2.0

### ISSUE THREAD

**Issue by cazfletch** [IBM-Blockchain/blockchain-vscode-extension#1779]

**Comment by Charlotte8699** [comment]
# Initial ideas
Had a brainstorming session this morning on this issue and come up with the following ideas - please leave feedback/message me on slack if you have any further ideas.

## 1. Simple VS Code notification
<img width="862" alt="Screenshot 2020-07-01 at 10 59 26" src="https://user-images.githubusercontent.com/52786879/86231116-ef6c7e80-bb89-11ea-99e0-a1f943b719dc.png">

**Thoughts**
- Probably get lost with other notifications; I feel like the fabric v2.0 update is more important than just a standard notification

## 2. Notification on the homepage
<img width="640" alt="Screenshot 2020-07-01 at 11 01 02" src="https://user-images.githubusercontent.com/52786879/86231242-28a4ee80-bb8a-11ea-8a7f-d256d24500cb.png">

**Thoughts**
- Could provide a link for the user to learn more about the update + direct them to the best places to get started using the update
- Space may be a bit limited... want to avoid the user scrolling as much as possible
- May still miss this notification if they often just close the home screen

## 3. Pop up notification
<img width="644" alt="Screenshot 2020-07-01 at 11 03 36" src="https://user-images.githubusercontent.com/52786879/86231481-846f7780-bb8a-11ea-8893-10a2ec93adfe.png">

**Thoughts**
- Similar pop up style to the architecture diagram in the console
- Allows for much more info about update being put on screen without having to scroll
- Might be annoying to users... but this is information they should be taking the time to understand

**Comment by Charlotte8699** [comment]
# Update
Been having a think about a few different things today on this issue... so will go through those!

### My thoughts
- This 'congrats for upgrading to v2.0' notification will only appear to people who have upgraded to v2.0 from v1.4... those who have installed it for the first time wont want to know about the new 'things' in the extension and fabric if they never even worked with v1.4.
- A side panel would be the best way of displaying this information; a user may not look at the welcome screen to see the upgrade notification and waaaaay more information can be shown in a panel without making the user scroll for it. HOWEVER, after discussions with Jake, I've added in a notification on the welcome screen so a user is able to reopen this notification... will go more into the flow of this further down.

### The designs

Presently I'm waiting to see what the 'i've just upgraded screen' looks like to see how the side panel would open initially, but for now.... here is the flow for a user opening the panel from the welcome page.

**1. User opens welcome screen and sees notification regarding fabric v2.0**

<img width="1130" alt="Screenshot 2020-07-02 at 16 23 08" src="https://user-images.githubusercontent.com/52786879/86378033-0fcb3480-bc81-11ea-8863-5056cead781c.png">

- Not sure about the rocket icon but I want to somehow differentiate this from the tutorials tile

**2. "Welcome to Fabric v2.0" panel opens**

<img width="1129" alt="Screenshot 2020-07-02 at 16 23 17" src="https://user-images.githubusercontent.com/52786879/86378038-122d8e80-bc81-11ea-8579-cfd94be48498.png">

- Opinions on the way i'm showing 'what's new'?
- I feel like having an open accordion is a good way of showing it, but the deployment view and tutorial parts may get lost if the user just instantly closes this panel when it opens
- Not really sure what to do with the 'i've got a production env. help me with bugs' and 'learn more about fabric v2.0' parts as they are important but look strange here


Feedback welcome!

**Comment by Charlotte8699** [comment]
# Flow for 'i've just updated to v2.0'
So the one above is just where you want to reopen the panel for the second time, this examines the flow for updating and getting the panel pop up automatically once the extension has been updated.

Assuming the user has done the whole **go to extensions** --> **sees 'reload required'** --> **clicks 'reload required'**

### Welcome screen opens automatically with update

Once the extension has been reloaded, this update page appears
<img width="947" alt="Screenshot 2020-07-03 at 09 47 14" src="https://user-images.githubusercontent.com/52786879/86451017-3b4a2f80-bd12-11ea-8792-eb0245f5b415.png">

Followed by the welcome page... I imagine the panel would open automatically with the welcome page like this
<img width="942" alt="Screenshot 2020-07-03 at 09 47 20" src="https://user-images.githubusercontent.com/52786879/86451473-e0fd9e80-bd12-11ea-9412-d0d9435faf9a.png">

### Welcome screen is disabled from opening automatically by the user

Users can disable the welcome screen opening automatically meaning merely having a button to get the panel open on the welcome screen may mean some users miss this notification.

<img width="931" alt="Screenshot 2020-07-03 at 09 53 56" src="https://user-images.githubusercontent.com/52786879/86451643-1e622c00-bd13-11ea-84e9-6a617363298c.png">

Here it opens with the updates page with a message towards the top stating that if the user doesn't want to read this now, they can find it again on the welcome screen.


@EdMoffatt

**Comment by Charlotte8699** [comment]
# UPDATE
Had a meeting with @Jakeeyturner & @erin-hughes about the designs so this will include their feedback
The designs above would be possible if the panel and shadow were kept within the extension window, so I will produce some designs for that - however, below I have done some designs for an alternative way of showing this information.

### Tab focussing on telling the user about the new chaincode lifecycle
<img width="1071" alt="Screenshot 2020-07-13 at 14 51 07" src="https://user-images.githubusercontent.com/52786879/87312302-4a05c300-c518-11ea-9ff2-e0e9d967dd59.png">

### Tab focussing on tutorials to help users get started using new chaincode lifecycle
<img width="1075" alt="Screenshot 2020-07-13 at 14 51 27" src="https://user-images.githubusercontent.com/52786879/87312345-55f18500-c518-11ea-8084-7c5471e1f960.png">
- Personally prefer the visuals on this as it grabs the attention more due to the colours, but maybe there is less useful information on this one compared to the first?

### Feedback;
- Combination of both these ideas; "this is the new chaincode lifecycle, and here is the relevant tutorial for this bit of information"
- First idea can be done as a markdown file, second idea has to be done as a web view... perhaps the first is easier to implement (?)

**Comment by Charlotte8699** [comment]
# UPDATE

Had some feedback from design this morning, they key points were;
- Liked the tab opening next to the homepage more than the shadow disabling the rest of the extension
- Preferred the 'what's new' version over the 'go to relevant tutorial' version
- Is telling the user about the Fabric v2.0 chaincode lifecycle first the best thing? deployment flow explains it in a nicer way so direct them to that first

Based on those points, i've generated a few more mock ups

## Layout 1: Using the "What's new" accordion

Changes;
- Deploy view now first in accordion with suggestions to visit relevant tutorials
- Chaincode lifecycle is second with suggestions to visit fabric docs 

### Initial view with 1 section expanded
<img width="913" alt="Screenshot 2020-07-21 at 15 27 42" src="https://user-images.githubusercontent.com/52786879/88067294-b9a62e80-cb66-11ea-93e7-30887e5097ac.png">

### Both sections expanded
<img width="913" alt="Screenshot 2020-07-21 at 15 27 55" src="https://user-images.githubusercontent.com/52786879/88067317-c165d300-cb66-11ea-89f9-fd2b9326f843.png">

## Layout 2: Alternative way of dividing up information

Having 2 items in an accordion seems a bit pointless to me as all info can fit on 1 page - so this is me trying to figure out how best to divide up the information so the user doesn't get too overwhelmed by the sheer amount of text.

### Dividing information by informative tiles
<img width="917" alt="Screenshot 2020-07-21 at 15 28 07" src="https://user-images.githubusercontent.com/52786879/88067352-c88ce100-cb66-11ea-91eb-58e1ccb0af2f.png">

I quite like this but not sure if there is the best layout

## Feedback request
Again, @Jakeeyturner and @erin-hughes feel free to slack me/ comment on this thread with any feedback!

Looking for feedback on the following;
- General layout
- Content (Phrasing, what might be missing, what isn't neccessary etc.)

**Comment by Charlotte8699** [comment]
# HANDOVER 

### General layout

**Diagram showing where the tile and tab go within the UI**
<img width="911" alt="Screenshot 2020-07-24 at 12 03 09" src="https://user-images.githubusercontent.com/52786879/88385110-a7fe9a00-cda5-11ea-805f-a6b578facd0b.png">

Notes
- The tab will automatically open on the right hand side next to the welcome screen
- The tile will disappear from the welcome screen after a certain number of updates (maybe 3? @Jakeeyturner what's your thoughts on this?)


## Hi fis 
### Dark theme hi fis

**Welcome screen tile**
<img width="568" alt="Screenshot 2020-07-24 at 12 06 40" src="https://user-images.githubusercontent.com/52786879/88385389-23f8e200-cda6-11ea-8762-912333e787b5.png">
Notes
- Rocket icon centrally aligns vertically with the heading

**The tab - initial view**
<img width="822" alt="Screenshot 2020-07-24 at 12 08 42" src="https://user-images.githubusercontent.com/52786879/88385525-6cb09b00-cda6-11ea-919f-18afdf24b3fb.png">

Notes
- This is how the tab will open initially (the first option in the accordion open)
- Rocket icon and tag centrally align vertically


**The tab - fully expanded accordion**
<img width="823" alt="Screenshot 2020-07-24 at 12 11 05" src="https://user-images.githubusercontent.com/52786879/88385697-c1541600-cda6-11ea-9e81-236a4f534676.png">

Notes
- The blue links in the first section of the accordion direct to the relevant sections of vs code (A3: Deploying.... --> a3 tutorial, Tutorial gallery --> the tutorials page)
- Blue link directing to fabric docs in second section of the accordion goes here [
https://hyperledger-fabric.readthedocs.io/en/latest/chaincode_lifecycle.html]

### Light theme hi fis

**Welcome screen tile**
<img width="582" alt="Screenshot 2020-07-24 at 12 13 42" src="https://user-images.githubusercontent.com/52786879/88385864-1ee86280-cda7-11ea-9929-1494ca9ff74f.png">

**The tab - initial view**
<img width="843" alt="Screenshot 2020-07-24 at 12 14 13" src="https://user-images.githubusercontent.com/52786879/88385893-31629c00-cda7-11ea-85f3-3e534d76fd69.png">

**The tab - fully expanded accordion**
<img width="844" alt="Screenshot 2020-07-24 at 12 14 32" src="https://user-images.githubusercontent.com/52786879/88385921-3cb5c780-cda7-11ea-932a-ccd6e365f493.png">

All notes from dark theme apply here as well


## Pixel measurements

**Tile measurements**
<img width="715" alt="Screenshot 2020-07-24 at 12 37 45" src="https://user-images.githubusercontent.com/52786879/88387504-7b994c80-cdaa-11ea-9c69-5eb058c45c62.png">

**Tab measurements**
<img width="703" alt="Screenshot 2020-07-24 at 12 37 09" src="https://user-images.githubusercontent.com/52786879/88387468-658b8c00-cdaa-11ea-8419-df0286a48df8.png">

## Files
Box folder for designs; https://ibm.box.com/s/2gyv7cjw6t5tqxr0spk7w4smehk735da 

## Notes for @erin-hughes 
Slack me if I've missed anything!

**Comment by erin-hughes** [comment]
Closed by #2568
