### ISSUE TITLE
As a user i can get beta versions of the extension that supports 2.0

### ISSUE THREAD

**Issue by cazfletch** [IBM-Blockchain/blockchain-vscode-extension#1780]
We should add the vsix to a github release so that users can get the vsix from there.

This should be added for 1.x and 2.x . We should be able to do a release of either version but only 1.x are published to the market place

**Comment by cazfletch** [comment]
done so closing

**Comment by b-fett** [comment]
@cazfletch as i understand this should add for v2 github releases `vsix`. But i can't find any at release assets. Should it be reopened?

**Comment by Jakeeyturner** [comment]
Hi @b-fett,
For some reason the v2.0.0-beta.8 release didn't attach the VSIX automatically - it has now been fixed.

Thanks,
Jake
