### ISSUE TITLE
Extension issue

### ISSUE THREAD

**Issue by arishma108** [IBM-Blockchain/blockchain-vscode-extension#1785]
- Issue Type: `Bug`
- Extension Name: `ibm-blockchain-platform`
- Extension Version: `1.0.17`
- OS Version: `Windows_NT ia32 10.0.17763`
- VSCode version: `1.41.1`

:warning: We have written the needed data into your clipboard. Please paste! :warning:

**Comment by cazfletch** [comment]
closing as no details. Please feel free to reopen after you have provided more details
