### ISSUE TITLE
Unable to start local_fabric runtime in vscode

### ISSUE THREAD

**Issue by VinGeek15** [IBM-Blockchain/blockchain-vscode-extension#1797]
![hyperledger](https://user-images.githubusercontent.com/35720655/71705318-00b81680-2e05-11ea-9cfb-ff4717ca479b.JPG)
I'm not able to start the local_fabric runtime in vscode. It says permission denied to remove the crypto materials.

**Comment by cazfletch** [comment]
Hi @VinGeek15 can you remove it manually then try again. What OS is this on?

**Comment by cazfletch** [comment]
closing as no response
