### ISSUE TITLE
Getting error - The Go smart contract is not a subdirectory of the path specified by the environment variable GOPATH. 

### ISSUE THREAD

**Issue by manish1635** [IBM-Blockchain/blockchain-vscode-extension#1799]
Hi,

When I try to package smart contracts from IBM blockchain platform extension. Getting error - The Go smart contract is not a subdirectory of the path specified by the environment variable GOPATH. Please correct the environment variable GOPATH.

Please find attached the source code folder placed inside path (C:\Blockchain\HLFabric\From_VSCode\src\github.com).
Output of command : go env GOPATH
C:\Go;C:\Blockchain\HLFabric\From_VSCode;

[chaincode_example02.zip](https://github.com/IBM-Blockchain/blockchain-vscode-extension/files/4024941/chaincode_example02.zip)

**Comment by manish1635** [comment]
Hi, 

Apart from the above code, Please find attached error.

Regards,
Manish
[VSCodeThrowsError.zip](https://github.com/IBM-Blockchain/blockchain-vscode-extension/files/4044107/VSCodeThrowsError.zip)

**Comment by cazfletch** [comment]
closing as this will be fixed by supporting go mod files
