### ISSUE TITLE
Connection details not exposed from plugin

### ISSUE THREAD

**Issue by m-g-k** [IBM-Blockchain/blockchain-vscode-extension#181]
As a dev type person trying to use a locally (from within the plugin) installed and instantiated smart-contract package I need to be able to get the connection information to use in my app for the locally started fabric containers. Multiple possibilities abound, including an "export connection profile command" to allowing the user to specify static ports and hostnames in "VSCode settings".

**Comment by caroline-church** [comment]
assigned to Matthew White

**Comment by mbwhite** [comment]
The scenario where I encountered this was, as a developer I've written my contract, installed, instantiated the local fabric.

I then want to write some fv tests/applications against this to confirm the operation. An expectation is that I have a local directory within my project that would be a holder for the connection profile.

Therefore ask first if there's a directory before opening the file dialog for this. 

![image](https://user-images.githubusercontent.com/6673453/47418774-b653f800-d772-11e8-8abe-c2f33a014893.png)

The privatekey/certificate I'd prefer to add as a separate option; but following the same format.

**Comment by mbwhite** [comment]
@caroline-church @EdMoffatt ^fyi  just want to get your blessing on that before moving on.

**Comment by caroline-church** [comment]
@mbwhite i'm confused about your proposal, i don't understand what the actions would be

**Comment by m-g-k** [comment]
So maybe I'm misunderstanding as well, but I would try the simplest approach I can think of which is to have an "export profile" command which would automatically create a profile either in the root of the workspace or in a well-known (predefined name) folder such as "config/connectionProfile.json". And in the profile I would expect to be able to have everything needed to connect, just like I would get if I export a profile from IBP starter plan. If this makes sense and would work then I don't see the need for the "open file" dialog box at all - just let the command tell the user where it put the profile so the know where it is in a msg box.

**Comment by mbwhite** [comment]
Sorry I think I'm confusing everybody...

The steps are 

1 - right click on the running local_fabric
2 - select 'export connection profile'
3 - select the workspace folder you want the profile in, or click browse to get a standard dialog box
4 - file is written to the location
5 - standard notification appears bottom right. 

Have a video of this but can't attach those!

**Comment by mbwhite** [comment]
![ezgif com-optimize](https://user-images.githubusercontent.com/6673453/47502877-b7fbe980-d860-11e8-85fe-d727420f7f83.gif)

**Comment by mbwhite** [comment]
The branch if anybody wishes to pick this up... https://github.com/mbwhite/blockchain-vscode-extension/pull/new/export-cp

**Comment by caroline-church** [comment]
closing as this is now done
