### ISSUE TITLE
I would like to be able to work with just a CA and an MSP

### ISSUE THREAD

**Issue by m-g-k** [IBM-Blockchain/blockchain-vscode-extension#1816]
In some scenarios it an organization does not want to run a peer infrastructure, rather they want to be able to submit transactions through another organizations peer. In this scenario, the organization without any peers (let's call them smallOrg) will have an MSP that bigOrg adds to the channel they want to transact on. However, in VSCode you cannot make Gateway Connection in this scenario - you get an error about MSPs. However, if you use a command line app then smallOrg can submit transactions just fine. This appears to be because VSCode tries to query the bigOrg peer for the channel and then for the smart contracts and the channel query fails. However, if VSCode could detect this can ask the user for the name of the channel (and smart contract?) then transaction submission should work just fine.

**Comment by jt-nti** [comment]
It's unlikely that the extension will be enhanced to work for this scenario
