### ISSUE TITLE
Error: Failed to connect to any peer event hubs

### ISSUE THREAD

**Issue by moritz121** [IBM-Blockchain/blockchain-vscode-extension#1817]
Following this tutorial (https://hyperledger.github.io/composer/latest/tutorials/deploy-to-fabric-single-org) I encounter the following error when executing the "composer network start" command:

Error: Error trying to start business network. Error: Failed to connect to any peer event hubs. It is required that at least 1 event hub has been connected to receive the commit event
Command failed

## Description
After a successful development of a Hyperledger composer blockchain smart contrac, that works within the Hyperleder Playground, I've tried the following tutorial on how to set up the network for it:

https://hyperledger.github.io/composer/latest/tutorials/deploy-to-fabric-single-org

Everything is fine, until I execute the composer network start command like established by the tutorial:

composer network start --networkName tutorial-network --networkVersion 0.0.1 -A admin -S adminpw -c PeerAdmin@fabric-network

With the values according to my contract (only changing the name of the network).

This has resulted in the following error (which I presume that has nothing to do with my contract having tested it in the playground):

Error: Error trying to start business network. Error: Failed to connect to any peer event hubs. It is required that at least 1 event hub has been connected to receive the commit event
Command failed

I do not know what this referes to, neither do I find further information online. The only answers that I get for this particular problem are "check if you have misspelled the name of the channel". No official response exists to my knowledge. Maybe some of the respondants on github are part of the project (they seem to be), but they haven't answered the question in particular, only similar ones.

I have changed the "fabric-dev-servers" directory to try find the solution, but without changes it responds the same way.
I am using the hlfv12 fabric scrip, as it is the most updated, but trying in the other versions (namely hlfv1 and hlfv11) has the same results, with the same error. Every step previous to the start command is succesful and does not result in any error, and shows the expected results.

## Expected Behavior
The command tu run successfuly and the network to be started.

## Actual Behavior
Error is shown and network is not started.

## Possible Fix
None.

## Steps to Reproduce

Follow the tutorial

## Your Environment

Ubuntu 18.4.0

Composer 0.20

**Comment by cazfletch** [comment]
closing as this is not a problem with the extension but with hyperledger composer
