### ISSUE TITLE
Issue with Prerequisites Check for OpenSSL

### ISSUE THREAD

**Issue by aah50** [IBM-Blockchain/blockchain-vscode-extension#1820]
Open SSL prerequisite installation isn't being detected.
## Description

I have followed the steps to install via the prerequisites page. (https://marketplace.visualstudio.com/items?itemName=IBMBlockchain.ibm-blockchain-platform) Everything has worked well so far, however there is one prerequisite which is still marked as unresolved. I have installed Open SSL 1.1.1d into C:\OpenSSL-Win64, yet there check isnt detecting this installation.

On a side note, is it safe to bypass the check if this is the only issue?
## Your Environment

* IBM Blockchain Platform Extension Version: 1.0.17
* Visual Studio Code version: 1.39.2 (Also tried 1.41.1)
* Environment name and version (e.g. Node.js v8.12.0, npm v6.4.1): Node 10.18.0, npm 6.13.4
* Operating System and version: Windows10 Pro x64 1909 (18363.476)
* Link to your project:

**Comment by Jakeeyturner** [comment]
Hi @aah50,

I've put a fix in for this [here](https://github.com/IBM-Blockchain/blockchain-vscode-extension/pull/1802) which should be available in our v1.0.18 release.

Until then, it's safe to bypass the pre-req page check!

Thanks,
Jake
