### ISSUE TITLE
all SubConns are in TransientFailure

### ISSUE THREAD

**Issue by the-inevitable** [IBM-Blockchain/blockchain-vscode-extension#1842]
I'm trying to upgrade a chaincode in the IBM Blockchain Platform using the Console.

## Description
So, I have one chaincode with one contract in it installed on a peer and instantiated on a channel. Everything works fine with this chaincode. Now I want to upgrade the chaincode, I changed it using VS Code extension, tested it on Local Fabric Environment that the extension provides. Everything was fine until I tried to upgrade it in the Console. 

I've successfully installed new chaincode on all the peers in my channel (I have only one peer at the moment), then in the **Instantiated Smart Contracts** field blue label with text `Upgrade Available` appeared. I've opened the overflow menu and chose **Upgrade** option. After about a minute after clicking **Upgrade** in the right-side panel, `all SubConns are in TransientFailure` error was displayed. 

After that everything messed up, my peer is switching between `Pending` and `Running` state and I'm not able to see any installed smart contracts on that peer. Also, when clicking on the Peer in the Nodes tab in the Console, I see error saying `Unable to retrieve channel information from OrgName Org Peer 1.`. I'll paste all the error messages below.

Also, I am able to successfully perform all of this on my local Hyperledger Fabric network using VS Code extension. Specifically, I was able to successfully:
1) package my smart contract of version 0.0.1 
2) install it on a peer and instantiated it then on a channel
3) change the smart contract a bit, change its version to 0.0.2 and package it
4) install new smart contract with the same name, but with version 0.0.2 on a peer
5) upgrade existing smart contract on my channel by clicking right mouse button on it and choosing **Upgrade** option.

## Expected Behavior
Smart contract should be successfully instantiated on a channel using the Console.

## Actual Behavior
An error saying `all SubConns are in TransientFailure`.

## Possible Fix
Could it be because of current maintenance **MAINTENANCE: Internal Provisioning System Maintenance** that is currently in progress? Although in the maintenance description there is no mentioning of possible downtime.

## Log File
This is the error messages that appear in the IBM Blockchain Platform Console:
****************************************************************
PeerRestApi:{
    "function_name": "getChannelsOnPeer",
    "error": true,
    "msp_id": "karuschainOrgMSP",
    "stitch_msg": "all SubConns are in TransientFailure",
    "grpc_resp": {
        "status": 14,
        "statusMessage": "all SubConns are in TransientFailure",
        "headers": {
            "headersMap": {
                "access-control-allow-credentials": [
                    "true"
                ],
                "access-control-allow-origin": [
                    "https://24a4692e7280406f8f894d783c86e868-optools.euc02.blockchain.cloud.ibm.com"
                ],
                "content-type": [
                    "application/grpc"
                ],
                "grpc-message": [
                    "all SubConns are in TransientFailure"
                ],
                "grpc-status": [
                    "14"
                ],
                "vary": [
                    "Origin"
                ]
            }
        },
        "message": null,
        "trailers": {
            "headersMap": {
                "access-control-allow-credentials": [
                    "true"
                ],
                "access-control-allow-origin": [
                    "https://24a4692e7280406f8f894d783c86e868-optools.euc02.blockchain.cloud.ibm.com"
                ],
                "content-type": [
                    "application/grpc"
                ],
                "grpc-message": [
                    "all SubConns are in TransientFailure"
                ],
                "grpc-status": [
                    "14"
                ],
                "vary": [
                    "Origin"
                ]
            }
        },
        "_proxy_resp": {
            "code": 14,
            "status_message": "all SubConns are in TransientFailure"
        }
    },
    "host": "https://n1158fc-karuschainorgpeer1-proxy.karuscluster-stage-0134cc27a1ed0b90f1c557d26a061481-0000.eu-de.containers.appdomain.cloud",
    "_input2stitch": {
        "msp_id": "karuschainOrgMSP",
        "client_cert_b64pem": "LS0tLS....==",
        "host": "https://n1158fc-karuschainorgpeer1-proxy.karuscluster-stage-0134cc27a1ed0b90f1c557d26a061481-0000.eu-de.containers.appdomain.cloud",
        "funk": "getChannelsOnPeer"
    }
}
****************************************************************
peerChaincode:{
    "function_name": "getInstalledChaincode",
    "error": true,
    "msp_id": "karuschainOrgMSP",
    "stitch_msg": "all SubConns are in TransientFailure",
    "grpc_resp": {
        "status": 14,
        "statusMessage": "all SubConns are in TransientFailure",
        "headers": {
            "headersMap": {
                "access-control-allow-credentials": [
                    "true"
                ],
                "access-control-allow-origin": [
                    "https://24a4692e7280406f8f894d783c86e868-optools.euc02.blockchain.cloud.ibm.com"
                ],
                "content-type": [
                    "application/grpc"
                ],
                "grpc-message": [
                    "all SubConns are in TransientFailure"
                ],
                "grpc-status": [
                    "14"
                ],
                "vary": [
                    "Origin"
                ]
            }
        },
        "message": null,
        "trailers": {
            "headersMap": {
                "access-control-allow-credentials": [
                    "true"
                ],
                "access-control-allow-origin": [
                    "https://24a4692e7280406f8f894d783c86e868-optools.euc02.blockchain.cloud.ibm.com"
                ],
                "content-type": [
                    "application/grpc"
                ],
                "grpc-message": [
                    "all SubConns are in TransientFailure"
                ],
                "grpc-status": [
                    "14"
                ],
                "vary": [
                    "Origin"
                ]
            }
        },
        "_proxy_resp": {
            "code": 14,
            "status_message": "all SubConns are in TransientFailure"
        }
    },
    "host": "https://n1158fc-karuschainorgpeer1-proxy.karuscluster-stage-0134cc27a1ed0b90f1c557d26a061481-0000.eu-de.containers.appdomain.cloud",
    "_input2stitch": {
        "msp_id": "karuschainOrgMSP",
        "client_cert_b64pem": "LS0tLS....==",
        "host": "https://n1158fc-karuschainorgpeer1-proxy.karuscluster-stage-0134cc27a1ed0b90f1c557d26a061481-0000.eu-de.containers.appdomain.cloud",
        "funk": "getInstalledChaincode"
    },
    "translation": {
        "title": "error_getting_chaincodes",
        "translation_opts": {
            "peerName": "karuschainorgpeer1"
        },
        "details": null
    }
}
****************************************************************
peerChannels:{
    "function_name": "getChannelsOnPeer",
    "error": true,
    "msp_id": "karuschainOrgMSP",
    "stitch_msg": "all SubConns are in TransientFailure",
    "grpc_resp": {
        "status": 14,
        "statusMessage": "all SubConns are in TransientFailure",
        "headers": {
            "headersMap": {
                "access-control-allow-credentials": [
                    "true"
                ],
                "access-control-allow-origin": [
                    "https://24a4692e7280406f8f894d783c86e868-optools.euc02.blockchain.cloud.ibm.com"
                ],
                "content-type": [
                    "application/grpc"
                ],
                "grpc-message": [
                    "all SubConns are in TransientFailure"
                ],
                "grpc-status": [
                    "14"
                ],
                "vary": [
                    "Origin"
                ]
            }
        },
        "message": null,
        "trailers": {
            "headersMap": {
                "access-control-allow-credentials": [
                    "true"
                ],
                "access-control-allow-origin": [
                    "https://24a4692e7280406f8f894d783c86e868-optools.euc02.blockchain.cloud.ibm.com"
                ],
                "content-type": [
                    "application/grpc"
                ],
                "grpc-message": [
                    "all SubConns are in TransientFailure"
                ],
                "grpc-status": [
                    "14"
                ],
                "vary": [
                    "Origin"
                ]
            }
        },
        "_proxy_resp": {
            "code": 14,
            "status_message": "all SubConns are in TransientFailure"
        }
    },
    "host": "https://n1158fc-karuschainorgpeer1-proxy.karuscluster-stage-0134cc27a1ed0b90f1c557d26a061481-0000.eu-de.containers.appdomain.cloud",
    "_input2stitch": {
        "msp_id": "karuschainOrgMSP",
        "client_cert_b64pem": "LS0tLS...==",
        "host": "https://n1158fc-karuschainorgpeer1-proxy.karuscluster-stage-0134cc27a1ed0b90f1c557d26a061481-0000.eu-de.containers.appdomain.cloud",
        "funk": "getChannelsOnPeer"
    },
    "peerName": "Karuschain Org Peer 1"
}

## Your Environment

I'm trying to perform smart contract upgrade using IBM Blockchain Platform and the Console, I'm using paid kubernetes cluster with 32GiB of RAM, there is enough resources (not more than 10-12% used as shown in Kubernetes dashboard).

**Comment by the-inevitable** [comment]
@cazfletch @sstone1 @mbwhite 
Please take a look if possible. Could it really be due to maintenance in progress?

**Comment by cazfletch** [comment]
Hi @the-inevitable it sounds from your description like everything was working in the VSCode extension and the problem is when you try and do it in the operational console. If so then you should raise an issue with the operational console.

**Comment by flaviomauro** [comment]
Hello @the-inevitable. Have you found the root cause and/or solution for this problem?
