### ISSUE TITLE
1. Failed to activate extension: spawn cmd.exe ENOENT

### ISSUE THREAD

**Issue by Krishna812** [IBM-Blockchain/blockchain-vscode-extension#1860]
When installed this extension in vs code got 2 errors. Also i have installed node.js and i ensured this installation in cmd but it shows error in vscode.

![image](https://user-images.githubusercontent.com/37139394/73582301-907bcf80-445a-11ea-9f79-c0d028390586.png)

2.

**Comment by cazfletch** [comment]
What version of the extension do you have? Does the prereqs check show you have all the dependencies?

**Comment by cazfletch** [comment]
closing as no response
