### ISSUE TITLE
Support for hyperledger fabric 2.0 ?

### ISSUE THREAD

**Issue by bigworld12** [IBM-Blockchain/blockchain-vscode-extension#1873]
does/will the extension support hyperledger fabric 2.0 ?

**Comment by cazfletch** [comment]
It doesn’t currently but it will do in the future

**Comment by siddjain** [comment]
ping on this...

**Comment by ssword62** [comment]
any news?

**Comment by cazfletch** [comment]
This is still a work in progress. We hope to have beta versions as github releases soon
