### ISSUE TITLE
Sort out cucumber tests

### ISSUE THREAD

**Issue by cazfletch** [IBM-Blockchain/blockchain-vscode-extension#1874]
The cucumber tests take too long to run and we should add in some extra tests

**Comment by jt-nti** [comment]
Suggestion from #1644

> One suggestion is to split up the tests by contract language into separate jobs. This would speed up the cucumber tests and we'd be able to restart any separate jobs that failed randomly.

**Comment by jt-nti** [comment]
See #3183
