### ISSUE TITLE
As a user i can stop my local fabric and start it again without everything being deleted

### ISSUE THREAD

**Issue by caroline-church** [IBM-Blockchain/blockchain-vscode-extension#190]
Add in a stop command that doesn't delete stuff, but keep a reset local fabric incase you want to actually start again

**Comment by sstone1** [comment]
Proposal:

1) Fabric scripts updated to use volumes to persist the data, and ensure that the volumes are only removed during a "teardown" operation - "start" and "stop" should just do what they say on the tin.

2) New "Teardown Fabric Runtime" command that performs a "teardown" operation.

3) Command is available from the connections tree by right clicking:

![screen shot 2018-10-16 at 14 06 54](https://user-images.githubusercontent.com/7118158/47018505-c9e8d880-d14c-11e8-9d1b-cfcfbe596e5d.png)

4) Command is available from the command palette:

![screen shot 2018-10-16 at 14 08 01](https://user-images.githubusercontent.com/7118158/47018575-ea189780-d14c-11e8-9f7a-b9e07f563d72.png)

5) The command prompts the user with a warning to say this is destructive, are you sure?

![screen shot 2018-10-16 at 14 08 33](https://user-images.githubusercontent.com/7118158/47018643-0d434700-d14d-11e8-889c-0cacf1031462.png)

6) Assuming the user clicks "Yes", then everything is destroyed. If the Fabric was running before, it is not restarted until the user explicitly starts it again.

@EdMoffatt @caroline-church thoughts? You like?
