### ISSUE TITLE
A developer can deploy their Fabric v2 smart contract packages to an environment

### ISSUE THREAD

**Issue by EdMoffatt** [IBM-Blockchain/blockchain-vscode-extension#1902]
Deployment of Fabric v2 smart contracts uses the new chaincode lifecycle flow.

The most important flow for a developer is "I've got a project I'm working on, I need it running somewhere so that I can test it out". All the wonderful governance capabilities that chaincode lifecycle offers to multi-org consortiums of network operators... Should ideally not get in a developer's way too much!

Plan is to take the stance that developers should only be looking to deploy a contract to an environment that they have full control over. If they need to phase approvals, cooperate with other organisations, use different packages for different orgs etc. etc... They need to check out either the IBM Blockchain Platform Ops Console or the Fabric CLIs.

So, we're going to assume a simplified set of use-cases, and drive for the simplest deployment workflow we can manage! Designs so far attached in comments...

**Comment by EdMoffatt** [comment]
Low-fis of the deployment flow: https://xd.adobe.com/view/db15e128-8799-4103-47e2-91f766111e02-ad24/?fullscreen

(Will keep this link updated as I iterate)

**Comment by EdMoffatt** [comment]
A bit of additional thinking around "could we have devs only changing the version number in package.json if they explicitly want to, and otherwise let them achieve "deploying a different version of an existing committed contract" (what v1 lifecycle might have called "upgrading a smart contract") without needing the commit step".

![image](https://user-images.githubusercontent.com/7454304/74329985-be311480-4d88-11ea-97e6-75c8062fa08a.png)

Documenting our subsequent discussion on the matter too!

![image](https://user-images.githubusercontent.com/7454304/74330015-cee18a80-4d88-11ea-807f-d7143b9806cd.png)

**Comment by EdMoffatt** [comment]
Making myself a to-do list of things to cover in the next iteration of these designs:

- [ ] Separate out Nodes and Organisations
- [ ] Demonstrate that we _think_ you could deploy an updated version without changing the version number (as long as the package content has actually changed)
- [ ] Trim down the "it's complete!" screen to not show all the info about what was deployed, and offer clearer "here are the next steps".

**Comment by cazfletch** [comment]
done so closing
