### ISSUE TITLE
Fabric 2: Deploy View

### ISSUE THREAD

**Issue by cazfletch** [IBM-Blockchain/blockchain-vscode-extension#1913]
Epic for stories needed for the deploy view

[v2 Deploy in Dev Tools.pdf](https://github.com/IBM-Blockchain/blockchain-vscode-extension/files/4504469/v2.Deploy.in.Dev.Tools.pdf)
 above are the latest designs

**Comment by EdMoffatt** [comment]
Uploading design specs here for @Jakeeyturner ! Individual redlined screens first, then I'll add a Sketch-measure export as a separate comment...

![image](https://user-images.githubusercontent.com/7454304/80972382-f428e680-8e15-11ea-9e4f-5591c28ac49b.png)

![image](https://user-images.githubusercontent.com/7454304/80972409-fee37b80-8e15-11ea-87fc-0884cd4ddd7b.png)

![image](https://user-images.githubusercontent.com/7454304/80972476-0f93f180-8e16-11ea-9b65-caae2c6a3270.png)

![image](https://user-images.githubusercontent.com/7454304/80972500-17539600-8e16-11ea-9132-2f5b1b8f3ff6.png)

![image](https://user-images.githubusercontent.com/7454304/80972526-1e7aa400-8e16-11ea-816b-5b5af1a1d5dc.png)

(In that last one, it's a Carbon multi-select dropdown, with the peers we'd have used by default anyway (I'm guessing maybe 1 per org in the environment or even just all the peers in the environment?) so it's default state has some already selected - 2 in this case).

**Comment by EdMoffatt** [comment]
[v2 deploy in dev tools.zip](https://github.com/IBM-Blockchain/blockchain-vscode-extension/files/4575032/v2.deploy.in.dev.tools.zip)

^ And here's the sketch measure export
