### ISSUE TITLE
Fabric 2: Deploy view: When the view opens i can see info about what i'm going to do

### ISSUE THREAD

**Issue by cazfletch** [IBM-Blockchain/blockchain-vscode-extension#1916]
The view should show info about which channel and env the contract will be deployed to and also info about that this is a simplified flow etc

![image](https://user-images.githubusercontent.com/23044145/74351358-edf31300-4dae-11ea-85ae-e9cd6e69952e.png)

**Comment by Jakeeyturner** [comment]
Implemented in PR #2232 - the latest designs only show the channel name and environment name.
