### ISSUE TITLE
Fabric 2: Deploy View: When i click deploy i can see the progress made

### ISSUE THREAD

**Issue by cazfletch** [IBM-Blockchain/blockchain-vscode-extension#1932]
![image](https://user-images.githubusercontent.com/23044145/74355602-ff3f1e00-4db4-11ea-9939-e929d8cb4f60.png)

**Comment by Jakeeyturner** [comment]
Closing this issue as designs have changed.
When you click 'Deploy', we'll show the progress as standard VS Code notifications.
