### ISSUE TITLE
Fabric 2: Deploy view: After deployment the view should close

### ISSUE THREAD

**Issue by cazfletch** [IBM-Blockchain/blockchain-vscode-extension#1933]
![image](https://user-images.githubusercontent.com/23044145/74353450-d5382c80-4db1-11ea-9152-818490c798af.png)

**Comment by Jakeeyturner** [comment]
After the user clicks 'Deploy' the view should close and the deploy command should be kicked off, where the progress is reported in the notifications.
The view should close regardless of whether the deploy passes or fails.
