### ISSUE TITLE
Extension issue

### ISSUE THREAD

**Issue by avinash13715** [IBM-Blockchain/blockchain-vscode-extension#1947]
- Issue Type: `Bug`
- Extension Name: `ibm-blockchain-platform`
- Extension Version: `1.0.19`
- OS Version: `Windows_NT x64 10.0.18362`
- VSCode version: `1.42.1`

:warning: We have written the needed data into your clipboard. Please paste! :warning:

**Comment by cazfletch** [comment]
closing as no details
