### ISSUE TITLE
Ops Tools enhancements and fixes

### ISSUE THREAD

**Issue by lquintai** [IBM-Blockchain/blockchain-vscode-extension#1950]
Required improvements from system testing and team feedback:

- [x] Wording
- [x] Stop auto-refresh when user clicks/cmd pallet Edit filters - Caroline
- [x] Stop connected message to terminal when no changes detected by auto-refresh - Akshat
- [x] Do not auto-choose environment when importing nodes even if there is only one possible environment (1) - Caroline
- [x] When right clicking a CA on an ops tools environment, the option 'register and enroll an identity' should not be present.
- [x] Adding an empty env should ask you if you are sure you want to add - Caroline
- [x] Modify CA certificate usage (2)

(1) Scenario: we are connected to an ops tools environment. We use the command pallet to trigger 'Import Nodes' (only works on non ops tools environments). There is only one non ops tools environment, so that gets auto selected. It is not clear which environment we are importing nodes to. We should not auto-select.

(2) workflow modified to:
1) GET to the health end point /ak/api/v1/health without sending the API key/secret - this means we don’t send any confidential data to an untrusted service - it should return HTTP 401 Unauthorized. If it does, we can continue.
2) If 1) doesn’t return an HTTP 401 Unauthorized, try 1) again but this time disable certificate validation. If we get a HTTP 401 Unauthorized back, then we know the certificates are invalid, and we can ask the user if they are happy to ignore certificate problems
3) If 1) and 2) do anything other than return a HTTP 401 Unauthorized, then the URL is bust due to some form of other network problem, and we report whatever the error is back to the user
￼

**Comment by cazfletch** [comment]
done so closing
