### ISSUE TITLE
Node JS not recognised 

### ISSUE THREAD

**Issue by designMoreWeb** [IBM-Blockchain/blockchain-vscode-extension#1981]
## Description
I have a mac with Node 13.9 installed, however when installing the extension it fails to register that node is installed and insists that i install node again

## Expected Behaviour
Should see that node is installed and continue normally with the setup
## Actual Behaviour
Fails to recognise that Node is installed and fails in setup

## Possible Fix
I believe its a bug and also could be a bug with mac as the new OS has been buggy for many people

## Steps to Reproduce
1. Installed Blockchain extension
2. Open and setup for the first time and might get issues with setup

## Log File
https://gist.github.com/designMoreWeb/0c00516fb38375ff52ca33e3befe2a5e

## Your Environment

* IBM Blockchain Platform Extension Version:
* Visual Studio Code version:Version: 1.42.1
* Environment name and version (e.g. Node.js v8.12.0, npm v6.4.1): Node.js v13.9, npm v6.13.7
* Operating System and version: Mac OS Mojave Version 10.14.6

**Comment by Jakeeyturner** [comment]
Hi @designMoreWeb,

You extension will only work with Node 8 or Node 10.
If you don't have either of those versions installed, then the Prerequisites page will open up - which is what I suspect you're seeing.

Thanks,
Jake

**Comment by cazfletch** [comment]
closing as a user problem
