### ISSUE TITLE
Welcome page updates to re-focus on tutorials

### ISSUE THREAD

**Issue by EdMoffatt** [IBM-Blockchain/blockchain-vscode-extension#1982]
The plan here is to massively focus on the tutorials! We want to make them front and centre with the other resources also available but at much lower priority. We also want to tie in to the link in the bottom bar, making it clear that going to the tutorials will help you gain those "levels".

Here's what I'm thinking on the design:

![image](https://user-images.githubusercontent.com/7454304/75211086-eb9a9c80-5750-11ea-9553-eac3337604c2.png)

**Comment by EdMoffatt** [comment]
This is using the Carbon 16 column grid, layout shown in the next screenshot. There are also padding margins at the left and right (as part of the grid system):
![image](https://user-images.githubusercontent.com/7454304/75211148-1a187780-5751-11ea-9b67-70b11169040a.png)

All the text stylings should be standard Carbon ones, and the key paddings are shown.
We'll want to figure out what to do at narrower widths - I'll do some narrower versions next to figure that out!

Illustration in SVG format is here: https://ibm.box.com/s/zwrfs5ogp8n6yyrnl7u4i9zad3pr4j1y

And in case we need to use PNG here's one to get started with (tho let me know and I'll render down a higher quality one if that's what we need!): https://ibm.box.com/s/59fuloimcfrt0x34i90vn9b4l2ji2lfk

**Comment by EdMoffatt** [comment]
Updated design with feedback from Shauno! I've red-boxed everything that's changed:

![image](https://user-images.githubusercontent.com/7454304/75972877-1a8cdd00-5ecc-11ea-9fe3-9d32a800d08e.png)

Note: we'll leave off the "Current level" in the first delivery of this work so that we can get it in earlier, and then loop back to add that in once the Tutorials page is re-worked!

**Comment by EdMoffatt** [comment]
Dark version!

![image](https://user-images.githubusercontent.com/7454304/75994741-55eed200-5ef3-11ea-827e-9a3031b648cb.png)

This uses the CARBON GREY 100 versions of the same text stylings, and swaps the illustration out for a re-coloured one, which is available here on Box: https://ibm.box.com/s/rzpniqswrrgv4ttykhme6iz74a0zruef

**Comment by erin-hughes** [comment]
Closed by #2043
