### ISSUE TITLE
Instantiating chaincode on the external network

### ISSUE THREAD

**Issue by easeev** [IBM-Blockchain/blockchain-vscode-extension#1985]
## Description

I cannot instantiate chaincode on the channel if the orderer and its admin identity are not imported.

It looks odd that you need to specify order manually and, what is worse, its admin identity (which is not necessary to work with chaincode). The only things required are orderer address (which seems to be discovered by the extension) and TLS cert to connect to the orderer in case it's enabled. Since TLS is still needed, why not allow to import orderer JSON without an identity?

## Expected Behavior
Chaincode is instantiated.

## Actual Behavior
Getting the following error:
```
Error instantiating smart contract: Failed to find Fabric orderer(s) orderer-hostname.com:7050 for channel defaultchannel
```

## Possible Fix
Allow to import orderer JSON without an identity.

## Steps to Reproduce
1. Import an external network (environment, peer, peer identity)
2. Try to instantiate chaincode
3. Get error

## Your Environment
* IBM Blockchain Platform Extension Version: v1.0.20
* Visual Studio Code version: 1.42.1
* Environment name and version: Node.js v8.9.0 npm v6.12.0
* Operating System and version: macOS Mojave v10.14.6

**Comment by EnekoGomezTecnalia** [comment]
Same problem here. It seems to be ignoring the "api_url" parameter of the orderers specified in the environment JSON file. Instead, it is using the "name" parameter as the domain name and a hard-coded 7050 port.

**Comment by EnekoGomezTecnalia** [comment]
And there is some related (less annoying) behaviour when submitting a transaction from the Fabric Gateways panel. When selecting a custom peer-targeting set, the list shows both the peers declared in the connection profile and those read from the channel configuration (which in my case are the same, but accessed from inside or outside the docker network). That's not necessarily bad. But when selecting the default peer-targeting option, it is fault-prone.

I must clarify that my current use case is using the IBM Blockchain Platform VS Code with my own pre-existing Go chaincode and a pre-existing development network. I was using my own scripts till now.

**Comment by cazfletch** [comment]
Hi @EnekoGomezTecnalia are you saying you see each peer listed twice? when you try and use peer targeting?

**Comment by EnekoGomezTecnalia** [comment]
```
FABRIC GATEWAYS -> Channels -> channel_name -> mycc@0.0.1
Right click -> Submit transaction
...
Select a peer targeting policy for this transaction 
Custom
```
And I see:
```
peer0.org0
peer1.org0
peer0.org1
peer1.org1
peer0.org0:7050
peer1.org0:7050
peer0.org1:7050
peer0.org1:7050
```
...where the 4 first elements in the list are the peer names taken from my connection profile and the 4 last elements are the domains and ports read from the channel configuration (referring to the same peers).

In my case, the first 4 lines work (as my connection profile is suitable) but the last 4 not (as the domain and ports are internal to the docker network).

When selectin `Default` instead of `Custom`, the plugin selects some of the last 4 lines and fail.

**Comment by cazfletch** [comment]
can you raise a separate issue please looks like a bug

**Comment by EnekoGomezTecnalia** [comment]
@cazfletch Done: https://github.com/IBM-Blockchain/blockchain-vscode-extension/issues/2033

**Comment by cazfletch** [comment]
closing as this will be fixed when fabric 2 is supported
