### ISSUE TITLE
CDS file size increased above 10 MB with version 1.0.20

### ISSUE THREAD

**Issue by bhanuratnakaram** [IBM-Blockchain/blockchain-vscode-extension#1991]
we are users IBM blockchain network in production. We have been told by IBM that the cds file can not be more than 4MB. VSCode plugin got updated an hour ago which bumped the cds size of +10MB.
Please can you help us as soon as you can as this is impacting our production release

**Comment by cazfletch** [comment]
Hi @bhanuratnakaram can you attach the project that you are trying to package or at least send a screen shot of the file explorer view from vscode

**Comment by cazfletch** [comment]
Also when you package the file names are outputted to the blockchain output channel so you can see what files were included in the package

**Comment by cazfletch** [comment]
closing as no response
