### ISSUE TITLE
Creating A Playbook from an IBP Environment

### ISSUE THREAD

**Issue by bmos299** [IBM-Blockchain/blockchain-vscode-extension#2001]
## Description
The ability to pull the IBP configuration from the SaaS or Software into the extension is very powerful.   I think it would be beneficial to pull in the IBP configuration and then reverse engineer it into a playbook.  The benefits are obvious in that you can then quickly deploy to your local docker environment and/or make configuration changes and submit back to your corresponding IBP consortium. 

## Expected Behavior
This is not a bug but an enhancement. 

## Actual Behavior
This is not a bug but an enhancement.

**Comment by Jakeeyturner** [comment]
Closing - no longer using Ansible playbooks.
There's now a tutorial on how to easily create custom microfab configs.
