### ISSUE TITLE
Coudn't rebuild native modules

### ISSUE THREAD

**Issue by Sinha199** [IBM-Blockchain/blockchain-vscode-extension#2012]
- Issue Type: `Bug`
- Extension Name: `ibm-blockchain-platform`
- Extension Version: `1.0.20`
- OS Version: `Windows_NT x64 10.0.18362`
- VSCode version: `1.42.1`

:warning: We have written the needed data into your clipboard. Please paste! :warning:

**Comment by cazfletch** [comment]
closing as this is a duplicate of the pinned issue
