### ISSUE TITLE
Extension issue

### ISSUE THREAD

**Issue by Trailblazer29** [IBM-Blockchain/blockchain-vscode-extension#2013]
- Issue Type: `Bug`
- Extension Name: `ibm-blockchain-platform`
- Extension Version: `1.0.20`
- OS Version: `Windows_NT x64 10.0.18362`
- VSCode version: `1.42.1`
[Error.txt](https://github.com/IBM-Blockchain/blockchain-vscode-extension/files/4271629/Error.txt)

**Comment by cazfletch** [comment]
Closing as no details
