### ISSUE TITLE
Not working for latest version of Node.js

### ISSUE THREAD

**Issue by Srayoshi-Mirza** [IBM-Blockchain/blockchain-vscode-extension#2019]
Blockchain extension won't work on node.js version is 12.16.1

## Description
As the requirement is 10x version of node.js, it won't start in 12.16.1 version. The 10x version installer is not available anymore. Don't know what to do. Please can you tell me a solution regarding this solution.

## Your Environment
* IBM Blockchain Platform Extension Version: 1.0.20
* Visual Studio Code version: 1.24
* Node JS :  12.16.1 npm: 6.13.4
* Operating System and version: Windows 10

**Comment by Jakeeyturner** [comment]
Hi @Srayoshi-Mirza,

You can find older versions of NodeJS here - https://nodejs.org/en/download/releases/ 
(v10.x downloads can be found here - https://nodejs.org/dist/latest-v10.x/)

Thanks,
Jake
