### ISSUE TITLE
Extension issue

### ISSUE THREAD

**Issue by LouzirMohamedAziz** [IBM-Blockchain/blockchain-vscode-extension#2025]
- Issue Type: `Bug`
- Extension Name: `ibm-blockchain-platform`
- Extension Version: `1.0.20`
- OS Version: `Linux x64 5.3.0-26-generic`
- VSCode version: `1.42.1`

:warning: We have written the needed data into your clipboard. Please paste! :warning:

**Comment by LordDraagonLive** [comment]
what's the issue?

**Comment by cazfletch** [comment]
closing as no details
