### ISSUE TITLE
Failed to activate extension. 

### ISSUE THREAD

**Issue by ManojRakshu** [IBM-Blockchain/blockchain-vscode-extension#2051]
Node Version:10.19.0
NPM Version 6.13.4
I tried downgrading vs code to 1.38 still it didnt work.

## Actual Behavior
Failed to activate extension: Failed to execute command "npm" with arguments "rebuild, grpc, --target=7.1.11, --runtime=electron, --update-binary, --fallback-to-build, --target_arch=x64, --dist-url=https://atom.io/download/electron" return code 1 
Please Please help me i need to start my university project asap

**Comment by Jakeeyturner** [comment]
This is related to https://github.com/IBM-Blockchain/blockchain-vscode-extension/issues/1621.

The workaround is to install VS Code 1.38 / 1.39 and use that instead of the latest.

Closing as this is a duplicate.

**Comment by ManojRakshu** [comment]
Dear Sir, I used VS Code 1.38 version still it didn't work

**Comment by cazfletch** [comment]
What was the error you got with 1.38?
