### ISSUE TITLE
Handle IBP v2.1.3 changes to exported node files

### ISSUE THREAD

**Issue by sstone1** [IBM-Blockchain/blockchain-vscode-extension#2073]
IBP v2.1.3 will be changing the JSON files exported for peers and orderers so that the `pem` property becomes `tls_ca_root_cert`, so we need to handle this - whilst still supporting older IBP versions.

**Comment by sstone1** [comment]
@erin-hughes I hear you are going to work on this - I'm afraid this is a bit more complicated than just one property change!

**Certificate Authority**
`name` is now `display_name`
`pem` is now `tls_cert`

**Peer**
`name` is now `display_name`
`pem` is now `tls_ca_root_cert`
Note that a peer has a `tls_cert` field, but this is not the correct certificate to use.

**Ordering Service Node**
`name` is now `display_name`
`pem` is now `tls_ca_root_cert`
Note that an ordering service node has either a `tls_cert` field, or both a `client_tls_cert` and a `server_tls_cert` field, but none of these are the correct certificate to use.

We still need to support the old property names and the new property names.

**Comment by erin-hughes** [comment]
Closed by #2096
