### ISSUE TITLE
Suggest extension installation for devs who don't have it

### ISSUE THREAD

**Issue by caroline-church** [IBM-Blockchain/blockchain-vscode-extension#21]
A developer opening a project that was created using the Fabric VSCode extension should have it suggested that they install said extension if they don't already have it.

(There is apparently a file that can do this!)

We need a better story about why this makes sense! But probably not Phase 1 anyhow.

**Comment by sstone1** [comment]
@EdMoffatt @caroline-church this requires a quick generator change which I'll take care of.

The experience will be as follows:

1. User A, who has the extension installed, creates a smart contract project and checks it into GitHub.

2. User B, who does not have the extension installed, clones out the smart contract project from GitHub and opens it in VS Code.

3. User B gets the following prompt:

<img width="1136" alt="screen shot 2018-10-24 at 18 19 30" src="https://user-images.githubusercontent.com/7118158/47450621-9f86c300-d7bd-11e8-85f6-6f927a7472a2.png">

4. If user B clicks "Install All", the extension will automatically be installed.

5. If user B clicks "Show Recommendations", they will see the following:

<img width="1136" alt="screen shot 2018-10-24 at 18 19 35" src="https://user-images.githubusercontent.com/7118158/47450661-b88f7400-d7bd-11e8-8b85-0e4fea16534b.png">

**Comment by EdMoffatt** [comment]
I would just like to comment that this is wicked :) . Love it!

**Comment by caroline-church** [comment]
closing as this is now in the generator
