### ISSUE TITLE
As a developer I can export my smart contract packages for use elsewhere

### ISSUE THREAD

**Issue by EdMoffatt** [IBM-Blockchain/blockchain-vscode-extension#210]
Packaging a smart contract project puts it in a set location for the VSCode extension to use.  One option for devs who want to use their packages elsewhere (e.g. need to send them to someone else to deploy into an IBM Blockchain Platform runtime) is to find this location on disk and copy them from there.  Finding where they're stored is likely a Google search tho, so could be useful to add something more discoverable into the extension.

Opening suggestion: right-click on a package in the Smart Contract Packages view has an option "Export Package", which then gets you a save-as file dialog, to pick where you want to save a copy of that package to.

**Comment by sstone1** [comment]
Proposed design:

1. New command added called "Export Package".

2. Can trigger this command from the package tree:

<img width="1035" alt="screen shot 2018-10-18 at 15 28 36" src="https://user-images.githubusercontent.com/7118158/47161743-8fb53d80-d2ea-11e8-83cf-adac7ea6a122.png">

3. Can trigger this command from the command palette

<img width="1034" alt="screen shot 2018-10-18 at 15 28 54" src="https://user-images.githubusercontent.com/7118158/47161772-9cd22c80-d2ea-11e8-9f98-d12eab140aea.png">

4. The command opens a save dialog:

<img width="1036" alt="screen shot 2018-10-18 at 15 29 55" src="https://user-images.githubusercontent.com/7118158/47161843-be331880-d2ea-11e8-9ae0-c81f8c0ecf81.png">

5. The package is exported and the user informed:

<img width="1035" alt="screen shot 2018-10-18 at 15 30 09" src="https://user-images.githubusercontent.com/7118158/47161869-c9864400-d2ea-11e8-8f97-40af8283b3cf.png">

6. ???

7. Profit.

@EdMoffatt @caroline-church any comments?

**Comment by caroline-church** [comment]
looks good
