### ISSUE TITLE
As a developer I can investigate an instantiated smart contract by generating a test project

### ISSUE THREAD

**Issue by heatherlp** [IBM-Blockchain/blockchain-vscode-extension#214]
As a user I've stumbled across a fabric network, connected to it and want to generate some tests for some instantiated smart contract I've found. 

In this case, the generate tests command added in #60 should create a default location for test files (e.g. ~/.fabric.vscode/testFiles/) and generate a test project in there, including a package.json, node_modules etc so the test file is ready to run in that location. 

The "chose test file location" dialog box that is shown once the command is invoked should show and allow the user to chose "default location", so the user is aware that the test file will be generated in a location the extension controls.

**Comment by caroline-church** [comment]
closing as not planning to do this anytime soon
