### ISSUE TITLE
Inconsistent Use of Channel name from Connection.json

### ISSUE THREAD

**Issue by rthatcher** [IBM-Blockchain/blockchain-vscode-extension#215]
I have a Fabric with a channel called **alice**.
I make an error in my connection.json and specify **bob** as the channel
I 'Add new connection' to my Fabric in vscode
The Fabric displays nicely in the tree view show alice as the channel - so it seems happy to ignore the bob error in the file.
I can install a SC to the Peer
Instantiate fails - even though I am right clicking on alice - until I change the connection.json to alice.

I think I would prefer for it to fail to display the tree in the first place with bob in the connection.json.

**Comment by caroline-church** [comment]
closing as there is nothing the extension can do about this. The extension gets the channels from fabric and not the connection profile. Also vscode is not involved with how instantiate works
