### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by m-g-k** [IBM-Blockchain/blockchain-vscode-extension#2157]
Issue Type: `Performance`
- Extension Name: `ibm-blockchain-platform`
- Extension Version: `1.0.25`
- OS Version: `Linux x64 4.4.0-142-generic`
- VSCode version: `1.43.2`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`/home/blockchain/IBMBlockchain.ibm-blockchain-platform-unresponsive.cpuprofile.txt`

Find more details here: https://github.com/microsoft/vscode/wiki/Explain-extension-causes-high-cpu-load
[IBMBlockchain.ibm-blockchain-platform-unresponsive.cpuprofile.txt](https://github.com/IBM-Blockchain/blockchain-vscode-extension/files/4429531/IBMBlockchain.ibm-blockchain-platform-unresponsive.cpuprofile.txt

**Comment by Jakeeyturner** [comment]
Going to close this as I think this is related to the periodic refresh panel problem.

**Comment by Jakeeyturner** [comment]
MGK still sees this on 1.0.26, primarily when he starts the 1 Org Local Fabric - going to re-open this issue.
