### ISSUE TITLE
Deploying new contract with same version fails silently

### ISSUE THREAD

**Issue by jambonrose** [IBM-Blockchain/blockchain-vscode-extension#2158]
##  Description
During the development cycle, I expect to need to test a smart contract repeatedly. This involves tearing down existing Fabric environments so that I may package/install/instantiate the smart contract. As I do so, I am not changing the version of the package. A version change is for public releases, and I should not need to update the version of a package during the development cycle.

However, in the latest versions of the extension, deploying newly packaged code does not work as expected. If I have already deployed `chaincode@1.0.0` on a previous network, my newly packaged `chaincode@1.0.0` on a new network will not actually be installed/instantiated. Instead, the behavior from the original build will continue to be seen. However, if I increase the version number, package, install, and instantiate `chaincode@1.0.1`, now I can see the changes made to the code.

This behavior is not desired in development, and violates the principle of least surprise: at no point did the extension warn me that my package was not being properly installed by the peer. This is particularly surprising given that I am using a brand new environment, and that no other package is listed by the system.

## Expected Behavior
1. When I deploy a chaincode package to a newly created Fabric environment, I expect that the package I supply will be deployed.
2. If a package cannot be installed on the peer, I expect to see an error.

## Actual Behavior
Even when using a new package and a new environment, if the name and version of the package are the same, then a previous version of the package is installed (or was already available - I am unclear on the problem, as I have been unable to debug the issue even after tearing down Docker entirely).

Please note that I have not tried to change the name of the environment during this process. I have simply been naming my environments `Org1` each time.

## Steps to Reproduce
1. Use the extension to create a new package for TypeScript
2. Modify the `readMyAsset` transaction to return a string `'v1'`
3. Create a new single-org Fabric environment named `Org1`
4. Package, install, and instantiate the project
5. Use the gateway to connect and evaluate the `readMyAsset` transaction: see `'v1'` be returned
6. Teardown the environment, delete the environment, and delete the package
7. Without changing the version in the package, modify the `readMyAsset` transaction to return a string `'v2'`
8. Repeat steps 3, 4, 5; **note how `'v1'` is returned, despite expectation that contract would return `'v2'` after creation of new package and new successful installation on new environment**
9. Repeat step 6
10. Change version of package listed in `package.json`
11. Repeat steps 3, 4, 5; note how `'v3'` is returned

## Your Environment
* IBM Blockchain Platform Extension Version: 1.0.25
* Visual Studio Code version: 1.39.2
* Environment name and version: Node.js v10.19.0, npm v6.14.2:
* Operating System and version: macOS 10.14.6

Additionally, I have had another developer confirm this behavior on their own Mac using the same versions of Node, VSCode, and IBM Blockchain Extension.

**Comment by Jakeeyturner** [comment]
Hi @jambonrose,

I suspect you're seeing this as when you install a package, the peer creates the chaincode Docker image.
When you delete the package file, it doesn't delete the images - only the CDS file. 

So, when you make some code changes and package it, an image already exists with that name and version - so it doesn't create a new image.

I'm currently speaking to someone regarding this behaviour and whether it needs changing, or is intended.
It could probably do something different such as:
- Overwrite the existing Docker image
- Error as a Docker image already exists with that name and version.

As you're making iterative changes to your smart contract, I suspect that you might benefit from running the smart contract debugger - where you can make changes to your contract without having to re-package and teardown your Fabric environment. 

Alternatively, if you manually delete the chaincode image created by the install - when you make you changes, package and install again - it will create a new chaincode image, using the latest code changes.

The chaincode Docker image looks something like:
`1orglocalfabric-org1peer1-contract1025-0.0.1-9506761fc5fc0ff8df8108db9ce829c8727c4552578d8f12130c15fc39c61f9b          latest              a32195e83e4b        4 days ago          1.37GB`

Thanks,
Jake

**Comment by Jakeeyturner** [comment]
Going to close this issue and create a new one, regarding an enhancement we can make to try to prevent other users from hitting this. Due to Fabric 1.4's lifecycle design, it seems that the behaviour of re-using chaincode images is intentional. In Fabric 2.0 the lifecycle is different and the chaincode image id will be unique every time you change your code.

I haven't heard from you, so I'm assuming you tried one of those methods which worked.

Let me know if there's anything else I can help with!

Thanks,
Jake

**Comment by jambonrose** [comment]
@Jakeeyturner : thanks for the clarity you provided. I have not yet had a chance to test any of the methods above, but will keep you informed.

I think that a warning that a smart contract is being re-used during installation / instantiation---as noted in #2174---is a great start. Otherwise, user expectation is that the specified installation package is the code that has been installed, which is not true.

If the smart contract is now in separate infrastructure, should it not also be listed in the environment?

I would also have expected the teardown or deletion of an environment to remove all infrastructure associated with it. As I understand it, to remove an environment, I currently need to (1) delete the environment, and (2) clean up Docker images separately. That is unexpected.
