### ISSUE TITLE
Linting rules

### ISSUE THREAD

**Issue by sstone1** [IBM-Blockchain/blockchain-vscode-extension#219]
The automated linting rules for this project do not match up with the stricter linting done by the likes of @caroline-church and @heatherlp, which makes it harder for people to contribute.

We need to turn on additional rules such as:

https://palantir.github.io/tslint/rules/no-unused-variable/
https://palantir.github.io/tslint/rules/typedef/

**Comment by heatherlp** [comment]
and @Jakeeyturner !

**Comment by caroline-church** [comment]
done so closing
