### ISSUE TITLE
Error instantiating contract

### ISSUE THREAD

**Issue by jexus6** [IBM-Blockchain/blockchain-vscode-extension#220]
I have an installed contract, but when I try to instantiate it I get the message:

> Error instantiating smart contract No valid responses from any peers.
> Response from attempted peer comms was an error: {"status":500,"payload":{"type":"Buffer","data":[]},"isProposalResponse":true}

It's a new installation, following all the steps until the contract is installed

**Comment by caroline-church** [comment]
@jexus6 do you see any errors in the docker logs?

**Comment by jexus6** [comment]
I just watch it right now. I'm afraid the problem is the proxy server. The peer node make external connections. 
Shoud I configure it in every peer container?
Here is the log:

> 018-10-18 14:14:53.442 UTC [sccapi] deploySysCC -> INFO 039 system chaincode +lifecycle/mychannel(github.com/hyperledger/fabric/core/chaincode/lifecycle) deployed
> 2018-10-18 14:14:59.442 UTC [gossip/election] beLeader -> INFO 03a [61 97 241 125 96 173 40 203 239 81 147 191 102 161 39 23 0 117 69 217 56 120 139 152 120 223 29 9 23 115 238 6] : Becoming a leader
> 2018-10-18 14:14:59.443 UTC [gossip/service] func1 -> INFO 03b Elected as a leader, starting delivery service for channel mychannel
> 2018-10-18 14:18:16.038 UTC [couchdb] CreateDatabaseIfNotExist -> INFO 03c Created state database mychannel_lscc
> 2018-10-18 14:18:46.006 UTC [lscc] executeInstall -> INFO 03d Installed Chaincode [smart_contract] Version [0.0.1] to peer
> 2018-10-18 14:22:57.469 UTC [chaincode-platform] func1 -> ERRO 03e Failed to generate platform-specific docker build: Error returned from build: 1 "npm ERR! code ECONNRESET
> npm ERR! errno ECONNRESET
> npm ERR! network request to https://registry.npmjs.org/fabric-contract-api failed, reason: socket hang up
> npm ERR! network This is a problem related to network connectivity.
> npm ERR! network In most cases you are behind a proxy or have bad network settings.
> npm ERR! network
> npm ERR! network If you are behind a proxy, please make sure that the
> npm ERR! network 'proxy' config is set properly.  See: 'npm help config'
> 
> npm ERR! A complete log of this run can be found in:
> npm ERR!     /root/.npm/_logs/2018-10-18T14_22_55_656Z-debug.log
> "
> 2018-10-18 14:22:57.470 UTC [dockercontroller] deployImage -> ERRO 03f Error building images: Failed to generate platform-specific docker build: Error returned from build: 1 "npm ERR! code ECONNRESET
> npm ERR! errno ECONNRESET
> npm ERR! network request to https://registry.npmjs.org/fabric-contract-api failed, reason: socket hang up
> npm ERR! network This is a problem related to network connectivity.
> npm ERR! network In most cases you are behind a proxy or have bad network settings.
> npm ERR! network
> npm ERR! network If you are behind a proxy, please make sure that the
> npm ERR! network 'proxy' config is set properly.  See: 'npm help config'

**Comment by caroline-church** [comment]
@jexus6 yes the peer needs to be able to do an npm install to install the external dependencies.

**Comment by caroline-church** [comment]
closing as this has been resolved. Feel free to reopen if it hasn't
