### ISSUE TITLE
Unable to activate extension: Cannot read property 'major' of null

### ISSUE THREAD

**Issue by droopygit** [IBM-Blockchain/blockchain-vscode-extension#2200]
When trying to activate extension I get the following error: Cannot read property 'major' of null".

## Description
I tried the "Retry activation" button and also uninstall/reinstall the extension but I got the same error.

## Steps to Reproduce
1. Install IBM Blockchain Platform extension from VS Code 
2. Go to IBM Blockchain Platform in the VS Code Side Bar 

## Log File
[17/04/2020 à 18:18:10] [INFO] Starting IBM Blockchain Platform Extension
[17/04/2020 à 18:18:10] [INFO] Attempting to require dependency: grpc
[17/04/2020 à 18:18:10] [INFO] Restoring command registry
[17/04/2020 à 18:18:11] [INFO] Registering commands
[17/04/2020 à 18:18:12] [INFO] Execute stored commands in the registry
[17/04/2020 à 18:18:12] [INFO] IBM Blockchain Platform Extension activated
[17/04/2020 à 18:18:12] [ERROR] Failed to activate extension: TypeError: Cannot read property 'major' of null
[17/04/2020 à 18:18:12] [ERROR] TypeError: Cannot read property 'major' of null
	at Function.<anonymous> (c:\Users\xxx\.vscode\extensions\ibmblockchain.ibm-blockchain-platform-1.0.26\build\extension\util\ExtensionUtil.js:596:54)
	at Generator.next (<anonymous>)
	at fulfilled (c:\Users\xxx\.vscode\extensions\ibmblockchain.ibm-blockchain-platform-1.0.26\build\extension\util\ExtensionUtil.js:18:58)

## Your Environment
* IBM Blockchain Platform Extension Version: 1.0.26
* Visual Studio Code version: 1.44.2
* Environment name and version (e.g. Node.js v8.12.0, npm v6.4.1): Node.js 10.20.1, npm 6.14.4
* Operating System and version: Windows 10.0.18363

**Comment by droopygit** [comment]
When I install the extension I got also this error:

[20/04/2020 à 12:16:51] [INFO] Error requiring dependency: Failed to load gRPC binary module because it was not installed for the current system
Expected directory: electron-v7.1-win32-x64-unknown
Found: [node-v64-linux-x64-glibc]
This problem can often be fixed by running "npm rebuild" on the current system
Original error: Cannot find module 'c:\Users\xxx\.vscode\extensions\ibmblockchain.ibm-blockchain-platform-1.0.26\node_modules\grpc\src\node\extension_binary\electron-v7.1-win32-x64-unknown\grpc_node.node'

Perhaps is it related? I don't how to fix this.

**Comment by droopygit** [comment]
When I apply your fix, I can activate the extension. Thanks.
But, after when I try to create a new project in the "smart contracts" area, the project is created but not displayed in this area. When I try the "Package Open Project" action I got an error: "TypeError: Cannot read property 'fsPath' of undefined".

**Comment by cazfletch** [comment]
The project will only appear in the "smart contracts" area once it has been packaged. Did you do an npm install before you tried to package the open project?

**Comment by droopygit** [comment]
Yes, I do an "npm install" then "Packages Open Project". I get the error 

> [ERROR] TypeError: Cannot read property 'fsPath' of undefined

I do this because when I "Create New Project" (Default Contract, TypeScript, MyAsset, Add to workspace), files are generated and the log indicates no error but the smart contract doesn't appear in the panel "smart contacts".

> I'm all done. Running npm install for you to install the required dependencies. If this fails, try running the command yourself.
> [21/04/2020 à 11:31:02] [SUCCESS] Successfully generated Smart Contract Project

I try to npm install manually. No error. 

When I try npm start build I get the following error:

> Project@0.0.1 start C:\Sources\Projects\Project
> fabric-chaincode-node start "build"
> Configuring yargs through package.json is deprecated and will be removed in the next major release, please use the JS API instead.
> Configuring yargs through package.json is deprecated and will be removed in the next major release, please use the JS API instead.
> fabric-chaincode-node start --peer.address localhost:7051 --chaincode-id-name mycc
> Options:
>   --help                                  Affiche de l'aide  [booléen]
>   -v, --version                           Affiche le numéro de version  [booléen]
>   --peer.address  [chaine de caractère] [requis]
>   --grpc.max_send_message_length  [nombre] [défaut: -1]
>   --grpc.max_receive_message_length  [nombre] [défaut: -1]
>   --grpc.keepalive_time_ms  [nombre] [défaut: 110000]
>   --grpc.http2.min_time_between_pings_ms  [nombre] [défaut: 110000]
>   --grpc.keepalive_timeout_ms  [nombre] [défaut: 20000]
>   --grpc.http2.max_pings_without_data  [nombre] [défaut: 0]
>   --grpc.keepalive_permit_without_calls  [nombre] [défaut: 1]
>   --ssl-target-name-override  [chaine de caractère]
>   --chaincode-id-name  [chaine de caractère] [requis]
>   --module-path  [chaine de caractère] [défaut: "C:\Sources\Projects\Project"]
> Arguments requis manquants: peer.address, chaincode-id-name
