### ISSUE TITLE
Homepage doens't show up

### ISSUE THREAD

**Issue by droopygit** [IBM-Blockchain/blockchain-vscode-extension#2233]
Unable to open the extension homepage

## Description

Try to open the extension homepage (available on the top right square button)

## Expected Behavior

Open the home page

## Actual Behavior

Only a black page appears (with the title IBM Blockchain Platform Home) and the following error pop up:
>'ENOENT: no such file or directory, open '/C:/Users/xxx/.vscode/extensions/ibmblockchain.ibm-blockchain-platform-1.0.27/node_modules/ibm-blockchain-platform-ui/build/static/js/main.1e050cc0.js'.
Note that the file exists.

## Steps to Reproduce
1. Open VS Code
2. Open a file
3. Click on the top right square button

## Your Environment
* IBM Blockchain Platform Extension Version: 1.0.27
* Visual Studio Code version: 1.44.2
* Environment name and version (e.g. Node.js v8.12.0, npm v6.4.1): v1.20.1 / 6.14.4
* Operating System and version: Win 10 Pro 1909

**Comment by Shiaondo-Orkuma** [comment]
I have the same problem

**Comment by Cassain2019** [comment]
Failed to activate extension: ENOENT: no such file or directory, open '/c:/Users/XXX/.vscode/extensions/ibmblockchain.ibm-blockchain-platform-1.0.28/node_modules/ibm-blockchain-platform-ui/build/static/js/main.534e74bd.js'

Facing Same Problem, anybody has find any solutions ?

**Comment by droopygit** [comment]
You can browsee files in your profile folder under .vscode\extensions\ibmblockchain.ibm-blockchain-platform-1.0.28\tutorials\developer-tutorials

**Comment by navneet108** [comment]
Could not rebuild native dependencies Failed to execute command "npm" with arguments "rebuild, grpc, --target=7.3.1, --runtime=electron, --update-binary, --fallback-to-build, --target_arch=x64, --dist-url=https://atom.io/download/electron" return code 1. Please ensure that you have node and npm installed

what to do?

**Comment by Jakeeyturner** [comment]
> Could not rebuild native dependencies Failed to execute command "npm" with arguments "rebuild, grpc, --target=7.3.1, --runtime=electron, --update-binary, --fallback-to-build, --target_arch=x64, --dist-url=https://atom.io/download/electron" return code 1. Please ensure that you have node and npm installed
> 
> what to do?

https://github.com/IBM-Blockchain/blockchain-vscode-extension/issues/1621#issuecomment-552926559
