### ISSUE TITLE
Microfab

### ISSUE THREAD

**Issue by sstone1** [IBM-Blockchain/blockchain-vscode-extension#2266]
Microfab is a containerised Fabric network from the IBM Blockchain Platform team, which enables you to spin up a custom Fabric network with control over organizations and channels within a single Docker container. 

Microfab will be used to provide a Fabric network to users of Red Hat CodeReady Workspaces and Eclipse Che, which cannot make use of the existing Ansible support for local networks. The IBM Blockchain Platform extension will not need to stand up Microfab in this environment, but it will need support for connecting to Microfab.

Microfab exposes everything over a single port, including a REST API that provides a very small subset of the REST API provided by the IBM Blockchain Platform console which can be used to get information on nodes, wallets, and gateways.

Finally, it is also likely that we will replace the built in Fabric networks (one and two organization templates) with Microfab as well, as Microfab is significantly faster and requires less prerequisites to start.

**Comment by Jakeeyturner** [comment]
Closing - done.
