### ISSUE TITLE
A new user can find a tutorial after they install

### ISSUE THREAD

**Issue by EdMoffatt** [IBM-Blockchain/blockchain-vscode-extension#227]
As the extension installs, we show the Output panel.

Once we have a "getting started with VSCode" code pattern (over on IBM Code Patterns https://developer.ibm.com/patterns/) we should add a section at the bottom of the install Output that's like - Want to learn how to get started developing blockchain smart contracts and apps?  Follow a beginner tutorial here: <URL>"

**Comment by caroline-church** [comment]
We should also link to this from the new welcome page, see issue https://github.com/IBM-Blockchain/blockchain-vscode-extension/issues/336

**Comment by Jakeeyturner** [comment]
A single tutorial has been added in PR #444 
Additional work for tutorials can be seen in the epic #336 

Closing this issue.
