### ISSUE TITLE
Generated tests offer explanatory comments

### ISSUE THREAD

**Issue by EdMoffatt** [IBM-Blockchain/blockchain-vscode-extension#229]
We'd like to offer a commented-out passage at the top of a generated test file to set the context of what they are and how they're used.  I'm gonna suggest something, and then tag people to weigh in and correct any inaccuracies of missing bits please :)

`Use this file for functional-level testing of the transactions in your smart contract.`
`Fill out the arguments for a transaction and use the CodeLens features (links above the transaction block) to invoke/submit transactions.`
`You can also use this skeleton as the basis for building out your own functional-level test file to run as part of a Continuous Integration pipeline.`
`Or, it works well with debugging locally-deployed smart contracts: start debugging a smart contract project, then generate one of these test files to allow you to invoke/submit individual transactions.`

I guess I'd also appreciate any feedback that helps it be more succinct, looking at my first draft ;)

I shall tag @heatherlp @nklincoln @caroline-church for input on this one, please :)

**Comment by caroline-church** [comment]
looks good to me maybe show Ed Prosser?

**Comment by EdProsser** [comment]
Speak his name and he shall appear.

**Comment by EdProsser** [comment]
How do people feel about this edit?

```
Use this file for functional testing of the functions in your smart contract. Fill out the arguments for a function and use the CodeLens links above the function block to invoke/submit transactions.

This basic test file can also be used as the basis for building further functional tests to run as part of a continuous integration pipeline, or for debugging locally deployed smart contracts by invoking/submitting individual transactions.
```

**Comment by EdMoffatt** [comment]
Looks good - can I also summon @nklincoln tho, as he seemed quite particular about saying "functional-level tests" rather than "functional tests" when we were talking about it in the room!  Nick - what say you?

**Comment by nklincoln** [comment]
Nothing to add, those words are so finely crafted, a heathen like me would only serve to pollute the dizzying delight that is above 👌 👍

**Comment by heatherlp** [comment]
So PR #269 adds this to the test template, but I've removed the reference to CodeLens as we're not adding the ability to be able to run the tests using CodeLens features just yet. That's covered under #62, so I'll add a comment there saying we need to update the comment 🙃
