### ISSUE TITLE
Difficulty in installing packaged Customer Loyalty Contract

### ISSUE THREAD

**Issue by tobydickins** [IBM-Blockchain/blockchain-vscode-extension#2302]
I was able to create the customerloyalty@1.0.0 contract, but was unable to install to the local fabric. When I select +install no additional window allows me to select the contract above.

![screen1](https://user-images.githubusercontent.com/65092153/81727848-93259200-9457-11ea-9341-212579873592.png)

## Environment
* v1.0.28 - IBM Blockchain Platform Extension Version:
* v1.45.0 - Visual Studio Code version:
* v10.20.1 - Node JS
* v19.03.8 - Docker
* Windows 10 Enterprise - Operating System and version:

**Comment by Jakeeyturner** [comment]
Hi @tobydickins,

Are you trying to use a sample contract? Can you point me at the repository if so.

Thanks,
Jake
