### ISSUE TITLE
Error populating fabric enviroment panel. Port should be >=0 and <65536. Received Nan

### ISSUE THREAD

**Issue by Durgesh4AI** [IBM-Blockchain/blockchain-vscode-extension#2443]
In VScode IBM Blockchain platform, while selecting "IBM Blockchain Platform: Package Open Project", and then moving to extensions panel results in an error "**Error populating fabric enviroment panel. Port should be >=0 and <65536. Received Nan**".

Detailed description:- This is happening while trying to implement any IBM code pattern. Example , https://github.com/IBM/global-financing-blockchain/blob/master/README.md

After the contract folder is opened, -> press F1  to see the different VS code options. Choose IBM Blockchain Platform: Package Open Project. Click the IBM Blockchain Platform extension button on the left. This will show the packaged contracts on top and the blockchain connections on the bottom. This is when the error appears. Not able to connect to any local network in the "Fabric environment".

## Your Environment
* IBM Blockchain Platform Extension Version: 1.0.32
* Visual Studio Code version: 1.45.1
(Node.js v10+,)
* Operating System and version: Ubuntu 20

**Comment by Jakeeyturner** [comment]
Hi @Durgesh4AI,

Can you run `> Open Settings (JSON)` and replace the `ibm-blockchain-platform.fabric.runtime` property with:

```
"ibm-blockchain-platform.fabric.runtime": {
        "1 Org Local Fabric": {
            "ports": {
                "startPort": 17190,
                "endPort": 17209
            }
        }
    }
```

It looks like some of the instructions/screenshots are out of date on that repository.
Let me know how that fix goes.

Thanks,
Jake

**Comment by Durgesh4AI** [comment]
Hi Jake and team,

I applied the new start and end port settings you provided but still the same issue. 
Please refer the document attached.

Also please note, the default port settings that came with IBM extension originally was:
{
    "ibm-blockchain-platform.fabric.wallets": [],
    "ibm-blockchain-platform.fabric.gateways": [],
    "ibm-blockchain-platform.fabric.environments": [],
    "ibm-blockchain-platform.ext.repositories": [],
    "ibm-blockchain-platform.ext.enableLocalFabric": true,
    "ibm-blockchain-platform.fabric.runtime": {
        "1 Org Local Fabric": {
            "ports": {
                **"startport": 17050,
                "endport": 17069**
                
            }
[Issue 2443 - Blockchain-vscode-extension.docx](https://github.com/IBM-Blockchain/blockchain-vscode-extension/files/4745616/Issue.2443.-.Blockchain-vscode-extension.docx)

        }
    },
    "ibm-blockchain-platform.ext.featureFlags": {       
    
    
    }
}

**Comment by Jakeeyturner** [comment]
The error seems to me like it's a network problem. In our code, we look for open ports (so that we can start a local environment on those ports), and I suspect it's unable to do that.

<img width="958" alt="Screenshot 2020-06-02 at 09 09 43" src="https://user-images.githubusercontent.com/10009752/84032027-9a748880-a98e-11ea-8774-1dbd5e3296c0.png">

Can you click on the following areas (shown above) and send the logs please.

Thanks,
Jake

**Comment by Durgesh4AI** [comment]
Hi Jake,

Not sure what went ok but now I see the port error is gone. Perhaps a machine restart was required? 
So I continued with adding smart contract. But now the problem is with instantiating. It says the below error:

**"Error instantiating smart contract: Error: REQUEST_TIMEOUT"**
**"Error instantiating smart contract: chaincode registration failed: timeout expired while starting chaincode globalfinancing:0.0.1 for transaction"**

Not sure if this should be raised as a separate issue, but if you know the way to fix it then please help.

I have attached the screenshots, and detail error logs, please check.
[Issue 2443 - Instantiating smart contract.docx](https://github.com/IBM-Blockchain/blockchain-vscode-extension/files/4746519/Issue.2443.-.Instantiating.smart.contract.docx)

**Comment by Durgesh4AI** [comment]
Hi Jake,

I am able to fix the timeout issue by extending the time in configuration.

We can close this issue, if I see any problem I will open it in the corresponding repository.

Thank you for helping. 

Regards
Durgesh
