### ISSUE TITLE
The extension should document how to package and include couchDB indexes

### ISSUE THREAD

**Issue by m-g-k** [IBM-Blockchain/blockchain-vscode-extension#2446]
Currently you have to figure out yourself how to package up couchDB indexes to deployment in a cds file. It would be useful to document this process so it's more obvious. Ideally there would be a way to "create new index" in the extension as well so generating the indexes is simpler as well...

**Comment by jt-nti** [comment]
It's unlikely that the extension will be enhanced to support index creation but there is Fabric documentation for this https://hyperledger-fabric.readthedocs.io/en/latest/couchdb_as_state_database.html#couchdb-indexes

**Comment by jt-nti** [comment]
Just discovered that there is a wiki page which could include a section for this if anyone can come up with some suitable words -> https://github.com/IBM-Blockchain/blockchain-vscode-extension/wiki/Common-tasks-and-how-to-complete-them
