### ISSUE TITLE
Validate connection data

### ISSUE THREAD

**Issue by caroline-church** [IBM-Blockchain/blockchain-vscode-extension#245]
We should try and validate the users chosen files and if not valid don't add them to user settings

- [ ] try and parse the cert

**Comment by Jakeeyturner** [comment]
We can improve validation for certificates and private keys by checking for `-----BEGIN CERTIFICATE-----`, etc. This validation should be triggered when the user selects 'Browse' and selects a file. If the file is valid, then add the value to the user settings, else throw an error.

**Comment by Jakeeyturner** [comment]
Completed in PR #277
