### ISSUE TITLE
V2 connection to ops console - verify/fix functionality and cucumber tests

### ISSUE THREAD

**Issue by lquintai** [IBM-Blockchain/blockchain-vscode-extension#2471]
When IBP running on fabric v2 is available, we need to:
1. Check if current connection to ops console still works, and fix it if not.
2. Create the two required networks and fix cucumber tests to use the new lifecycle.

**Comment by james-wallis** [comment]
PR https://github.com/IBM-Blockchain/blockchain-vscode-extension/pull/2723 is related to this issue (Adds IBM Cloud Account Extension as a dependency). The PR description contains the missing code blocks to fix https://github.com/ibm-blockchain/blockchain-vscode-extension/issues/2682 for V2.

**Comment by Jakeeyturner** [comment]
Done.
