### ISSUE TITLE
error of npm

### ISSUE THREAD

**Issue by sohan-24** [IBM-Blockchain/blockchain-vscode-extension#2472]
Could not rebuild native dependencies Failed to execute command "npm" with arguments "rebuild, grpc, --target=6.1.5, --runtime=electron, --update-binary, --fallback-to-build, --target_arch=x64, --dist-url=https://atom.io/download/electron" return code 1. Please ensure that you have node and npm installed
my node.jsv install 10.12.0v
my npm 6.4.1
visualstudio code Version: 1.41.1 (system setup)
Commit: 26076a4de974ead31f97692a0d32f90d735645c0
Date: 2019-12-18T14:58:56.166Z
Electron: 6.1.5
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Windows_NT x64 10.0.19041

**Comment by Jakeeyturner** [comment]
I've already responded this this here - https://github.com/IBM-Blockchain/blockchain-vscode-extension/issues/2463#issuecomment-647521335

Closing issue.
