### ISSUE TITLE
Extension issue

### ISSUE THREAD

**Issue by pennammanikantagupta** [IBM-Blockchain/blockchain-vscode-extension#2476]
- Issue Type: `Bug`
- Extension Name: `ibm-blockchain-platform`
- Extension Version: `1.0.33`
- OS Version: `Windows_NT x64 10.0.19042`
- VSCode version: `1.46.1`

:warning: We have written the needed data into your clipboard. Please paste! :warning:

**Comment by Jakeeyturner** [comment]
Hi @pennammanikantagupta 

Please can you provide more information such as all the logs from here.
<img width="958" alt="Screenshot 2020-06-02 at 09 09 43" src="https://user-images.githubusercontent.com/10009752/85551142-9ba5e680-b619-11ea-8378-2c98f6209c57.png">


Thanks,
Jake

**Comment by Jakeeyturner** [comment]
No response - closing issue.
