### ISSUE TITLE
I am having the problem with IBM Extension VS code 

### ISSUE THREAD

**Issue by boteny02** [IBM-Blockchain/blockchain-vscode-extension#2483]
I am having the problem in Window 10 also

Failed to activate extension: Failed to execute command "npm" with arguments "rebuild, grpc, --target=7.1.11, --runtime=electron, --update-binary, --fallback-to-build, --target_arch=x64, --dist-url=https://atom.io/download/electron" return code 1

**Comment by Jakeeyturner** [comment]
Closing issue as it's a duplicate - please see https://github.com/IBM-Blockchain/blockchain-vscode-extension/issues/1621#issuecomment-552926559 for a workaround.

Thanks,
Jake
