### ISSUE TITLE
issue with downloading a prerequisite for the extension "IBM Blockchain Platform"

### ISSUE THREAD

**Issue by himanshu2399** [IBM-Blockchain/blockchain-vscode-extension#2485]
## Description
<I need to download a prerequisite tool for one of my course "IBM Blockchain platfrom">
, the tool is C++ build tools. I am unable to download the tool. The extension that I am using is in the Visual Studio Code. Can anyone help me in this regard.

## Your Environment

* IBM Blockchain Platform Extension Version: 1.0.33
* Visual Studio Code version: 1.46.1
* Environment name and version (e.g. Node.js v8.12.0, npm v6.4.1): Node.js v10.17.0, npm v6.11.3, Docker v19.3.1, Docker Compose v1.24.1, OpenSSL v1.0.2
* Operating System and version: Windows Operating System (Windows10 Home)

**Comment by Jakeeyturner** [comment]
Please refer to the required dependencies [here](https://github.com/IBM-Blockchain/blockchain-vscode-extension#dependency-installation).

Unfortunately Windows 10 Home is not supported and won't work with the extension.

Closing issue.
