### ISSUE TITLE
Provide example that shows maintaining state of an asset vs. console log

### ISSUE THREAD

**Issue by DennisM330** [IBM-Blockchain/blockchain-vscode-extension#249]
With generating a new Smart Contract project, it would be preferable if the sample smart contract code showed an example of maintaining state of an asset with a couple of attributes.

**Comment by EdMoffatt** [comment]
Hey @DennisM330 - we're just doing an issue-review this morning, and wanted to get your thoughts on this suggestion.

- We'd prefer to keep the skeleton smart contract as "skeletal" as possible i.e. whatever you're doing you don't have to delete anything out before you start
- We'd prefer to show examples of this sort of pattern through Samples
- We're planning to add a "welcome" page to the extension, which links to recommended samples
- One of those recommended samples ("Commercial Paper") will provide an example of this pattern

**Comment by DennisM330** [comment]
Samples is a good approach. I agree

**Comment by EdMoffatt** [comment]
Closing this one as it should be covered by #338 and/or #336
