### ISSUE TITLE
Unable to create smart contract

### ISSUE THREAD

**Issue by amannk** [IBM-Blockchain/blockchain-vscode-extension#2495]
Issue Type: <b>Bug</b>

Working on IBM Blockchain Platform using Visual Studio. While trying to create a new project under the smart contracts option, no project is getting opened.

Extension version: 1.0.33
VS Code version: Code 1.46.1 (cd9ea6488829f560dc949a8b2fb789f3cdc05f5d, 2020-06-17T21:13:20.174Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i3-7130U CPU @ 2.70GHz (4 x 2712)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.88GB (1.15GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>

**Comment by Jakeeyturner** [comment]
Hello,

Please could you provide some more information on what you were attempting to do and which buttons/options you pressed.
In addition, please could you try to recreate the problem and provide the logs from the following 'Blockchain' logs:

<img width="958" alt="Screenshot 2020-06-02 at 09 09 43" src="https://user-images.githubusercontent.com/10009752/86352718-24e29c00-bc5e-11ea-92eb-26312ed30b35.png">

Thanks,
Jake

**Comment by gs-repo** [comment]
Having same issue v1.0.35, vs code 1.39.2; output shows installSmartContract but dropdown doesn't appear, so can't install contract.

![image](https://user-images.githubusercontent.com/39061746/88462735-5ff17d00-ce62-11ea-88e1-c5ab83b166a2.png)

**Comment by Jakeeyturner** [comment]
@gs-repo Looks like your environment was never started correctly - I notice you have no Fabric Gateways!

I would try tearing down your local environment, starting it (check the logs to see if this was successful), then try installing again.

Thanks,
Jake

**Comment by Jakeeyturner** [comment]
No response, closing.

**Comment by gs-repo** [comment]
@Jakeeyturner I tried deleting and creating a new environment, the gateway doesn't seem to be getting created. I've create a new issue here: https://github.com/IBM-Blockchain/blockchain-vscode-extension/issues/2617#issue-684824487.
