### ISSUE TITLE
Unable to setup fabric environment in IBM Blockchain Platform in VScode

### ISSUE THREAD

**Issue by himanshu2399** [IBM-Blockchain/blockchain-vscode-extension#2496]
## Description
I'm following Hyperledger's tutorial 1 and setting up a Fabric environment. I have all the right dependencies installed with the right versions. An error occured while I was trying to set up a fabric environment in IBM Blockchain platform in VScode.
The error says that : 
"docker: error during connect: Post https://192.168.99.100:2376/v1.40/containers/create: dial tcp 192.168.99.100:2376: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond."

## Expected Behavior
The environment should be downloaded.
 
## Actual Behavior
Its showing an Error.

## Your Environment
* IBM Blockchain Platform Extension Version: 1.0.33
* Visual Studio Code version: 1.46.1
* Environment name and version (e.g. Node.js v8.12.0, npm v6.4.1):
* Operating System and version: Windows Operating System vWindows10 home x64
* Link to your project:

**Comment by Jakeeyturner** [comment]
Hi @himanshu2399,

Please refer to the [required dependencies](https://github.com/IBM-Blockchain/blockchain-vscode-extension#dependency-installation).

It looks like you're using Windows 10 Home which is not supported.

Closing issue.

**Comment by himanshu2399** [comment]
Hi,
 I have installed the docker toolbox of virtualbox version, which fulfilled the requirment earlier, but the above problem exists.
Is there any other way to get access of the tutorial of the course.

**Comment by Jakeeyturner** [comment]
Hello,

Unfortunately Docker Toolbox will not work - you will need Docker for Windows.

From the dependencies:
`Docker for Windows is configured to use Linux containers (this is the default)`

Thanks,
Jake

**Comment by himanshu2399** [comment]
Hi,
 Is there any alternative for accessing the course.
