### ISSUE TITLE
Suddenly stopped detecting global Node version (set with nvm)

### ISSUE THREAD

**Issue by DeeprajPandey** [IBM-Blockchain/blockchain-vscode-extension#2498]
## Description
The extension was working for a week and it suddenly stopped today when I closed and reopened VS Code. The prerequisites page incorrectly identifies the installed Node version as 14.4.0 but I don't have this version. I use node with nvm (I only have 10.21.0 and 12.17.0) and I have also set up the global default to 10.21.0 and restarted the device and VS Code and reinstalled the extension multiple times.

I have also tried using previous versions of VS Code ([1.45.1](https://code.visualstudio.com/updates/v1_45) and [1.39.2](https://code.visualstudio.com/updates/v1_39)) but it still keeps recognising Node 14.4.0.
The logs are also quite limited.

## Expected Behavior

It should recognise the Node version that's set to default in nvm, i.e. 10.21.0.

## Actual Behavior

It's recognising 14.4.0 which isn't installed and doesn't even show up on the list `nvm ls`.

## Existing issues

- [ ] #1621 I have tried `npm rebuild` in the extension folder (again, default node version is 10.21.0).
- [ ] [VS Code #18253](https://github.com/microsoft/vscode/issues/18253#issuecomment-271235914) This comment says that Code will use the node version that electron is built on. The issue is quite old and I am not sure if this is still the case. And if it is, I'm not sure how it was working before. :/

## Log File
[INFO] Starting IBM Blockchain Platform Extension
[SUCCESS] Finished checking installed dependencies
[WARNING] Required prerequisites are missing. They must be installed before the extension can be used.

## Your Environment

* IBM Blockchain Platform Extension Version: 1.0.34
* Visual Studio Code version: 1.46.1
* Environment name and version: Node.js v10.21.0, npm v6.14.4
* Operating System and version: MacOS 10.15.5

**Comment by Jakeeyturner** [comment]
Have you recently updated to macOS Catalina?
I know that in this update they changed the default shell to be `zsh`.

It might be that an instance of node/npm is installed on `/bin/bash` and is being picked up instead.

I'd start by calling `echo $SHELL` and go from there to figure out why it's not working.

**Comment by DeeprajPandey** [comment]
Hi @Jakeeyturner, I updated to Catalina when it came out last year and I have been using nvm for a long time now.

Also, I forgot which issue this was suggested on but I have also set up `terminal.integrated.automationShell.osx` to `/bin/zsh` and I've checked with `echo $SHELL` that the default shell being picked up by VS Code is in fact ZSH (I have a custom zshrc file and my command completions work as well, so the shell is probably not the issue :/).

I am imagining that after the new update of VS Code, it is probably using the node version of Electron that Code is built on instead of picking up what is set up on the user's terminal.

**Comment by Jakeeyturner** [comment]
If you've downgraded to other VS Code versions, then it probably suggests that somewhere Node 14 is installed on your machine and is being picked up by our extension.

We use the following code to detect versions on the Prereq page, where a `command` might be `node -v`
```
const exec: any = childProcessPromise.exec;

export class CommandUtil {

    // Send shell command
    public static async sendCommand(command: string, cwd?: string): Promise<string> {
        const result: childProcessPromise.childProcessPromise = await exec(command, { cwd: cwd });
        return result.stdout.trim();
    }

...
```

This code hasn't changed in a while so I suspect something on your machine has changed - also indicated that the extension was previously working okay for you.

Let me know how it goes.

Thanks,
Jake

**Comment by Jakeeyturner** [comment]
No response, closing issue.

**Comment by DeeprajPandey** [comment]
Hi,

Sorry I missed this somehow. I remember having to nuke VSCode and reinstalling it to get it working again. I imagine the auto update changed something and made the extension act weird - if I get some time later, I will try reproducing this and add here if I find something substantial.

Putting this here in case someone else faces this and comes here looking for a solution.

Thanks,
DP.
