### ISSUE TITLE
How to remove instantiated, useless chaincode?

### ISSUE THREAD

**Issue by CHCP** [IBM-Blockchain/blockchain-vscode-extension#2509]
## Description
Hi there,
I use IBM Blockchain Platform to debug and test chaincode,  and there are many installed and instantiated Chaincode, so how to remove instantiated, useless chaincode? Thank you very much.

## Expected Behavior
 Remove instantiated, useless chaincode.

## Actual Behavior
I try stop/teardown Fabric Runtime, but it does not work.

## Your Environment
Windows 10, 
IBM Blockchain Platform v1.0.34,
Docker v19.03.8,
VSCode v1.44.1,
Node v12.16.2,
npm v6.13.7,

**Comment by Jakeeyturner** [comment]
Hi @CHCP,

I'm assuming you mean chaincode instantiated and running on your network?

When you teardown your environment it will stop all containers including the network and chaincodes, in addition to killing them and removing them.

When you stop an environment, it only stops the containers - it won't delete / remove them.

Thanks,
Jake

**Comment by CHCP** [comment]
Hi @Jakeeyturner ,
  Thanks for your help. 
  Yes, I want to remove  chaincodes those instantiated and running on my local environment.

 If teardown can remove all chaincodes, so the question changes to: How to teardown the local  Fabric Runtime? 

  I try to teardown Fabric Runtime, but nothing happened. The logs of teardown command as follows:
 ![image](https://user-images.githubusercontent.com/5645296/87213859-6e706c80-c36b-11ea-91a0-6c7ea333044f.png)

**Comment by Jakeeyturner** [comment]
Hello,

That seems like strange behaviour!

In `~/.fabric-vscode/environments/` there should be a directory called `1 Org Local Fabric` (or whatever your environment is called).
Inside that directory should be a `teardown.cmd` script - this is what should get run when you call the 'Teardown environment' command.

Could you try running this `teardown.cmd` script manually?

**Comment by CHCP** [comment]
Hi Jack,
  I found and ran the teardown.cmd script manually, yes all instantiated smart contracts are removed. 
 So the question changed to: Must this script file should be running manually? Any way, it is works, that's a good news.  Thank you again.

**Comment by Jakeeyturner** [comment]
That's good to hear!

That script should be executed when the teardown command is run.
This issue hasn't been reported before, so it could be something to do with your environment or system. Perhaps try deleting the `1 Org Local Fabric` environment and re-creating it?

Anyhow, at least it's working now - closing issue.

Thanks,
Jake
