### ISSUE TITLE
Display Error in the Blockchain Connection Tree

### ISSUE THREAD

**Issue by rthatcher** [IBM-Blockchain/blockchain-vscode-extension#251]
Seeing this display:
![image](https://user-images.githubusercontent.com/29195399/47496801-dc02ff00-d84f-11e8-8a39-30658047cff3.png)

Steps to re-produce:
1. Add a connection to a 'real' fabric, and add 2 identities
2. Stop the 'real' Fabric (haven't tested with fabric started)
3. Double click on one of the IDs, then quite quickly afterwards double click again

Not a serious problem as clicking the Disconnect Icon restores the display.

Other users might see the problem by double clicking twice - retrying if you don't see instant response after the first double click.

**Comment by Jakeeyturner** [comment]
Completed in #267
