### ISSUE TITLE
issue in blockchain environment channels in not working

### ISSUE THREAD

**Issue by sohan-24** [IBM-Blockchain/blockchain-vscode-extension#2510]
error
 Error connecting to environment 1 Org Local Fabric: Error: Error querying channels: 2 UNKNOWN: Stream removed

**Comment by Jakeeyturner** [comment]
Hello,

Please can you provide more information on what you were doing, what actions you performed and the logs.

Thanks,
Jake

**Comment by Jakeeyturner** [comment]
No response, closing issue.
