### ISSUE TITLE
Environment group name "IBM Cloud" is potentially misleading

### ISSUE THREAD

**Issue by erin-hughes** [IBM-Blockchain/blockchain-vscode-extension#2521]
Currently the "IBM Cloud" environment group can have two types of environment in it: ops tools environments and SaaS environments. But only the SaaS environments are guaranteed to run on IBM Cloud, whereas ops tools environments could potentially be running elsewhere. 

This also causes a problem for the `+ Log in to IBM Cloud` tree item, as the logic that determines whether or not it shows up is impacted by environments that might not even be running on IBM Cloud.

We should consider renaming the IBM Cloud group to something else, or moving the ops tools environments to the "other networks" group or a new group of its own.

**Comment by EdMoffatt** [comment]
I think having a group that is "IBP Environments on whatevs cloud" is probably desirable... I'm just guessing but I'd assume a user with IBP consoles on multiple cloud platforms would think of them all as "IBP" not separated into "IBP in IBM Cloud" and "IBP not in IBM Cloud", so the alternative grouping is more a reflection of the implementation than the user logic.

That leaves the question of what to call that group! "IBP Cloud" or "IBP on cloud" would work great, but I don't know if we're supposed to use the abbreviation. I imagine the answer is "no, you're not supposed to do that". And then "IBM Blockchain Platform on cloud" is a stupidly long title (and also repeats the name of the damn extension haha).

Err... I'll keep thinking 😂

**Comment by erin-hughes** [comment]
Chatted with Ed and decided to go with "IBM Blockchain Platform on cloud" for the name of the group.

We're also going to update the logic that shows the `+ Log in to IBM Cloud` button in that group, so that it won't be impacted by the presence of ops tools environments.
