### ISSUE TITLE
Handle connecting to network with 1.4 & 2.0 channels (v2)

### ISSUE THREAD

**Issue by Jakeeyturner** [IBM-Blockchain/blockchain-vscode-extension#2540]
## Description

In a users network there might be numerous channels, each with different capabilities enabled.
At the moment, if any channels aren't V2, then we throw an error and prevent the user from connecting.

As people start to migrate from Fabric 1.4 to 2, it's likely that they'll have a mix of both - so we should handle this behaviour.

One suggestion is that instead of erroring out, we could warn the user that they have a mix of channels but only show/allow interaction with V2 channels.
Another suggestion is to show an icon next to the V1.4 channels.

We also need to make sure we cover the case where all channels are v1.

Will need some design input on this! @Charlotte8699 @EdMoffatt 

## Decision
Display only v2 channels, and alert the user that v1 channels were present and are not going to be displayed.

This is needed to allow users with mixed channels, however the behaviour will change once v1->v2 merge is one.

**Comment by lquintai** [comment]
closed by #2585
