### ISSUE TITLE
Error: Failed to execute command "npm"

### ISSUE THREAD

**Issue by nikduvall** [IBM-Blockchain/blockchain-vscode-extension#2567]
Receiving an error message in VS Code when VS Code Starts.  All Required Prerequisites are satisfied.

## Description
Log show a 404 is being returned when attempting to update the rebuild the native node modules

## Expected Behavior
No error to occur

## Actual Behavior
Error occurs

## Possible Fix
https://medium.com/flawless-app-stories/gyp-no-xcode-or-clt-version-detected-macos-catalina-anansewaa-38b536389e8d

## Steps to Reproduce
1.  Install Visual Studio Code
2.  Install IBM BlockChain Extension from VSCode Marketplace
3.  Install NVM (CMD: curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.35.3/install.sh | bash)
4.  Install node (latest) using NVM (CMD: nvm install node)
5.  Install node v10 using NVM (CMD: nvm install 10)
6.  Set default verson of node to 10 using NVM (CMD: npm alias default 10)
7.  Install Docker App
8.  Run Docker App and follow the prompts until it reaches a running state
9.  Restart VS Code
10.  Verify Blockchain pre-reqs are satisfied
11.  Error message occurs

## Existing issues
Could not find related issues

## Log File
[2-Blockchain.log](https://github.com/IBM-Blockchain/blockchain-vscode-extension/files/4988520/2-Blockchain.log)

## Your Environment

* IBM Blockchain Platform Extension Version: 1.0.35
* Visual Studio Code version: 1.47.3
* Environment name and version:
-     Node.js: 10.22.0
-     npm: 6.14.6
-     Docker: 19.3.12
-     Docker Compose: 1.26.2
* Operating System and version: MacOS Catalina 10.15.6

**Comment by nikduvall** [comment]
Updated bug report to reflect a possible fix.  After running **npm install** in the .vscode extension directory, I saw the error _**gyp: No Xcode or CLT version detected!**_, which I new was untrue because Xcode is installed.  I followed the possible fix above and it worked to resolve the issue in VS Code.

**Comment by Jakeeyturner** [comment]
Glad to hear it now works - closing issue.
