### ISSUE TITLE
How to deploy fabric network to ec2 instance 

### ISSUE THREAD

**Issue by yehia67** [IBM-Blockchain/blockchain-vscode-extension#2580]
Hello,
I had developed my hlf Blockchain project using your extension. Now, I want to deploy it on a vultr instance(of 4GB RAM). Is that possible? How to copy/generate the used docker containers on the instance cloud?
( I can't use IBM cloud as it's expensive for me)

**Comment by Jakeeyturner** [comment]
If you've developed a smart contract, you can install that and run it on peers running anywhere.
I'd recommend taking a look at the Hyperledger Fabric documentation for more information on standing up your network - https://hyperledger-fabric.readthedocs.io/en/release-1.4/
