### ISSUE TITLE
Change debug/toolbar to debug/toolBar

### ISSUE THREAD

**Issue by isidorn** [IBM-Blockchain/blockchain-vscode-extension#2593]
Hi VS Code dev here 👋 

We are deprecating the `debug/toolbar` contribution point in favor of `debug/toolBar`.
Can you please change your contribution point? Thanks

**Comment by Jakeeyturner** [comment]
Hi @isidorn,

Thanks for the information.
What version of VS Code will this change be going into?

Am I correct in thinking that if we change `debug/toolbar` to `debug/toolBar` it will break all users of our extension with an older version of VS Code?

**Comment by isidorn** [comment]
No. It will work for all vscode versions. You can just change it right now no problem.

**Comment by Jakeeyturner** [comment]
Sounds good, thanks for the heads up.
