### ISSUE TITLE
GOPATH issues when packaging

### ISSUE THREAD

**Issue by sstone1** [IBM-Blockchain/blockchain-vscode-extension#2596]
https://github.com/IBM-Blockchain/blockchain-vscode-extension/blob/13b23135fbedf8589d8e9e5fa2ab329cb5be3900/packages/blockchain-extension/extension/commands/packageSmartContractCommand.ts#L117

`GOPATH` can actually contain a set of directories separated by the system path separator (`:` on Linux/macOS, `;` on Windows). This isn't handled by this code. We need to scan all of the directories in the `GOPATH` environment variable looking to see if the project directory is under `GOPATH`.

In the case that `GOPATH` is not set, we check that `<project directory>/../../src` exists. This assumes one path element and only works for `~/projects/src/sstone1/myproject`. There can be any number of path elements between the `src` directory and the project directory, for example a common Go directory structure is ~/projects/src/github.com/sstone1/myproject`.

**Comment by knagware5** [comment]
When this issue will be fixed? I am facing issue while creating package for go chaincode. There is any temporary way to fix this. I think ms-vscode-go extenstion not found in Vscode as this extension changed to some name different name.

**Comment by knagware5** [comment]
It worked when we put the chaincode folder in $GOPATH/src ..Thanks
