### ISSUE TITLE
Issue to Install Block chain platform

### ISSUE THREAD

**Issue by Anakarenrgj** [IBM-Blockchain/blockchain-vscode-extension#2609]
Could not rebuild native dependencies Failed to execute command "npm" with arguments "rebuild, grpc, --target=7.3.2, --runtime=electron, --update-binary, --fallback-to-build, --target_arch=x64, --dist-url=https://atom.io/download/electron" return code 1. Please ensure that you have node and npm installed

**Comment by Jakeeyturner** [comment]
Related to #1621 - the solution is to use an older version of VS Code such as 1.39 - https://code.visualstudio.com/updates/v1_39
