### ISSUE TITLE
Got error DNS resolution failed while submitting transactions to local network on VS Code

### ISSUE THREAD

**Issue by techatwork-a** [IBM-Blockchain/blockchain-vscode-extension#2610]
## Steps to Reproduce
I have installed **vscode v1.39.2 and IBP extension version 1.0.33**.
1. Created smart contract and instantiated on local fabric running using extention.
2. Node SDK
i) Gateway connect, getNetwork, getChannel, getContract executed successufully.
ii) Getting error while executing submitTransaction function.

## Error Description message
```
{
"message": "Endorsement has failed",
"stack": "Error: Endorsement has failed\n at DiscoveryEndorsementHandler._endorse(/Users/workdir/restapi/node_modules/fabric-network/node_modules/fabric-client/lib/impl/DiscoveryEndorsementHandler.js: 185:19)",
"endorsements":[
{
"message": "14 UNAVAILABLE: DNS resolution failed",
"stack": "Error: 14 UNAVAILABLE: DNS resolution failed\n at Object.exports.createStatusError (/Users/workdir/restapi/node_modules/grpc/src/com-mon.js:91:15)\n at Object.onReceiveStatus(/Users/workdir/restapi/node_module/grpc/src/client_interceptors.js:1209:28)\n at InterceptingListener._callNext (/Users/workdir/restapi/node_module/grpc/src/client_interceptors.js: 568:42)\n at InterceptingListener.onReceiveStatus(/Users/workdir/restapi/node_module/grpc/src/client_interceptors.js: 618:8)\n at callback (/Users/workdir/restapi/node_module/grpc/src/client_interceptors.js: 847:24)",
"code": 14,
"metadata": {
"_internal_repr": {},
"flags": 0
},
"details": "DNS resolution failed"
}
]
}
```

## Expected Behavior
Transaction should have been endorsed by "1 Org Local Fabric" network.

## Actual Behavior
DNS resolution failed

## Your Environment

* IBM Blockchain Platform Extension Version: 1.0.33
* Visual Studio Code version: 1.39.2
* Environment name and version (e.g. Node.js v8.12.0, npm v6.4.1): Node.js 10.21.0 npm 6.14.4
* Operating System and version: macOS Catalina 10.15.6 Darwin x64 19.6.0

##System Info
Item | Value
-- | --
CPUs | Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz (12 x 2600)
GPU Status | 2d_canvas: enabledflash_3d: enabledflash_stage3d: enabledflash_stage3d_baseline: enabledgpu_compositing: enabledmetal: disabled_offmultiple_raster_threads: enabled_onoop_rasterization: disabled_offprotected_video_decode: unavailable_offrasterization: enabledskia_renderer: disabled_offsurface_control: disabled_offsurface_synchronization: enabled_onvideo_decode: enabledviz_display_compositor: enabled_onviz_hit_test_surface_layer: disabled_offwebgl: enabledwebgl2: enabled
Load (avg) | 1, 1, 2
Memory (System) | 16.00GB (6.24GB free)
Process Argv |  
Screen Reader | no
VM | 0%

**Comment by techatwork-a** [comment]
Additional information: Catalina os version upgraded from 10.15.1 to 10.15.6 and since then it has stopped working. 

Kindly let me know if anyone is looking into this issue.

**Comment by techatwork-a** [comment]
Additional information: Catalina os version upgraded from 10.15.1 to 10.15.6 and since then it has stopped working.  Kindly let me know if anyone is looking into this issue.

**Comment by techatwork-a** [comment]
Additional information: Catalina os version upgraded from 10.15.1 to 10.15.6 and since then it has stopped working.

Kindly let me know if anyone is looking into this issue or need any additional information.

**Comment by charlesoconor** [comment]
@techatwork-a How did you fix this?
