### ISSUE TITLE
Discovery error from application

### ISSUE THREAD

**Issue by pstuermlinger** [IBM-Blockchain/blockchain-vscode-extension#2615]
## Description
My node application tries to connect to the "1 Org Local Fabric" network but fails with the error `Error: DiscoveryService: mychannel error: access denied`. The VSCode logs are showing `[discovery] processQuery -> WARN 0d7 got query for channel mychannel from 172.x.x.x:44420 but it isn't eligible: signature set did not satisfy policy`

## Expected Behavior
Node SDK should connect without error.

## Actual Behavior
See description

## Steps to Reproduce

1. Start 1 Org Local Fabric network
2. Export Wallet + Connection Profile
3. Use Node SDK to connect:

```
const gateway = new Gateway();
const connectionOptions = {
    identity: "admin",
    wallet: this.wallet,
    discovery: { enabled: true, asLocalhost: false} // already tried all permutations
};

await gateway.connect(this.ccp, connectionOptions);
const network = await gateway.getNetwork("mychannel");
```

## Existing issues
Maybe related to #530?

## Your Environment

* IBM Blockchain Platform Extension Version: 1.0.36
* Visual Studio Code version: 1.48.0
* Environment name and version: Node.js v10.22.0, npm v6.14.6, fabric-network 2.2.0
* Operating System and version: Ubuntu 20 @ WSL2 @ Windows 10 Pro

**Comment by Jakeeyturner** [comment]
Hi @pstuermlinger

So as you're using v1.0.36 of the extension (and not the v2 beta, found in our GitHub releases), `fabric-network@2.2.0` won't be compatible - as it expects the Fabric network to be v2 as well.

A solution would probably be using `fabric-network@1.4.11` or any other version with the same 'major' version (v1.X)

**Comment by pstuermlinger** [comment]
Thanks @Jakeeyturner . I will try the beta.
