### ISSUE TITLE
V2 Beta: Cannot deploy smart contract

### ISSUE THREAD

**Issue by pstuermlinger** [IBM-Blockchain/blockchain-vscode-extension#2616]
## Description
When the extension tries to deploy (no custom settings) the contract to a local 1 Org network, it fails with `Failed to deploy smart contract, Package was not installed. No packageId was returned` and
```
Failed to install on peer Org1Peer1 with reason: Could not install smart contact received error: failed with status:500 ::failed to invoke backing implementation of 'InstallChaincode': could not build chaincode: docker build failed: docker image build failed: docker build failed: Error returned from build: 1 "can't load package: package .: no Go files in /go "
```
The chaincode is within `$GOPATH/src/mycc`. I did a `go mod init` and `go mod vendor`. Packaging+Deployment worked with extension 1.36.x

## Expected Behavior
Chaincode should be deployed.

## Actual Behavior
Deployment fails

## Log File
```
[8/24/2020 3:43:52 PM] [INFO] 1OrgLocal_peer0.org1.example.com|2020-08-24 13:43:52.793 UTC [chaincode.platform] func1 -> ERRO 136 docker build failed: Error returned from build: 1 "can't load package: package .: no Go files in /go
[8/24/2020 3:43:52 PM] [INFO] 1OrgLocal_peer0.org1.example.com|"
[8/24/2020 3:43:52 PM] [INFO] 1OrgLocal_peer0.org1.example.com|2020-08-24 13:43:52.793 UTC [dockercontroller] buildImage -> ERRO 137 Error building image: docker build failed: Error returned from build: 1 "can't load package: package .: no Go files in /go
[8/24/2020 3:43:52 PM] [INFO] 1OrgLocal_peer0.org1.example.com|"
[8/24/2020 3:43:52 PM] [INFO] 1OrgLocal_peer0.org1.example.com|2020-08-24 13:43:52.794 UTC [dockercontroller] buildImage -> ERRO 138 Build Output:
[8/24/2020 3:43:52 PM] [INFO] 1OrgLocal_peer0.org1.example.com|********************
[8/24/2020 3:43:52 PM] [INFO] 1OrgLocal_peer0.org1.example.com|
[8/24/2020 3:43:52 PM] [INFO] 1OrgLocal_peer0.org1.example.com|********************
```

## Your Environment

* IBM Blockchain Platform Extension Version: 2.0.0-beta.6
* Visual Studio Code version: 1.48.0
* Environment name and version: Node.js v10.22.0, npm v6.14.6, go 1.14.4
* Operating System and version: Ubuntu 20 @ WSL2 @ Windows 10 Pro

**Comment by deanzaka** [comment]
Any update on how to solve this issue?
I'm on IBP Extension 2.0.0, VS Code 1.52.1, Windows 10 build 19042
Still having the same issue with the deployment

**Comment by Jakeeyturner** [comment]
There are additional notes here on how to package & deploy Go contracts correctly - https://github.com/IBM-Blockchain/blockchain-vscode-extension/wiki/Errors-&-Fixes#go-projects

**Comment by deanzaka** [comment]
Appreciate the quick response.
Tried all the things in the mentioned notes. Unfortunately, still not able to deploy the contract that packaged from inside the VS Code itself. Tried packaged it manually using hlf peer command outside VS Code, import the package to VS Code, then finally able to deploy from that.

It might be an issue on my VS Code configuration though. Since when I tried to package it as cds, it gives me 'not gopath subdir' error, even though I put it under the correct path, and configure gopath values both in system variables and vs code gopath, correctly.

Will leave the issue, for now, at least I'm able to continue to work with the manually packaged contract.
But, again, thank you for your response.

**Comment by Jakeeyturner** [comment]
Hi @deanzaka,

If you set the GOPATH whilst VS Code is open, you'll need to restart it.

Thanks,
Jake

**Comment by harishkgithub** [comment]
> Appreciate the quick response.
> Tried all the things in the mentioned notes. Unfortunately, still not able to deploy the contract that packaged from inside the VS Code itself. Tried packaged it manually using hlf peer command outside VS Code, import the package to VS Code, then finally able to deploy from that.
> 
> It might be an issue on my VS Code configuration though. Since when I tried to package it as cds, it gives me 'not gopath subdir' error, even though I put it under the correct path, and configure gopath values both in system variables and vs code gopath, correctly.
> 
> Will leave the issue, for now, at least I'm able to continue to work with the manually packaged contract.
> But, again, thank you for your response.

"Tried packaged it manually using hlf peer command outside VS Code, import the package to VS Code, then finally able to deploy from that."

Can you please explain me How did you do this?
I don't know how to install and use "peer" command 

Thanks

**Comment by winterpi** [comment]
@[harishkgithub](https://github.com/harishkgithub) use "peer" command as follows:
```
Package Smart Contract chaincode (into tar.gz'). For my example, run: /Users/paul/dev/hyperledgerfabric/fabric-samples/bin/peer lifecycle chaincode package smartcontract05.tar.gz --path . --lang golang --label smartcontract05_1.0
```
source from: https://github.com/IBM-Blockchain/blockchain-vscode-extension/issues/3007

But unfortunately, I still cannot deploy smart contract yet.
