### ISSUE TITLE
Unable to create fabric gateway locally

### ISSUE THREAD

**Issue by gs-repo** [IBM-Blockchain/blockchain-vscode-extension#2617]
I'm trying to create a HLF local environment and it errors out with: 

Error: Failed to execute command "cmd" with  arguments "/c, generate.cmd" return code 2

I've attached the log file below. I realize there are issues with channel configuration update. Rather than setting up manually would prefer to do it through the extension.

[2-Blockchain.log](https://github.com/IBM-Blockchain/blockchain-vscode-extension/files/5119210/2-Blockchain.log)

* IBM Blockchain Platform Extension Version: 1.0.36
* Visual Studio Code version: 1.39.2
* Environment name and version (e.g. Node.js v8.12.0, npm v6.4.1): Node 10.17.0, npm 6.11.3
* Operating System and version: Windows 10 Pro

**Comment by Jakeeyturner** [comment]
Closing - no longer using Ansible playbooks. Local environments now use microfab, which should fix the problem.
