### ISSUE TITLE
I am having the following issue at the time of Installing IBM platform 

### ISSUE THREAD

**Issue by PatelPriyanka** [IBM-Blockchain/blockchain-vscode-extension#2626]
### Error message
Failed to activate extension: Failed to lo
ad /home/priya/.vscode/extensions/ibmblockchain.ibm-blockchain-platform-1.0.37/node_modules/grpc/src/node/extension_binary/electron-v7.3-linux-x64-glibc/grpc_node.node. /snap/core/current/lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by /home/priya/.vscode/extensions/ibmblockchain.ibm-blockchain-platform-1.0.37/node_modules/grpc/src/node/extension_binary/electron-v7.3-linux-x64-glibc/grpc_node.node)

![Error](https://user-images.githubusercontent.com/17672443/92414895-4a8b9600-f124-11ea-9645-bac7ac243780.jpeg)

**Comment by Jakeeyturner** [comment]
Hi,

Please could you provide more information on the issue you're having, including logs, etc?

**Comment by PatelPriyanka** [comment]
So, when I was trying to add IBM platform I was having error. Than I uninstall  and reinstall my few libraries (gRPC, Node) in Ubuntu machine and then Then uninstall Visual studio code and delete all the old library and install fresh and It work. 

I guess there is something in libraries which get Brock by accident and reinstall work. 
Sorry I do not have error code now. 

Thank you for asking

**Comment by davidkel** [comment]
Are you installing vscode via snap ? if you are then that could be contributing to mismatch of c libraries. Maybe try installing vscode direct from a .deb download instead.

**Comment by PatelPriyanka** [comment]
ok I will 
I install through Ubuntu software. I will try cmd

**Comment by PatelPriyanka** [comment]
It work 
Thank you 

(I would like to say that the gRPC is also important. Need to install "npm install grpc". Without this I was having problem. )
