### ISSUE TITLE
Extension issue

### ISSUE THREAD

**Issue by adityakr** [IBM-Blockchain/blockchain-vscode-extension#2630]
- Issue Type: `Bug`
- Extension Name: `ibm-blockchain-platform`
- Extension Version: `1.0.37`
- OS Version: `Windows_NT x64 10.0.18363`
- VSCode version: `1.48.2`

:warning: We have written the needed data into your clipboard. Please paste! :warning:

**Comment by Jakeeyturner** [comment]
Hi,

Please could you provide more information on the error you're seeing?

Thanks,
Jake
