### ISSUE TITLE
cant start local fabric 

### ISSUE THREAD

**Issue by shp206** [IBM-Blockchain/blockchain-vscode-extension#2632]
Issue Type: <b>Performance Issue</b>

Failed to start 1 Org Local Fabric: Error: Failed to execute command "cmd" with  arguments "/c, generate.cmd" return code 125 .......please help i am a student trying to learn

Extension version: 1.0.37
VS Code version: Code 1.39.2 (6ab598523be7a800d7f3eb4d92d7ab9a66069390, 2019-10-15T15:35:18.241Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i3-7020U CPU @ 2.30GHz (4 x 2304)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.87GB (1.77GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    2	    70	 30536	code main
    0	   151	  9288	   window (Preview a3.md - Untitled (Workspace) - Visual Studio Code)
    0	     4	  7400	     C:\WINDOWS\System32\cmd.exe
    0	     4	 23012	     C:\WINDOWS\System32\cmd.exe
    0	     5	 23208	     console-window-host (Windows internal process)
    0	     6	 25772	     console-window-host (Windows internal process)
    0	    10	 26828	     watcherService 
    0	     6	 34396	       console-window-host (Windows internal process)
    0	   119	 32164	     extensionHost
    0	    23	 25996	       electron_node server.js 
    0	     4	 33828	       cmd /c is_running.cmd
    0	     4	 19992	         C:\WINDOWS\system32\cmd.exe /c docker ps -f label=fabric-environment-name="1 Org Local Fabric" -q | find /v /c ""
    0	     2	 20488	           find  /v /c ""
    0	    23	 30868	           docker  ps -f label=fabric-environment-name="1 Org Local Fabric" -q 
    0	    11	 25024	         console-window-host (Windows internal process)
    1	   213	 20972	   gpu-process
    0	    46	 24876	   window (undefined)
    0	    62	 26912	   shared-process
    0	    12	 32684	   electron-crash-reporter
    3	    66	 36256	   window (Issue Reporter)
```

</details>
<details>
<summary>Workspace Info</summary>

```
|  Window (Preview a3.md - Untitled (Workspace) - Visual Studio Code)
|    Folder (demo-contract): 19 files
|      File types: json(6) ts(4) editorconfig(1) gitignore(1) npmignore(1)
|                  txdata(1)
|      Conf files: package.json(1) tsconfig.json(1) tslint.json(1)
|                  launch.json(1)
|      Launch Configs: fabric:node;
```

</details>

**Comment by Jakeeyturner** [comment]
Hello,

Please could you provide more information about this issue? Can you provide the logs in the Output also?

Thanks,
Jake
