### ISSUE TITLE
Failed to instantiate smart contract on macOS

### ISSUE THREAD

**Issue by outk** [IBM-Blockchain/blockchain-vscode-extension#2647]
I could not continue tutorial because of an error during instantiating smart contract on macOS.

### Environment

- macOS Catalina 10.15.6
- VSCode: 1.49.1
- IBM Blockchain Platform: v1.0.37
- Docker: v19.03.12
- node: v10.22.1
- npm: 6.14.6

### Blockchain Log

> [9/22/2020 9:04:08 PM] [ERROR] Error instantiating smart contract: Error: chaincode registration failed: container exited with 1

### Fabric Peer Container Log

> 2020-09-22 12:02:15.434 UTC [endorser] callChaincode -> INFO 06e [mychannel][e446b7b6] Entry chaincode: name:"lscc"
> 
> 2020-09-22 12:04:08.248 UTC [endorser] callChaincode -> INFO 06f [mychannel][e446b7b6] Exit chaincode: name:"lscc" (112810ms)
> 
> 2020-09-22 12:04:08.252 UTC [endorser] SimulateProposal -> ERRO 070 [mychannel][e446b7b6] failed to invoke chaincode name:"lscc" , error: container exited with 1
> github.com/hyperledger/fabric/core/chaincode.(*RuntimeLauncher).Launch.func1
> /opt/gopath/src/github.com/hyperledger/fabric/core/chaincode/runtime_launcher.go:63
> runtime.goexit
> /opt/go/src/runtime/asm_amd64.s:1337
> chaincode registration failed
> 
> 2020-09-22 12:04:08.257 UTC [comm.grpc.server] 1 -> INFO 071 unary call completed grpc.service=protos.Endorser grpc.method=ProcessProposal grpc.peer_address=172.20.0.1:44652 grpc.code=OK grpc.call_duration=1m52.824717935s

**Comment by yuriaps** [comment]
As I know, IBM Blockchain vs code extension doesn't work in vs code version >= 1.40, I use
Node v10.22.0
macOS Catalina 10.15.7
VS Code 1.38.1
