### ISSUE TITLE
[v2 merge] As a user I can create v1 and v2 contracts

### ISSUE THREAD

**Issue by lquintai** [IBM-Blockchain/blockchain-vscode-extension#2652]
## Description
Currently we can only create v1 contracts on the v1 extension and v2 contracts on the v2 extension. We will need to be able to create both types. To do that. we need to:

- [ ] Update flow to ask the user which version they want
- [ ] Change generator-fabric to be able to create both types of contract in the same version - [link to issue in generator-fabric
](https://github.com/IBM-Blockchain/generator-fabric/issues/354)

**Comment by Jakeeyturner** [comment]
Closing as this has been merged.
