### ISSUE TITLE
[v2 merge] As a user I can install v1 chaincode packages (implement fabric-client functionality)

### ISSUE THREAD

**Issue by lquintai** [IBM-Blockchain/blockchain-vscode-extension#2654]
## Description

Need to be able to follow the two types of chain code lifecycle. Currently v1 extension follows v1 lifecycle, and v2 extension follows v2 lifecycle.
- [ ] Probably need to implement fabric-client (1.4) functionality
- [ ] Decide which way to install in the install command - should be straightforward because the package extension will be different.

**Comment by Jakeeyturner** [comment]
Closing as complete.
