### ISSUE TITLE
[v2 merge] As a user I can instantiate and upgrade v1 chaincodes

### ISSUE THREAD

**Issue by lquintai** [IBM-Blockchain/blockchain-vscode-extension#2655]
## Description

Need to be able to follow the two types of chain code lifecycle. Currently v1 extension follows v1 lifecycle, and v2 extension follows v2 lifecycle.

- [ ] Probably need to implement fabric-client (1.4) functionality
- [ ] Re-introduce instantiate command (this lifecycle step does not exist in the v2 lifecycle)

**Comment by Jakeeyturner** [comment]
Merged.
