### ISSUE TITLE
[v2 merge] As a user I can install+instantiate my v1 chaincode packages using a ‘deploy’ webview similar to current v2

### ISSUE THREAD

**Issue by lquintai** [IBM-Blockchain/blockchain-vscode-extension#2656]
## Description

In the v1 extension the chain code deployment is done by right-clicking or command palette commands, for install and instantiate.
In the v2 extension the deploy steps are unified in a single deploy webview.

We want to create a similar experience for the v1 deployment:
- [ ] Create UI for install and instantiate steps
- [ ] Choose which UI to present to the user depending on the channel capabilities

**Comment by erin-hughes** [comment]
Delivered in PR #2860
