### ISSUE TITLE
[v2 merge] As a user I can create v1 and v2 local environments

### ISSUE THREAD

**Issue by lquintai** [IBM-Blockchain/blockchain-vscode-extension#2657]
## Description

To do this we need to:
- [ ] Add to the flow: ask user which version they want
- [ ] Use microfab to deploy local environment
- [ ] v1 Local Fabric: v2 binaries with v1 capabilities
- [ ] v2 Local Fabric: v2 binaries with v2 capabilitites

**Comment by Jakeeyturner** [comment]
Marking as blocked - requires local microfab work first.

**Comment by Jakeeyturner** [comment]
Closing as merged.
