### ISSUE TITLE
[v2 merge] Design decision for tree structure and presentation

### ISSUE THREAD

**Issue by lquintai** [IBM-Blockchain/blockchain-vscode-extension#2659]
## Description

Since we are supporting 2 versions of everything (contracts, packages, environments, gateways, wallets) we need to decide how we will present this to the user.

Here are some options in no particular order. Some of them might not be feasible, and **should be removed if that is the case**:

1. No differentiation. The user will have to know/remember/guess what I what. Cheaper, no need for further work.
2. Differentiate using icons on each of the tree elements.
3. Differentiate by adding text: something like a grey `v1.4` or `v2` in front of the element name - **check if possible**
4. Differentiate with groups: we do this for local/cloud/other environments/wallets/etc. We need to check we can have subgroups, as all these existing groups would need to be present  - **check if possible**
5. Differentiate with new panels - this would probably make it too crowded but thought I should include it.
6. Differentiate by creating a tab, so that we can 'switch' between the 2 versions. Would need to disconnect from everything when switching - **check if possible**

If there is something missing from the list, please add it.

**Comment by Jakeeyturner** [comment]
This is something we should do on a second pass!
