### ISSUE TITLE
[v2 merge] Debug smart contract - update or remove

### ISSUE THREAD

**Issue by lquintai** [IBM-Blockchain/blockchain-vscode-extension#2660]
## Description

Check if:

- v1 debug still works with microfab
- v2 debug would work with microfab

**Decide if we should support debug for both versions, just one, or none. Create issues as needed.**

**Comment by Jakeeyturner** [comment]
We won't be doing this in the first pass!

**Comment by koakh** [comment]
Hello **I'm try hard to debug chaincodes in vscode with blockchain-vscode-extension**, 
for me it's a vital feature, useful when we have big chaincodes with many models and some logic

I try **enable dev-mode in peers** and a hack container, 
but now way it seems that it's is not possible or not documented

I read in [README](https://github.com/IBM-Blockchain/blockchain-vscode-extension)

_The IBM Blockchain Platform extension helps developers to **create, test and debug smart contracts**, connect to Hyperledger Fabric environments, and build applications that transact on your blockchain network._

Is this information valid? debug smart contracts?

other question is, it is possible to debug v2 with minifab or it will be in a near future

I think is better to update the README to show this info, this way other users don't waste precious time like

debug v1 OK
debug v2 KO

currently I use v1 with **convector package** and can debug typescript easy

awesome extension

thanks

**Comment by FelipeSanchezCalzada** [comment]
Debug chaincode is vital for me too, without the possibility of debugging it is impossible for me to use the new version of the extension. Is there an approximate date for the implementation of the fabric version 2.0 debug? Is there an approximate date for the second pass?
Thanks for the work

**Comment by koakh** [comment]
After I google a lot i cant find anyone that know how to do that por better that want/have time to help, 
But I never guve up and I have found a way to debug it with javascript, and with typescript sourceMaps too 👍 )

I lost 4 nights but in the end is simple and awesome.
And the developing experience is perfect, better that with Convector, is super fast se debug in 5 seconds por less

Just launch debug and it works

The trick is using peer in dev-mode

I think its easy to put vscode extension works with it
In the past i put the extension with peer and dev-mode but in that time I dont know every piece of the trick

I can try to do that in extension por can share my findings, no problem

**Comment by lasharela** [comment]
I'm facing the same issue.
Looks like everything is running but the debugger is not working still.

**Comment by lasharela** [comment]
any updates on this?

**Comment by davidkel** [comment]
@lasharela It looks like for fabric v2, only fabric 2.3.x supports dev mode required for debug and the fabric environment used by the extension is from microfab which only provides a fabric 2.2 environment. Also microfab would have to be able to bring the peers up in dev mode and doesn't have the capability to do so.
You may be able to get debug working yourself by bringing up your own local fabric 2.3 network and enabling dev mode on the peers yourself (see https://hyperledger-fabric.readthedocs.io/en/release-2.3/peer-chaincode-devmode.html) then importing that into the extension (see https://github.com/IBM-Blockchain/blockchain-vscode-extension/wiki/Common-tasks-and-how-to-complete-them#connecting-to-an-instance-of-hyperledger-fabric). I've not tried this myself. The alternative is to go back to the V1 extension.

**Comment by lasharela** [comment]
Guys, is there any information on when debugging will be solved?

**Comment by riki95** [comment]
I am using extension version 2.0.4, created a smart contract package from scratch and I cannot debug neither in local environment neither in microfab.
Any idea of when this will be fixed? Debugging smart contracts is a very useful feature and a high priority one

**Comment by SamYuan1990** [comment]
hi guys, is this feature ready?

**Comment by riki95** [comment]
Greetings, any update on this? Debugging locally is very important to test chaincode.

**Comment by riki95** [comment]
Greetings, just checking if there is any update on this thread or maybe possibility to contribute. Debugging chaincodes is a very important feature. I've seen that there is an investigation opened by @jt-nti  so maybe also further updates on what you will be doing to re-insert the feature on the extension. Thanks a lot

**Comment by jt-nti** [comment]
Hi @riki95, sorry I should have left a comment as well as adding the `investigation` tag! It would be useful to investigate whether using the Chaincode As A Server (CCaaS) feature in Fabric would help with debugging chaincodes. 

Having said that, no one is actively investigating but the recent Fabric release has simplified CCaaS so it should be possible to debug chaincode in this way without changes to the vscode extension. For example, [Running Chaincode as Service with the Test Network](https://github.com/hyperledger/fabric-samples/blob/main/test-network/CHAINCODE_AS_A_SERVICE_TUTORIAL.md) explains how to run CCaaS in the Fabric test network. If I find more details that would help, I'll add them here.

Any contributions to help to fix debugging in the vscode extension would be very welcome.

**Comment by riki95** [comment]
Hi @jt-nti , I managed to deploy the typescript assets transfer basic on the test-network and invoking it via the peer commands but that's not exactly what I would like to do.
I would need to debug with vs code and breakpoints and this was doable in the past (Fabric 1.4).

I have no idea of how to debug the chaincode that I deployed. Also, there are scripts to deploy typescript files but not standard javascript ones. With them, the scripts are failing so I think they are not complete.

I think the breakpoint debug is a very needed feature for production projects so it's strange is not well implemented

**Comment by lasharela** [comment]
Common guys, is this still an open issue? :)

**Comment by riki95** [comment]
Still needed! Really hope this can be developed

**Comment by jt-nti** [comment]
Hyperledger Fabric is moving away from the traditional chaincode deployment model and development mode, towards [executing chaincode outside of Fabric](https://hyperledger-fabric.readthedocs.io/en/release-2.4/cc_service.html), which does make developing and debugging chaincode much easier.

Recent updates in Fabric 2.4 make deploying chaincode as a server more straightforward than it used to be, unfortunately there are still missing pieces, and I'm also not sure when the vscode extension is likely to be updated to support this approach.

Having said that, it should still be possible to use built in vscode capabilities to debug chaincode, and there is an early draft of some documentation which will hopefully help with that...

https://github.com/hyperledgendary/fabric-contract-debug-scenario/blob/main/README.md

**Comment by jt-nti** [comment]
See #3183
