### ISSUE TITLE
can't find install smart contract 

### ISSUE THREAD

**Issue by christinesu12** [IBM-Blockchain/blockchain-vscode-extension#2662]
![2020-09-24 10-05-06 的螢幕擷圖](https://user-images.githubusercontent.com/50400404/94093953-f9ccaa80-fe50-11ea-8dde-5aa288e778a9.png)

## Steps to Reproduce

1.link to the actual extension 
https://github.com/IBM-Blockchain/blockchain-vscode-extension/releases/download/v2.0.0-beta.7/ibm-blockchain-platform-2.0.0-beta.7.vsix
https://open-vsx.org/api/vscode/markdown-language-features/1.39.1/file/vscode.markdown-language-features-1.39.1.vsix
https://github.com/IBM/vscode-ibmcloud-account/releases/download/v1.0.2/ibmcloud-account-1.0.2.vsix
2.steps to reproduce the bug  - browser
3.include any console logs in the issue  - The server IP address of  be100ca5-76b9-4063-9268-5e50421d7732.webview.10.78.153.145  cannot be found.

## Your Environment

* IBM Blockchain Platform Extension Version:
* Theia
* Environment name and version (e.g. Node.js v8.12.0, npm v6.4.1):node v10.22.1,npm 6.14.6,Docker version 19.03.13,docker-compose version 1.27.3

**Comment by Jakeeyturner** [comment]
Hi @christinesu12,

With version 2 of the extension you will need to use the 'Deploy Smart Contract' command - this handles the new Fabric 2.0 lifecycle which includes, installing, approving and committing a smart contract definition.

Let me know how it goes.

Thanks,
Jake
