### ISSUE TITLE
Welcome page and tutorials do not render correctly

### ISSUE THREAD

**Issue by christinesu12** [IBM-Blockchain/blockchain-vscode-extension#2663]
IBM-Blockchain/blockchain-vscode-extension - Welcome page and tutorials do not render correctly

blockchain-vscode-extension : Welcome page and tutorials do not render correctly

![theia-blockchain-home](https://user-images.githubusercontent.com/50400404/94100248-add53200-fe5f-11ea-8ec8-f6490207d2fb.png)
![theia-blockchain-pre](https://user-images.githubusercontent.com/50400404/94100249-af9ef580-fe5f-11ea-95ab-53a2c732afa8.png)

1.extension -
https://github.com/IBM-Blockchain/blockchain-vscode-extension/releases/download/v2.0.0-beta.7/ibm-blockchain-platform-che-2.0.0-beta.7.vsix
https://open-vsx.org/api/vscode/markdown-language-features/1.39.1/file/vscode.markdown-language-features-1.39.1.vsix
https://github.com/IBM/vscode-ibmcloud-account/releases/download/v1.0.2/ibmcloud-account-1.0.2.vsix
2.browser
3. The server IP address of 7310ff67-f4be-44b9-b8b1-5e885e582d32.webview.10.78.153.145 cannot be found.

## Your Environment

* IBM Blockchain Platform Extension Version: 2.0.0-beta.7
* theia 
* Environment name and version :
   node v10.22.1, npm v6.14.6, Docker version 19.03.13, docker-compose version 1.27.3

**Comment by Jakeeyturner** [comment]
Hi @christinesu12,

I suspect you haven't downloaded the 'Che' version of the extension from the releases page (which should work with Theia).
Try https://github.com/IBM-Blockchain/blockchain-vscode-extension/releases/download/v2.0.0-beta.7/ibm-blockchain-platform-che-2.0.0-beta.7.vsix - I just tried it and these pages seem to render fine.

Let me know how that goes!

Thanks,
Jake

**Comment by christinesu12** [comment]
IBM-Blockchain/blockchain-vscode-extension - Welcome page and tutorials do not render correctly

blockchain-vscode-extension : Welcome page and tutorials do not render correctly
 The server IP address of 7d503c03-c30a-40eb-8dca-f276b7dadc86.webview.0.0.0.0 cannot be found.

extension - https://github.com/IBM-Blockchain/blockchain-vscode-extension/releases/download/v2.0.0-beta.7/ibm-blockchain-platform-2.0.0-beta.7.vsix
![theia-2](https://user-images.githubusercontent.com/50400404/94650019-74ea0100-0328-11eb-8e8f-98619650fefb.png)

extension - https://github.com/IBM-Blockchain/blockchain-vscode-extension/releases/download/v2.0.0-beta.7/ibm-blockchain-platform-che-2.0.0-beta.7.vsix
![theia-2-che](https://user-images.githubusercontent.com/50400404/94650028-787d8800-0328-11eb-812b-615a00e770b6.png)
* other problem
2.0-che => fabric environment 
[ERROR] Cannot connect to environment: Error: Error when choosing environment, no environments found to choose from.
