### ISSUE TITLE
pre-req page for windows can be confusing

### ISSUE THREAD

**Issue by davidkel** [IBM-Blockchain/blockchain-vscode-extension#2670]
If using a version of VS Code 1.39 or earlier then you don't need to windows build tools if you turn off local fabric. But for newer VS Code versions then you do need the windows build tools to build the grpc native module for the extension. The pre-reqs page would need to take the version of VS Code into account.

A further minor problem is in the description of the pre-reqs for windows.

The Windows Build Tools is really a meta npm package as it doesn't install an npm module but rather it installs an old copy of Python (2.7) and a 2017 version of the microsoft build tools which includes a C++ compiler onto the system. It's perfectly feasible for someone to install their own versions of the microsoft development tools and python interpreter, however the pre-reqs only check for the existence of the npm metapackage and label it as C++ build tools (which isn't technically correct).
At a minimum it would probably be worth changing the name from `C++ Build tools` to perhaps the `NPM packaged Windows Build Tools` ?

**Comment by Jakeeyturner** [comment]
Closing - I don't think this is relevant any more for the latest extension version.
