### ISSUE TITLE
Error while adding external network : Error: Error querying channels: 14 UNAVAILABLE: Empty update

### ISSUE THREAD

**Issue by poojaKamat** [IBM-Blockchain/blockchain-vscode-extension#2676]
Getting error while adding custom network running locally.

## Description
The plugin can successfully connect to the local network which is bootstrapped by the plugin. On similar basis have created a custom Hyperledger Fabric network residing locally .
Have provided the input node json files while adding the network, have added appropriate wallets and admin identities, however the plugin is not able to query channel.

## Expected Behavior
The network should successfully connect to the local custom network which was not bootstrapped by the plugin.

## Actual Behavior
Getting below error at plugin(in OUTPUT console)
[10/1/2020 6:02:05 PM] [ERROR] Error connecting to environment custom-network: Error: Error querying channels: 14 UNAVAILABLE: Empty update

## Steps to Reproduce

1. Created a Hyperledger Fabric network locally by using fabric samples v1.4 [link](https://github.com/hyperledger/fabric-samples/tree/release-1.4)
Executed the 

> ./startFabric.sh javascript

 command to bootstrap the network.
2. Create channel, create admin identities for all nodes.
3.Create json files in the following format : TLS is enabled on the network.

{
    "name": "peer0.org1.example.com",
    "api_url": "grpcs://localhost:17051",
    "type": "fabric-peer",
    "msp_id": "Org1MSP",
    "pem": "Add root TLS certificate pem file content"
}

4. Add environment using node json files.
5. Add wallets and identities, have enrolled admin on the network for each organization, created admin users for each org, gave the input signing certificate and private key of the identity.

## Log File

[10/1/2020 6:02:05 PM] [INFO] connecting to fabric environment
[10/1/2020 6:02:05 PM] [ERROR] Error connecting to environment custom-network: Error: Error querying channels: 14 UNAVAILABLE: Empty update

## Your Environment

* IBM Blockchain Platform Extension Version:v1.0.37
* Visual Studio Code version:1.49.2
* OS: Windows 10 machine

**Comment by Jakeeyturner** [comment]
Closing - problem is with the network.
Custom networks can be easily created using microfab as detailed in the `Create and use a custom Fabric network` tutorial.
