### ISSUE TITLE
Prerequisite OpenSSL is not getting recognized by IBP extension of vscode on Windows 10

### ISSUE THREAD

**Issue by techatwork-a** [IBM-Blockchain/blockchain-vscode-extension#2678]
Prerequisite OpenSSL is not getting recognized by IBP extension of vscode on Windows 10

## Description
IBP vscode extension has multiple dependencies on external softwares like docker, OpenSSL etc. I have installed Docker and OpenSSL. Docker is getting recognized by extension and does not give missing prerequisites error but OpenSSL is not getting recognized by extension and gives missing prerequisites error on Windows 10 system. 

## Expected Behavior
OpenSSL should have been recognized by IBM extension on Windows 10 system.

## Actual Behavior
OpenSSL is not recognized by IBM extension on Windows 10 system.

## Steps to Reproduce
Perform below steps on Windows 10 system.
1. Install VS code
2. Install IBP extension. 
3. Install prerequisites by following instructions given.
4. Install "Win64 OpenSSL v1.1.1h" by downloading from http://slproweb.com/products/Win32OpenSSL.html.

* IBM Blockchain Platform Extension Version: 1.0.32
* Visual Studio Code version: 1.39.2
* Environment name and version (e.g. Node.js v8.12.0, npm v6.4.1): node.js v10.22.0 and npm 6.13.1
* Operating System and version: Windows 10 Pro

**Comment by davidkel** [comment]
I think the instructions for openssl are currently not correct.
Try uninstalling OpenSSL v1.1.1 and installing Win64 OpenSSL v1.0.2 instead
see #2633 which hopefully will update the docs on the next release

**Comment by techatwork-a** [comment]
@davidkel 
Win64 OpenSSL v1.0.2 does not exist on website http://slproweb.com/products/Win32OpenSSL.html. Which website can I refer to get the same as IBP extension doesn't work after skipping OpenSSL prerequisite.

**Comment by davidkel** [comment]
You are right, it's been removed now :-( That's a problem because the npm package that the fabric chaincode 1.4 relies on that uses it only works with OpenSSL 1.0.2

**Comment by techatwork-a** [comment]
@davidkel Thank you!

**Comment by pxlfrk** [comment]
@techatwork-a @davidkel if you need the old installer, have a look here:
https://web.archive.org/web/20191113082429/http://slproweb.com/download/Win64OpenSSL-1_0_2t.exe

Hope this helps :)

**Comment by prajdus** [comment]
> @techatwork-a @davidkel if you need the old installer, have a look here:
> https://web.archive.org/web/20191113082429/http://slproweb.com/download/Win64OpenSSL-1_0_2t.exe
> 
> Hope this helps :)

Thx, You saved life .
