### ISSUE TITLE
A5.27 results in:  src/create.ts:1:10 - error TS2305:  has no exported member 'FileSystemWallet'

### ISSUE THREAD

**Issue by winf3** [IBM-Blockchain/blockchain-vscode-extension#2716]
## Description
I did the Blockchain Platform Basic Tutorials until Step A5.27 ok. There I do a Run Build Task in VS Code on Windows 10.
Then I get the following 2 errors:

src/create.ts:1:10 - error TS2305: Module '"../node_modules/fabric-network/types"' has no exported member 'FileSystemWallet'.
Did I miss to export the wallet in the IBM Cloud ?

2nd Error:
rc/create.ts:16:31 - error TS2345: Argument of type 'string' is not assignable to parameter of type 'object | Client'.

16         await gateway.connect(connectionProfile, connectionOptions);

What can I do to fix these errors ? 

create.ts content:
import { FileSystemWallet, Gateway } from 'fabric-network';
import * as path from 'path';

async function main() {
    try {

        // Create a new file system based wallet for managing identities.
        const walletPath = path.join(process.cwd(), 'Org1Wallet');
        const wallet = new FileSystemWallet(walletPath);
        console.log(`Wallet path: ${walletPath}`);

        // Create a new gateway for connecting to our peer node.
        const gateway = new Gateway();
        const connectionProfile = path.resolve(__dirname, '..', 'connection.json');
        let connectionOptions = { wallet, identity: 'org1Admin', discovery: { enabled: true, asLocalhost: true }};
        await gateway.connect(connectionProfile, connectionOptions);

        // Get the network (channel) our contract is deployed to.
        const network = await gateway.getNetwork('mychannel');

        // Get the contract from the network.
        const contract = network.getContract('demo-contract');

        // Submit the specified transaction.
        await contract.submitTransaction('createMyAsset', '002', 'Night Watch');
        console.log(`Transaction has been submitted`);

        // Disconnect from the gateway.
        await gateway.disconnect();

    } catch (error) {
        console.error(`Failed to submit transaction: ${error}`);
        process.exit(1);
    }
}
main();

**Comment by Jakeeyturner** [comment]
Hi @winf3,

Can you verify that you have the following in your package.json?:
```
"dependencies": {
    "fabric-network": "~1.4.0"
  }
```
 
Please can you run `npm ls --depth=0` inside your application directory and paste the output here.

Thanks,
Jake

**Comment by winf3** [comment]
Hi Jake,
here is what is happening.
When I do npm install in A5.25, I get the message at the end:
found 9 low severity vulnerabilities
  run `npm audit fix` to fix them, or `npm audit` for details
I run that, and get
(use `npm audit fix --force` to install breaking changes;
up to then, 
package.json still contains 
dependencies": {
    "fabric-network": "~1.4.0"

When I invoke npm audit fix --force
my package.json contains
"dependencies": {
    "fabric-network": "^2.2.2"
After that, I get the described A5.27 Run Build error.

I restored package.json to dependencies": {
    "fabric-network": "~1.4.0"
Then it builds correctly and I find a new dist directory. great- thanks, I should not have done the npm audit fix --force ;-)

The I do a Task Run on dist/create.js  and get 
Executing task in folder Demo-Application: npm run start <
> demo-application@1.0.0 start C:\Users\winre\OneDrive\Dokumente\Blockchain2020\IBM\Get-started-Example\VSCode-Tutorial\Demo-Application
> node ./dist/create.js

Wallet path: C:\Users\winre\OneDrive\Dokumente\Blockchain2020\IBM\Get-started-Example\VSCode-Tutorial\Demo-Application\Org1Wallet
2020-10-19T17:47:10.884Z - error: [Channel.js]: Error: 14 UNAVAILABLE: failed to connect to all addresses
2020-10-19T17:47:10.889Z - error: [Network]: _initializeInternalChannel: Unable to initialize channel. Attempted to contact 1 Peers. Last error was Error: 14 UNAVAILABLE: failed to connect to all addresses.

In order to check my installation,
 
here is also the requested npm ls --depth=0



PS C:\Users\winre\OneDrive\Dokumente\Blockchain2020\IBM\Get-started-Example\VSCode-Tutorial\Demo-Application> npm ls --depth=0
demo-application@1.0.0 C:\Users\winre\OneDrive\Dokumente\Blockchain2020\IBM\Get-started-Example\VSCode-Tutorial\Demo-Application
+-- @types/chai@4.2.14
+-- @types/mocha@5.2.7
+-- @types/node@10.17.40
+-- @types/sinon@7.5.2
+-- @types/sinon-chai@3.2.5
+-- chai@4.2.0
+-- chai-as-promised@7.1.1
+-- fabric-network@2.2.2
+-- jsrsasign@8.0.24
+-- minimist@1.2.5
+-- mocha@6.2.3
+-- nyc@14.1.1
+-- sinon@7.5.0
+-- sinon-chai@3.5.0
+-- ts-node@8.10.2
+-- tslint@5.20.1
`-- typescript@3.9.7

npm ERR! extraneous: es-abstract@1.18.0-next.1 C:\Users\winre\OneDrive\Dokumente\Blockchain2020\IBM\Get-started-Example\VSCode-Tutorial\Demo-Application\node_modules\es-abstract\node_modules\es-abstract

**Comment by Jakeeyturner** [comment]
So you need to make sure that you delete your node_modules directory, 'fabric-network' in the package.json's dependencies is set to '~1.4.0' and you've ran `npm install`.

```
2020-10-19T17:47:10.884Z - error: [Channel.js]: Error: 14 UNAVAILABLE: failed to connect to all addresses
2020-10-19T17:47:10.889Z - error: [Network]: _initializeInternalChannel: Unable to initialize channel. Attempted to contact 1 Peers. Last error was Error: 14 UNAVAILABLE: failed to connect to all addresses.
```
This is a gRPC error stating that it cannot connect to the network which your connection profile defines. You need to make sure that your network is running and the connection profile details are correct.

**Comment by winf3** [comment]
Hi Jake, in the tutorial, I did not found a mention, how I should set up the connection profile details. Could point point that out to me ?  My Network is running in the IBM Cloud.

**Comment by Jakeeyturner** [comment]
Hello,

If you have imported your network into the extension you can click `+` in the Fabric Gateways panel, create a new gateway from an environment, then select your environment.
That should create a gateway, which you can right-click on and export the connection profile for.
