### ISSUE TITLE
Unable to package chaincode with v2

### ISSUE THREAD

**Issue by jambonrose** [IBM-Blockchain/blockchain-vscode-extension#2719]
I have a Golang chaincode that we have run with HLF 1.4 that I would like to upgrade for IBP 2.5 and HLF 2. The `go.mod` file currently lists `github.com/hyperledger/fabric v1.4.6` as one of the dependencies.

I've downloaded extension v2.0.0-beta.8 and installed it on VS Code 1.50 on macOS 10.15. When I package the contract, I am shown the following message: "Unable to package contract. Contract API dependency must support Fabric 2."

I gather from reading other documentation that the shim dependency must now use the shim provided in `github.com/hyperledger/fabric-chaincode-go`. Are there other steps I need to follow? I find the error a little bit cryptic, and I am unsure where to find documentation helping me with this upgrade. Thank you.

**Comment by Jakeeyturner** [comment]
Hi @jambonrose,

V2 of the extension has been built to support the new Fabric v2 lifecycle (install, approve, commit).
IBP 2.5 doesn't support the Fabric v2 capabilities/lifecycle, however a future IBP 2.5.1 release will.

Just to help me understand what you're wanting to achieve, do you want to deploy to a network which uses Fabric 2 binaries with v1 capabilities?
Or do you want to deploy to a network which uses Fabric 2 binaries with v2 capabilities / new lifecycle?

When generating a new Go smart contract (which uses the contract-api), the `go.mod` has the following:
```
	github.com/hyperledger/fabric-chaincode-go v0.0.0-20200424173110-d7076418f212
	github.com/hyperledger/fabric-contract-api-go v1.1.0
```

Thanks,
Jake

**Comment by jambonrose** [comment]
Hi @Jakeeyturner ,

Thank you for the information about IBP v2.5 and v2.5.1. I was unaware the HLFv2 lifecycle was not supported in v2.5.

My original motivation: We are about to launch new channels with a few clients, and we would like to run the latest version of HLF. This is doubly important given that data-migration from  HLF v1.4 to v2 appears to be impossible in the IBP. We have therefore been attempting to upgrade our chaincode to be compatible with HLF v2.

It looks like we can continue to use our existing code by importing the `shim` from `github.com/hyperledger/fabric-chaincode-go`. Integrating `github.com/hyperledger/fabric-contract-api-go` into our existing code is work I would like to avoid, at least for the moment.

Do you know if there are other steps that we will need to take to allow the extension to package our chaincode for HLF v2?

Thanks,
Andrew

**Comment by Jakeeyturner** [comment]
Hey @jambonrose ,

IBP 2.5.1 will have data migration support for Fabric 1.4 to 2 - so this should be possible quite soon!

Currently, creating a local network with v2 binaries and v1 channel capabilities isn't possible with either extension.
However, you can create your own network (v2 binaries, with v1 capabilities), import it into the v1 extension and interact with it.

At the moment, you should only be using the v2 extension if you want to use the new v2 channel capabilities and lifecycle.
If you are wanting to package your contract to work with v1 channels, you should use the v1 extension (which will create a .cds package). Alternatively, if you want to work with v2 channels, you should use the v2 extension (which will create a .tar.gz package).

**Comment by jambonrose** [comment]
Hi @Jakeeyturner ,

Thank you for the information! I was unaware.

For posterity, I am noting that we only needed three changes, all in the form of updated imports:

- `github.com/hyperledger/fabric/core/chaincode/shim` → `github.com/hyperledger/fabric-chaincode-go/shim`
- `github.com/hyperledger/fabric/protos/peer` → `github.com/hyperledger/fabric-protos-go/peer`
- importing the `MockStub` struct and and `NewMockStub` function from `github.com/hyperledger/fabric-chaincode-go/shimtest` instead of `github.com/hyperledger/fabric/core/chaincode/shim` or `github.com/hyperledger/fabric-chaincode-go/shim`

As feedback: I was unable to find detailed documentation about upgrading chaincode from Fabric 1.4 to 2. Some of the documentation was also misleading. For instance, the [IBP documentation](https://cloud.ibm.com/docs/blockchain?topic=blockchain-ibp-console-smart-contracts#ibp-console-smart-contracts-write-package-vendor) mentions the need to vendor the `shim`, but several paragraphs down vendors the v1.4 shim. That is rather confusing.

Thank you again for providing clarity on the capabilities offered by the different versions of the IBP and the extensions. I will close this as I believe my issue is resolved.
