### ISSUE TITLE
1 Org local fabric network is not getting created PEER and orderer with latest version i.e. 2.2+

### ISSUE THREAD

**Issue by techatwork-a** [IBM-Blockchain/blockchain-vscode-extension#2727]
1 Org local fabric network is not getting created PEER and orderer with latest version i.e. 2.2+

## Description
I have created Blockchain network using "1 Org local fabric" option of extension. It has created network with version "1.4.6". Kindly let me know option to create network with 2.2 or latest version of PEER and orderer.

**Comment by Jakeeyturner** [comment]
Hello,

Local environments created using the v1 extension will only be created with 1.4.x binaries.
However, you are able to import your own network into the extension which uses v2 binaries (with v1 capabilities).

Thanks,
Jake

**Comment by techatwork-a** [comment]
> Hello,
> 
> Local environments created using the v1 extension will only be created with 1.4.x binaries.
> However, you are able to import your own network into the extension which uses v2 binaries (with v1 capabilities).
> 
> Thanks,
> Jake

Sorry, I didn't get you. Do you we have import any file which will create local network with 2.2. Also, if you have any sample file or tutorial, please post here.

**Comment by jambonrose** [comment]
@techatwork-a :

How did you install the IBP extension? If you installed it within the VS Code marketplace, you are running version 1 of the extension. If you would like to use Hyperledger Fabric 2 capabilities, you must download a VSIX file directly from the [Github releases page for the extension](https://github.com/IBM-Blockchain/blockchain-vscode-extension/releases). Here's a direct link to the [`2.0.0-beta.8.vsix` file](https://github.com/IBM-Blockchain/blockchain-vscode-extension/releases/download/v1.0.38/ibm-blockchain-platform-2.0.0-beta.8.vsix), which is the latest version at the time of writing.

**Comment by techatwork-a** [comment]
Closing
