### ISSUE TITLE
[v2] Update tutorials - text and images

### ISSUE THREAD

**Issue by lquintai** [IBM-Blockchain/blockchain-vscode-extension#2756]
### Text changes:

- Add sentence to install javascript test runner on functional tests tutorial
- 3.2 (close to end of this section) add one line to tell user how to re-create local fabric if they don't have one (just below image with local fabric showing):

>  If you do not have a “1 Org Local Fabric” environment, then click **+ add local or remote environment** to create the environment.  If creating the environment, click **Create new from template** and click 1 Org template.  Enter “1 Org local Fabric” as the name, and when you press **enter** the environment will start which may take up to 5 minutes..

- A5.30 and A5.43: tell user they might need to click to see all possible tasks: 

> you may also need to click **Show All Tasks**.

- A6: Remove first paragraph that is only for v1 (telling user about v2 lifecycle) 

### Image changes:
- A2.5 - figure shows v1 options, ie, go low level.
- A5.24.1 - open in terminal - wording for this option has changed
- A 5.33 - figure is wrong, it should show newfileSystemWallet() bus instead shows FileSystemWallet()
- A8.7: it should show code before modification, it shows code after modification
- three other figures (in A5) with incorrect folder structure.

**Comment by rthatcher** [comment]
Updated Images attached:
[BasicTutorialsV2-UpdatedImages.zip](https://github.com/IBM-Blockchain/blockchain-vscode-extension/files/5429942/BasicTutorialsV2-UpdatedImages.zip)
