### ISSUE TITLE
Can't find OpenSSL 1.0.2

### ISSUE THREAD

**Issue by BenCemlyon** [IBM-Blockchain/blockchain-vscode-extension#2763]
Issue Type: <b>Feature Request</b>

Hello,

I'm trying to find an openSSL 1.0.2 installer for Windows but it seems impossible to find it.
The 1.0.2 version isn't exist on the link Visual Studio Code show me to install openssl.

I tried to install 1.1.1 but the software is required 1.0.2 (1.1.1 is well detected but not the right version).

Can you send me a link to install openssl 1.0.2 please ?

Thanks

Extension version: 1.0.38
VS Code version: Code 1.50.1 (d2e414d9e4239a252d1ab117bd7067f125afd80a, 2020-10-13T15:06:15.712Z)
OS version: Windows_NT x64 10.0.15063

**Comment by Jakeeyturner** [comment]
Closing issue - OpenSSL isn't required in v2.0.0 of the extension (unless working with older smart contracts).

**Comment by ynynloxx** [comment]
Hey @Jakeeyturner,
I tried your solution but the extension still didn't detect the v1.1.1 of OpenSSL. I need it for smart contracts. Hope you can help out.

Kind regards
