### ISSUE TITLE
Extension issue

### ISSUE THREAD

**Issue by thiblly** [IBM-Blockchain/blockchain-vscode-extension#2767]
- Issue Type: `Bug`
- Extension Name: `ibm-blockchain-platform`
- Extension Version: `1.0.38`
- OS Version: `Windows_NT x64 10.0.19042`
- VSCode version: `1.50.1`

:warning: We have written the needed data into your clipboard. Please paste! :warning:

**Comment by Jakeeyturner** [comment]
Hi @thiblly,

Please could you provide some more information?
