### ISSUE TITLE
Links to snippets in the resources folder aren't active

### ISSUE THREAD

**Issue by rthatcher** [IBM-Blockchain/blockchain-vscode-extension#2780]
Using version v1.0.39 the links to the code snippets are not active.
Example 1: B7.8
Example 2: A5.13

The code snippets are available in-line in the tutorial, but not as separate files.

Running on:
Ubuntu 20.04.1 LTS

VSCode Version: 1.50.1
Commit: d2e414d9e4239a252d1ab117bd7067f125afd80a
Date: 2020-10-13T14:44:48.716Z
Electron: 9.2.1
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Linux x64 5.4.0-52-generic

**Comment by Jakeeyturner** [comment]
Closing - this seems to have been fixed.
