### ISSUE TITLE
Updates to install/instantiate in one fell swoop

### ISSUE THREAD

**Issue by EdMoffatt** [IBM-Blockchain/blockchain-vscode-extension#279]
After showing a preview of this functionality, we had some feedback, then a hurried whiteboarding session, and now we have ideas for how to improve it!

![image](https://user-images.githubusercontent.com/7454304/47863205-a7161f80-ddee-11e8-8c8b-c9150c1fb016.png)

**Comment by heatherlp** [comment]
Can this include a docs update please :) ?
