### ISSUE TITLE
A developer can use the Fabric extension in their native language

### ISSUE THREAD

**Issue by caroline-church** [IBM-Blockchain/blockchain-vscode-extension#28]
How we enable translation of the Fabric extension, so it can be used in Chinese, Spanish, Pirate?

If we put the infrastructure in place to enable this, then we could potentially crowd source the translations from the community, or try to get some IBM translation budget.

**Comment by Jakeeyturner** [comment]
Using something like this would help support additional languages within the extension:

https://github.com/Microsoft/vscode-nls
https://github.com/Microsoft/vscode-extension-samples/tree/master/i18n-sample

**Comment by caroline-church** [comment]
closing as done initial work to enable translation
