### ISSUE TITLE
IBM BLOCKCHAIN - PROBLEMS with "my-asset-contract.ts" - Expected 0 arguments, but got 1. ts(2554)

### ISSUE THREAD

**Issue by duranalvaro** [IBM-Blockchain/blockchain-vscode-extension#2822]
PROBLEMS with "my-asset-contract.ts" - Expected 0 arguments, but got 1. ts(2554)

I would like to know how to fix the attached problem. I´m following the instructions of the tutorials but in the Tutorial "A7: Debugging a smart contract" but I can´t Debug the smart contrat due to this. 

![image](https://user-images.githubusercontent.com/74452453/99146227-76704e00-2676-11eb-916f-6df47881d307.png)

I appreciated your help! thanks

**Comment by sunnylong10** [comment]
Same issue here, any solutions?

**Comment by Jakeeyturner** [comment]
There isn't actually a problem with this. If you're using Node 10 or 12 this is perfectly fine as per the docs - https://nodejs.org/docs/latest-v10.x/api/buffer.html#buffer_buf_tostring_encoding_start_end

UTF8 is actually the default, so you can just change `.toString('utf8')` to `.toString()` and it should be fine.

Closing issue.
