### ISSUE TITLE
[merge] Support v1 packages without version in the name

### ISSUE THREAD

**Issue by lquintai** [IBM-Blockchain/blockchain-vscode-extension#2824]
Need to use the equivalent of [this code](https://github.com/hyperledger/fabric-sdk-node/blob/a78870596b3098dc5092b9c3a42a477b6e9f8039/fabric-client/lib/Package.js#L75) in fabric-client 1.4.

Once that is in, or the packaging infrastructure where this can be added to, we will then be able to modify `PackageRegistry.getEntries()` to read the package and extract the name and version, instead of relying on the package name, for CDS packages.

**Comment by Jakeeyturner** [comment]
Merged.
