### ISSUE TITLE
IBM Blockchain Platform issues with grpc

### ISSUE THREAD

**Issue by DUSTAstaroth** [IBM-Blockchain/blockchain-vscode-extension#2828]
[2020-11-19T18_47_17_939Z-debug_1.log](https://github.com/IBM-Blockchain/blockchain-vscode-extension/files/5569329/2020-11-19T18_47_17_939Z-debug_1.log)
[a5.pdf](https://github.com/IBM-Blockchain/blockchain-vscode-extension/files/5569332/a5.pdf)

## Description##
I am working through the IBM BLockchain curriculum. The problem arises during the fifth tutorial, "invoking...from an external application." Everything works until I have to run the 'start' script, at which point I get the errors shown below and in the attached log file.

## Expected Behavior
According to the documentation the contract and transaction submission should be a success.

## Actual Behavior
The 'start' script terminates pointing out grpc module issues.

## Possible Fix
N/A

## Steps to Reproduce
I followed the instructions exactly as outlined in the attached tutorial.
Attached a5.pdf
## Existing issues
This is the closest issue to mine. By all appearances the problems are completely different, though.

https://github.com/IBM-Blockchain/blockchain-vscode-extension/issues/1205

## Log File
Attached debug log

Terminal output:
> demo-application@1.0.0 start
> node ./dist/create.js       

C:\Users\asime\OneDrive\Desktop\demo-application\node_modules\grpc\src\grpc_extension.js:58
    throw e;
    ^

Error: Failed to load C:\Users\asime\OneDrive\Desktop\demo-application\node_modules\grpc\src\node\extension_binary\node-v88-win32-x64-unknown\grpc_node.node. Cannot 
find module 'C:\Users\asime\OneDrive\Desktop\demo-application\node_modules\grpc\src\node\extension_binary\node-v88-win32-x64-unknown\grpc_node.node'
Require stack:
- C:\Users\asime\OneDrive\Desktop\demo-application\node_modules\grpc\src\grpc_extension.js
- C:\Users\asime\OneDrive\Desktop\demo-application\node_modules\grpc\src\client_interceptors.js
- C:\Users\asime\OneDrive\Desktop\demo-application\node_modules\grpc\src\client.js
- C:\Users\asime\OneDrive\Desktop\demo-application\node_modules\grpc\index.js
- C:\Users\asime\OneDrive\Desktop\demo-application\node_modules\fabric-client\lib\ProtoLoader.js
- C:\Users\asime\OneDrive\Desktop\demo-application\node_modules\fabric-client\lib\client-utils.js
- C:\Users\asime\OneDrive\Desktop\demo-application\node_modules\fabric-client\lib\Client.js
- C:\Users\asime\OneDrive\Desktop\demo-application\node_modules\fabric-client\index.js
- C:\Users\asime\OneDrive\Desktop\demo-application\node_modules\fabric-network\lib\gateway.js
- C:\Users\asime\OneDrive\Desktop\demo-application\node_modules\fabric-network\index.js
- C:\Users\asime\OneDrive\Desktop\demo-application\dist\create.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:919:15)
    at Function.Module._load (node:internal/modules/cjs/loader:763:27)
    at Module.require (node:internal/modules/cjs/loader:991:19)
    at require (node:internal/modules/cjs/helpers:92:18)
    at Object.<anonymous> (C:\Users\asime\OneDrive\Desktop\demo-application\node_modules\grpc\src\grpc_extension.js:32:13)
    at Module._compile (node:internal/modules/cjs/loader:1102:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1131:10)
    at Module.load (node:internal/modules/cjs/loader:967:32)
    at Function.Module._load (node:internal/modules/cjs/loader:807:14)
    at Module.require (node:internal/modules/cjs/loader:991:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    'C:\\Users\\asime\\OneDrive\\Desktop\\demo-application\\node_modules\\grpc\\src\\grpc_extension.js',
    'C:\\Users\\asime\\OneDrive\\Desktop\\demo-application\\node_modules\\grpc\\src\\client_interceptors.js',
    'C:\\Users\\asime\\OneDrive\\Desktop\\demo-application\\node_modules\\grpc\\src\\client.js',
    'C:\\Users\\asime\\OneDrive\\Desktop\\demo-application\\node_modules\\grpc\\index.js',
    'C:\\Users\\asime\\OneDrive\\Desktop\\demo-application\\node_modules\\fabric-client\\lib\\ProtoLoader.js',
    'C:\\Users\\asime\\OneDrive\\Desktop\\demo-application\\node_modules\\fabric-client\\lib\\client-utils.js',
    'C:\\Users\\asime\\OneDrive\\Desktop\\demo-application\\node_modules\\fabric-client\\lib\\Client.js',
    'C:\\Users\\asime\\OneDrive\\Desktop\\demo-application\\node_modules\\fabric-client\\index.js',
    'C:\\Users\\asime\\OneDrive\\Desktop\\demo-application\\node_modules\\fabric-network\\lib\\gateway.js',
    'C:\\Users\\asime\\OneDrive\\Desktop\\demo-application\\node_modules\\fabric-network\\index.js',
    'C:\\Users\\asime\\OneDrive\\Desktop\\demo-application\\dist\\create.js'
  ]
}
npm ERR! code 1
npm ERR! path C:\Users\asime\OneDrive\Desktop\demo-application
npm ERR! command failed
npm ERR! command C:\windows\system32\cmd.exe /d /s /c "node ./dist/create.js"

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\asime\AppData\Local\npm-cache\_logs\2020-11-19T18_47_17_939Z-debug.log
The terminal process "C:\windows\System32\WindowsPowerShell\v1.0\powershell.exe -Command npm run start" terminated with exit code: 1.

## Your Environment

IBM Blockchain Platform: v1.0.40
Version: 1.51.1 (user setup)
Commit: e5a624b788d92b8d34d1392e4c4d9789406efe8f
Date: 2020-11-10T23:34:32.027Z
Electron: 9.3.3
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Windows_NT x64 10.0.19042

**Comment by Jakeeyturner** [comment]
As you're using VS Code 1.51.1 you need to do the following - https://github.com/IBM-Blockchain/blockchain-vscode-extension/issues/1621#issuecomment-552926559
Closing issue as it's a duplicate.

**Comment by DUSTAstaroth** [comment]
Thanks
