### ISSUE TITLE
[Bug] Old style drop down menu on transaction view when submitting manual entry after selecting transaction directory

### ISSUE THREAD

**Issue by lquintai** [IBM-Blockchain/blockchain-vscode-extension#2834]
## Description

If a user associates a transaction directory for transaction data to a contract, they are able to use the pre-filled transaction arguments in the `Transaction data directory` tab of the transaction view.

If however they then chose to submit transactions with `Manual input`, they are presented with the old style drop down menu for `Do you want to provide a file of transaction data for this transaction?`

<img width="1089" alt="image" src="https://user-images.githubusercontent.com/54178486/100457291-a88fa000-30b9-11eb-8905-e84564310eaf.png">

## Expected Behavior
It is not unreasonable for users to want to submit manual transactions even if they have associated a directory for transaction data.

Therefore the expected behaviour is for the old style menu not to appear when trying to do this, and instead just submit/evaluate the transaction without any further user input required. This already happens when the user selects `Manual input` without associating a transaction data directory.

## Steps to Reproduce

1. Deploy contract
2. Associate directory for transaction data
3. Use `Manual Input` tab in the transaction view to submit/evaluate a transaction manually
4. The old style drop down menu should appear.

**Comment by Jakeeyturner** [comment]
Merged.
