### ISSUE TITLE
[bug][merge] Low level go contract packaged in merge cannot be installed/instantiated

### ISSUE THREAD

**Issue by lquintai** [IBM-Blockchain/blockchain-vscode-extension#2841]
### Networks used for testing:
Both v1 and merge extension were used with **v1 channel capability** microfab, ie, with **nodes running fabric 2**.

### Using the merge extension:
- Create low level go contract and open in workspace
- Package open project
- Install: `Failed to install on peer Org1 Peer with reason: chaincode installed to peer but could not build chaincode: external builder failed: external builder failed to build: external builder 'golang' failed: exit status 1`
- Instantiate: `Error instantiating smart contract: Could not deploy smart contract definition, received error: No valid responses from any peers. Errors: peer=Org1 Peer, status=500, message=error in simulation: could not launch chaincode go-low-level-contract:1: error building chaincode: error building image: external builder failed: external builder failed to build: external builder 'golang' failed: exit status 1`
- **When installing and instantiating this package in the v1 extension, got the same errors.**
- `go mod tidy && go mod vendor` prior to packaging made no difference

### Using the v1 extension:
- Copy/paste the contract folder to $GOPATH/src (to make sure was using the exact same starting point)
- Open this copied folder in the workspace
- Package open project
- Successfully installed and instantiated
- **Also successfully installing and instantiating this package in the merge extension.**

### Further info
This seems to be related to the path in the package:
- If GOPATH is `/Users/me/go`
- And the chaincode file in `/Users/me/go/src/github.com/me/my-chaincode/chaincode.go`
- Then the path in the package should be `github.com/me/my-chaincode`

**Comment by Childult** [comment]
I ran into the same error when installing chaincode. Do you know how to fix it?
