### ISSUE TITLE
Allow user to import v1 and v2 packages with same name and version

### ISSUE THREAD

**Issue by lquintai** [IBM-Blockchain/blockchain-vscode-extension#2852]
## Description
For the extension to handle both v1 and v2 functionality, we allow the import and packaging of both v1 and v2 chaincode packages.

Since a user can deploy a contract with the same name and version in the same node (running fabric v2) and use them with the appropriate gateways, we must support the import of these packages.

**Comment by Jakeeyturner** [comment]
Closing - merged.
