### ISSUE TITLE
Memory Requirement Query

### ISSUE THREAD

**Issue by mikethebee** [IBM-Blockchain/blockchain-vscode-extension#2856]
The memory requirement is given as 4GB 

## Description
Maybe not a problem for most devs, my Ubuntu m/c is limited to 4GB of memory, but fully populated gives VSC a value of 3.6GB. I skipped the check, and was requested to provide a reason here. 

## Existing issues

I did a search but didn't find more info about the necessity of a full 4GB

## Log File
N/A

## Your Environment

* IBM Blockchain Platform Extension Version: v1.0.40
* Visual Studio Code version: Version: 
Version: 1.51.1
Commit: e5a624b788d92b8d34d1392e4c4d9789406efe8f
Date: 2020-11-10T23:31:29.624Z
Electron: 9.3.3
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Linux x64 4.15.0-126-generic snap

**Comment by Jakeeyturner** [comment]
Hi @mikethebee,

We use `const systemRequirementsVersion: number = OS.totalmem() / 1073741824;` to determine the amount of total memory available. If you have 4GB of total memory then I'm unsure why/how `totalmem` determines that you have less.
I don't think this is a problem with our code and I suspect it's either `totalmem` or your environment.

Not a problem though, as long as you have it then you should be fine to skip the prerequisites check!

Thank you for making us aware.

Closing issue.
