### ISSUE TITLE
instantiate function name mismatch

### ISSUE THREAD

**Issue by rthatcher** [IBM-Blockchain/blockchain-vscode-extension#288]
The template/boilerplate functions in VSCode include **instantiate()** , but the default instantiate function name used by the Extension is **init**.

This mismatch will cause errors with first timers and tyre kickers which can be avoided.  I think that @mbwhite would prefer that the default becomes instantiate, leaving the template functions as they are.

As an aside, the last time I tested with a namespace as a superclass there was a requirement to supply the full name of the function to instantiate - that might cause some avoidable errors too.

**Comment by caroline-church** [comment]
opend https://jira.hyperledger.org/browse/FAB-12821 as this is a fabric issue
