### ISSUE TITLE
ibm blockchain vscode extension not working

### ISSUE THREAD

**Issue by sakura1313** [IBM-Blockchain/blockchain-vscode-extension#2885]
Error-
Could not rebuild native dependencies Failed to execute command "npm" with  arguments "rebuild, grpc, --target=9.3.5, --runtime=electron, --update-binary, --fallback-to-build, --target_arch=x64, --dist-url=https://atom.io/download/electron" return code 1. Please ensure that you have node and npm installed

vscode version- 1.52.1

**Comment by Jakeeyturner** [comment]
Closing - duplicate of https://github.com/IBM-Blockchain/blockchain-vscode-extension/issues/1621#issuecomment-552926559
