### ISSUE TITLE
2.0.0-rc1 After attempting a chaincode upgrade (which failed) and switching to code to fix and returning to blockchain extension the channel had disapeared from the environments panel

### ISSUE THREAD

**Issue by davidkel** [IBM-Blockchain/blockchain-vscode-extension#2906]
For some reason my channel which was there had disappeared
![image](https://user-images.githubusercontent.com/25582377/104014885-adad3800-51ab-11eb-84eb-e2e6e63751dd.png)

I had to disconnect and reconnect to the environment to get it back

![image](https://user-images.githubusercontent.com/25582377/104014926-c3baf880-51ab-11eb-95e3-0e5e8c22d9d0.png)

I'm not sure if it was the chaincode upgrade failure that caused this or the switch to code to fix the problem and return back to the blockchain perspective to repackage

Update: 
It happens during chaincode upgrade when the error message appeared
```
Error populating channel view: Error querying channels: Could not get all channel names, received: 2 UNKNOWN: access denied: channel [] creator org [org1msp]
```
 so possibly related to #2905

**Comment by Jakeeyturner** [comment]
Closing as this is related to #2905 and will be fixed with that.
