### ISSUE TITLE
As a Developer I have CouchDB Query Index files that I wish to include in the package

### ISSUE THREAD

**Issue by rthatcher** [IBM-Blockchain/blockchain-vscode-extension#292]
Developers will want to test their Query Indexes as part of the dev/test process - this is not just a production deployment requirement.

Standard location for the query files is `META-INF/statedb/couchdb/indexes`

**Comment by caroline-church** [comment]
created a fabric issue for this https://jira.hyperledger.org/browse/FAB-12820 closing as not a vscode issue

**Comment by caroline-church** [comment]
Reopenig as its a vscode issue
