### ISSUE TITLE
Implicit collections don't work on fabric 1

### ISSUE THREAD

**Issue by lquintai** [IBM-Blockchain/blockchain-vscode-extension#2922]
## Description

We are now using implicit collections as default for private data contracts.

However the extension supports both fabric 1 and fabric 2, and **implicit collections are only available in fabric 2.**

This means that when a user wants to deploy a private data contract on a v1 fabric, the generated contracts will fail when trying to submit transactions.
The user needs to modify the contract to accept non implicit collections, and create a collections file.

## Expected Behavior

We should be able to use the generated contracts out of the box

## Actual Behavior

- Just deploy without associating collection file:
> Error submitting transaction: No valid responses from any peers. Errors:
>     peer=org1peer-api.127-0-0-1.nip.io:8088, status=500, message=error in simulation: transaction returned with failure: Error: GET_PRIVATE_DATA_HASH failed: transaction ID: 95e5784391f4727edb03c0ee71206f8ed16805bfbbb8f8b7bf773fa5484fb636: collection config not defined for chaincode [ts-private-contract-1401], pass the collection configuration upon chaincode definition/instantiation
> 
- Deploy with a collection file:

> Error submitting transaction: No valid responses from any peers. Errors:
> peer=org1peer-api.127-0-0-1.nip.io:8088, status=500, message=error in simulation: transaction returned with failure: Error: GET_PRIVATE_DATA_HASH failed: transaction ID: 3895e599e30e6d73916ee1f60e626408058f73794ce0c5da6911c3ae4029f131: collection [_implicit_org_Org1MSP] not defined in the collection config for chaincode [ts-private-contract-1401]
> 

Also, when deploying the contract on a v1 network we see the same option for collections file as v2, which is wrong:
`Default (implicit private data collections only) will be used unless you add your own.`
There should be no mention of implicit collections.

## Possible Fix

1. Change the wording only. The user will have to modify the contract and create a collections file.
2. Modify the generator to accept another option: when the user asks for a private contract, we we ask if it should use implicit or regular collections, and the option for implicit collections should be clearly highlighting the fact it is a v2 only feature. Functional tests will have to be modified to account for the extra question. Still need to change the wording on v1 deploy.

## Steps to Reproduce

1. Create private data contract using latest (v2/new master) version of the extension.
2. Create v1 local fabric
3. Deploy contract on local fabric without adding collection file - try to submit a transaction
4. Upgrade contract (or create a new contract) and deploy it on local fabric adding the **collections.json** file below - try to submit a transaction.
```
[
    {
         "name": "CollectionOne",
         "policy": "OR('Org1MSP.member')",
         "requiredPeerCount": 0,
         "maxPeerCount": 1,
         "blockToLive": 0,
         "memberOnlyRead": true
    }
]
```

> This is just a copy of an old style collections.json file, no modification.

**Comment by jt-nti** [comment]
Fabric 1.4 is no longer LTS so this may not get fixed
