### ISSUE TITLE
Fix nightly builds

### ISSUE THREAD

**Issue by erin-hughes** [IBM-Blockchain/blockchain-vscode-extension#2932]
Now that we've merged the v2 code into the master branch we should investigate our nightly builds, which are currently failing due to issues with VS Code Insiders.

Example build: https://dev.azure.com/IBPComposer/IBM-Blockchain-VSCode-Extension/_build/results?buildId=4560&view=results

**Comment by Jakeeyturner** [comment]
First thoughts on this is that we need to:
- Update the version of the `vscode-test` dependency
- Modify some tests which check the registered commands - internal commands can vary depending on the version of VS Code.

**Comment by Jakeeyturner** [comment]
Merged.
