### ISSUE TITLE
Couchdb not exposed

### ISSUE THREAD

**Issue by bhanuratnakaram** [IBM-Blockchain/blockchain-vscode-extension#2938]
With the new IBM VSCode extension, everything is in microfab. This means we can not access couchdd directly anymore. This is limiting out ability to test our code where most of reads are dependant on views configured in Couchdb 

## Description
With the new IBM VSCode extension, everything is in microfab. This means we can not access couchdd directly anymore. This is limiting out ability to test our code where most of reads are dependant on views configured in Couchdb 

## Expected Behavior
Ability to access couchdb

## Actual Behavior
couchdb is in microfab

## Possible Fix
couchdb exposed as a docker container in host machine?

## Steps to Reproduce
Start IBM network 2.x with latest plugin

**Comment by Jakeeyturner** [comment]
We can close this issue when we merge https://github.com/IBM-Blockchain/blockchain-vscode-extension/issues/2937.

A workaround for now is to start a network using the `ibmcom/ibp-microfab:0.0.8` image, visit `http://couchdb.127-0-0-1.nip.io:${PORT}/_utils/` and login using `admin:adminpw`.

**Comment by lquintai** [comment]
#2937 merged. Closing.
