### ISSUE TITLE
Suggestions on being able to add an external environment

### ISSUE THREAD

**Issue by davidkel** [IBM-Blockchain/blockchain-vscode-extension#2942]
Currently you can add an external environment using JSON node files, but the JSON node files doesn't support the ability to provide an ssl-target-name-override option to allow connection to something like the fabric samples test network. You can work around this but it would be useful to add this option.

I think it would be nice to be able to create an environment from a connection profile as well. The connection profile should provide enough information to do this as well.

**Comment by aakzubaidi** [comment]
I would be a really useful feature to have. Now can you please hint on the workaround to enable this in the current version?

**Comment by jt-nti** [comment]
@aakzubaidi the workaround is to use your local hosts file to remap the hostnames so you don't need the override option
