### ISSUE TITLE
Unable to start Chaincode in debug mode

### ISSUE THREAD

**Issue by siglesiasg** [IBM-Blockchain/blockchain-vscode-extension#2944]
Hello,

I was trying to debug my chaincode but I'm no able to do it with the default VSCode configuration and latest plugin extension (2.0.0):

"version": "0.2.0", "configurations": [ { "type": "fabric:node", "request": "launch", "name": "Debug Smart Contract", "preLaunchTask": "tsc: build - tsconfig.json", "outFiles": [ "${workspaceFolder}/dist/**/*.js" ] } ] }

peer complains with following message:

[ org1peer] 2021-01-25 08:02:05.741 UTC [chaincode] notifyRegistry -> ERRO 17d failed to start bkchain-contract:0.0.4 -- peer will not accept external chaincode connection bkchain-contract:0.0.4 (except in dev mode)

How do I configure the blockchain in dev mode?

Thanks

**Comment by koakh** [comment]
Hello @siglesiasg please follow this link [[v2 merge] Debug smart contract - update or remove #2660](https://github.com/IBM-Blockchain/blockchain-vscode-extension/issues/2660)

thanks

**Comment by Jakeeyturner** [comment]
Closing issue - debug is currently not supported (https://github.com/IBM-Blockchain/blockchain-vscode-extension/issues/2660)
