### ISSUE TITLE
How to get enrollment id and secret for microfab?

### ISSUE THREAD

**Issue by PierrickI3** [IBM-Blockchain/blockchain-vscode-extension#2960]
This is not an issue but a question.

I just started using the extension and use it to create a local environment to practice.

I need to be able to create a user using the `fabric-network` library however it requires an `enrollment id` and `secret` which I do not have

How can I retrieve (or set) this enrollment id/secret when using the microfab? Tutorials point to the IBM Blockchain Platform but do not indicate how to do this in a local environment.

Thanks.

**Comment by Jakeeyturner** [comment]
Hi @PierrickI3,

Using the `>Create identity (register and enroll)` command, you're able to create new identities for local environments.
I believe it uses the enrollment id `admin` and secret `adminpw` under the covers for this process.

Feel free to re-open this issue if you're still having problems!

Thanks,
Jake

**Comment by PierrickI3** [comment]
Thanks @Jakeeyturner
