### ISSUE TITLE
remove multiple packages

### ISSUE THREAD

**Issue by lasharela** [IBM-Blockchain/blockchain-vscode-extension#2968]
remove multiple packages from the "SMART CONTRACTS" panel would be nice. or the 'clear all' button. 
BTW, where those packages are saved? was not able to find.

**Comment by Jakeeyturner** [comment]
Hi @lasharela,

If you call `>Delete package` from the command palette you are able to delete multiple/all packages at once.

Regarding the package location, by default they can be found in `~/.fabric-vscode/v2/packages`. This is an internal directory used by the extension, so it is not recommended to modify it.

Thanks,
Jake
