### ISSUE TITLE
add more organizations

### ISSUE THREAD

**Issue by lasharela** [IBM-Blockchain/blockchain-vscode-extension#2969]
Is there any way to add more organizations? 
This would be useful to test transfer between organizations and more complicated scenarios.

**Comment by Jakeeyturner** [comment]
Hi @lasharela,

We have a tutorial detailing how to create custom environments - including how to create networks with multiple organisations, channels, etc.

This can be found by running the `>View Tutorial Gallery` command, clicking `Other Tutorials`, then viewing the `Create and use a custom Fabric network` tutorial.

Thanks,
Jake
