### ISSUE TITLE
Query assets not working as expected

### ISSUE THREAD

**Issue by bhanuratnakaram** [IBM-Blockchain/blockchain-vscode-extension#2971]
## Description
Query assets not working as expected. 

## Expected Behavior
Query to return the result. Blank if no objects matching the query

## Actual Behavior
![image](https://user-images.githubusercontent.com/25284495/108222754-f94eec00-7130-11eb-8ddd-453ca55cf0be.png)
Shows above error - Error running query. Reason: error (enoent)

## Steps to Reproduce
1. Start the network.
2. Install chaincode
3. Open couchdb url using - http://couchdb.127-0-0-1.nip.io:8081/_utils/#database/<channel+chaincode name>/_find
4. Try to execute following query from couchdb 
{
   "selector": {
      "namespace": "abc"
   },
   "use_index": "namespace-Index"
}
5. The same issue even when trying execute query via chaincode

## Existing issues
https://github.com/IBM-Blockchain/blockchain-vscode-extension/issues/2966

## Your Environment
* IBM Blockchain Platform Extension Version: 2.2
* Visual Studio Code version: 1.53.2
* Environment name and version (e.g. Node.js v12.16.3, npm v6.13.4):
* Operating System and version: Ubuntu 18.04

**Comment by james-wallis** [comment]
Closing as it's similar to https://github.com/IBM-Blockchain/blockchain-vscode-extension/issues/2966
There is a CouchDB indexes fix in the upcoming release.
