### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by NeonNdlovu** [IBM-Blockchain/blockchain-vscode-extension#2972]
- Issue Type: `Performance`
- Extension Name: `ibm-blockchain-platform`
- Extension Version: `2.0.1`
- OS Version: `Windows_NT x64 10.0.19042`
- VSCode version: `1.53.2`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`c:\Users\NEONNT~1\AppData\Local\Temp\IBMBlockchain.ibm-blockchain-platform-unresponsive.cpuprofile.txt`

Find more details here: https://github.com/microsoft/vscode/wiki/Explain-extension-causes-high-cpu-load

**Comment by james-wallis** [comment]
Hi, the CPU profile file hasn't attached so we can't see any information. 
Could you please provide more information on what part of the extension you were using when you encountered the high CPU load?

**Comment by james-wallis** [comment]
Closing but if you see this again and can attach more information reopen it.
