### ISSUE TITLE
Capture console.log messages from Fabric on submit/evaluate transaction

### ISSUE THREAD

**Issue by lasharela** [IBM-Blockchain/blockchain-vscode-extension#2977]
Where console logs are printed inside of VS Code?
I see the environment name inside of the OUTPUT window, but that's the only way to check the console log and it's too messy. 

```
[2/18/2021 1:35:58 PM] [INFO] gallant_ritchie|[        org1peer] 2021-02-18 18:35:58.663 UTC [chaincode.externalbuilder.node] waitForExit -> INFO 6d4 Print Test command=run
```
in this case, I consoled only "Print Test" and I see much more information there. I know that debug functionality is not ready but maybe there is a better way to check "console.log" messages?

Thanks

P.S.
Debug console is completely empty. I'm using typeScript

**Comment by james-wallis** [comment]
Thanks for raising @lasharela. 

I ran a little test and I think the answer is unfortunately yes, the only way to see the `console.log` statements is the method you've described. - I agree, it's not great.

The issue we have is that we only get a `result` string when we submit/evaluate a transaction:
https://github.com/IBM-Blockchain/blockchain-vscode-extension/blob/master/packages/blockchain-extension/extension/commands/submitTransaction.ts#L333-L338

I'll discuss with the team next week to see if there is anything we can do about getting the `console.log` outputs. Failing that I wonder if there is an external logger that you could use?

**Comment by james-wallis** [comment]
Currently, we don't have the bandwidth to look at this. I believe it'll be something that needs to change inside Fabric, to return the output.

**Comment by james-wallis** [comment]
Closing as this isn't achievable at the moment.

**Comment by RafaelAPB** [comment]
@james-wallis is there a way to check for chaincode logs via this extension? (or even by accessing the docker container that runs minifabric)?
