### ISSUE TITLE
Error while submitting transaction in Debugger mode

### ISSUE THREAD

**Issue by lasharela** [IBM-Blockchain/blockchain-vscode-extension#2978]
1. Run debugger mode for codechain node
2. press blue blockchain icon on debugging panel
3. Select "Submit transaction", select method "CreateMyAsset"
4. submit as it is (empty array)
5. submit `{  "myAssetId": "A1",  "value": "5"}`

Output:
```
[2/19/2021 6:30:35 PM] [INFO] submitTransaction
[2/19/2021 6:30:42 PM] [INFO] submitting transaction myAssetExists with no args on channel mychannel
[2/19/2021 6:30:42 PM] [ERROR] Error submitting transaction: No valid responses from any peers. Errors:
    peer=org1peer-api.127-0-0-1.nip.io:8080, status=500, message=error in simulation: transaction returned with failure: Error: Expected 1 parameters, but 0 have been supplied
```
same for evaluating transactions. 

BTW
1. remove existing environment with 1 node and 1 organization
2. CMD+P > IBM add environment > Create new from template > 2 Org template
You'll get
```
[2/19/2021 6:35:29 PM] [ERROR] The current debug session is not debugging a smart contract, this command can only be run when debugging a smart contract
```

```
{
    // Use IntelliSense to learn about possible attributes.
    // Hover to view descriptions of existing attributes.
    // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [
        {
            "type": "fabric:node",
            "request": "launch",
            "name": "Debug Smart Contract",
            "preLaunchTask": "tsc: build - tsconfig.json",
            "outFiles": [
                "${workspaceFolder}/dist/**/*.js"
            ]
        }
    ]
}
```
My launch.json if it's needed

But because this issue is already reported I won't open it again. Just want to underline that It's 1 Org vs 2 Org templates. There is some difference 

P.S. I attached some images on StackOverflow https://stackoverflow.com/questions/66307043/how-to-debug-chaincode-with-ibm-blockchain-platform

## Your Environment
everything latest

**Comment by erin-hughes** [comment]
Hi @lasharela 

This is a [known issue](https://github.com/IBM-Blockchain/blockchain-vscode-extension/issues/2660) - currently debugging smart contracts is not possible in v2 releases of the extension.
