### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by aakzubaidi** [IBM-Blockchain/blockchain-vscode-extension#2992]
- Issue Type: `Performance`
- Extension Name: `ibm-blockchain-platform`
- Extension Version: `2.0.2`
- OS Version: `Darwin x64 20.3.0`
- VSCode version: `1.54.2`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`/var/folders/tk/dh804tw500b6_bh1n75108140000gn/T/IBMBlockchain.ibm-blockchain-platform-unresponsive.cpuprofile.txt`

Find more details here: https://github.com/microsoft/vscode/wiki/Explain-extension-causes-high-cpu-load

**Comment by james-wallis** [comment]
@aakzubaidi please reopen if you add a log file.
