### ISSUE TITLE
Hyperledger fabric custom validation plugin

### ISSUE THREAD

**Issue by joshua-roberts** [IBM-Blockchain/blockchain-vscode-extension#2997]
Does the extension support configuring the network to use custom validation plugins? See https://hyperledger-fabric.readthedocs.io/en/release-2.3/pluggable_endorsement_and_validation.html

**Comment by Jakeeyturner** [comment]
Hi @joshua-roberts,

I don't think the local environments support custom validation plugins.
However, with the extension you can import any network - so technically if you create your own network with custom validation, you could import it with no problems (hopefully!).

Thanks,
Jake
