### ISSUE TITLE
A developer can see the packages they've created in VSCode in the main Explorer view

### ISSUE THREAD

**Issue by caroline-church** [IBM-Blockchain/blockchain-vscode-extension#30]
Notes:
- should function in the same way as the view created in #4 (?)
- usefulness to be determined in Phase 2 after we've had some user feedback. 
- potentially not needed if "created smart contract package" notification implemented in  #2 works well
- quick mock up below:

![scp_explorer_view](https://media.github.ibm.com/user/117412/files/ef1960e8-ab90-11e8-8afb-c22c681b81e8)

**Comment by SamRasha** [comment]
Could this be further improved by having the contracts grouped by the language in which they are coded in? So all typescript projects which have been packed would be shown under a "typescript" drop down in the explorer window? This avoids confusion if packages are named the same thing but are coded in different languages (also allows for better management of packaged projects from a fabric developer point of view)

**Comment by caroline-church** [comment]
close for now unless hear more feedback saying we should
