### ISSUE TITLE
Migrate to GitHub Actions

### ISSUE THREAD

**Issue by lquintai** [IBM-Blockchain/blockchain-vscode-extension#3004]
The yml skeleton is in .github/workflows

- The idea with azure is to have multiple small chunks of yml to do the various actions, such as setup, unit tests, functional tests, etc, and make them reusable. This is not possible in GitHub Actions. There are 3 options:
1. Keep is as is, huge file
2. Create custom actions. These will be in JS instead of  yml. Why not in yml: There is the possibility of creating a yml 'action', it's called composite, but it has 2 limitations: a) we can only have one! B) we can't call other actions from within it, for example the action to install node, or to download files, etc. It has to be plain code. 
3. Create multiple workflows, and call them from within one another. It looks like this is possible, but I'm not sure how much of a CI pipeline that will be.

- I couldn't find any action for Cobertura, so I left the 'publish code coverage' part out. I hope this not too much of a pain to get to work, but it could either a) be left out, b) move from Cobertura to something else that is supported, c) write our own publish

- Some of the conditions are still in azure style and need to be changed (from `condition:` to `if:`) and the actual evaluation changed to GitHub Actions syntax.

- I've added a `runs-on` to each job to get it to work - needs removing

- attention to double comments - these are either the actions I couldn't find the equivalent in GA or that I commented out to protect against accidental runs (mostly around deploy)

**Comment by james-wallis** [comment]
Pausing this until Microsoft moves Azure Pipelines to GitHub Actions (as the rumour has hinted)

**Comment by erin-hughes** [comment]
Some additional things to consider/be aware of when we come back to this:

- Should make sure that only collaborators have the power to kick off pipeline builds
- Prevent merging if the tests don't pass
- Ensure naming of secrets is correct - there are a few secrets that we call from within the literal test code (e.g. the SaaS/Software cucumber tests) so if there are any differences in naming conventions between Azure and GHA we'll need to be careful on how we handle them

**Comment by SamYuan1990** [comment]
I had take a look at our current azure pipeline files.
They are too many, so I suppose a possible way for us is the break down this ticket. Making CI running in both azure and github action in parallel during migration?
btw, are we able to moving CI code, from azure pipeline to other place as some shell? as a summary I propose for this migration we may need to:

- [ ] migration current azure hard code to some shell script(or make file) for each pipeline.
- [ ] parallel each pipeline for azure and github action.
- [ ] build pipeline dependence in github action.
- [ ] migrate to github action as deprecated azure pipeline.

what do you guys think of?
