### ISSUE TITLE
Failed to start 1 Org local Fabric: Environment failed to become available. Please check the Docker container logs for more details.

### ISSUE THREAD

**Issue by ravenonline11** [IBM-Blockchain/blockchain-vscode-extension#3006]
- Issue Type: `Bug`
- Extension Name: `ibm-blockchain-platform`
- Extension Version: `2.0.2`
- OS Version: `Windows_NT x64 6.1.7601`
- VS Code version: `1.55.1`

:warning: We have written the needed data into your clipboard. Please paste! :warning:

**Comment by ravenonline11** [comment]
![Error](https://user-images.githubusercontent.com/58367250/114517476-00d7d080-9c5c-11eb-87d8-7f0fb10cc4c0.JPG)

**Comment by james-wallis** [comment]
Thanks for raising @ravenonline11 is this the first time you've seen this error? Have you been able to start the local Fabric Environment before?

**Comment by ravenonline11** [comment]
Thanks for looking into this @james-wallis . No. I am a newbie and learning through the IBM cognitive class tutorials. I tried multiple iterations but unable to connect and launch the local Fabric Environment before

**Comment by james-wallis** [comment]
Just noticed "docker is not recognized" in your terminal. Do you have Docker installed and available on your PATH?

**Comment by ravenonline11** [comment]
I don't know about that James. Do I need to check and install that from the extensions? If so which one exactly should I be installing? Thanks so much for your quick help. I greatly appreciate it.

**Comment by james-wallis** [comment]
Hi, yes you need Docker to run the local microfab. Here are the instructions to install: https://docs.docker.com/get-docker/.

**Comment by james-wallis** [comment]
Closing as this doesn't appear to be an issue with the extension.

**Comment by charishnaidu** [comment]
Hello @ravenonline11, I encountered the same issue. Did you managed to fix that?
