### ISSUE TITLE
As a Matthew, I'd like to create a smart contract project on Windows

### ISSUE THREAD

**Issue by heatherlp** [IBM-Blockchain/blockchain-vscode-extension#301]
![image](https://user-images.githubusercontent.com/40789053/48147333-fa84e380-e2ae-11e8-8ad6-2352ce97d93c.png)

as found by @mbwhite 
I've fixed the "java" missing from the list in the second error message under #298

**Comment by caroline-church** [comment]
closing as it was a user error
