### ISSUE TITLE
Required Prerequisite 'Docker for Windows' not recognized, although its installed.

### ISSUE THREAD

**Issue by ynynloxx** [IBM-Blockchain/blockchain-vscode-extension#3010]
Hello everyone, 

I tried to deploy a smart contract on the IBM Blockchain Platform and I have installed every needed prerequisite. Even checked if my Docker is set to 'switch to Windows container'.

## Expected Behavior

When I want to 'Deploy a smart contract' I will get the error 'Required prerequisites are missing. They must be installed before the extension can be used.' But I installed everything.

How can I fix this problem?

## Your Environment

* IBM Blockchain Platform Extension Version: v2.0.2
* Visual Studio Code version: 1.53.2
* Environment name and version : Node.js v14.16.1, npm v7.10.0
* Operating System and version: Windows 10

**Comment by james-wallis** [comment]
Need to find a resource with a windows machine to test this.

**Comment by jt-nti** [comment]
Closing as there hasn't been any activity on this issue for a while
