### ISSUE TITLE
In the section describing "Migrating a smart contract for Fabric 2" the information is out of date 

### ISSUE THREAD

**Issue by davidkel** [IBM-Blockchain/blockchain-vscode-extension#3016]
In the link here https://github.com/IBM-Blockchain/blockchain-vscode-extension/wiki/Common-tasks-and-how-to-complete-them#migrating-a-smart-contract-for-fabric-2

The recommended versions for node are old and it's recommending a version which isn't supported, it should be updated to reference the latest shim and contract npm modules.
Also there could be migration issues as well (ie the chaincode may require code modifications to work with the latest level, however I don't know if these changes are documented anywhere)

At the same time it would be worth checking the others in this section as well, note that for GoLang the contract api was only supported for fabric 2 (I believe) so would not be previously used.

**Comment by james-wallis** [comment]
I've updated the npm versions here in the docs and added a link to each languages chaincode documentation to help migration.
