### ISSUE TITLE
fabric-sample secured-agreement chaincode fails to deploy in IBP

### ISSUE THREAD

**Issue by robinsonkwame** [IBM-Blockchain/blockchain-vscode-extension#3030]
Expected built secured-agreement go chaincode from `fabric-samples` to successfully deploy on channel but received `Failed to install on peer Org2 Peer with reason: Could not install smart contact received error: failed with status:500 ::failed to invoke backing implementation of 'InstallChaincode': could not build chaincode: external builder failed: external builder failed to build: external builder 'golang' failed: exit status 1` instead.

However, the `./chaincode/abcstore` go chaincode from `fabric-samples` successfully deployed with no error when following the same steps.

## Description

1. cd ./asset-transfer-secured-agreement/
2. export GOPATH=/Users/kwamepr/go && code chaincode-go/
3. IBP Smart Contracts -> Package Open project -> tar.gz -> secured-agreement -> 0.0.1
4. IBP Fabric Environments -> mychannel -> +Deploy smart contract -> <select secured-argreement@0.0.1> -> accept defaults -> click *deploy* on all peers

## Expected Behavior
IBP should indicate that the deployment was successful. 

## Actual Behavior
Deployment failed, with all peers returning,
```
Failed to install on peer Org2 Peer with reason: Could not install smart contact received error: failed with status:500 ::failed to invoke backing implementation of 'InstallChaincode': could not build chaincode: external builder failed: external builder failed to build: external builder 'golang' failed: exit status 1
```

## Possible Fix
Copy `secured-agreement` .go into `abcstore` .go, modify until deploys?

## Steps to Reproduce
(see Description)

## Existing issues
[Closed but for .js, OP never followed up](https://github.com/IBM-Blockchain/blockchain-vscode-extension/issues/3028)
[Needs more info, for go, closed](https://github.com/IBM-Blockchain/blockchain-vscode-extension/issues/2983)
[Same error, OP had to manually build, never able to do through IBP](https://github.com/IBM-Blockchain/blockchain-vscode-extension/issues/2616)

## Log File

[10-Blockchain.log](https://github.com/IBM-Blockchain/blockchain-vscode-extension/files/6565369/10-Blockchain.log)

## Your Environment
* IBM Blockchain Platform Extension Version: 2.0.2
* Visual Studio Code version: 1.55.2
* Environment name and version: go version go1.16.2 darwin/amd64
* Operating System and version: mac catalina 10.15.7

**Comment by robinsonkwame** [comment]
I modified go.mod to use `go 1.13` and the contract deployed. The change from `go 1.14` might suggest that [Install of a Go 1.14 chaincode fails](https://jira.hyperledger.org/browse/FAB-17725?page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel&showAll=true) is still an issue in IBP when used by normal mortals.

**Comment by davidkel** [comment]
@robinsonkwame Sounds like the vscode extension is being too restrictive in what it packages for golang and doesn't package up the modules.txt file from the vendor directory
