### ISSUE TITLE
Extension issue

### ISSUE THREAD

**Issue by Wizzlight** [IBM-Blockchain/blockchain-vscode-extension#3031]
- Issue Type: `Bug`
- Extension Name: `ibm-blockchain-platform`
- Extension Version: `2.0.2`
- OS Version: `Windows_NT x64 10.0.19043`
- VS Code version: `1.56.2`

:warning: We have written the needed data into your clipboard. Please paste! :warning:

**Comment by erin-hughes** [comment]
Hi @Wizzlight, could you provide some info on the problem you've encountered?
