### ISSUE TITLE
Extension issue

### ISSUE THREAD

**Issue by oumaimasouguir8** [IBM-Blockchain/blockchain-vscode-extension#3033]
- Issue Type: `Bug`
- Extension Name: `ibm-blockchain-platform`
- Extension Version: `2.0.3`
- OS Version: `Windows_NT x64 10.0.19042`
- VS Code version: `1.56.2`

:warning: We have written the needed data into your clipboard. Please paste! :warning:

**Comment by james-wallis** [comment]
Thanks for opening @oumaimasouguir8. Please add more information and reopen.
