### ISSUE TITLE
IBM blockchain platform v2.0.3 does not open prerequisite tab in vs-code.  

### ISSUE THREAD

**Issue by skushagra** [IBM-Blockchain/blockchain-vscode-extension#3036]
## Description

As one installs the latest version of IBM Block chain platform v2.0.3 in vs-code released some 17 days ago, the prerequisite tab appears to have some error. As I installed the previous version, v2.0.2 the error seems to have gone.

## Expected Behavior

The prerequisite tab should open as the extension is installed or the Editor is restarted, but it does not open. The error is in v2.0.3 and not earlier.

## Actual Behavior

When the extension is installed the prerequisite tab does not open immediately or after restart, there is also no way to open it explicitly. 
## Possible Fix

A button can be provided to open it explicitly etc. 
## Steps to Reproduce

1. Open VSCode and install IBM Block Chain Platform v2.0.3
2. Restart the Editor if possible.
3. The prerequisite tab does not open.

## Your Environment

* IBM Blockchain Platform Extension Version: v2.0.3
* Visual Studio Code version: 1.57(/latest as June 20 2021)
* Environment name and version (e.g. Node.js v8.12.0, npm v6.4.1): - 
* Operating System and version: Windows 10 Pro (Last update :- 15 June 2021)
* Link to your project: Local

**Comment by skushagra** [comment]
Any Hint/idea

**Comment by erin-hughes** [comment]
Hi @skushagra, you can open the pre-requisites page yourself by running `View Prerequisites` from the [VS Code command palette](https://code.visualstudio.com/docs/getstarted/userinterface#_command-palette).

**Comment by skushagra** [comment]
> Hi @skushagra, you can open the prerequisites page yourself by running `View Prerequisites` from the [VS Code command palette](https://code.visualstudio.com/docs/getstarted/userinterface#_command-palette).

Great, Thank you.
