### ISSUE TITLE
Failed to connect to Starter Plan

### ISSUE THREAD

**Issue by DennisM330** [IBM-Blockchain/blockchain-vscode-extension#304]
Using v.4 on Mac OS, I am trying to connect to Starter Plan instance from extension. I always get this message in just a few seconds "Failed to connect before the deadline URL:grpcs://nee8e5a864f184ae88880f3c8ecf7f01c-org1-peer1.us01.blockchain.ibm.com:31002"

**Comment by DennisM330** [comment]
Ah, I see only Hyperledger Fabric 1.3 is supported. The Starter Plan is 1.2.1.

**Comment by floriancastelain** [comment]
Where did you find this information?
Is it still the case today?
