### ISSUE TITLE
Installing Docker Desktop headlessly on Mac is unreliable and not supported

### ISSUE THREAD

**Issue by erin-hughes** [IBM-Blockchain/blockchain-vscode-extension#3042]
For the longest while we've been using [this workaround ](https://github.com/docker/for-mac/issues/2359#issuecomment-607154849)to install Docker Desktop headlessly when running our unit test Azure job on Mac. This workaround broke recently, and although the person who came up with it was kind enough to provide an update, that has also recently broken.

Currently to get the builds through we pull a version of Docker Desktop that's at least one major version behind latest (could be more but can't remember off the top of my head), which isn't great. There's been [an issue open for this](https://github.com/docker/for-mac/issues/2359) since 2018 on the docker/for-mac repo (where our previous workaround was commented), but there doesn't seem to have been any movement in reintroducing a headless install method, or even simplifying the process.

As our entire unit test suite also runs on Linux in our builds, and does not have to deal with this issue, is it worth revisiting whether we need the Mac unit test run at all? Or are we content to continue to test against this older version of Docker Desktop?

**Comment by jt-nti** [comment]
Might be worth investigating using an alternative to Docker Desktop, e.g. podman

**Comment by jt-nti** [comment]
See #3183
