### ISSUE TITLE
Integrating Test Network with blockchain-vscode-extension 

### ISSUE THREAD

**Issue by shanmuksai** [IBM-Blockchain/blockchain-vscode-extension#3050]
Started Test Network with **./network.sh up** command. Trying to manage that network with help of blockchain-vscode-extension. By using add other network feature. For that i am using the below JSON configuration to import existing network. 
[
    {
        "name": "peer0.org1.example.com",
        "api_url": "grpc://peer0.org1.example.com:7051",
        "type": "fabric-peer",
        "msp_id": "Org1MSP"
    }
]
......
Config in /etc/hosts
......
127.0.0.1      localhost peer0.org1.example.com peer1.org1.example.com peer0.org2.example.com peer1.org2.example.com orderer.example.com ca.org1.example.com ca.org2.example.com
......
## Description
Vs Code extension should be able to import nodes from the existing network. Instead of the it will was throwing an error unable to query channels. 
...........................
Steps to start the network:
./network.sh up -ca => Start network with CA
./network.sh up createChannel => create a sample channel 
Link to test network tutorials
https://hyperledger-fabric.readthedocs.io/en/release-2.2/deploy_chaincode.html#start-the-network

## Expected Behavior
Should be able import node and able to deploy smart contract to the organization.

## Actual Behavior
Throwing below error and it is unable to fetch channels in the network.

Error connecting to environment Test2: Error querying channels: Could not get all channel names, received: 14 UNAVAILABLE: Connection dropped

## Steps to Reproduce

1. Created Node json files which represents network details
2. Go to Blockchain extension and select add existing network 
3. Provide json configuration as input
4. Complete setup by associating identity with the organization then facing issue while querying channels

## Log File
[8/1/2021 5:57:12 PM] [INFO] Add environment
[8/1/2021 5:57:15 PM] [INFO] Import nodes to environment
[8/1/2021 5:57:21 PM] [SUCCESS] Successfully imported nodes
[8/1/2021 5:57:21 PM] [SUCCESS] Successfully added a new environment
[8/1/2021 5:57:28 PM] [INFO] connecting to fabric environment
[8/1/2021 5:57:28 PM] [IMPORTANT] You must complete setup for this environment to enable deploy and register identity operations on the nodes. Click each node in the list to perform the required setup steps
[8/1/2021 5:57:30 PM] [INFO] associate identity with node
[8/1/2021 5:57:33 PM] [INFO] connecting to fabric environment
[8/1/2021 5:57:33 PM] [ERROR] Error connecting to environment Test2: Error: Error querying channels: Could not get all channel names, received: 14 UNAVAILABLE: Connection dropped
[8/1/2021 5:57:33 PM] [SUCCESS] Successfully associated identity admin from wallet wallet with node peer0.org1.example.com

## Your Environment

* IBM Blockchain Platform Extension Version: 2.0.4
* Visual Studio Code version: 1.56.1
* Environment name and version (e.g. Node.js v8.12.0, npm v6.4.1): v10.19.0
* Operating System and version: Ubuntu 20.x

**Comment by bellaj** [comment]
Facing the same issue

**Comment by kssp1214** [comment]
> Solved the issue by removing containers and their volumes

May I ask you how to solve in details?

**Comment by bellaj** [comment]
> > Solved the issue by removing containers and their volumes
> 
> May I ask you how to solve in details? I've met same exception.

look into this https://stackoverflow.com/questions/65224577/error-deploying-chaincode-in-hyperledger-fabric-2/68884461#68884461

**Comment by kssp1214** [comment]
> > > Solved the issue by removing containers and their volumes
> > 
> > 
> > May I ask you how to solve in details? I've met same exception.
> 
> look into this https://stackoverflow.com/questions/65224577/error-deploying-chaincode-in-hyperledger-fabric-2/68884461#68884461

Thanks. I'll try
