### ISSUE TITLE
Automatically generated tests for go chaincode fail

### ISSUE THREAD

**Issue by Cheffu** [IBM-Blockchain/blockchain-vscode-extension#3057]
## Description
The extension provides a mechanism to generate test code for smart contracts. 
In particular, I'm interested in test code for a go-based chaincode. 

I used the extension to generate test code for an unchanged demo-contract as it is described in the tutorial.
The generation worked, but when I try to run any created test, there is a problem with the gateway connection.

## Expected Behavior
The test should be executed.

## Actual Behavior
I receive the following error message:
```
 [fabsdk/core] 2021/08/17 12:43:26 UTC - cryptosuite.GetDefault -> INFO No default cryptosuite found, using default SW implementation
--- FAIL: TestReadMyAsset_fv (0.01s)
    --- FAIL: TestReadMyAsset_fv/SubmitReadMyAssetTest (0.01s)
        fv-MyAssetContract-demo-contract@0.0.1_test.go:54: Failed to connect to gateway: Failed to apply config option: failed to initialize configuration: unable to load identity config: failed to initialize identity config from config backend: failed to create identity config from backends: failed to load TLS Cert Pool: Org 'org1ca-api.127-0-0-1.nip.io:8080' doesn't have defined tlsCACerts
FAIL
```

## Steps to Reproduce
1. Use the extension to generate a go-based smart contract (e.g., follow Tutorial A2 but choose a "Go" in step A2.5)
2. Deploy the smart contract to the network (e.g., follow Tutorial A3)
3. Fix generated smart contract by calling `go mod tidy` in the `demo-contract` folder
4. Use extension to generate functional tests (e.g. follow Tutorial A8)
5. Run or debug any test and receive the mentioned error message.

## Log File
No `Blockchain.log` available

## Your Environment

* IBM Blockchain Platform Extension Version: 2.0.4
* Visual Studio Code version: 1.59.0
* Environment name and version (e.g. Node.js v8.12.0, npm v6.4.1): go1.16.7
* Operating System and version: Ubuntu 20.04 in WSL2

**Comment by jt-nti** [comment]
See #3183
