### ISSUE TITLE
Extension issue

### ISSUE THREAD

**Issue by sengaMo** [IBM-Blockchain/blockchain-vscode-extension#3058]
- Issue Type: `Bug`
- Extension Name: `ibm-blockchain-platform`
- Extension Version: `2.0.4`
- OS Version: `Windows_NT x64 10.0.18362`
- VS Code version: `1.59.1`

:warning: We have written the needed data into your clipboard. Please paste! :warning:

**Comment by cazfletch** [comment]
closing as no details
