### ISSUE TITLE
Update adding a new Fabric environment to support multiple JSON file selection

### ISSUE THREAD

**Issue by mbwhite** [IBM-Blockchain/blockchain-vscode-extension#3059]
## Description
When adding a new Fabric environment, it is cumbersome to add each node file one at a time. If these could be multiply selected it would make this a lot easier. 

Or in from a zip file would also be useful.

## Expected Behavior
Use a multi-file selection dialogue

**Comment by cazfletch** [comment]
closing as you can already select multiple node files

**Comment by mbwhite** [comment]
To add that is specific to when you run VSCode on windows and do remote development to WSL2.. you can't then select multiple files.
