### ISSUE TITLE
As a developer I can performance test my chaincode

### ISSUE THREAD

**Issue by nklincoln** [IBM-Blockchain/blockchain-vscode-extension#306]
The VSCode extension provides the perfect point of use for Caliper as a means to rapidly iterate my code and not only functionally test, but performance test deployed chaincode.

The completion of this story is by using the Caliper modules from npm, the following flow could be enabled:
- user develops chaincode
- user deploys and functionally tests chaincode
- user runs a performance test to probe the capabilities (TPS, latency etc) of their chaincode
- user optionally iterates

It is entirely possible that caliper is not even required here, as we would be targeting a fixed Fabric "test net", so the "only" requirement would be act as a basic client to drive a load on the instantiated chaincode, post analyse the results, and then display them to the user.

**Comment by EdMoffatt** [comment]
So, it's been a while on this issue ;)

@nklincoln - does the original issue still stand, or do we want update (or raise something new) now that both the extension and Caliper have progressed substantially? Happy to have a chat with the goal of working out the most effective tooling work to do in support of Caliper users if that's helpful?
