### ISSUE TITLE
Trying to use IBM VS Code blockchain extension to run a Hyperledger Fabric sample

### ISSUE THREAD

**Issue by jugma** [IBM-Blockchain/blockchain-vscode-extension#3063]
## Description
Visual Studio Code: 1.60.2 
MacOS: 20.6.0 
IBM Blockchain extension:2.0.3 
I successfully installed and deployed the chaincode in golang for the asset-transfer-private-data example in Hyperledger Fabric 2.3.2 in VS code using the IBM blockchain extension. I started the mini fab Test Network that comes with the extension. The chaincode was installed and deployed successfully to this network. But when I try to invoke the CreateAsset function in the chaincode I get the following error:

Error evaluating transaction: Query failed. Errors: ["Peer org1peer-api.127-0-0-1.nip.io:8081: failed to unmarshal JSON: invalid character '\x00' looking for beginning of value","Peer org2peer-api.127-0-0-1.nip.io:8081: failed to unmarshal JSON: invalid character '\x00' looking for beginning of value"]

Below is the JSON that I use for the Transient Data:

{
   "asset_properties":[
      {
         "objectType":"asset",
         "assetID":"asset1",
         "color":"green",
         "size":20,
         "appraisedValue":100
      }
   ]
}

## Expected Behavior
The asset should have been created in the HLF network

## Actual Behavior
I get the error described above and the asset is not added to the HLF network

**Comment by cazfletch** [comment]
The error suggests that the json isn't valid. Where did you get the data from that you should pass in for the transient data

**Comment by jugma** [comment]
I checked and the JSON is valid. I got the data from the tutorial on private data (https://hyperledger-fabric.readthedocs.io/en/release-2.2/private_data_tutorial.html)

**Comment by cazfletch** [comment]
I think the problem is that you have an array in your transient data. I think you need to do something like
```
{
   "asset_properties": {
         "objectType":"asset",
         "assetID":"asset1",
         "color":"green",
         "size":20,
         "appraisedValue":100
      }
}
```

**Comment by jt-nti** [comment]
No response since October so closing this issue

**Comment by MehdiKallel** [comment]
The right input should be in this form: 
{"asset_properties":"{\"objectType\":\"asset\", \"assetID\":\"asset1\", \"color\":\"green\", \"size\":20, \"appraisedValue\":100}"}

**Comment by MehdiKallel** [comment]
right input:
{"asset_properties": "{\"objectType\":\"asset\", \"assetID\":\"asset1\", \"color\":\"green\", \"size\":20, \"appraisedValue\":100\n}"}
