### ISSUE TITLE
cannot execute transactions, they aren't showing on Fabric Gateways panel

### ISSUE THREAD

**Issue by msalimbene** [IBM-Blockchain/blockchain-vscode-extension#3074]
I was working without problems, but I started to experience a problem when I tried to execute a transaction, they are not showing:

![image](https://user-images.githubusercontent.com/89998369/139285744-cf57d376-bf0a-4804-9aab-056b2eb9eb09.png)

I tried deleting the local environment and recreating it, but the problem remains. Not sure what the problem could be, I've been testing chaincodes for a while now with no problems. Any idea?

**Comment by cazfletch** [comment]
Can you comment with what your smart contract looks like please

**Comment by msalimbene** [comment]
I was working on a template created with the plugin. In the end, I deleted the environment and started over. 

Is it possible that changing the metadata fields in `main.go` caused problems? I had added `	hlpLoanContract.Info.Contact.Email`.
