### ISSUE TITLE
build.gradle.kts is not recognized by UserInputUtil

### ISSUE THREAD

**Issue by TenPetr** [IBM-Blockchain/blockchain-vscode-extension#3075]
Cannot package chaincode (smart contract) written in Kotlin, extension does not recognize build.gradle.kts file, so it throws an error.

## Description
When packaging chaincode written in Kotlin, VS Code extension cannot package chaincode into the archive, because it does not recognize build.gradle.kts, it is looking for an only build.gradle files and since Kotlin projects might contain build.gradle.kts instead, the error is thrown.

## Expected Behavior
build.gradle.kts file is find and packaged same as with the build.gradle file

## Actual Behavior
build.gradle.kts is not recognized and error is thrown

## Possible Fix
UserInputUtils.ts - Line: 1161 - const gradleFile: string = `path.join(workspaceDir.uri.fsPath, 'build.gradle');`
Should be also checked with the build.gradle.kts

## Steps to Reproduce
1. Open Kotlin project in the VS Code and run extension
2. Run package open project from command pallete 
3. Select tar.gz (channel V2)
4. Error pops up - Failed to determine workspace language type, supported languages are JavaScript, TypeScript, Go and Java. Please ensure your contract's root-level directory is open in the Explorer.

## Your Environment
* IBM Blockchain Platform Extension Version: **v2.0.5**
* Visual Studio Code version: **1.55.2**
* Environment name and version (e.g. Node.js v8.12.0, npm v6.4.1): **Kotlin 1.5.10, JVM**
* Operating System and version: **macOS Big Sur (11.6)**

**Comment by jt-nti** [comment]
I'm closing this issue and the related PR since there hasn't been any recent activity.
