### ISSUE TITLE
UI is very confusing with High Contrast Theme on

### ISSUE THREAD

**Issue by pratikpc** [IBM-Blockchain/blockchain-vscode-extension#3101]
## Expected Behavior

![image](https://user-images.githubusercontent.com/28534575/150686094-9cca2ffb-f2f0-4b6a-9bcf-3696f326b5d7.png)
![image](https://user-images.githubusercontent.com/28534575/150686291-672caae3-759f-469f-92a0-b6b49ed6c390.png)

With Regular Dark Theme

## Actual Behavior

![image](https://user-images.githubusercontent.com/28534575/150686049-18f456ed-d461-4fa7-94df-b64bd13f2a14.png)
![image](https://user-images.githubusercontent.com/28534575/150686270-6c4a6ca3-d3f6-4a98-b186-d7630bff8a6c.png)
With High Contrast Theme (Look at Output)

## Possible Fix

An implementation issue with High Contrast Theme?

## Steps to Reproduce

1. Switch between High Contrast and Dark themes

## Log File

NA I think. This is purely a UI issue.

## Your Environment

* IBM Blockchain Platform Extension Version: v2.0.7
* Visual Studio Code version: 1.63.2
* Environment name and version (e.g. Node.js v8.12.0, npm v6.4.1): NodeJS v17.4.0 npm v8.3.1
* Operating System and version: Windows 11
* Link to your project: NA

**Comment by jt-nti** [comment]
See #3183
