### ISSUE TITLE
FAILED - RETRYING: Wait for certificate authority to start (60 retries left).

### ISSUE THREAD

**Issue by libits** [IBM-Blockchain/blockchain-vscode-extension#3126]
When I started the Local Fabric，Something went wrong.
ubuntu version:18.04
vscode version:1.39.2
IBM Blockchain Platform:1.0.40
 TASK [ibm.blockchain_platform_manager : Wait for certificate 
 [INFO] FAILED - RETRYING: Wait for certificate authority to start 
[INFO] FAILED - RETRYING: Wait for certificate authority to start 
[INFO] FAILED - RETRYING: Wait for certificate authority to start 
 [ERROR] Failed to start 1Org9: Error: Failed to execute command "/bin/sh" with  arguments "generate.sh" return code 2

**Comment by jt-nti** [comment]
Unfortunately this project is no longer active - see #3183 - however the extension used [microfab](https://github.com/IBM-Blockchain/microfab) for local Fabric networks, which is hopefully [moving to a Hyperledger labs project](https://github.com/hyperledger-labs/hyperledger-labs.github.io/pull/225).
