### ISSUE TITLE
Migrate to new Gateway SDK

### ISSUE THREAD

**Issue by jt-nti** [IBM-Blockchain/blockchain-vscode-extension#3135]
There is a new [fabric-gateway](https://www.npmjs.com/package/@hyperledger/fabric-gateway) SDK to support the new Gateway functionality in Fabric 2.4, which the vscode extension should migrate to when possible.

**Comment by davidkel** [comment]
@jt-nti but you would still need the 2.2 sdk because the admin module relies on fabric-common to be able to do things like chaincode deployment

**Comment by jt-nti** [comment]
Good point. Awkward!

**Comment by jt-nti** [comment]
See #3183
