### ISSUE TITLE
Need Help😭 Failed to deploy smart contract, Package was not installed.No packageId was returned

### ISSUE THREAD

**Issue by lucy-lulu** [IBM-Blockchain/blockchain-vscode-extension#3146]
I used the 2ORG template environment, and had packaged the smart contract, but failed to deploy it on peers.

## Description
There are three warnings:
1. Failed to deploy smart contract, Error: Package was not installed. No packageId was returned
2. Failed to install on peer Org1 Peer with reason: Error: Could not install smart contact received error: failed with status:500 ::failed to invoke backing implementation of 'InstallChaincode': could not build chaincode: external builder failed: external builder failed to build: external builder 'node' failed: exit status 1
3.  Failed to install on peer Org2 Peer with reason: Error: Could not install smart contact received error: failed with status:500 ::failed to invoke backing implementation of 'InstallChaincode': could not build chaincode: external builder failed: external builder failed to build: external builder 'node' failed: exit status 1

<img width="722" alt="16BDDF49-299F-4139-B67C-190180D097F8" src="https://user-images.githubusercontent.com/72977932/164890121-188e99f3-2b80-49ee-b64b-0db4ced8419e.png">

## Expected Behavior
Successfully deployed the smart contract.

## Actual Behavior
Failed to deploy smart contract.

I guess there's something wrong with the 'node' as the warnings said, so I tried to reinstall it, but nothing changed.

## Your Environment

* IBM Blockchain Platform Extension Version:2.0.8
* Visual Studio Code version:1.66
* Environment name and version: node12.13.1/npm6.12.1/nodejs10.19.0/docker20.10.14
* Operating System and version: Linux Unbuntu20.04
* Link to your project: I tried to run this project:
   https://github.com/yashverma9/AI-Blockchain-Electronic-Health-Records-Management-System

**Comment by jt-nti** [comment]
It looks like a problem with the project you're trying to run. I also get errors running `npm ci --only=production` for the contract in [AI-Blockchain-Electronic-Health-Records-Management-System](https://github.com/yashverma9/AI-Blockchain-Electronic-Health-Records-Management-System). If you get that working, it should deploy ok, although the project seems quite stale so you may hit other problems.
