### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by tomjes03** [IBM-Blockchain/blockchain-vscode-extension#3163]
- Issue Type: `Performance`
- Extension Name: `ibm-blockchain-platform`
- Extension Version: `2.0.8`
- OS Version: `Windows_NT x64 10.0.19043`
- VS Code version: `1.69.2`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`file:///c%3A/Users/BASEPO~1/AppData/Local/Temp/IBMBlockchain.ibm-blockchain-platform-unresponsive.cpuprofile.txt`

Find more details here: https://github.com/microsoft/vscode/wiki/Explain-extension-causes-high-cpu-load

**Comment by tomjes03** [comment]
I was recommended by IBM to download the softwre so Ican use it for tutorial and this happened.

**Comment by jt-nti** [comment]
Unfortunately this project is no longer active- see #3183
