### ISSUE TITLE
my-asset-contract.ts incorrectly generated

### ISSUE THREAD

**Issue by zarifpour** [IBM-Blockchain/blockchain-vscode-extension#3166]
## Description

When a user creates a new project, following the instructions in the tutorial, the method `createMyAsset(...)` is missing `true` in the @Transaction() decorator.

## Expected Behavior

Per the documentation under the title: `Working with the world state` it would seem the method should be decorated with `@Transaction(true)`.

## Actual Behavior

The method `createMyAsset()` is decorated as follows: `@Transaction()`

## Possible Fix

Update the code that is used to generate the skeleton for my-asset-contract.ts and potentially others (I have not investigated other languages).

## Steps to Reproduce

1. Follow steps in A2.1: Creating a smart contract (Basic tutorials)
2. View my-asset-contract.ts

## Your Environment

* IBM Blockchain Platform Extension Version: v2.0.8
* Visual Studio Code version: latest
* Operating System and version: MacOS

**Comment by jt-nti** [comment]
Unfortunately, as mentioned in the pull request, this project is no longer active
