### ISSUE TITLE
help solve this error on microsoft azure

### ISSUE THREAD

**Issue by jchigu** [IBM-Blockchain/blockchain-vscode-extension#3170]
*  Executing task in folder api: npm install 

> api@1.0.0 build
> tsc

node_modules/@azure/core-tracing/types/core-tracing.d.ts:81:21 - error TS2456: Type alias 'Resolved' circularly references itself.

81 export declare type Resolved<T> = T extends {
                       ~~~~~~~~

node_modules/@azure/core-tracing/types/core-tracing.d.ts:83:41 - error TS2315: Type 'Resolved' is not generic.

83 } ? F extends (value: infer V) => any ? Resolved<V> : never : T;
                                           ~~~~~~~~~~~

node_modules/@azure/core-tracing/types/core-tracing.d.ts:131:212 - error TS2315: Type 'Resolved' is not generic.

131     }, Callback extends (updatedOptions: Options, span: Omit<TracingSpan, "end">) => ReturnType<Callback>>(name: string, operationOptions: Options, callback: Callback, spanOptions?: TracingSpanOptions): Promise<Resolved<ReturnType<Callback>>>;

**Comment by jt-nti** [comment]
Unfortunately this project is no longer active- see #3183
