### ISSUE TITLE
As a developer, I would like to import and use sample smart contract projects

### ISSUE THREAD

**Issue by Jakeeyturner** [IBM-Blockchain/blockchain-vscode-extension#321]
As a developer, I want to be able to import sample smart contract projects which demonstrate good practices.

- [ ] I can view the smart contract project README
- [ ] I can import a sample smart contract project
- [ ] I can view any associated applications

**Comment by simran-sohanpal** [comment]
Visuals for Samples page:
[Samples Page Visuals.zip](https://github.com/IBM-Blockchain/blockchain-vscode-extension/files/2685889/Samples.Page.Visuals.zip)

**Comment by simran-sohanpal** [comment]
Visuals above have been handed over to @Jakeeyturner for implementation

**Comment by Jakeeyturner** [comment]
![screen shot 2018-12-20 at 15 17 54](https://user-images.githubusercontent.com/10009752/50293083-a56ded00-046a-11e9-8815-68ce9412ab2a.png)

**Comment by simran-sohanpal** [comment]
Updated iteration of visuals - handed over to @Jakeeyturner :
[Samples Page.zip](https://github.com/IBM-Blockchain/blockchain-vscode-extension/files/2755930/Samples.Page.zip)
