### ISSUE TITLE
'Add new connection' action

### ISSUE THREAD

**Issue by simran-sohanpal** [IBM-Blockchain/blockchain-vscode-extension#325]
Currently there is a '+' symbol in the heading as well as an 'Add new connection' action below the heading. Is there a reason for having both? If not, I feel like it would make more sense having just one action here?

**Comment by caroline-church** [comment]
which action would you like to have?

**Comment by simran-sohanpal** [comment]
The '+' symbol seems to be the more natural action; the implications seem obvious as it is next to the heading so its clear that a new 'Blockchain connection' is being added

**Comment by caroline-church** [comment]
done so closing
