### ISSUE TITLE
Severity of deleting a connection

### ISSUE THREAD

**Issue by simran-sohanpal** [IBM-Blockchain/blockchain-vscode-extension#327]
Currently, a connection can be deleted without any confirmation of the action - what is the severity of deleting a connection? Should a second step be introduced to prevent connections being deleted accidentally/ before the user realises the severity of the action?

This action could trigger the dialogue box to prompt the user to 'enter the connection name' to confirm the action i.e. as a 'Are you sure you want to complete this action?' prompt

**Comment by caroline-church** [comment]
The severity isn't very high of deleting a connection you can easily add it again as you should have the files so is simple to add again. Maybe we just have a prompt saying are you sure. I don't think we need something as strong as having to type in the name of the connection

**Comment by caroline-church** [comment]
done so closing
