### ISSUE TITLE
Current readme for .5 implies Generate Smart Contracts Tests command is available.

### ISSUE THREAD

**Issue by DennisM330** [IBM-Blockchain/blockchain-vscode-extension#333]
Reviewing the Readme for .5 and the debug section implies a Generate Smart Contracts Tests command for debugging transactions is available. However, that command is not available in the command palette in .5 version of the extension. Am I looking in the wrong place? Also , need to note in the Debug section of the Readme, that you need to toggle the Fabric runtime to be in development mode in order to use Debug.

**Comment by heatherlp** [comment]
#335 is in and we'll be releasing 0.0.6 soon, so closing this
