### ISSUE TITLE
Create a gif for the readme showing submitting a transaction

### ISSUE THREAD

**Issue by caroline-church** [IBM-Blockchain/blockchain-vscode-extension#334]

**Comment by Jakeeyturner** [comment]
Can we not just use `CommandUtil.sendCommandWithProgress()`?

**Comment by caroline-church** [comment]
huh? this is right clicking on a transaction and clicking submit transaction

**Comment by simran-sohanpal** [comment]
![submit transaction](https://user-images.githubusercontent.com/41570203/48634689-09118000-e9be-11e8-907d-6a214310d07a.gif)

**Comment by simran-sohanpal** [comment]
![submit transaction](https://user-images.githubusercontent.com/41570203/48635746-ed5ba900-e9c0-11e8-919f-e6940b948886.gif)

**Comment by simran-sohanpal** [comment]
![submit transaction](https://user-images.githubusercontent.com/41570203/48636175-14ff4100-e9c2-11e8-9da4-c627addc2e8c.gif)

**Comment by simran-sohanpal** [comment]
![submit transaction 2](https://user-images.githubusercontent.com/41570203/48702516-034bb280-ebe9-11e8-9a05-b794b1ba1f59.gif)

**Comment by simran-sohanpal** [comment]
![submit transaction](https://user-images.githubusercontent.com/41570203/48702699-7ce3a080-ebe9-11e8-9d9a-158ae15d970a.gif)

**Comment by caroline-church** [comment]
done so closing
