### ISSUE TITLE
Unable to instantiate a contract if a toplevel workspace dir does not have a package.json

### ISSUE THREAD

**Issue by mbwhite** [IBM-Blockchain/blockchain-vscode-extension#367]
If I have a structure in vsode that is

```
directory_one
contract_one
contract_two
```

And I wish to instantiate one of the contracts, but the `directory_one` does not have a package.json file then I get an error saying that the package.json doesn't exist in `directory_one`

Appears the plugin is making the assumption that every project will have a package.json .

**Comment by caroline-church** [comment]
closing as this is now fixed, and nested projects are not supported

**Comment by Elvin94** [comment]
How did you fix this?

**Comment by jenil04** [comment]
Still having this issue, how to fix it?

**Comment by zaynabAlizadeh** [comment]
I had such a problem.That's how I solved it:
1.close all project
![Screenshot from 2019-09-29 17-35-26](https://user-images.githubusercontent.com/50650454/65833681-95c7e280-e2df-11e9-81e0-18c9822d5a00.png)
2.open vscode
3.open the folder that contains smart 
![Screenshot from 2019-09-29 17-36-43](https://user-images.githubusercontent.com/50650454/65833690-b98b2880-e2df-11e9-906a-f8e2a0576516.png)
contract,Actually last directory
