### ISSUE TITLE
Error when trying to generate tests for go or java

### ISSUE THREAD

**Issue by caroline-church** [IBM-Blockchain/blockchain-vscode-extension#373]
As this doesn't work for go or java i shouldn't be allowed to do it, or i should get an error saying it isn't supported rather than a random error

**Comment by heatherlp** [comment]
@caroline-church  What error do you see?
We've got no way of knowing what language an instantiated smart contract is written in so need to know at which point to fail

**Comment by heatherlp** [comment]
done in #385
