### ISSUE TITLE
Unable to create tests for instantiated contract if it's open more than once in workspace

### ISSUE THREAD

**Issue by mbwhite** [IBM-Blockchain/blockchain-vscode-extension#375]
With an instantiated smart contract, it is possible to create the functional tests via the context menu.

But only if a single contract is open in the workspace; if there are 2 or more then an error occurs stating that the contract you're creating tests for is not open. 

The presence of other directories, with or without package.json in them does not affect behaviour.

**Comment by heatherlp** [comment]
I can't reliably recreate this on my mac :/ The integration tests add all the smart contracts it creates to the workspace, so there are multiple (at least 2) smart contracts during an integration test run. I've added some more runs into the integration tests to test this. The integration tests are only run on linux/manually on mac so I'm starting to think this is a Windows thing
