### ISSUE TITLE
Cannot upgrade Smart Contract using VSCode extension 0.0.6

### ISSUE THREAD

**Issue by mahoney1** [IBM-Blockchain/blockchain-vscode-extension#381]
The scenario is that I try to instantiate a newly changed Commercial paper contract (version 0.0.2) but I cannot upgrade.  I successfully installed/instantiated 0.0.1 of the same contract name, and then installed the changed 0.0.2 contract package onto the peer (FYI I am using the basic_network fabric, as its being used by Commercial Paper) but am unable to instantiate / upgrade (0.0.2 doesn't show up to instantiate -  yet you can expand the 'Instantiated' list and see it listed there). Also, to confirm,  no docker container for 0.0.2 exists. I've tried the following combos in my package.json for "fabric-contact-api" and "fabric-shim":

"1.4.0-snapshot.41",  "1.4.0-snapshot.51" (taken from https://github.com/IBM-Blockchain/generator-fabric/blob/master/generators/contract/templates/javascript/package.json#L20 )
"1.4.0-beta",  "1.4.0-beta"
"unstable" : "unstable"

I get the "getMetaData" error reported  or 'function name' invariably.

the current Github sample commercial paper contract itself, uses "^1.4.0-snapshot.17" , "^1.4.0-snapshot.27" in its package.json but this won't work.

This scenario did work previously in VSCode extension 0.0.5

**Comment by caroline-church** [comment]
To do the upgrade, did you right click on the channel or right click on the smart contract. From version 0.0.6 you need to right click on the smart contract and click upgrade to upgrade

**Comment by mahoney1** [comment]
my observations with 0.0.6 captured below:

still no luck (in fact a see bit more going on), as in: I don't get the option to upgrade the smart contract - this is what I get with `1.4.0-beta` in `package.json`  - I can update on the ticket too FYI - this is with VSCode extension 0.0.6 (I reinstalled afresh, and new VSCode launch FYI).
1. Installed papercontract 0.0.1 on peer successfully
2. On 'mychannel' ..right click - instantiate S/Contract and provide 'org.papernet.commercialpaper:instantiate' as the function
All good, its instantiated, I get 'success' message and I see that 0.0.1 under the 'Instantiated' twisty - and I see the docker container for the chaincode - HOWEVER I do get a message in VSCode of "Cannot read property 'functions' of undefined",  when I expand the 'Instantiated Smart Contracts' twisty

3. I make code changes, save - and upgrade package.json to 0.0.2
4. I then install version 0.0.2 of the S/Contract on the peer (right-click install ..select 0.0.2 from list to install) - BUT  - I get a popup message "Cannot read property 'functions' of undefined" **
5. I do see two packages installed (see screenshot)  - despite the message above **
6. I now try to right-click .. upgrade .. on the Smart Contract 'papercontract' contract in the screenshot - but there's no option to **
7. Note that twisty under the 'Instantiated Smart Contracts'....peer0.org1.example.com' does NOT now expand (like it did previous) to show instantiated contract from previous (ie can't now see papercontract 0.0.1, whereas I could see earlier, when I had successfully instantiated v 0.0.1 on the channel 'mychannel'

** I suspect this 'function' error is why I don't see the 'upgrade' option. Attaching screenshot showing:  1. the 'functions' error msg and 2. The twisty under 'Instantiated Smart Contracts' not expanding.

**Comment by mahoney1** [comment]
![upgrade-issues](https://user-images.githubusercontent.com/22452289/49149087-13f2db80-f301-11e8-97bf-5c48bf1082c9.png)

**Comment by mahoney1** [comment]
![upgrade-issues](https://user-images.githubusercontent.com/22452289/49149157-41d82000-f301-11e8-9f7c-422d53c0c5c6.png)

**Comment by caroline-church** [comment]
i think this will be fixed by https://github.com/IBM-Blockchain/blockchain-vscode-extension/issues/370 but not sure why you can't get metadata.

**Comment by heatherlp** [comment]
@mahoney1 can you please re-try this using version 0.0.7?

**Comment by mahoney1** [comment]
@heatherlp will try it out today.

**Comment by caroline-church** [comment]
closing now have 0.1
