### ISSUE TITLE
As a user, my local Fabric ports are fixed

### ISSUE THREAD

**Issue by caroline-church** [IBM-Blockchain/blockchain-vscode-extension#388]
local fabric ports should be random the first time then fixed for every other start including after being torn down. The ports could be stored in the user settings

**Comment by sstone1** [comment]
- Ports for Fabric runtimes will be assigned starting at 17050
- A free port finder module will be used to ensure the ports assigned are free
- This will ensure the Fabric runtime should always start for new users
- The port assignments will be recorded in the user settings and used for next time
- The user can modify the ports in the user settings if they wish to change them
