### ISSUE TITLE
Version bump for upgrade should not rely on package.json

### ISSUE THREAD

**Issue by awjh-ibm** [IBM-Blockchain/blockchain-vscode-extension#390]
When developing a contract using the VSCode extension I have to manually bump the version in my contract's package.json to test new code added. This means then when I go to publish my new app my version has changed from the simple version bump I would want (e.g. 1.3.1 to 1.3.2). Instead the VSCode plugin should handle "behind the scenes" versions for my different saves so I can upgrade my code.

**Comment by caroline-church** [comment]
We do this for Debug but not normally, the only problem is how do you know when to use their version or when to use the generated version. A proposal would be that if you put your fabric in dev mode then we will worry about the version number, but if your fabric isn't in dev mode you will have to worry about the version number @awjh-ibm, @EdMoffatt  thoughts?

**Comment by awjh-ibm** [comment]
That sounds a good solution to me, not sure about others but I would also expect dev mode by default (maybe it already does this I'm not sure) that could just be because I am used to the fabric chaincode tutorial where they set you up in dev mode though. But as I'm a dev developing contracts using the  plugin I'd expect to see it in dev mode usually and then only later would I run it as a proper chaincode to test it at the end

**Comment by EdMoffatt** [comment]
I'm not quite getting this one at the moment - I hereby tag it as a "let's discuss when we're all back in the office" issue, sorry!

**Comment by EdMoffatt** [comment]
New plan - assign this one to Toby and he can figure it out mwahahahaha

**Comment by Tobias-Hunter** [comment]
After discussion with Andy, this issue may be solved with the Debug mode - just noting this here that we should check back with Andy to ensure this fixes this issue at hand, if it does then perhaps a suggestion of helping our users to understand this within VSCode may be appropriate!

**Comment by awjh-ibm** [comment]
Using debug mode fixes my issue. A guide on doing dev that uses this would be handy as, as a dev this would be my first approach, not using it in non-debug mode
