### ISSUE TITLE
As a smart contract developer, I want to get the return values from my smart contract transactions

### ISSUE THREAD

**Issue by heatherlp** [IBM-Blockchain/blockchain-vscode-extension#392]
We can some submit transactions now 🎉 but this doesn't show us what those transactions return

To begin with, we need some design sessions to figure out how we should present function return values to the user

**Comment by EdMoffatt** [comment]
Assigning this one to Niv as her second-priority for before her holiday next week - if she's not got to it by next Weds, I shall reassign, but please have a bash at this one if you get time @niv23 :)
