### ISSUE TITLE
As a developer, I want support for writing my own smart contract metadata

### ISSUE THREAD

**Issue by heatherlp** [IBM-Blockchain/blockchain-vscode-extension#396]
"Generate smart contract metadata template" command that puts it in the appropriate place with the appropriate bits and allows for schema validation

This user story should also include the option to right click on an instantiated smart contract and generate a metadata file from the metadata object returned when we run the command. 

@mbwhite

**Comment by mbwhite** [comment]
Can we add the following to the `contributes` section of the extensions `package.json` please?

```json
    "jsonValidation": [
      {
        "fileMatch": "*.contract.json",
        "url": "https://fabric-shim.github.io/contract-schema.json"
      },
      {
        "fileMatch": "*.contract-1.4.json",
        "url": "https://fabric-shim.github.io/release-1.4/contract-schema.json"
      },
      {
        "fileMatch": "*.contract-master.json",
        "url": "https://fabric-shim.github.io/master/contract-schema.json"
      }
    ]
```

This allows the built in JSON parsing and validation in vscode to pull the correct schema based on file extensions. 

For example:

- `commercial-paper.json` - won't be validated other than as syntax correct
- `commercial-paper.contract.json` - will use the the latest GA version of the contract schema
- `commercial-paper.contract-master.json` - will use the master branch schema version
- `commercial-paper.contract-1.4.json` - will use explicitly the release-1.4 version

The above is consistent with how the documentation is routed.

If the user wishes to override these values; then explicitly setting the schema in the json as follows

```json
{
  "$schema": "https://fabric-shim.github.io/master/contract-schema.json",
  "info": {
    "title": "Commercial Paper Smart Contract",
    "description": "Smart Contract definitions for Commercial Paper, issuing and trading",
    "termsOfService": "http://example.com/terms/",
    "contact": {
....
.....
```

**Comment by mbwhite** [comment]
vscode snippets:


```
	"Contract Info": {
		"scope": "json",
		"prefix": "contract.info",
		"body": [
			"\"info\": { ",
			"   \"title\": \"${1:Commercial Paper Smart Contract}\",  ",
			"   \"description\": \"${2:Smart Contract definitions for Commercial Paper, issuing and trading}\",",
			"   \"termsOfService\": \"${3:http://example.com/terms/}\",",
			"   \"contact\": { ",
			"      \"name\": \"${4:Peso Phillips}\",",
			"      \"url\": \"${5:http://www.example.com/support}\",",
			"      \"email\": \"${6:peso.phillips@example.com}\" ",
			"     },",			
			"   \"license\": {",
			"      \"name\": \"${8:Apache 2.0}\",",
			"      \"url\": \"${9:http://www.apache.org/licenses/LICENSE-2.0.html}\"",
			"     },",
			"   \"version\": \"${10:1.0.1}\"",
			"}",
		],
		"description": "Top level info object"
	}
```

**Comment by caroline-church** [comment]
https://github.com/IBM-Blockchain/blockchain-vscode-extension/issues/387

**Comment by caroline-church** [comment]
closing as not planning on doing this anytime soon
