### ISSUE TITLE
Errors are swallowed if initial "npm install" fails

### ISSUE THREAD

**Issue by jonathan-blood** [IBM-Blockchain/blockchain-vscode-extension#397]
When creating a new smart contract project, the initial `npm install` that is automatically executed doesn't surface any errors it encounters.

I was running on a reasonably new Macbook which I hadn't yet installed Xcode on. When attempting to package a smart contract I received an error that `node_modules/.bin/fabric-chaincode-node` was missing and subsequently discovered that the `fabric-shim` dependency hadn't installed. When attempting to manually install, I received the following:

```
No receipt for 'com.apple.pkg.CLTools_Executables' found at '/'.

No receipt for 'com.apple.pkg.DeveloperToolsCLILeo' found at '/'.

No receipt for 'com.apple.pkg.DeveloperToolsCLI' found at '/'.

gyp: No Xcode or CLT version detected!
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:345:16)
gyp ERR! stack     at emitTwo (events.js:126:13)
gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
gyp ERR! System Darwin 18.0.0
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/jonathanblood/Documents/workspace/code-extension-tutorial/node_modules/x509
gyp ERR! node -v v8.11.3
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
npm WARN code-extension-tutorial@0.0.1 No repository field.
```

I assume that the automatic dependency installation also hit this but I wasn't aware of it as I just received a message to say the project had been created successfully.

**Comment by erniepty** [comment]
> When creating a new smart contract project, the initial `npm install` that is automatically executed doesn't surface any errors it encounters.
> 
> I was running on a reasonably new Macbook which I hadn't yet installed Xcode on. When attempting to package a smart contract I received an error that `node_modules/.bin/fabric-chaincode-node` was missing and subsequently discovered that the `fabric-shim` dependency hadn't installed. When attempting to manually install, I received the following:
> 
> ```
> No receipt for 'com.apple.pkg.CLTools_Executables' found at '/'.
> 
> No receipt for 'com.apple.pkg.DeveloperToolsCLILeo' found at '/'.
> 
> No receipt for 'com.apple.pkg.DeveloperToolsCLI' found at '/'.
> 
> gyp: No Xcode or CLT version detected!
> gyp ERR! configure error
> gyp ERR! stack Error: `gyp` failed with exit code: 1
> gyp ERR! stack     at ChildProcess.onCpExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:345:16)
> gyp ERR! stack     at emitTwo (events.js:126:13)
> gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
> gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
> gyp ERR! System Darwin 18.0.0
> gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
> gyp ERR! cwd /Users/jonathanblood/Documents/workspace/code-extension-tutorial/node_modules/x509
> gyp ERR! node -v v8.11.3
> gyp ERR! node-gyp -v v3.8.0
> gyp ERR! not ok
> npm WARN code-extension-tutorial@0.0.1 No repository field.
> ```
> 
> I assume that the automatic dependency installation also hit this but I wasn't aware of it as I just received a message to say the project had been created successfully.

Hi. Was someone able to solve this issue?
