### ISSUE TITLE
Export Connection Details Should Always Shown on Context Menu

### ISSUE THREAD

**Issue by m-g-k** [IBM-Blockchain/blockchain-vscode-extension#406]
The context (right-click) menu for the "local_fabric" runtime is not shown after a connection is made to the runtime. A user should not have to disconnect just to see the options for 
"Export Connection Details" and "Open Fabric Runtime Terminal" which would be very useful at all times.

Details:
![image](https://user-images.githubusercontent.com/11261488/49521186-c9db9e00-f89c-11e8-91ca-aad5e933bf53.png)

The above image shows the context menu which is shown when you are not connected to the runtime.

![image](https://user-images.githubusercontent.com/11261488/49521283-04ddd180-f89d-11e8-8adf-dac291c89bdc.png)

The above image shows the lack of a context menu once a connection is made to the runtime. I would expect the context menu to be available when you are connected if you click on the box in red.

**Comment by heatherlp** [comment]
@caroline-church's already delivered this under #405
