### ISSUE TITLE
Don't show "instantiate" in list of transactions after we've instantiated

### ISSUE THREAD

**Issue by heatherlp** [IBM-Blockchain/blockchain-vscode-extension#414]
MGK's point is that we've already instantiated, so it's weird to see it again, so we should exclude it. 

Let's discuss this. Perhaps we want to only show it if we're in dev mode?

**Comment by rthatcher** [comment]
Is this specifically 'instantiate' or more generally the name of the function we called at instantiate time?

**Comment by sstone1** [comment]
The function used to instantiate or upgrade a smart contract does not have to be called `instantiate`, so we should avoid doing anything just based on the name.

I'd suggest instead that we look at adding additional metadata on the Fabric side of things that indicates a transaction function is for instantiating or upgrading a smart contract.

**Comment by caroline-church** [comment]
closing this issue as @sstone1 is right, and also there is no harm running the "instantiate" transaction again.
