### ISSUE TITLE
As a dev I can achieve a specific configuration in my local_fabric

### ISSUE THREAD

**Issue by simran-sohanpal** [IBM-Blockchain/blockchain-vscode-extension#422]
Local fabric connection with a chosen number of organisations, channels, and configuration for things like Identity Mixer and private data collections.
- Be clear how users can build something more complicated if they want  
- Format that describes a Fabric config, which could then be given to VSCode to spin up the local_fabric in that shape?  If the IBP Ops Tools could export such a thing and the IBP Dev Tools could use such a thing to configure a local fabric, we'd allow folks to easily recreate their cloud environments locally for dev/test

**Comment by heatherlp** [comment]
Blocked until we know more about what the "IBM Blockchain Platform network template" format is; we should have one format across the whole of IBP if possible

**Comment by heatherlp** [comment]
It might also be neat to have options for generating samples networks, i.e. "the commerical paper network"

Ed said: "It’d be cool to say in the sample “here’s how to add a “commercial_paper” config to your local Fabric config options”" & "So if samples want a specific config, they can tell you what to add to the config file"

**Comment by caroline-church** [comment]
closing as not doing t-shirt sizes anymore
