### ISSUE TITLE
Update wallet for connecting

### ISSUE THREAD

**Issue by caroline-church** [IBM-Blockchain/blockchain-vscode-extension#428]
Currently the extension asks the user for a cert and private key. It does not allow users to use an existing wallet, which means that it's confusing for a user to use with samples such as commercial paper that instructs users to create a wallet. 

Currently the extension uses the in-memory wallet. Under the covers. A proposal would be to change to using a file system wallet. This way a user could point the extension at an existing wallet to use for that connection. 

We would create the wallets on the file system where we keep other data if the user wasn't using their own wallet 

The other advantage is that when developing applications they could point their application at the wallet used in a configuration.

**Comment by caroline-church** [comment]
Proposal is that each connection has a wallet with the identities in for that connection. 

If you only had one wallet for all connections how would you know which identity was for which connection?

**Comment by sstone1** [comment]
@EdMoffatt @Tobias-Hunter @caroline-church the SDK allows you to use a single wallet across multiple gateway connections; IMO we should think about reflecting this in the developer tools as well. With the refocusing on peers rather than "networks", it is more likely that developers will use the same identities to connect to multiple peers.

Maybe the default is "one connection, one wallet" but you can have "two connections, one wallet" if you want to do the above?

**Comment by caroline-church** [comment]
i think when we do the refocusing on the peers we should then do the two connections, one wallet but until then i think we should have one connection one wallet

**Comment by EdMoffatt** [comment]
I think all these suggestions are spot on :)

**Comment by Tobias-Hunter** [comment]
Tried to capture everything that we talked about @heatherlp - once you have a first version of the implementation, if we could go through it that'd be great!

Command palette flows:
<img width="1427" alt="screenshot 2019-01-09 at 10 05 01" src="https://user-images.githubusercontent.com/25635381/50892306-12cfc680-13f6-11e9-8d02-cde6992a7175.png">


Blockchain connections pannel:
<img width="1993" alt="screenshot 2019-01-09 at 09 56 58" src="https://user-images.githubusercontent.com/25635381/50891783-039c4900-13f5-11e9-88db-3aae6afe1b59.png">

Any questions please lemme know! ✌🏻
