### ISSUE TITLE
As a dev I want to specify an optional endorsement policy when I instantiate my smart contract

### ISSUE THREAD

**Issue by heatherlp** [IBM-Blockchain/blockchain-vscode-extension#430]
"enter ur endorsement policy, or leave blank for the default"

**Comment by sstone1** [comment]
@caroline-church @heatherlp this one might be trickier than a text box because the SDK requires the JSON endorsement policy format, and the string endorsement policy format `AND(OR(Org1, Org2))`(something like that anyway) is not supported by the SDK.

**Comment by heatherlp** [comment]
Closing as we're not doing multi-Org local_fabric

**Comment by cazfletch** [comment]
closing as not doing for now
