### ISSUE TITLE
Smart Contract Packaging fails in VSCode Insiders Jan 2019

### ISSUE THREAD

**Issue by geahaad** [IBM-Blockchain/blockchain-vscode-extension#435]
In the most recent release of VSCode Insiders (Version 1.31.0-insider), the command "Package a Smart Contract Project" fails due to incompatible Nodejs versions:

`Failed to load gRPC binary module because it was not installed for the current system Expected directory: node-v64-darwin-x64-unknown Found: [node-v57-darwin-x64-unknown, node-v57-linux-x64-glibc] This problem can often be fixed by running "npm rebuild" on the current system Original error: Cannot find module '/Users/gdinhof/.vscode-insiders/extensions/ibmblockchain.ibm-blockchain-platform-0.1.0/node_modules/grpc/src/node/extension_binary/node-v64-darwin-x64-unknown/grpc_node.node'`

Running VSCode (Version 1.30.1) side-by-side still works.

I assume that the built-in Nodejs version in Electron has been bumped up - but this is just a guess.
Please verify and treat it as a heads-up for a potential upcoming compatibility issue, once the insiders changes get merged into stable.

- macOS Mojave 10.14.2 
- Node v8.15.0
- NPM 5.3
- IBM Blockchain Extension 0.1.0

**Comment by geahaad** [comment]
The initial assumption doesn't stand after some research: Electron is still based on v8, even in it's latest release

**Comment by caroline-church** [comment]
we should have a pr ready to go for this

**Comment by heatherlp** [comment]
Hi @MohammedFadin, we won't be delivering our fix for this until vanilla VSCode updates to electron 3 too, as it's not backwards compaitble and we can't release a version of the extension purely for insiders. We also need Hyperledger Fabric v1.4.1 for this too.

**Comment by caroline-church** [comment]
done so closing

**Comment by wisbech** [comment]
Had this exact problem as well - not a lot of documentation on this issue. Anyways, I found that uninstalling the extension and then removing the extension folder from 
`$ cd /home/[user_name]/.vscode/extension 
$ rm -rf ibmblockchain.ibm-blockchain-platform-0.3.2/`
then  reinstall the extension from vscode did the trick and is now in working order - I believe it came from upgrading vscode and having a legacy version of the extension on the installation.
