### ISSUE TITLE
Connections view - re-orient to Peers

### ISSUE THREAD

**Issue by EdMoffatt** [IBM-Blockchain/blockchain-vscode-extension#437]
Our current connections palette invites users to organise their connections in a "blockchain network up top" view of the world.  With changes to the latest version of Fabric, things are shifting more in a "peers up top" view.  This provides us with an interesting challenge to visualise in a tree-view, as neatly articulated by this mess of whiteboard scrawl from when we tried to think it through:  
![image](https://user-images.githubusercontent.com/7454304/50650923-babe3d80-0f79-11e9-9d7d-59954e067f99.png)

We need to do a design-re-visit of this view and see if we can make it more future-proof as users start to have the same peers participating in multiple "networks".

**Comment by EdMoffatt** [comment]
Note: should look at whether to do anything about the feedback around "connecting" to something taking you "into" that thing (with a back button) in the UI as part of looking at this issue.

**Comment by EdMoffatt** [comment]
Had a first play with this:

![image](https://user-images.githubusercontent.com/7454304/50760994-2dbd0200-1261-11e9-8e89-1de7ecf754ea.png)

I'm wondering about there being _two_ top-level items in the tree view, both of which are buckets to contain other things.  You've got your *local_fabric* and you've got your *gateway peers*.
Needs further work, but I present this first sketch anyhow to see if it sparks further thoughts!

**Comment by EdMoffatt** [comment]
We've agreed an overall strategy for this epic!  We'll be looking to end up with these panels in the Blockchain view...

![image](https://user-images.githubusercontent.com/7454304/51683771-7ce58f80-1fe2-11e9-8a12-41697cbed5a1.png)

i.e. SMART CONTRACT PACKAGES first (unchanged), LOCAL_FABRIC CONTROL PANEL second (designs still in-progress) and FABRIC GATEWAYS at the bottom (designs agreed, need uploading!)

**Comment by heatherlp** [comment]
General stuff for this epic:

- Need dark icons for peer, smart contract etc
- Need to rename each section, orientation is correct

**Comment by heatherlp** [comment]
Closing this out as we've merged the new look 🎉 and we've got an issue for the gifs
