### ISSUE TITLE
Exporting Connection Profile Command doesn't work when connected

### ISSUE THREAD

**Issue by bernarddk** [IBM-Blockchain/blockchain-vscode-extension#440]
When Export Connection Profile is clicked under Blockchain Connecitons nothing happens. Nothing shown in output to indicate why

**Comment by heatherlp** [comment]
We've also found this today, can you confirm it's broken for you when you're connected and therefore looking at the connected view (viewing channels, peers etc)? 
We think this works when you right click on a connection in the disconnected view (viewing list of connections)

**Comment by bernarddk** [comment]
Was looking at the connected view with the fabric network running. Also this is on Ubuntu 16

**Comment by heatherlp** [comment]
Does it work for you when you're not connected?

**Comment by bernarddk** [comment]
Yes works then

**Comment by heatherlp** [comment]
great - thanks for your help!

**Comment by caroline-church** [comment]
done so closing
