### ISSUE TITLE
Extract home directory for file paths in smart contract test files

### ISSUE THREAD

**Issue by DennisM330** [IBM-Blockchain/blockchain-vscode-extension#446]
When generating tests for a smart contract and using the embedded Fabric 1.4 runtime, can we obtain the home directory dynamically and form the full path of the connection profile, certificate path, and private key path as follows?

This is useful in case one wishes to put their VSCode IBM Blockchain Platform smart contract project in Git or some other SCM and when one subsequently clones the project, they do not end up with specific user hardcoded paths in the generated test module. Below works for MacOS. Have not tested for Linux or Windows.

        const homedir = require('os').homedir();
        const connectionProfilePath = homedir + '/' + '.fabric-vscode/local_fabric/connection.json';
        const certificatePath = homedir + '/' + '.fabric-vscode/local_fabric/certificate';
        const privateKeyPath = homedir + '/' + '.fabric-vscode/local_fabric/privateKey';

**Comment by heatherlp** [comment]
I agree :) and I think we should use `path.join` to join those strings together, so that Windows is kept happy
