### ISSUE TITLE
As a user I would like a tutorial to show me debug mode as my first introduction to the extension

### ISSUE THREAD

**Issue by awjh-ibm** [IBM-Blockchain/blockchain-vscode-extension#448]
As a developer when I begin a project I like it build it up from scratch (hello world -> greatness). I would not start with a fabric out of development mode but in it. I would like a tutorial to introduce me to debug mode so that I can understand how to quickly chop and change my application without upgrading constantly.

**Comment by EdMoffatt** [comment]
Reviewing a draft tutorial from @cazfletch , here are my notes so far.
I've reached the step of updating the contract and restarting the debug session, but then I get "Error submitting transaction: Endorsement has failed" when I try to invoke my updated CreateAsset transaction. (It doesn't reach the breakpoint in the first line of the function).

Aaaanyhow, here are my notes up to that point!

---

DEBUG TESTING NOTES

PART 1 STEP 4

Let’s edit out the colloquial language that’s exactly the same as tutorial 1! So maybe…

> The extension will ask you if you want to name the asset in the generated contract. For this tutorial we’ll stick with the default of `MyAsset`.

(I’d be less keen to encourage re-naming it in this one, as we’re having them paste across code that needs editing in multiple places if they change the asset name, so I think it’s easier for folks to trip themselves up!)

PART 2 INTRO  “Now the smart contract has been created we can use the VS Code debug tools. When you debug a smart contract, you run the chaincode, a docker container isn't created.”

I’m not sure this sentence will explain what’s going on sufficiently for most readers! Let’s have a go at it…

> Normal workflow is to package, then install, then instantiate a smart contract. This usual flow results in the smart contract running in a docker container on the peer(s)… But to debug we do things a little differently! We need to create a situation whereby the smart contract is running in the debugger rather than on the peer. Fortunately, this extension makes that easy to do: let’s learn how!

I might have butchered the truth a little there lol

PART 2 STEP 2

Is it worth saying “On the debug panel, make sure “Debug Smart Contract” is selected from the dropdown, then click the __Start Debugging__ icon (it looks like a green triangle). This will start a debug session.”?


PART 3 STEP 1

“Click on the __IBM Blockchain Platform__ icon on the debug toolbar. (it looks like a square and will probably be the button furthest to the right on the toolbar)”

Should we name the icon the same thing the hover-help calls it? I feel there’s probably some accessibility reason that we should do that!

“Click on the __Debug Command List__ icon on the debug toolbar. It’s represented by the IBM Blockchain Platform logo, a white square on a blue circle, and will probably be the furthest-right button on the toolbar.”

PART 3 STEP 2

Should be “Choose `Instantiate Smart Contract` from the list”.

PART 4 STEP 3

“Click on the __IBM Blockchain Platform__ icon on the debug toolbar.” < do you actually need to do this? For me the little debug toolbar is still there whichever view I’m in!

PART 4 STEP 6

Should mention just hitting enter and not providing any transient data. I.e.

> You will be asked to provide arguments for the transaction: try `["002", "a juicy delicious asset”]`. You can hit enter to skip the next question about transient data, as we don’t need any for this transaction.

PART 5 STEP 2

“Update the `createMyAsset` function to have the following code.”

Can we please add an explanation of what that update does? It’s difficult to see what’s changed when you’re pasting code over other code… It looks like we’ve added another argument, and then I assume we do something with it in the function :D

PART 5 STEP 4

I know we cover it _after_ the transaction submission currently, but I think I’d explain the lack of an instantiate step here, for example…
 
> On the debug panel click the __Start Debugging__ icon. The debugger is smart enough to realise that we already instantiated the smart contract we’re working on, and since the contract is actually running in the debugger there’s no need to re-instantiate or upgrade the contract to test out our updated transaction. This is one of the ways in which debugging makes it faster to test out small updates to your code!

**Comment by EdMoffatt** [comment]
PART 6 STEP 5

- Should be “choose `Upgrade Smart Contract`“
- Should mention “no” to private data

PART 7 

This one's not like the others in that it doesn’t _need_ to be followed, it's just "FYI". It could be e.g. “extra info” rather than a numbered PART? Something to try and be clear you’re not supposed to try and follow it to complete the tutorial?? Or labelled as “optional” perhaps?
