### ISSUE TITLE
Samples added to workspace need better names

### ISSUE THREAD

**Issue by sstone1** [IBM-Blockchain/blockchain-vscode-extension#451]
If you use the new sample gallery to import the TypeScript smart contract and TypeScript application for the `fabcar` sample, and choose add to workspace, then you end up with the following workspace:

<img width="1234" alt="screenshot 2019-01-17 at 09 23 18" src="https://user-images.githubusercontent.com/7118158/51308299-b85be900-1a39-11e9-9b68-27c1534b0219.png">

Note the two folders called `typescript`. This is confusing as to which one is which.

The workspace file (`*.code-workspace`) implies that you can provide a different name to the folder name:

```
{
	"folders": [
		{
			"path": "/Users/sstone1/Downloads/fabric-samples/chaincode/fabcar/typescript",
			"name": "typescript"
		},
		{
			"path": "/Users/sstone1/Downloads/fabric-samples/fabcar/typescript",
			"name": "typescript"
		}
	],
	"settings": {}
}
```

Can we allow samples to specify a different name, so the fabcar contract could be imported as `fabcar-contract-typescript`, and the fabcar app could be imported as `fabcar-app-typescript`?

**Comment by Jakeeyturner** [comment]
Done in PR #453
