### ISSUE TITLE
Hard to find the sample view again after you close it

### ISSUE THREAD

**Issue by sstone1** [IBM-Blockchain/blockchain-vscode-extension#454]
I know there's a command, but can we have a button in the UI please?

There is a possible place to put a "general" menu in the IBM Blockchain Platform panel, so maybe there? See this example of a `...` dropdown menu in the extensions panel:

![screenshot 2019-01-17 at 14 15 57](https://user-images.githubusercontent.com/7118158/51324382-814dfd80-1a62-11e9-95dd-f8e998b6ace8.png)

**Comment by caroline-church** [comment]
done so closing
