### ISSUE TITLE
Document scenario where VSCode does not have perms to run npm install

### ISSUE THREAD

**Issue by sstone1** [IBM-Blockchain/blockchain-vscode-extension#462]
Reported by Pam Andrejko:

When the system is configured with Node.js as a global install, you may need to use sudo/root to install npm modules. In this case, VSCode cannot install the generator dependencies required to create a smart contract project. We should document that in this case, the user should additionally install `yo` and `generator-fabric` as part of the *Requirements* section.

**Comment by sstone1** [comment]
@heatherlp I'd say no, sorry 😉 I spoke to @caroline-church about that problem the other day and suggested some alternative approaches to using the npm command, happy to discuss?

**Comment by caroline-church** [comment]
done so closing
