### ISSUE TITLE
As a peer orientated user, I want to view a list of connection profiles and their peer sets in the unconnected view

### ISSUE THREAD

**Issue by heatherlp** [IBM-Blockchain/blockchain-vscode-extension#463]
- convert the existing "Fabric Connections" view to a list of gateway peers per connection profile.
- Should show identities and should have the ability to add and edit connections, and connect via clicking on the gateway peer(s) or identity
- need to fix the "no wallet path set" bug when local_fabric is stopped
- need matching unicode spinners / infinity symbols for the local_fabric peer & useful hover over help as per the designs

Done:
- rename to "Fabric Gateways"

**Comment by EdMoffatt** [comment]
Ok, I _think_ we've got an agreed design for this one!  Please see this PDF on Box (which covers both #463 and #464 ): https://ibm.box.com/s/1pspbsgw3rn97szsldxh3pqy2gbb55nj

**Comment by heatherlp** [comment]
Done! thanks @Jakeeyturner
