### ISSUE TITLE
As a peer orientated user, I want to see the connected view

### ISSUE THREAD

**Issue by heatherlp** [IBM-Blockchain/blockchain-vscode-extension#464]
- Covert existing connected view to be peer orientated
- See Ed's designs when they are finished

**Comment by EdMoffatt** [comment]
Ok, I _think_ we've got an agreed design for this one!  Please see this PDF on Box (which covers both #463 and #464 ): https://ibm.box.com/s/1pspbsgw3rn97szsldxh3pqy2gbb55nj

**Comment by heatherlp** [comment]
Done!
