### ISSUE TITLE
As a peer orientated user, I want a connected/running "local_fabric operations" view 

### ISSUE THREAD

**Issue by heatherlp** [IBM-Blockchain/blockchain-vscode-extension#465]
- Needs:
- sort out the commands needing to connect via the bottom view for commands to work
- upgrade taking the version of instantiated smart contract you've clicked on
- no useful tooltips on instantiated/installed smart contracts
- get rid of @ in instantiated/installed smart contract names, replace with v as per designs

Done:
- mostly done under #509 
- devmode stuff done in #512
- Burger menu and orientation, rename are done

**Comment by EdMoffatt** [comment]
Have a PDF!  I'll also post this up on Slack for reviews :)

https://ibm.box.com/s/592yongp6dvy8bwkzak1s0cpc6w1agq6

**Comment by caroline-church** [comment]
done so closing
