### ISSUE TITLE
If the package.json is open when packaging, the view is modified

### ISSUE THREAD

**Issue by mbwhite** [IBM-Blockchain/blockchain-vscode-extension#473]
I have the package.json open for my contract - to update the version number prior to update.  Keeping this open I package correctly and then click install on the peer.. This completes - but the package.json view changes to show the git changes view .

![](https://files.slack.com/files-pri/T27SFGS2W-FFLL2B5TR/image.png)

**Comment by mbwhite** [comment]
![image](https://user-images.githubusercontent.com/6673453/51540242-dff1ed80-1e4d-11e9-82dc-bc037c7d3e00.png)

**Comment by Jakeeyturner** [comment]
Closing this issue as it cannot be recreated by @mbwhite and myself.
