### ISSUE TITLE
ReadME gif updates for file system wallet and gateway structure

### ISSUE THREAD

**Issue by heatherlp** [IBM-Blockchain/blockchain-vscode-extension#483]
Our gifs are quite out of date, after #475 file system wallet and #437 gateways view being released in v0.3.0. 
One that are definitely incorrect:
- [x] Connect
- [x] Teardown
- [x] Add your own Fabric instance
- [x] Install
- [x] Instantiate
- [x] Submit transaction
- [x] Edit gateway
- [x] Connecting to your own Fabric instance

Ones that are only partially incorrect:
- [x]  create smart contract project (shows the old panel view)
- [x] export package (shows the old panel view)

We might want to review what ones are missing too, like export connection details, open fabric runtime terminal and toggle dev mode

**Comment by caroline-church** [comment]
closing as new readme wont have gifs
