### ISSUE TITLE
New connection created, exit out & unable to edit connection profile & wallet

### ISSUE THREAD

**Issue by Tobias-Hunter** [IBM-Blockchain/blockchain-vscode-extension#497]
As discussed with @heatherlp earlier - there is a lil bug with the behaviour of the new Wallets work! 

Scenario to re-create:
1. Click the `+` to Add connection
2. The command palette opens
3. Name the new connection `porkPie`
4. Exit command palette
5. Click on `Connection Profile` or `Wallet` in the Blockchain Connections panel.
6. This doesn't open the Command palette 😢 

Any questions please lemme know!

**Comment by heatherlp** [comment]
Works for me on v0.2.0 and vscode 1.26.0, but not for Jake and Toby, who are running vscode 1.30.2
Still investigating...

**Comment by heatherlp** [comment]
Fixed by #498
