### ISSUE TITLE
Add to workspace after generating contract duplicate homepage

### ISSUE THREAD

**Issue by Jakeeyturner** [IBM-Blockchain/blockchain-vscode-extension#503]
If the Home page is already open, when generating a smart contract project and adding it to the workspace, a duplicate Home page is opened.

We should only be showing one Home page tab.

---

**Potential Fix**
- Pre-activation, close any Home page tabs (based on the title). Then open a new Home page.

**Comment by Jakeeyturner** [comment]
Currently this issue is being blocked by [a VS Code issue](https://github.com/Microsoft/vscode/issues/15178) which would allow us to easily manage open tabs/editors. Having tried multiple workarounds, we concluded that none of them were suitable enough to implement.

As an alternative, I propose that we disable the automatic Home page opening and instead include an action which opens the Home page manually. By doing this, we will prevent the Home page opening multiple times.

Below are some locations which it is possible to include a button/text which open the Home page.

1. Editor title menu bar
2. Right-click editor context menu
3. Status Bar
4. Collapsible View - Can either create a new collapsible group and add a tree item/icon, or add a new tree item/icon to an existing group.

![screen shot 2019-02-11 at 10 37 57](https://user-images.githubusercontent.com/10009752/52558208-9744a900-2de9-11e9-8367-0c01fda9c594.png)

**Comment by sstone1** [comment]
This is _really_ annoying; moving to sev2. I have an idea for a fix.

**Comment by m-g-k** [comment]
Yeah, I agree it's really annoying and I think you should be able to do what I did with the plantuml file in the composer plugin. Essentially you have a fixed name for your file, and if you open it, it will simply show the same page again. With plantuml I then replaced the contents but if your case you should be able to not bother as the contents does not change?

**Comment by Jakeeyturner** [comment]
> Yeah, I agree it's really annoying and I think you should be able to do what I did with the plantuml file in the composer plugin. Essentially you have a fixed name for your file, and if you open it, it will simply show the same page again. With plantuml I then replaced the contents but if your case you should be able to not bother as the contents does not change?
> 
> From a usability point of view, I would rather we did not disable showing of the page as it's a nice was to show people what we have without making them find a button to click...

Part of the problem is that the webview is not a file, but is actually created given a string (of HTML, JS, CSS, etc), which makes it incredibly difficult to manage as the state isn't persisted.
