### ISSUE TITLE
Correctly determine whether smart contract is open

### ISSUE THREAD

**Issue by mbwhite** [IBM-Blockchain/blockchain-vscode-extension#517]
IIf you start with a vs code workspace, that has a single folder open, the extensions attempts to build this - as it thinks it's a contract.

If this isn't the case, then you can get things 'built' that you really didn't want.

**Comment by heatherlp** [comment]
Matthew suggests we update generator-fabric to add something in the smart contract package.json to indicate it's a smart contract

**Comment by caroline-church** [comment]
We could but what if the contract wasn’t created through the generator?

**Comment by caroline-church** [comment]
closing as no way to tell if its a smart contract project
