### ISSUE TITLE
As a developer I can manage my wallets

### ISSUE THREAD

**Issue by cazfletch** [IBM-Blockchain/blockchain-vscode-extension#524]
Let's use this epic to track the UI changes required for managing wallets, and for discussion on how we link those with gateways.

**Comment by EdMoffatt** [comment]
Did a first sketch for wallets, and got some feedback + questions on Slack - posting it all up here for reference (and to invite further input from GitHub folks!):

![image](https://user-images.githubusercontent.com/7454304/54027895-07e9a600-419b-11e9-9196-dc082ed036d4.png)

**Some of my explanation of my thoughts:**

> What do you think to the idea of adding a “vscode_wallet”?  I’d figured
> 1. It’s there by default, and contains ID(s) for the local_fabric
> 2. Whenever we previously had the option of “filesystem wallet or _not_ filesystem wallet”, it becomes more “provide a specific filesystem wallet, or add it to this generic vscode one that definitely exists”?
> This is because I don’t think showing IDs as children of gateways makes sense anymore, therefore if the user isn’t providing a path to the filesystem wallet, we still need to put them _somewhere_ and show them in the UI so they can be added to, deleted etc.
> 
> I guess the alternative would be that if they don’t provide an explicit filesystem wallet, we create a wallet that is like “gateway_name_wallet”.
> 
> I quite like the idea of being able to add a gateway without specifying a wallet.  I don’t think there’s any actual utility to that, but something about “you make gateways, you make wallets, and for convenience you can associate wallets with gateways” feels logical to me, and having the step of needing to pick/add a wallet when you add a gateway doesn’t quite fit that model

*Caroline:*

> i think it makes sense, as now wallets aren't tied to gateways then calling it local fabric wallet doesn't make sense anymore as you could put extra id's in their that arent local fabric ones

**Heather:**

> regarding initial thoughts, I like what I can see so far :slightly_smiling_face: right now I can only thing of 1) whether we’re going to allow the user to see the wallets in their user settings (like we do for gateways) 2) will “edit wallet” be a thing? or if they want to use a different wallet path, they just need to delete and create a new one?
> 3) this is just rambling thoughts: I might need to treat the in-house local_fabric wallet as a different thing? like we do the local_fabric gateway, because we wouldn’t want to be able to delete it? or in fact, edit the local_fabric wallet path or “disassociate it”. I’ve finished the “create a new identity from a CA” code, which adds a new identity to the local_fabric wallet, which right now can only be removed upon teardown. So I guess I’d need to make sure the local_fabric wallet and gateway are inherently associated, and by tearing down local_fabric, I clear the wallet too? (like we do right now), or we change that behaviour, and allow the user to delete identities

**Comment by EdMoffatt** [comment]
Attaching command palette flows to the Epic (I'll go attach them to related sub-issues too!)

![gateway and wallet command palette key flows](https://user-images.githubusercontent.com/7454304/54036889-a9312600-41b4-11e9-9069-9d8db79fcfa1.png)

**Comment by heatherlp** [comment]
Currently thinking:
- create wallet registry (done in #702 )
- create new wallet panel (#704)
- "Add new wallet" command
- separate link between gateways and wallets (may need to be done alongside above)
- "Associate wallet" command 
- import/export and delete IDs functionality
- Tidy up old command flows

Need to:
- discuss "delete/remove wallet" command, do we want to actually do file system delete?

**Comment by Jakeeyturner** [comment]
Some of the work has been completed for https://github.com/IBM-Blockchain/blockchain-vscode-extension/issues/640. Before this epic is closed, it would be worth checking that that the 'Add Gateway' part of designs in this issue are implemented.

**Comment by cazfletch** [comment]
done so closing
