### ISSUE TITLE
Escape on submit transaction command still submits transaction

### ISSUE THREAD

**Issue by sstone1** [IBM-Blockchain/blockchain-vscode-extension#534]
If you try and submit a transaction, and then escape from the "please enter args" prompt, the transaction is still submitted anyway. We should catch this case and stop executing.

**Comment by Jakeeyturner** [comment]
Not too sure how we'll differentiate between empty arguments being passed (which is valid for an instantiate function) and the user escaping from the prompt. Both of these will return `undefined` for the the prompt. Any ideas @sstone1?

**Comment by sstone1** [comment]
@Jakeeyturner that's not what the doc says:

```
The returned value will be undefined if the input box was canceled (e.g. pressing ESC). Otherwise the returned value will be the string typed by the user or an empty string if the user did not type anything but dismissed the input box with OK.
```

**Comment by Jakeeyturner** [comment]
Ahh, you're right. Just need to be strict with our comparisons!
Thanks @sstone1!
