### ISSUE TITLE
README fails to point out that Edit Connection is not available for local_fabric

### ISSUE THREAD

**Issue by lehors** [IBM-Blockchain/blockchain-vscode-extension#550]
Current section reads: "Connections can be edited by right-clicking and selecting Edit Connection. This will open User Settings, with the connection available for editing."
This fails to say that this is not available for local_fabric.

**Comment by caroline-church** [comment]
@heatherlp can we address this after we have merged in the reorientating around the peer branch please

**Comment by heatherlp** [comment]
Done under #572
