### ISSUE TITLE
Present list of functions in the contract as suggestions on instantiate/upgrade

### ISSUE THREAD

**Issue by awjh-ibm** [IBM-Blockchain/blockchain-vscode-extension#593]
Running the fabric-chaincode-node generate metadata command prior to an instantiate/upgrade would provide inside on possible functions that could be called. These could then be presented to the user so they can select which to call on instantiate/upgrade.

Process:
1. User clicks instantiate for package
2. Contract installed
3. Generate metadata ran for contract to get list of functions
4. User is asked for instantiation function to call and can select from dropdown
5. Continue about their day free from pesky spelling errors

**Comment by Jakeeyturner** [comment]
Labelling this issue as blocked until https://jira.hyperledger.org/browse/FAB-14185 is completed.
When adding `fabric-shim` (1.4.1-snapshot.15) to our optional dependencies, we are hit with gRPC errors. I believe this caused by a conflict of grpc versions in the extension and fabric-shim

**Comment by caroline-church** [comment]
removed blocked as we can get the function names directly we don't need to use the sdk
