### ISSUE TITLE
Ensure home page is easily discoverable again after it is closed

### ISSUE THREAD

**Issue by sstone1** [IBM-Blockchain/blockchain-vscode-extension#599]
PR #590 will change the behaviour of the home page so that it automatically appears just once per version of the extension when you launch VSCode. The reasons for this are detailed in #590.

We need to ensure that the home page is easily discoverable again after it is closed.

**Comment by Jakeeyturner** [comment]
Copied from Issue #503 

> Currently this issue is being blocked by [a VS Code issue](https://github.com/Microsoft/vscode/issues/15178) which would allow us to easily manage open tabs/editors. Having tried multiple workarounds, we concluded that none of them were suitable enough to implement.
> 
> As an alternative, I propose that we disable the automatic Home page opening and instead include an action which opens the Home page manually. By doing this, we will prevent the Home page opening multiple times.
> 
> Below are some locations which it is possible to include a button/text which open the Home page.
> 
> 1. Editor title menu bar
> 2. Right-click editor context menu
> 3. Status Bar
> 4. Collapsible View - Can either create a new collapsible group and add a tree item/icon, or add a new tree item/icon to an existing group.
> 
> ![screen shot 2019-02-11 at 10 37 57](https://user-images.githubusercontent.com/10009752/52558208-9744a900-2de9-11e9-8367-0c01fda9c594.png)

@EdMoffatt would you be able to help with this?

**Comment by EdMoffatt** [comment]
Thanks for the tag :) . Agree with every opinion expressed so far, so I won't chip in too heavily on the discussion.

I think the primary reasons for using the "Getting Started" page right now are:
- Find handy links to samples
- Find handy links to GitHub, StackOverflow, Docs (ok, we need to add the docs link, but...)
- Click the key commands in case you're super new to VSCode and not au-fait with the command palette yet

So, fairly wide-ranging actions, not taken on a particular "thing" or context.
As such, of the options Jake presents above, 2 and 4 seem too "it's an action you're taking on this one specific bit of the screen".
I'm convinced literally nobody ever looks at that blue bar at the bottom, so I'd plump for (1) as our first thing to try personally.

If we could get an IBP icon and the word "Home" up there as a link to re-open it, that would be super-ideal :)
