### ISSUE TITLE
Shrinkwrap support would help drive good practice for node.js chaincode

### ISSUE THREAD

**Issue by davidkel** [IBM-Blockchain/blockchain-vscode-extension#600]
The problem is around guaranteeing the chaincode image across peers. Currently if you deploy a cds image at different times you run the risk of building a chaincode image that differs across peers due to different versions of dependencies being installed. The other problem because of this is you also have no idea of the actual versions of dependencies being used. For example consider a simple package.json dependencies
```
    "dependencies": {
        "fabric-contract-api": "~1.4.0",
        "fabric-shim": "~1.4.0"
    },
```
from this it's not possible to tell what versions of the shim or contract-api were installed in the chaincode image. It's also impossible to tell what dependencies and versions are pulled in.
The package-lock.json file that get's generated is used for development installs only so is ignored by the chaincode image builder. however it will honour shrinkwrap.json. A CDS file ideally should include a shrinkwrap.json file.

The tooling should drive this best practice for node chaincode packaging. A couple of thoughts could be
1. Automatically shrinkwrap at package time
2. Warn the user at package time if no shrinkwrap is present and present the option to shrinkwrap it.

I prefer option 2 as it helps advise the user of a best practice rather than seamlessly hides it from the user.

**Comment by jt-nti** [comment]
Should be covered by package lock and `npm ci`
