### ISSUE TITLE
Merge builds fail on windows

### ISSUE THREAD

**Issue by cazfletch** [IBM-Blockchain/blockchain-vscode-extension#603]
builds work fine on windows for pr's but fail on merge builds and release builds

**Comment by Jakeeyturner** [comment]
I think this is blocked until there is a reasonable solution. I found this thread, so it's a known problem - https://travis-ci.community/t/node-js-build-fails-with-no-obvious-error/961

**Comment by cazfletch** [comment]
closing as we don't run travis build on windows anymore due to other windows issues
