### ISSUE TITLE
Debugger shouldn't need to install/instantiate all the time

### ISSUE THREAD

**Issue by sstone1** [IBM-Blockchain/blockchain-vscode-extension#619]
The debugger currently makes you install/instantiate (or upgrade) every time. This is not actually needed; if the user does not wish to re-run their instantiate function, then the chaincode can be started with a name and version that is already instantiated (as long as it's not already running).

We might need to ask the user what they want to do when they start a debug session.

**Comment by caroline-church** [comment]
closed as duplicate of #703
