### ISSUE TITLE
As a developer I can run all tests

### ISSUE THREAD

**Issue by caroline-church** [IBM-Blockchain/blockchain-vscode-extension#62]
All tests in a test file can be run

**Comment by heatherlp** [comment]
Remember to update the comment at the top of the test file on how to run the tests locally: "...and use the CodeLens features (links above the transaction block) to invoke/submit transactions." for example

**Comment by heatherlp** [comment]
I've already delivered support for running JavaScript tests, and PR #346 covers support for running TypeScript tests
