### ISSUE TITLE
Uninstalling the extension also uninstalls the "JavaScript Test Runner" extension

### ISSUE THREAD

**Issue by SamRasha** [IBM-Blockchain/blockchain-vscode-extension#626]
Uninstalling the IBM Blockchain Extension results in the JavaScript Test Runner dependency being uninstalled too, regardless of whether you had it installed before or after you installed the IBM extension. 
If i already had it installed, i may not want uninstalling the extension to also remove it. 
In addition, say I like the test runner extension after first encountering it through the IBM extension, and don't want it removed when i uninstall the extension, perhaps there should be an option to keep it rather than having to install it again through the extension library.

**Comment by heatherlp** [comment]
@SamRasha I've afraid this is out of our control, see the first comment here: https://github.com/Microsoft/vscode/issues/64436
