### ISSUE TITLE
use an id and secret in vscode to enroll and add identity to wallet

### ISSUE THREAD

**Issue by caroline-church** [IBM-Blockchain/blockchain-vscode-extension#640]
Improve integration with IBPv2 SaaS by allowing a user to enroll (using an ID and secret) when creating a connection, so users do not have to enroll outside of VSCode and then pass VSCode the certificates

**Comment by EdMoffatt** [comment]
![image](https://user-images.githubusercontent.com/7454304/53495577-1d264c80-3a98-11e9-9389-cea9385c45a2.png)

^^ Photo from our design session this afternoon

**Comment by Tobias-Hunter** [comment]
Command prompt .XD file for assistance - [DevTools Wallets TMH v1.zip](https://github.com/IBM-Blockchain/blockchain-vscode-extension/files/2910630/DevTools.Wallets.TMH.v1.zip)

**Comment by EdMoffatt** [comment]
Here's a neater version!  I've been more pedantic about wording etc. on this one.  Involves some tweaks to existing wording too:
![image](https://user-images.githubusercontent.com/7454304/53502556-40f08f00-3aa6-11e9-8526-01630024cac4.png)

**Comment by Jakeeyturner** [comment]
This issue shouldn't be closed until Issue #524 is completed!
