### ISSUE TITLE
sample code gallery

### ISSUE THREAD

**Issue by caroline-church** [IBM-Blockchain/blockchain-vscode-extension#641]
Allow users, business partners, clients, etc to submit sample smart contract and application code to a sample code gallery of some sort, and allow users to easily discover sample code and import it into VSCode

**Comment by EdMoffatt** [comment]
Photos of some whiteboard discussions on this one today!

Needs statements for 2 rough personas (developer using samples, business partner submitting samples):
![image](https://user-images.githubusercontent.com/7454304/53570542-abfd9c80-3b5e-11e9-9b84-59b212589151.png)

Rough flow of sample submission suggested for first MVP deliverable:
![image](https://user-images.githubusercontent.com/7454304/53570595-ce8fb580-3b5e-11e9-828c-392c83622d8d.png)

**Comment by EdMoffatt** [comment]
Neater writeup of those scrawls now on Box here: https://ibm.box.com/s/3ltxs2zjcc2593wzlu0jvhsy3hc9ulkc

**Comment by caroline-church** [comment]
closing as not vscode
