### ISSUE TITLE
As a developer i can see details of events emitted

### ISSUE THREAD

**Issue by cazfletch** [IBM-Blockchain/blockchain-vscode-extension#643]
This could be done via a popup with a button that takes you to the logs to show any data that was emitted in the event

**Comment by EdMoffatt** [comment]
Assigning this one to Charlotte to take a look at! Your tasks:

1) Learn about what Events are, why developers would be using them in their smart contracts (the Fabric docs and our team can help you out here!)
2) Decide how we should let developers know when events are emitted by transactions that they Submit via the VS Code dev tools
3) Attach some mockups to this issue

I'm about to assign another issue too, so when you've got mockups for both of those it'd be good to set up a review meeting with the VS Code squad to look at both sets of designs - we'll sort that out later tho :)

**Comment by Charlotte8699** [comment]
I am looking at incorporating this into the transactions web view. Presently the result of the submitted transaction (event) is being displayed in an independent output for that transaction. 
Mockups will be posted in the issue #1155

**Comment by cazfletch** [comment]
done so closing
