### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by TitusKinyui** [IBM-Blockchain/blockchain-vscode-extension#646]
- Issue Type: `Performance`
- Extension Name: `ibm-blockchain-platform`
- Extension Version: `0.3.0`
- OS Version: `Linux x64 4.15.0-45-generic`
- VSCode version: `1.31.1`

:warning: Make sure to **attach** this file from your *home*-directory: `/home/titus/IBMBlockchain.ibm-blockchain-platform-unresponsive.cpuprofile.txt` :warning:

Find more details here: https://github.com/Microsoft/vscode/wiki/Explain:-extension-causes-high-cpu-load

**Comment by caroline-church** [comment]
@TitusKinyui what were you doing when this happened?

**Comment by TitusKinyui** [comment]
@caroline-church I was trying to launch the IBM hyperledger fabric platform on VSCode but I managed to resolve the problem. Thank you very much for your concern.

**Comment by caroline-church** [comment]
closing as resolved
