### ISSUE TITLE
As a developer i can understand the readme

### ISSUE THREAD

**Issue by cazfletch** [IBM-Blockchain/blockchain-vscode-extension#649]
Review readme and improve it

**Comment by EdProsser** [comment]
Started working on this. :)

**Comment by heatherlp** [comment]
branch is here: https://github.com/heatherlp/blockchain-vscode-extension/tree/newReadMe

Still left to do are:
- section on how to connect the local_fabric to an application by exporting the connection details
- gifs off Sim
- section about go and java smart contracts, including debugging
- homepage and importing samples
- fix line 148
- add import packages
- everything else!
- copy to client/ readme

**Comment by heatherlp** [comment]
Doing this in PR #900 but we've agreed on a much more slimmed down readMe, due to the introduction of tutorials, so it won't cover what's in the list above

**Comment by cazfletch** [comment]
done so closing
