### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by bdampuri** [IBM-Blockchain/blockchain-vscode-extension#655]
- Issue Type: `Performance`
- Extension Name: `ibm-blockchain-platform`
- Extension Version: `0.3.0`
- OS Version: `Windows_NT x64 6.3.9600`
- VSCode version: `1.31.1`

:warning: Make sure to **attach** this file from your *home*-directory: `C:\Users\D.Bharath\IBMBlockchain.ibm-blockchain-platform-unresponsive.cpuprofile.txt` :warning:

Find more details here: https://github.com/Microsoft/vscode/wiki/Explain:-extension-causes-high-cpu-load

**Comment by caroline-church** [comment]
@bdampuri what were you doing when the problem happened?

**Comment by caroline-church** [comment]
closing as no response to question, feel free to reopen
