### ISSUE TITLE
Display the list of files packaged into a cds package file

### ISSUE THREAD

**Issue by davidkel** [IBM-Blockchain/blockchain-vscode-extension#706]
As a suggestion, I think it would be really handy to show the list of files packaged into a CDS file, either at package creation time or via a request to view it.

This would help fine tune the `.npmignore` file to ensure only what is required is packaged and also ensure things like indexes were indeed included.

Example code to retrieve the list of files from a cds file
```
const Pack = require('fabric-client/lib/Package');
const fs = require('fs');
...

const cdsBuffer = fs.readFileSync(cdsFile);
const cdsStruct = await Pack.fromBuffer(cdsBuffer);
// cdsStruct.fileNames contains the array of files which I am assuming are the files in the code_package.
```

**Comment by cazfletch** [comment]
The list of files should be displayed when doing the packaging step in the output log

**Comment by Jakeeyturner** [comment]
PR #840 implements listing the files when calling the 'Package Smart Contract' command.
Perhaps we want to do some work around allowing users to explore .CDS files in the Fabric Packages panel and view the source.
