### ISSUE TITLE
Duplicate "getting smart contract languages" message when creating a smart contract project

### ISSUE THREAD

**Issue by heatherlp** [IBM-Blockchain/blockchain-vscode-extension#712]
## Description
When running through "Create Smart Contract Project" command - you see a status info message for "getting smart contract languages.." and a static one,

## Expected Behavior

 should ideally only see one

## Actual Behavior

see two

## Steps to Reproduce
Run through "Create smart contract project" command

**Comment by caroline-church** [comment]
closing as this was fixed by the issue that changed the way we generate the smart contract project
