### ISSUE TITLE
make the extension work on windows

### ISSUE THREAD

**Issue by caroline-church** [IBM-Blockchain/blockchain-vscode-extension#72]
- [x] Fix grpc problem - need to `add node_modules\grpc\src\node\extension_binary\node-v57-win32-x64-unknown` to package.json
- [x] npm commands need to run in a shell - this can be done with an option on the spawn command
- [x] Fix create smart contract - this currently runs commands in `bin/sh`
- [x] Fix local fabric - this also currently runs commands in `bin/sh`

**Comment by caroline-church** [comment]
moving out of phase 1 as won't get done in time

**Comment by jt-nti** [comment]
Seems like a local fabric environment is going to be more problematic on Windows. Agreed with @caroline-church to disable those features on Windows for now

**Comment by jt-nti** [comment]
Also need to look at pkcs11 module!
