### ISSUE TITLE
After Debug Session AND Restart, a Chaincode container is created

### ISSUE THREAD

**Issue by rthatcher** [IBM-Blockchain/blockchain-vscode-extension#721]
## Scenario
After a debug session I want to shutdown my machine.
- Stop Fabric Runtime
- Exit VSCode
- (shutdown machine)

When I start VSCode and Start Fabric Runtime a Chaincode container is created e.g.
fabricvscodelocalfabric-peer0.org1.example.com-ztz-vscode-debug-201903141148

Should I expect to teardown after a Debug session?
The README does not advise me to teardown.

I have seen this in v0.3.2 and in previous versions.

**Comment by caroline-church** [comment]
this is blocked by #703

**Comment by RiehaB** [comment]
After restarting, having tore down my fabric runtime, I have a container associated with my smart contract created.

**Comment by cazfletch** [comment]
done so closing
