### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by Vishnupriya-M** [IBM-Blockchain/blockchain-vscode-extension#740]
- Issue Type: `Performance`
- Extension Name: `ibm-blockchain-platform`
- Extension Version: `0.3.2`
- OS Version: `Linux x64 4.15.0-29-generic`
- VSCode version: `1.32.1`

:warning: Make sure to **attach** this file from your *home*-directory: `/home/vishnu/IBMBlockchain.ibm-blockchain-platform-unresponsive.cpuprofile.txt` :warning:

Find more details here: https://github.com/Microsoft/vscode/wiki/Explain:-extension-causes-high-cpu-load

**Comment by caroline-church** [comment]
Hi @Vishnupriya-M what were you doing when the problem happened?

**Comment by caroline-church** [comment]
closing as no response

**Comment by Vishnupriya-M** [comment]
@cazfletch I couldn't fix that problem until I tried the same in another laptop.
