### ISSUE TITLE
Generated .npmignore missing auto generated files and directories

### ISSUE THREAD

**Issue by jpayne23** [IBM-Blockchain/blockchain-vscode-extension#743]
## Description
When you package a smart contract through the vscode plugin command, the files that are to be excluded from that package are defined in the file `.npmignore`. If this file doesn't exist then a new `.npmignore` file is created with some standard files and directories listed to ignore.

This generated `.npmignore` file is missing some standard files as well as some which are created as a result of developing using the `Create Smart Contract Project` command which should not be included in the package.

Examples of this include:
- `.editorconfig`
- `.nyc_output`
- `coverage/`

## Expected Behavior
The `Package a Smart Contract Project` should only include the necessary files to run the chaincode on a peer.

## Actual Behavior
Unnecessary files are being packaged up and being stored in the chaincode container. 

## Possible Fix
Include these files by default in the generated `.npmignore` file

## Environment

VSCode plugin version: 0.3.2

**Comment by caroline-church** [comment]
done under https://github.com/IBM-Blockchain/generator-fabric/pull/80 so closing
