### ISSUE TITLE
Missing compiler options in autogenerated tsconfig that are required to invoke a non-default contract

### ISSUE THREAD

**Issue by Th1rstyGiant** [IBM-Blockchain/blockchain-vscode-extension#747]
## Description

The autogenerated `tsconfig.json` file is missing the following compiler options :
`"emitDecoratorMetadata":true` and `"experimentalDecorators": true`

This option is required in order to submit transactions to non-default smart contracts.

Without this option, if you attempt to submit a transaction to a non-default smart contract, the following error is returned even when the correct number of parameters are actually submitted:
```
"message":"Expected 0 parameters, but 1 have been supplied","stack":"Error: Expected 0 parameters, but 1 have been supplied\n    at DataMarshall.handleParameters (/usr/local/src/node_modules/fabric-shim/lib/contract-spi/datamarshall.js:94:19)\n    at ChaincodeFromContract.invokeFunctionality (/usr/local/src/node_modules/fabric-shim/lib/contract-spi/chaincodefromcontract.js:315:49)\n    at ChaincodeFromContract.Invoke (/usr/local/src/node_modules/fabric-shim/lib/contract-spi/chaincodefromcontract.js:278:21)\n    at handleMessage (/usr/local/src/node_modules/fabric-shim/lib/handler.js:614:47)\n    at ChaincodeSupportClient.handleTransaction (/usr/local/src/node_modules/fabric-shim/lib/handler.js:356:9)\n    at ClientDuplexStream.<anonymous> (/usr/local/src/node_modules/fabric-shim/lib/handler.js:296:30)\n    at emitOne (events.js:116:13)\n    at ClientDuplexStream.emit (events.js:211:7)\n    at addChunk (_stream_readable.js:263:12)\n    at readableAddChunk (_stream_readable.js:250:11)"}
2019-03-21T11:56:05.987Z ERROR [lib/handler.js] [mychannel-5553bae8]Calling chaincode Invoke() returned error response [Error: Expected 0 parameters, but 1 have been supplied]. Sending ERROR message back to peer 
instantiate function called
```

## Expected Behaviour
Be able to submit transactions to non-default contracts without having to amend the `tsconfig.json` that is generated for you. Although it's trivial to do manually, it's not clear that these compiler options are required and the error message gives no hints as to what the issue is. 

## Actual Behaviour
submitTransaction returns the following error:
`Expected 0 parameters, but 1 have been supplied"`

## Possible Fix
Add the following lines to the `tsconfig.json` file that is autogenerated by the `IBM Blockchain Platform: Create Smart Contract` tool:
```
"experimentalDecorators": true,
"emitDecoratorMetadata": true
```

## Steps to Reproduce
1. Create a new Typescript smart contract using the VSCode plugin
2. Create a new contract with a simple function that takes in a number of arguments
3. Use the plugin to Generate Smart Contract tests
4. Update the tests for your newly created contract so that the correct args are submitted to the transaction (by default `args` is an empty array)
5. Run the functional test for this contract.

## Existing issues
None found

## Logs
See error message in description

## Your Environment
* IBM Blockchain Platform Extension Version:  0.3.2
* Visual Studio Code version: 1.32.3

**Comment by caroline-church** [comment]
There is a pull request open that will fix this in the generator repository https://github.com/IBM-Blockchain/generator-fabric/pull/56

**Comment by caroline-church** [comment]
closing as done in above pr
