### ISSUE TITLE
Autogenerated smart contract tests for non-default contracts fail

### ISSUE THREAD

**Issue by Th1rstyGiant** [IBM-Blockchain/blockchain-vscode-extension#748]
## Description
The autogenerated smart contract tests do not specify which contract to get in the `network.getContract()` call that happens as part of `submitTransaction()`.

This means that any attempts to call a method on a non-default contract are routed to the default contract opposed to the intended contract and thus the following error is returned.
```
Error: You've asked to invoke a function that does not exist: <function_name>
```

## Expected Behaviour
Autogenerated smart contract tests should pass out of the box.

## Actual Behaviour
The autogenerated functional test for the non-default contract fails with the following error:
```
  NewContract-tmp@0.0.1
2019-03-21T17:07:33.544Z - warn: [Transaction]: _validatePeerResponses: Received error response from peer: message=transaction returned with failure: Error: You've asked to invoke a function that does not exist: sum, stack=Error: transaction returned with failure: Error: You've asked to invoke a function that does not exist: sum
    at self._endorserClient.processProposal (/Users/jvines@uk.ibm.com/tmp/node_modules/fabric-network/node_modules/fabric-client/lib/Peer.js:140:36)
    at Object.onReceiveStatus (/Users/jvines@uk.ibm.com/tmp/node_modules/fabric-network/node_modules/grpc/src/client_interceptors.js:1191:9)
    at InterceptingListener._callNext (/Users/jvines@uk.ibm.com/tmp/node_modules/fabric-network/node_modules/grpc/src/client_interceptors.js:564:42)
    at InterceptingListener.onReceiveStatus (/Users/jvines@uk.ibm.com/tmp/node_modules/fabric-network/node_modules/grpc/src/client_interceptors.js:614:8)
    at callback (/Users/jvines@uk.ibm.com/tmp/node_modules/fabric-network/node_modules/grpc/src/client_interceptors.js:841:24), status=500, , url=grpc://localhost:17051, name=peer0.org1.example.com, name=peer0.org1.example.com, request-timeout=300000, grpc.max_receive_message_length=-1, grpc.max_send_message_length=-1, isProposalResponse=true
2019-03-21T17:07:33.547Z - error: [Transaction]: _validatePeerResponses: No valid responses from any peers. 1 peer error responses:
    transaction returned with failure: Error: You've asked to invoke a function that does not exist: sum
```

(sum is the name of the function we created on a new contract called `NewContract`)

## Possible Fix
The `submitTransaction()` function that is defined in the autogenerated functional tests should specify the contract name when getting the contract from the network, ie:

```
        const contract: fabricNetwork.Contract = await network.getContract(
           '<chaincode_name>',
           '<contract_name>'
        );
```
opposed to:
```
        const contract: fabricNetwork.Contract = await network.getContract(
           '<chaincode_name>'
        );
```

## Steps to Reproduce

1. Create a new Typescript smart contract using the plugin
2. Create a new contract and add a simple function that takes a couple of arguments
3. Add this contract to the end of the contracts Array in `index.ts` and import/export it.
4. Package up the smart contract and install/instantiate it on the local network using the plugin.
5. Run `IBM Blockchain Platform: Generate Smart Contract Tests`
6. Run the tests

## Existing issues
None found.

## Your Environment
* IBM Blockchain Platform Extension Version: 0.3.2
* Visual Studio Code version: 1.32.3

**Comment by biksen** [comment]
Hello, I am not sure whether this is related with this issue or not. I am new to IBM Blockchain Platform VSCode Extension and using IBM Blockchain Platform Extension Version: 0.3.2 and Visual Studio Code version: 1.32.3. First time I followed the following steps: 1. Under FABRIC GATEWAYS and under Channels expand mychannel, and right-click on my latest smart contract demoContract@0.0.2 and then selected Generate Smart Contract Tests.

2. The extension asked me which language to generate the test files in. Chosen JavaScript.

3. Once the extension is done generating the tests, it created a test folder under that it created a test js file. But when clicked on the run test button from the VSCode UI from the MyContract-demoContract@0.0.2.test.js file, it was showing "no test runner in your project. please install one". Then I hard deleted the test folder from my workspace and trying to generate test js file again. This time nothing is generating and VSCode console is not showing anything. Please help me. Thanks.

**Comment by heatherlp** [comment]
Hi @biksen, this sounds like a different issue. Have you got the "JavaScript Test Runner" extension also installed? It should come installed with this extension too. Might be worth reloading/quitting vscode to help troubleshoot the second issue of no tests being generated

**Comment by biksen** [comment]
Hi @heatherlp, I double cross checked that "JavaScript Test Runner" is already installed and enabled. I tried multiple times reloading/quitting vscode. I am running default local_fabric instance. Even I tried restarted local_fabric instance multiple times. But no luck :(.

> Hi @biksen, this sounds like a different issue. Have you got the "JavaScript Test Runner" extension also installed? It should come installed with this extension too. Might be worth reloading/quitting vscode to help troubleshoot the second issue of no tests being generated

**Comment by heatherlp** [comment]
> Hi @heatherlp, I double cross checked that "JavaScript Test Runner" is already installed and enabled. I tried multiple times reloading/quitting vscode. I am running default local_fabric instance. Even I tried restarted local_fabric instance multiple times. But no luck :(.
> 
> > Hi @biksen, this sounds like a different issue. Have you got the "JavaScript Test Runner" extension also installed? It should come installed with this extension too. Might be worth reloading/quitting vscode to help troubleshoot the second issue of no tests being generated

Can you raise a different issue please :)?

**Comment by cazfletch** [comment]
this is already fixed, i just generated some tests and i can see the name of the contract in the submit transaction function

```
async function submitTransaction(functionName: string, args: string[]): Promise<Buffer> {
        // Submit transaction

        const network: fabricNetwork.Network = await gateway.getNetwork('mychannel');
        const contract: fabricNetwork.Contract = await network.getContract('typeScriptSmartContract');

        const responseBuffer: Buffer = await contract.submitTransaction(functionName, ...args);
        return responseBuffer;
    }
```

**Comment by cazfletch** [comment]
Reopened as this was fixed for javascript but not typescript

**Comment by cazfletch** [comment]
done so closing
