### ISSUE TITLE
User preferences shouldn't be overwritten by tests

### ISSUE THREAD

**Issue by Jakeeyturner** [IBM-Blockchain/blockchain-vscode-extension#75]
In the SetupTests function, user preferences should be stored before the tests start, then restored after each lot of tests.

**Comment by heatherlp** [comment]
Submitted pull request #106 but with caveats:


- can't store/restore empty user settings, with the exception of the package.directory setting. We think that's to do with vscode/typescript/json handling an empty object
- local_fabric connection is added to fabric.connections and fabric.runtimes by some tests, but doesn't overwrite any existing settings
- integration.test.ts performs similarly, user settings are added to and not wiped. It's not possible to remove these changes at the end of the test.
