### ISSUE TITLE
Improve usability of add connection with enroll ID and secret 

### ISSUE THREAD

**Issue by sstone1** [IBM-Blockchain/blockchain-vscode-extension#755]
The add connection command with an enroll ID and secret asks the following questions:

- What is the identity name?
- What is the MSP ID?
- What is the enrolment ID?
- What is the enrolment secret?

Identity name in a lot of cases may just be the same as the enrolment ID, for example "admin". In which case I end up answering: admin, Org1MSP, admin, adminpw

We could also default the identity name when a certificate is provided, by extracting the common name (CN) from the certificate itself.

@EdMoffatt had some ideas around this

**Comment by heatherlp** [comment]
This action will be on a wallet when #524 is in. When I was discussing this with @EdMoffatt, we were also saying that we need to look at the language used for when we ask for known things (i.e. like MSPID) and made up things (like identity name)

**Comment by Jakeeyturner** [comment]
Currently when importing a JSON identity file, it asks you for the name and MSP ID.
However, as the name is already in the JSON file - there probably isn't a need to ask for the user for a name.

We should move the "where do you want to add an identity from” question to be the first action. If the user wants to add an identity from a JSON identity file, it will grab the name from the JSON file.
If the user selects ones of the other options, we should probably ask for a name at that point.
