### ISSUE TITLE
As a developer, I can associate a wallet with a gateway

### ISSUE THREAD

**Issue by heatherlp** [IBM-Blockchain/blockchain-vscode-extension#758]
Via a new command
- This also needs to address the `local_wallet` name hardcoded-ness everywhere 
- Needs to address inherent association between `local_fabric` and `local_wallet`
- `local_wallet` should be allowed to also associate with other gateways (but not dissociate from `local_fabric`
- `admin@blah` should be deleted when `local_fabric` is torn down, but the whole wallet shouldn't be deleted
- `adamin@blah` needs an icon - to show the user it's associated with `local_fabric`
- tool tips for when associated, to match designs in #524 
- Disable deleting `admin@blah` - to close off #690

**Comment by cazfletch** [comment]
done so closing
