### ISSUE TITLE
Creating auto Generated Smart Contract Tests for new contracts forces you to overwrite existing functional tests for other contracts

### ISSUE THREAD

**Issue by Th1rstyGiant** [IBM-Blockchain/blockchain-vscode-extension#760]
## Description
When attempting to create new auto generated smart contract tests for a newly created contract, after already generating tests for previous contracts, the plugin forces you to either overwrite your pre-existing functional tests in order for tests to be created for the new contract.

This is a problem because we add additional assertions and test functionality to the generated tests. Overwriting the tests causes us to lose these changes.

## Expected Behaviour
The generate Smart Contract Tests command should provide a mechanism by which to choose which smart contracts to generate a new test for.

## Actual Behaviour
You are asked if you want to overwrite your pre-existing tests, choosing no results in no new tests being generated for newly created contracts that do not have a test already generated.

## Possible Fix
The generate Smart Contract Test command should check on an individual contract basis to see which contracts have tests already in the `functionalTests` dir based on their names.
This will allow the command to generate the tests for contracts with no tests detected whilst giving the user the option to over write pre-existing tests if they so desire.

## Steps to Reproduce
1. Generate a smart contract project
2. Generate Smart Contract Tests
3. Create a new contract
4. Generate Smart Contract Tests
5. Select no to over write
6. No smart contract tests for the new contract will have been created

## Existing issues
None

## Your Environment
* IBM Blockchain Platform Extension Version: 0.3.2
* Visual Studio Code version: 1.32.3

**Comment by cazfletch** [comment]
The fix for this should be that when you have multiple contracts move the generate tests option to a specific contract so that you can just generate tests for that contract
