### ISSUE TITLE
Cannot delete multiple smart contract packages at the same time

### ISSUE THREAD

**Issue by Th1rstyGiant** [IBM-Blockchain/blockchain-vscode-extension#761]
## Description
Cannot delete more than one smart contract package at a time using the plugin. Whilst this isn't a big problem, it is rather annoying when you have lots of packages from testing on your local network and would improve the user experience.

## Expected Behavior
Be able to select multiple smart contract packages for deletion in a single action.

## Actual Behavior
You have to right click on each package individually and select delete package.
Currently to delete multiple packages in one go, you need to navigate to the hidden ./fabric-vscode directory and delete them outside of VSCode.

## Possible Fix
-

## Steps to Reproduce
1. create lots of packages
2. attempt to delete more than one

## Existing issues
none found

## Your Environment
* IBM Blockchain Platform Extension Version: 1.32.3
* Visual Studio Code version: 0.3.2

**Comment by caroline-church** [comment]
If you run the command then you can delete multiple at once but right clicking them in the package view it is not possible to implement this as it is a limitation of vscode.
