### ISSUE TITLE
Welcome page updates part 2

### ISSUE THREAD

**Issue by EdMoffatt** [IBM-Blockchain/blockchain-vscode-extension#772]

**Comment by EdMoffatt** [comment]
Very rough mockup:

![image](https://user-images.githubusercontent.com/7454304/55072723-c191b380-5083-11e9-9648-73d5c602d495.png)

(Basically, the tutorial button now links to the gallery, and display of individual samples is replaced with a button that links off to that gallery)

**Comment by Jakeeyturner** [comment]
Closing, as the only uncompleted bit of work is #834.
