### ISSUE TITLE
Investigate linking tutorial completion to badges

### ISSUE THREAD

**Issue by EdMoffatt** [IBM-Blockchain/blockchain-vscode-extension#775]
Wouldn't it be cool if completing a set of tutorials in the IBM Blockchain Platform developer tools could earn you, like, an "IBM Blockchain Developer" badge / qualification or something??
This issue is to cover investigating whether that's even possible and figuring out how we might do it.

No sizing yet, because establishing the sizing is kinda the first bit of work ;)

**Comment by cazfletch** [comment]
closing as not doing anytime soon
