### ISSUE TITLE
As a developer, I can use service discovery with the local Fabric

### ISSUE THREAD

**Issue by sstone1** [IBM-Blockchain/blockchain-vscode-extension#776]
The local Fabric currently does not enable you to use service discovery. This is because the peer does not currently have an external endpoint address set, and the orderer address in the channel configuration block does not work outside of the Docker network.

This is _okay_, but it means that any sample applications run inside VSCode cannot be configured to use service discovery, and this means that developers must write different code to toggle service discovery on or off depending on if they are using the local Fabric or trying to interact with the SaaS.

Our desire is to see all applications running with service discovery, so we should really be demonstrating this out of the box from the start with the local Fabric working with the samples, and allow you to use those exactly same samples with the SaaS.

**Comment by heatherlp** [comment]
@sstone1 is this done?
