### ISSUE TITLE
debugger question

### ISSUE THREAD

**Issue by Moni-Haimovich** [IBM-Blockchain/blockchain-vscode-extension#777]
I followed the instructions on how to debug a smart contract.
Every thing works fine but when I click the play button (to start deploy and debug) the debugger disconnects and it doesn't listen any more:

Debugger attached.
Waiting for the debugger to disconnect...

So when I send a transaction - the breakpoints are not avalible

**Comment by caroline-church** [comment]
Hi @Moni-Haimovich can you elaborate abit more on the steps you went through please? Which steps worked fine?

**Comment by Moni-Haimovich** [comment]
I followed the steps blelow:
I went through 1-6. In step 5 when I click the 'play' button - the contract starts running and runs okay from start to end and the debugger disconnects. So when doing step 7 the debugger is already disconnected and doesn't stop in the break points


    1. Ensure you are connected to the local_fabric runtime and that the local_fabric peer is in development mode. Development mode is indicated by an infinity symbol on a peer, under Nodes in the Local Fabric Ops panel. To toggle development mode, right-click the peer and select Toggle Development Mode.
    2. Open your smart contract project in your workspace.
    3. Open the debug view in Visual Studio Code using the left-hand navigation bar.
    4. Select the Debug Smart Contract configuration by using the dropdown in the upper-left.
    5. Package and install the smart contract by clicking the play button.
    6. Add breakpoints to the smart contract by clicking on the relevant line numbers in your smart contract files.
    7. Click Instantiate in the Local Fabric Ops panel. In the Fabric Gateways panel, you can now right click on transactions to submit them, execution will be paused on any breakpoints you've defined.
    8. To submit or evaluate a transaction click the blockchain icon on the debug toolbar.

**Comment by caroline-church** [comment]
@Moni-Haimovich Is the smart contract packaged and installed i.e. do you see an installed smart contract call <contract-name>@vscode-debug-<time-stamp>?

Can you also show me what your launch.json looks like that is in the smart contract project under the `.vscode` folder

**Comment by Moni-Haimovich** [comment]
yes I can see the contract installed.
This is how my launch.json looks:

{ 
    "version": "0.2.0",
    "configurations": [
        {
            "type": "fabric:node",
            "request": "launch",
            "name": "Debug Smart Contract",
            "program": "${workspaceFolder}/index.js"
        }
       
      
    ]
}

**Comment by cazfletch** [comment]
Are you using a typescript smart contract or javascript smart contract?

**Comment by Moni-Haimovich** [comment]
JavaScript

בתאריך יום ו׳, 29 במרץ 2019, 16:11, מאת Caroline Fletcher ‏<
notifications@github.com>:

**Comment by edisinovcic** [comment]
Same problem here, transactions get evaluated and are not stopped on breakpoints.

I'm using vscode on ubuntu, could that be a problem?

**Comment by edisinovcic** [comment]
@Moni-Haimovich my problem was with different node versions. In debug mode mark uncaught exceptions too so you can check why debug fails. Ping me if you need more help. ;)

**Comment by cazfletch** [comment]
Hi @Moni-Haimovich are you still having an issue with this?

**Comment by Richard-YAN** [comment]
Hi @cazfletch, when I debugging Golang Smart Contract, the process could be stopped at the break points within Init function and main function, but the process couldn't be stopped at Invoke function, is there any setting I need to put in the launch.json file or some other things I missed. Thanks!

**Comment by Richard-YAN** [comment]
Hi @cazfletch, I managed to use it for debugging Golang smart contract. Now the new concern is the endorsement would timeout if the debugging process takes too much time.  Is it possible to remove the timeout under debugging mode? Thanks!

**Comment by cazfletch** [comment]
Hi @Richard-YAN yes there is already an issue for the #953

**Comment by cazfletch** [comment]
closing as no response

**Comment by kmadenski** [comment]
Hi. Got this problem on node 10.20
On 8.17 everything works good. 
On 10.20 have "Waiting for the debugger to disconnect..." and cant work.
