### ISSUE TITLE
An app dev can use a test file generated by another dev

### ISSUE THREAD

**Issue by EdMoffatt** [IBM-Blockchain/blockchain-vscode-extension#78]
Should test we can do the following scenario:

1. Dev1 installs and instantiates a smart contract package
2. Dev1 generates a test file from the instantiated package
3. Dev1 sends the test file to Dev2
4. Dev2 edits the file to replace the credentials with their own
5. Dev2 runs the tests

**Comment by caroline-church** [comment]
closing as not planning to do this anytime soon
