### ISSUE TITLE
Failed to package smart contract project: FabCar

### ISSUE THREAD

**Issue by jenil04** [IBM-Blockchain/blockchain-vscode-extension#798]
Error: "Failed to determine language type, supported languages are JavaScript, Go, TypeScript and Java"

Code repository: https://github.com/IBM/fabcar-blockchain-sample#2-package-the-smart-contract

**Comment by Jakeeyturner** [comment]
Hi @jenil04,

Have you opened the contract at its root level?

**Comment by cazfletch** [comment]
no response so closing
