### ISSUE TITLE
Tutorial Tiles: Initial tutorial gallery page

### ISSUE THREAD

**Issue by EdMoffatt** [IBM-Blockchain/blockchain-vscode-extension#810]
Show a list of all the tutorials

First implementation of tiles for the tutorial page should include:

- Tutorial #
- Title
- Succinct description
- "Based on" URL
- Metadata (estimated completion time, difficulty level)

**Comment by Jakeeyturner** [comment]
Although we have a PR (#888) for this, we should probably only close this issue once all of the tutorial content has been placed inside the gallery!

**Comment by cazfletch** [comment]
closing as covered by #812

**Comment by cazfletch** [comment]
oops pr not gone in yet so reopening
