### ISSUE TITLE
Tutorials Side Panel: initial tutorial content

### ISSUE THREAD

**Issue by EdMoffatt** [IBM-Blockchain/blockchain-vscode-extension#812]
To get the first set of tutorials in, we need:

- Markdown file for each tutorial
- Metadata for each tutorial
- "Next step" at the end of each (as part of the markdown)

Suggested initial set:

1) Intro to IBM Blockchain Platform - [ ] Created - [ ] In gallery
2) Local development workflow - [ ] Created - [ ] In gallery
3) FabCar sample - [ ] Created - [ ] In gallery
4) Getting IBP SaaS - [ ] Created - [ ] In gallery
5) Configuring SaaS for dev use - [ ] Created - [ ] In gallery
6) Installing + Instantiating to SaaS - [ ] Created - [ ] In gallery
7) Creating a Gateway to your SaaS peer(s) - [ ] Created - [ ] In gallery

**Comment by cazfletch** [comment]
done so closing
