### ISSUE TITLE
Telemetry updates

### ISSUE THREAD

**Issue by EdMoffatt** [IBM-Blockchain/blockchain-vscode-extension#814]
To help understand how people are using the extensions newer features, let's make some telemetry updates!

- Track when a tutorial is opened (get an idea of how popular they are, which ones are most used etc.)
- Track when someone navigates to the IBP SaaS signup via the extension (helps us understand how many SaaS users come from the dev tools)
- Track gateways created that are for IBP networks
- Agree the list of command-palette commands that we want to count instances of

Note, none of this data will be personally identifiable, we're not tracking anything for specific users, just a global count of how many times a particular thing is done by _any_ user.

**Comment by cazfletch** [comment]
This is the complete list of telemetry events we should have

- [ ] Add gateway
- [ ] Add identity to wallet - are they adding certificates or using enrolment id and secret
- [ ] Connect via gateway - should be able to tell if IBP v2 network see issue #674 
- [ ] Create Smart contract project - which language and old/new style smart contracts
- [ ] Create identity (register and enrol)
- [ ] Debug - which language
- [ ] Export connection profile - local, ibp or other
- [ ] Export wallet (when this is implemented)
- [ ] Export package
- [ ] Import package
- [ ] Instantiate smart contract
- [ ] Open fabric runtime terminal
- [ ] Package smart contract
- [ ] Submit transaction
- [ ] Evaluate transaction
- [ ] Upgrade smart contract
- [ ] View sample
- [ ] Clone sample
- [ ] Open sample
- [ ] View tutorial
- [ ] Completed tutorial (when implemented)
- [ ] Steps user gets to in tutorial (when implemented)
- [ ] Clicking to next tutorial (when implemented)
- [ ] Click links to ICP or SaaS

**Comment by heatherlp** [comment]
#883 addresses the majority of these, but we're still missing some, so removing the GA tags and unassigning Sam for now. Let's use this issue to track the remaining items on the list

**Comment by cazfletch** [comment]
closing as the remaining items relate to tutorial improvements that are not yet planned
