### ISSUE TITLE
Extension hangs on file conflict when creating duplicate smart contract project

### ISSUE THREAD

**Issue by Jakeeyturner** [IBM-Blockchain/blockchain-vscode-extension#82]
When creating a new smart contract project, if an existing project exists in the same directory, then the VSCode extension hangs. This is due to yeoman generator detecting conflicting files (with the same name) and asking the user how to handle the conflict. At the moment the VSCode extension can't handle the Yeoman file conflict process.

This can be prevented by creating a custom Yeoman Conflicter which spits out the conflict options through the VSCode extension to the user. The user could then select a option on how to resolve the file conflicts, which passes the result back through to the generator.

**Comment by Jakeeyturner** [comment]
This issue is related to https://github.com/sstone1/generator-fabric/issues/20

**Comment by caroline-church** [comment]
done so closing

**Comment by caroline-church** [comment]
https://github.com/IBM-Blockchain/blockchain-vscode-extension/pull/107
