### ISSUE TITLE
Package Registry doesn't error if package.json doesn't contain a version

### ISSUE THREAD

**Issue by heatherlp** [IBM-Blockchain/blockchain-vscode-extension#83]
We should throw an error to the user if their smart contract package doesn't contain a version string (See TODO in PackageRegistry.ts) because we'll need it's version to install it on a peer. 

Test directory: /blockchain-vscode-extension/client/test/data/smartContractDir/typescript/smartContractPackageYellow contains a package.json without a version string for this purpose. So this needs moving or something needs stubbing out in the other tests once this codes been updated. 

This probably won't be needed once we've got proper packaging.

**Comment by caroline-church** [comment]
done so closing
