### ISSUE TITLE
Offline Chaincode unit test using stub mocking (re-open)

### ISSUE THREAD

**Issue by netanyahuyasser** [IBM-Blockchain/blockchain-vscode-extension#838]
## Description
I would like to perform unit testing of my chaincode offline (i.e. not within the docker container) using the code as follows:
```typescript
import { Context } from 'fabric-contract-api';
import { ChaincodeStub, ClientIdentity } from 'fabric-shim';
import { MyContract } from '.';

import * as chai from 'chai';
import * as sinon from 'sinon';
import * as sinonChai from 'sinon-chai';

chai.should();
chai.use(sinonChai);

class TestContext implements Context {
  public stub: ChaincodeStub = sinon.createStubInstance(ChaincodeStub);
  public clientIdentity: ClientIdentity = sinon.createStubInstance(ClientIdentity);
}

describe('MyContract', () => {
  
  describe('#instantiate', () => {
    
    it('should work', async () => {
      const contract = new MyContract();
      const ctx = new TestContext();
      (ctx.stub as sinon.SinonStubbedInstance<ChaincodeStub>)
        .getFunctionAndParameters
        .returns({
          fcn: 'initFunc',
          params: [],
        })
      ;
      const res = await contract.instantiate(ctx);
      res.status.should.equal(ChaincodeStub.RESPONSE_CODE.OK); // trying to console.log(res) returns undefined
      // trying to console.log(ctx.stub) here also returns empty TestContext object 
    });

  });

});`
```

## Expected Behavior
When running the ```npm run test```, it should perform the unit test without any problems:
1. ```ctx.stub``` should not be undefined.
2. ```res.status``` should not be undefined.

## Actual Behavior
Unit test fails:
1. ```ctx.stub``` undefined.
2. ```res.status``` undefined.

The problem is not lies within the logic to put (any) object within the stub. I already confirm it by console.logging the actual object (in the ```contract.instantiate``` function) before putting it in the stub. 

## Possible Fix
1. Make offline chaincode unit testing possible. 

## Steps to Reproduce
1. Using the source code above as the test script.
2. Issue ```npm run test``` on the terminal.

## Existing issues
- [Offline Chaincode unit test using stub mocking](https://github.com/IBM-Blockchain/blockchain-vscode-extension/issues/606)

**Comment by cazfletch** [comment]
closing as this will be fixed in 0.4.0
