### ISSUE TITLE
Trouble starting fabric up

### ISSUE THREAD

**Issue by Stewthebosshog** [IBM-Blockchain/blockchain-vscode-extension#848]
$ ./startFabric.sh
### Development only script for Hyperledger Fabric control

> Running'startFabric.sh'
> FABRIC_VERSION is set to 'hlfv12'
> FABRIC_START_TIMEOUT is unset, assuming 15 (seconds)
### get:
.IOError: [Errno 2] No such file or directory: '/cygdrive/c/Users/fabric-tools/fabric-scripts/hlfv12/composer/docker-compose.yml'

I don't know why this is happening. The file should be in there, is this a configuration issue?

**Comment by cazfletch** [comment]
Hi @Stewthebosshog that error looks like its not from the vscode extension but from the fabric-dev-server scripts that were used by hyperledger composer.
