### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by Casper0513** [IBM-Blockchain/blockchain-vscode-extension#859]
- Issue Type: `Performance`
- Extension Name: `ibm-blockchain-platform`
- Extension Version: `0.3.3`
- OS Version: `Linux x64 4.15.0-48-generic`
- VSCode version: `1.33.1`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`/home/casper8219/IBMBlockchain.ibm-blockchain-platform-unresponsive.cpuprofile.txt`

Find more details here: https://github.com/Microsoft/vscode/wiki/Explain:-extension-causes-high-cpu-load

**Comment by cazfletch** [comment]
Hi @Casper0513 what were you doing when this occured?

**Comment by cazfletch** [comment]
no response so closing
