### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by douglascavanaugh** [IBM-Blockchain/blockchain-vscode-extension#860]
- Issue Type: `Performance`
- Extension Name: `ibm-blockchain-platform`
- Extension Version: `0.3.3`
- OS Version: `Darwin x64 18.5.0`
- VSCode version: `1.33.1`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`/Users/apple/IBMBlockchain.ibm-blockchain-platform-unresponsive.cpuprofile.txt`

Find more details here: https://github.com/Microsoft/vscode/wiki/Explain:-extension-causes-high-cpu-load

**Comment by cazfletch** [comment]
Hi @douglascavanaugh what were you doing when this occurred?

**Comment by douglascavanaugh** [comment]
Attempting to "Package a Smart Contract Project"

**Comment by douglascavanaugh** [comment]
System: macOS Mojave 10.14.4, VS Code 1.33.1, IBM Blockchain Platform Extension 0.3.3, and the latest Blockchain Fabric 1.4.

**Comment by cazfletch** [comment]
would the packaged smart contract result in a large file size, for example do you have images and other data in your project?

**Comment by cazfletch** [comment]
no response so closing
