### ISSUE TITLE
Guidance on the following topics would be very useful

### ISSUE THREAD

**Issue by davidkel** [IBM-Blockchain/blockchain-vscode-extension#861]
These are suggestions for tutorials/documentation as they are common use cases (maybe not so common for java). More items may be added in the future.

1. How to import an existing chaincode project into the extension, should cover at least Go, Javascript/Typescript
2. How to debug Go and Java chaincode

**Comment by heatherlp** [comment]
Hoping a future debugging tutorial can provide more information on this

**Comment by EdMoffatt** [comment]
Excellent suggestions :) I do think some kind of "local dev masterclass" topic/set might be good next:?

**Comment by cazfletch** [comment]
We should add a section into the readme for using the extension with a non generated contract.

**Comment by cazfletch** [comment]
closing as duplicate
