### ISSUE TITLE
"No identities found in wallet: local_fabric_wallet" when clicking on local_fabric

### ISSUE THREAD

**Issue by heatherlp** [IBM-Blockchain/blockchain-vscode-extension#862]
## Description

Under the changes in #847, we no longer start local_fabric if it's stopped, when the user clicks on local_fabric in the gateways view. But now we see a "No identities found in wallet: local_fabric_wallet" error when we do. I don't think it's clear to user that they need to start local_fabric to get rid of that error. Instead I think we should do nothing if they click on local_fabric and it's not started, or we should provide a more useful error message

This message is specific to when the local_fabric has been torndown and there aren't any identities in the wallet yet.

**Comment by heatherlp** [comment]
If local_fabric has been created, but is stopped, i.e. there is an identity in a wallet, what happens is worse. It tries to connect, fails and we get a grpc error "Failed to connect before the deadline URL:grpc://localhost:17051"

**Comment by cazfletch** [comment]
We should check then if it is running before trying to connect

**Comment by SamRasha** [comment]
Fixes merged so closing

**Comment by sekarbala123** [comment]
Today I see there is no default admin Identity created in the local_fabric_wallet. Unable to create new identity in the local-fabric_wallet as well.

**Comment by Jakeeyturner** [comment]
> Today I see there is no default admin Identity created in the local_fabric_wallet. Unable to create new identity in the local-fabric_wallet as well.

Hi @sekarbala123,

You need to start the Local Fabric environment before the admin identity is created and placed in the `local_fabric_wallet`

**Comment by banatara** [comment]
Thanks Team, I found the issue, I have run the local fabric sample containers in my local, due to which vscode fabric extension does not work properly even after tear down and restart. Once I clean up docker containers externally and restart, it worked.
