### ISSUE TITLE
Bring the Blockchain output channel to focus when starting local_fabric

### ISSUE THREAD

**Issue by jt-nti** [IBM-Blockchain/blockchain-vscode-extension#865]
## Description
Starting local_fabric can take some time and, apart from the status (below), it's not clear whether it's everything is going ok or not

![image](https://user-images.githubusercontent.com/3535067/56891725-5b7ac080-6a75-11e9-8308-129690af563e.png)

## Expected Behavior
There is more detailed information in the Blockchain output channel which it would be useful to show

## Actual Behavior
It can look like nothing is actually happening unless you know where to look

## Possible Fix
Bring the Blockchain output channel to focus when starting local_fabric

## Steps to Reproduce

1. Start local fabric
2. Wait

**Comment by SamRasha** [comment]
Completed so closing
