### ISSUE TITLE
Tearing down fabric runtime in dev mode does not reset the dev mode icon

### ISSUE THREAD

**Issue by liam-grace** [IBM-Blockchain/blockchain-vscode-extension#877]
## Description
Tearing down fabric runtime does not reset the dev mode status of the peer/gateway, so when the fabric runtime is restarted, the UI reports being in the wrong mode 

## Expected Behavior

There are 2 options:
1. The fabric runtime is always started in 'normal' mode and the UI reflects that
2. The fabric runtime starts in the same mode as the last runtime to be torn down

## Your Environment

* IBM Blockchain Platform Extension Version:
* Visual Studio Code version: 1.33.1
* Environment name and version Node.js v8.15.0, npm v6.4.1
* Operating System and version: MacOS 10.14.4

**Comment by heatherlp** [comment]
I think we figured out in the testing session that this is a fabric thing? The environment variable that is set for dev mode persists?
