### ISSUE TITLE
Clean up the names of the configuration settings

### ISSUE THREAD

**Issue by sstone1** [IBM-Blockchain/blockchain-vscode-extension#880]
The extension currently has quite a few configuration settings:

```
    "fabric.runtime": {
        "ports": {
            "orderer": 17050,
            "peerRequest": 17051,
            "peerChaincode": 17052,
            "peerEventHub": 17053,
            "certificateAuthority": 17054,
            "couchDB": 17055,
            "logs": 17056
        },
        "developmentMode": false
    },
    "fabric.gateways": [],
    "fabric.wallets": [],
    "blockchain.ext.directory": "~/.fabric-vscode",
    "extension.home.showOnStartup": true,
    "blockchain.repositories": []
```

These names are mixed in with all other configuration settings from all other extensions. They're not in a namespace for our extension. It would be better if these names were consistent - for example, a single `ibm-blockchain-platform` prefix?

The worst offender is `"extension.home.showOnStartup"` which doesn't mention blockchain, fabric, or IBM. It could be from any extension!

v1.0.0 is our chance to get this right, so we should change it before GA.

**Comment by heatherlp** [comment]
I still hate the idea of all our old contributions hanging around user settings though :(

**Comment by heatherlp** [comment]
I am pro them being consistent :)

**Comment by Jakeeyturner** [comment]
```
"ibm-blockchain-platform.fabric.runtime": {},
"ibm-blockchain-platform.fabric.gateways": [],
"ibm-blockchain-platform.fabric.wallets": [],
"ibm-blockchain-platform.ext.directory": "~/.fabric-vscode",
"ibm-blockchain-platform.ext.repositories": [],
"ibm-blockchain-platform.home.showOnStartup": true
```

How about this?
