### ISSUE TITLE
Tutorials Improvements

### ISSUE THREAD

**Issue by EdMoffatt** [IBM-Blockchain/blockchain-vscode-extension#897]
List of improvements that could/should be made to tutorials (based on testing sessions):

- Sort the scroll position when moving to another tutorial
- Keep previous tutorials open in tabs
- Change the names of the tutorial files to something better
- Pretty sure I stop giving command-palette alternatives at some point! Definitely there are none in Tutorial 3!

**Comment by nklincoln** [comment]
If I double click on the preview, it takes me to the raw file at the location I double-clicked ... can this be disabled?

**Comment by RiehaB** [comment]
Is it possible to make the tutorial remember what dropdown you had open when you go back to the tab, as opposed to having them all closed?

**Comment by Jakeeyturner** [comment]
**Tutorial 1**
_Took 14 minutes_

- All references of `myChannel` should be `mychannel`
- `ca.example.com` should be `ca.org1.example.com`
- We should format/highlight ‘createMyAsset’ in Step 7 > Step 3
- `Successful submitTransaction` is a bad popup window message - we should change it
- Step 7 > Step 4 - should mention to press `Submit Transaction`

**Comment by heatherlp** [comment]
Some assumptions about what is required at the start of each tutorial, so people can jump to start with tutorial 2, but know what they need to to do that

**Comment by EdMoffatt** [comment]
Seems pretty common that the "next tutorial" link doesn't work :'(

**Comment by RiehaB** [comment]
Apart from finding the existing tutorial gallery tab, there's no way of going back to that page from the individual tutorial page.

**Comment by simran-sohanpal** [comment]
- Tutorial 1, Step 1: on the last step (when asked to open src/my-asset-contract.ts) a new panel opens and closes the tutorial + when you navigate back to the tutorial tab, its closed the steps and taken you to the top of the tutorial
- Starting up local fabric runtime took some time, maybe give a prompt to say there might be a wait time but everything is fine?
- At the end of Tutorial 1, clicking 'next tutorial' does nothing
- Scroll of Tutorial 1 panel goes down past the content
- Would you want to open the next tutorial in a new tab or just replace the previously opened tutorial?
- Tutorial 3, Step 3: the enrollment id and secret is different to what is provided by the tutorial on cloud.ibm.com, so if you follow that tutorial you'll get a bit lost if you don't remember what you put in...
