### ISSUE TITLE
Smart contract package doesn't show in view

### ISSUE THREAD

**Issue by Tobias-Hunter** [IBM-Blockchain/blockchain-vscode-extension#902]
Smart contract package doesn't show in the view however its in the `packages` directory!

I would expect the smart contract that has been packaged to appear in the `Smart Contract Packages` view

<img width="1680" alt="Screenshot 2019-05-03 at 10 37 17" src="https://user-images.githubusercontent.com/25635381/57130066-47de9b00-6d90-11e9-9a65-4803a5c70731.png">

**Comment by Tobias-Hunter** [comment]
Might be something to do with this error 🤷🏻‍♂️
![image](https://user-images.githubusercontent.com/25635381/57131489-6f376700-6d94-11e9-9a12-6ce3c2cc155f.png)

**Comment by sstone1** [comment]
@Tobias-Hunter can you run `ls -lartR ~/.fabric-vscode/packages` and paste the output in here please? Looks like you have something that is not a package in that directory.
