### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by mrsetia1** [IBM-Blockchain/blockchain-vscode-extension#920]
- Issue Type: `Performance`
- Extension Name: `ibm-blockchain-platform`
- Extension Version: `0.4.0`
- OS Version: `Windows_NT x64 10.0.17134`
- VSCode version: `1.33.1`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`C:\Users\rizal\IBMBlockchain.ibm-blockchain-platform-unresponsive.cpuprofile.txt`

Find more details here: https://github.com/Microsoft/vscode/wiki/Explain:-extension-causes-high-cpu-load

**Comment by cazfletch** [comment]
closing as no response
