### ISSUE TITLE
Unable to upgrade Smart Contract in Step 8 of ibm-blockchain-platform-vscode-smart-contract Tutorial

### ISSUE THREAD

**Issue by singhrajgithub** [IBM-Blockchain/blockchain-vscode-extension#921]
## Description

I followed https://developer.ibm.com/tutorials/ibm-blockchain-platform-vscode-smart-contract/ tutorial and it worked fine for me until step 8. I stuck at  step 8 sub steps 8.3 and 8.4 . Unable to upgrade smart contract.

## Expected Behavior
Smart contract upgrade should have been completed.

## Actual Behavior
I updated smart contract , version in package.json to "version": "0.0.2" . Now when i tried to upgrade Smart Contract  it did not work instead the extension is showing message like packaging the smart contract , this does not stops until i explicitly close it. After some time under Problems tab in VSCode i could see below error getting populated

String does not match the pattern of "^(?:@[a-z0-9-~][a-z0-9-._~]*/)?[a-z0-9-~][a-z0-9-._~]*$".

In blockchain.log file i could find below message : 
[5/5/2019 7:30:29 AM] [ERROR] Error upgrading smart contract: spawn ENOMEM

## Possible Fix
According to me i think the version of the smart contract package did not get updated to version 0.0.2 after upgrading it. So i feel this could be the cause but i am unable to fix it.

## Steps to Reproduce

1. Follow the tutorial until steps 8.
2. Copy and paste the following code into your lib/my-contract.js file:
3. Update the package.json file such that line 3, which contains the version number to  "version": "0.0.2".
4. To upgrade your existing smart contract to the new version, under LOCAL FABRIC OPS
expand Instantiated until you see demoContract@0.0.1. Next, right-click on demoContract and choose Upgrade Smart Contract.

So for  me it is failing at step 4.

## Log File

[Blockchainlog.txt](https://github.com/IBM-Blockchain/blockchain-vscode-extension/files/3145647/Blockchainlog.txt)

* IBM Blockchain Platform Extension Version: 0.4.0
Version: 1.33.1
Commit: 51b0b28134d51361cf996d2f0a1c698247aeabd8
Date: 2019-04-11T08:20:22.771Z
Electron: 3.1.6
Chrome: 66.0.3359.181
Node.js: 10.2.0
V8: 6.6.346.32
OS: Linux x64 4.15.0-48-generic

Please find attached snapshots of VSCode .
![Screenshot from 2019-05-05 07-07-42](https://user-images.githubusercontent.com/24280813/57195654-c7c45b00-6f72-11e9-8d3f-6f8e58d99114.png)
![Screenshot from 2019-05-05 07-07-25](https://user-images.githubusercontent.com/24280813/57195655-c7c45b00-6f72-11e9-898f-ffb39bd1d90e.png)

**Comment by cazfletch** [comment]
Hi @singhrajgithub from the log you attached it looked like the upgrade failed as it ran out of memory `[ERROR] Error upgrading smart contract: spawn ENOMEM`. Do you need to give your docker more memory?

**Comment by singhrajgithub** [comment]
Hi @cazfletch Thanks for responding. I am not sure how to allocate more memory to docker. I would need to figure out on this point . As of now i am using ubuntu 18.04 on Vmware tools.  Do you know how to do it ?

I did notice many gif files in my package . I found out that in tutorial step 7 says below :
- Later in the tutorial, we will query the network. To do this we will need some scripts. Clone this Github Repo outside of your smart contract directory to get the necessary scripts required to query the network.
- $ git clone https://github.com/horeaporutiu/VSCodeTutorialBlockchain 
- Import this folder into your VSCode workspace by right-clicking an empty space under your smart contract directory in VSCode and selecting Add folder to workspace. Find the recently cloned folder VSCodeTutorialBlockchain and double-click it.

I believe this is the cause of of gif files coming to the package directory. VSCodeTutorialBlockchain folder contains doc folder where these gif files exist. Do you have any idea on this ?

I would try it again after cleaning workspace.

**Comment by cazfletch** [comment]
Which version of the extension do you have?

**Comment by singhrajgithub** [comment]
it's 0.4.0 as per change log of the extension.

**Comment by cazfletch** [comment]
@singhrajgithub can you try following the new tutorial inside VS Code, its an updated version of that tutorial?

**Comment by singhrajgithub** [comment]
sure @cazfletch , i will have a look at it. I could see latest release is v1.0.0 . 
Thanks for your help.

**Comment by cazfletch** [comment]
@singhrajgithub did that tutorial work for you?

**Comment by cazfletch** [comment]
closing as no response

**Comment by singhrajgithub** [comment]
Apologies could not reply earlier. It had worked for me.

Thanks for helping me..
