### ISSUE TITLE
Enable extension to support json identiities

### ISSUE THREAD

**Issue by cazfletch** [IBM-Blockchain/blockchain-vscode-extension#926]
The format for identities that are exported from ibp is a json file. We should enable vscode to support importing this type of identity as well as pem files and enroll id and secret

**Comment by EdMoffatt** [comment]
Capturing some discussion from Slack, reviewing the PR...

Me:
Woohoo!
Yeah, that looks good :slightly_smiling_face: I think we should do a little tweak…
Given we replaced entering paths with browsing for files on both the certs + json options…
![image](https://user-images.githubusercontent.com/7454304/60030156-6418fd00-969a-11e9-9e7f-ce8caf5bdbb6.png)
Maybe we should go with “Provide” on all 3
I reckon calling it “a json identity file” is probably the most accurate naming I know of for it right now lol

**Comment by heatherlp** [comment]
Done in #1075
