### ISSUE TITLE
Generated JavaScript tests contain eslint errors

### ISSUE THREAD

**Issue by liam-grace** [IBM-Blockchain/blockchain-vscode-extension#927]
## Description

Generated tests do not run when `npm test` is run due to eslint errors
e.g.
```
102:32  error  'submitTransaction' was used before it was defined  no-use-before-define
```

## Expected Behavior

Tests should pass as soon as they are generated (or at least once the the TODO's are complete)

## Actual Behavior

`hasLocalhostURLs` and `submitTransaction` give an eslint error since they are used before they are defined

**Comment by cazfletch** [comment]
Think this might be fixed by #827

**Comment by cazfletch** [comment]
check if this is actually fixed

**Comment by lquintai** [comment]
No further eslint errors on JavaScript tests of TypeScript contract, or JavaScript unittests of JavaScript contract.

The current eslint (no-unused-vars) on JavaScript functional tests for JavaScript contracts are WAD.
