### ISSUE TITLE
Toggle Dev Mode - Display error

### ISSUE THREAD

**Issue by rthatcher** [IBM-Blockchain/blockchain-vscode-extension#928]
Testing latest **v1.0.0** extension version, on **Ubuntu 18.04**, VS Code version **1.32.3**

I have a New Project (and no package or installed/instantiated code).
When I toggle dev mode I get this error message, but all seems happy (apart from the message)
<img width="530" alt="image" src="https://user-images.githubusercontent.com/29195399/57307976-65d43480-70dd-11e9-80d8-e2534c949a75.png">

**Comment by heatherlp** [comment]
Hi @rthatcher can you reliably recreate this?

**Comment by rthatcher** [comment]
Using the Market Place version (1.0.0) of the extension I now see different Notifications when toggling Development Mode.
![image](https://user-images.githubusercontent.com/29195399/58111736-f173b800-7be9-11e9-9a70-590665dba3c8.png)

I'm running with a VM rather than natively, so I see slightly slower performance than native users, but I have a relatively new machine with an i7 processor and an SSD drive.

I have seen these messages each time I have Toggled Development Mode today.

**Comment by cazfletch** [comment]
this will be solved by #877

**Comment by Jakeeyturner** [comment]
Issue fixed as a result of removing development mode in PR #1043
