### ISSUE TITLE
When Restarting Debug, the Blockchain Box Graphic to select a function disappears

### ISSUE THREAD

**Issue by rthatcher** [IBM-Blockchain/blockchain-vscode-extension#929]
Testing latest **v1.0.0 extension** version, on **Ubuntu 18.04**, VS Code version **1.32.3**

When Restarting Debug with the green recirculating arrow, the Blockchain Box Graphic to select a function disappears.

Stopping Debug, and starting from the debug window restores the Blockchain Box Graphic for me.

**Comment by heatherlp** [comment]
I can recreate this on v1.0.0/MacOS
