### ISSUE TITLE
Warn/block users from reloading VSCode window when tutorial is open

### ISSUE THREAD

**Issue by sstone1** [IBM-Blockchain/blockchain-vscode-extension#948]
If you follow a tutorial, and you create a new project, and you choose an option that causes VSCode to reload (e.g. open in current window) - the tutorial disappears. Can we warn them with a yes/no "are you sure" prompt, or remove the options that cause this to happen, when viewing a tutorial?

**Comment by cazfletch** [comment]
Can we make VSCode remember that the tutorial is open some how?

**Comment by SamRasha** [comment]
Hi @cazfletch I tried to use vscode.window.viewTextEditors (I believe it was to my recollection) but it wasn’t showing me the tutorials, or many of my open windows in fact. I had opened for example the extension home page, a tutorial and multiple files from a generated smart contract project, and it showed limited ones when printing out the results
