### ISSUE TITLE
Problems in default TypeScript Smart Contract Project

### ISSUE THREAD

**Issue by m-g-k** [IBM-Blockchain/blockchain-vscode-extension#958]
After running the "Create Smart Contract Project Command" on Windows to generate a TypeScript project, if you open the generated file "*.spec.ts" there will be a number of problems shown:

![image](https://user-images.githubusercontent.com/11261488/57518124-453ff080-7310-11e9-86e3-cee803d0bf20.png)

To remove these problems I need to run the following commands to make the types available:

npm i @types/mocha
npm i @types/chai-as-promised
npm i @types/Winston

I would have expected the extension to have already imported these types so that there are no problems in this file or the project by default.

**Comment by cazfletch** [comment]
@sstone1 @mbwhite have you seen this issue on windows?

**Comment by m-g-k** [comment]
FYI, I also see this on Linux

**Comment by cazfletch** [comment]
are you using a version of the extension from the market place or one that you have installed from a vsix? If you have previously used a vsix you might need to remove it from the .vscode folder

**Comment by m-g-k** [comment]
Installed from the marketplace

**Comment by m-g-k** [comment]
Done a little bit more debugging with @cazfletch and it looks like the npm install is failing, but I'm not sure why. From the npm install log:

0 info it worked if it ends with ok
1 verbose cli [ '/home/blockchain/.nvm/versions/node/v8.15.0/bin/node',
1 verbose cli   '/home/blockchain/.nvm/versions/node/v8.15.0/bin/npm',
1 verbose cli   'install',
1 verbose cli   'grpc@1.17.0-pre1',
1 verbose cli   '--ignore-scripts' ]
2 info using npm@6.4.1
3 info using node@v8.15.0
4 verbose npm-session 9f17aa8c4be04f2d
5 silly install loadCurrentTree
6 silly install readLocalPackageData
7 http fetch GET 200 https://registry.npmjs.org/grpc 13ms (from cache)
8 silly pacote version manifest for grpc@1.17.0-pre1 fetched in 24ms
9 timing stage:loadCurrentTree Completed in 155ms
10 silly install loadIdealTree
11 silly install cloneCurrentTreeToIdealTree
12 timing stage:loadIdealTree:cloneCurrentTree Completed in 0ms
13 silly install loadShrinkwrap
14 timing stage:loadIdealTree:loadShrinkwrap Completed in 109ms
15 silly install loadAllDepsIntoIdealTree
16 silly resolveWithNewModule grpc@1.17.0-pre1 checking installable status
17 silly tarball trying https://registry.npmjs.org/grpc/-/grpc-1.17.0-pre1.tgz by hash: sha512-LWoGYW+ylOo2Ldvq/1i/SEwDsIxmDEJK9KoHPHEQkkwdG5zC+9D3/wJsgf/JFvpUoHrPdzLfBUqxfzRVCR90jw==
18 warn tar invalid entry
19 warn tar invalid entry
20 warn tar invalid entry
21 warn tar invalid entry
22 warn tar invalid entry
23 warn tar invalid entry
24 warn tar invalid entry
25 warn tar invalid entry
26 warn tar invalid entry
27 warn tar invalid entry
28 warn tar invalid entry
29 warn tar invalid entry
30 warn tar invalid entry
… [several 1000 identical lines removed] …
3984 warn tar invalid entry
3985 warn tar invalid entry
3986 warn tar invalid entry
3987 warn tar zlib: unexpected end of file
3988 silly removeObsoleteDep removing grpc@1.17.0 from the tree as its been replaced by a newer version or is no longer required
3989 silly removeObsoleteDep removing lodash.camelcase@4.3.0 from the tree as its been replaced by a newer version or is no longer required
3990 silly removeObsoleteDep removing lodash.clone@4.5.0 from the tree as its been replaced by a newer version or is no longer required
3991 silly removeObsoleteDep removing nan@2.13.2 from the tree as its been replaced by a newer version or is no longer required
3992 silly removeObsoleteDep removing node-pre-gyp@0.12.0 from the tree as its been replaced by a newer version or is no longer required
3993 silly removeObsoleteDep removing detect-libc@1.0.3 from the tree as its been replaced by a newer version or is no longer required
3994 silly removeObsoleteDep removing mkdirp@0.5.1 from the tree as its been replaced by a newer version or is no longer required
3995 silly removeObsoleteDep removing minimist@0.0.8 from the tree as its been replaced by a newer version or is no longer required
3996 silly removeObsoleteDep removing needle@2.2.4 from the tree as its been replaced by a newer version or is no longer required
3997 silly removeObsoleteDep removing debug@2.6.9 from the tree as its been replaced by a newer version or is no longer required
3998 silly removeObsoleteDep removing ms@2.0.0 from the tree as its been replaced by a newer version or is no longer required
3999 silly removeObsoleteDep removing iconv-lite@0.4.24 from the tree as its been replaced by a newer version or is no longer required
4000 silly removeObsoleteDep removing safer-buffer@2.1.2 from the tree as its been replaced by a newer version or is no longer required
4001 silly removeObsoleteDep removing sax@1.2.4 from the tree as its been replaced by a newer version or is no longer required
4002 silly removeObsoleteDep removing nopt@4.0.1 from the tree as its been replaced by a newer version or is no longer required
4003 silly removeObsoleteDep removing abbrev@1.1.1 from the tree as its been replaced by a newer version or is no longer required
4004 silly removeObsoleteDep removing osenv@0.1.5 from the tree as its been replaced by a newer version or is no longer required
4005 silly removeObsoleteDep removing os-homedir@1.0.2 from the tree as its been replaced by a newer version or is no longer required
4006 silly removeObsoleteDep removing os-tmpdir@1.0.2 from the tree as its been replaced by a newer version or is no longer required
4007 silly removeObsoleteDep removing npm-packlist@1.1.12 from the tree as its been replaced by a newer version or is no longer required
4008 silly removeObsoleteDep removing ignore-walk@3.0.1 from the tree as its been replaced by a newer version or is no longer required
4009 silly removeObsoleteDep removing minimatch@3.0.4 from the tree as its been replaced by a newer version or is no longer required
4010 silly removeObsoleteDep removing brace-expansion@1.1.11 from the tree as its been replaced by a newer version or is no longer required
4011 silly removeObsoleteDep removing balanced-match@1.0.0 from the tree as its been replaced by a newer version or is no longer required
4012 silly removeObsoleteDep removing concat-map@0.0.1 from the tree as its been replaced by a newer version or is no longer required
4013 silly removeObsoleteDep removing npm-bundled@1.0.5 from the tree as its been replaced by a newer version or is no longer required
4014 silly removeObsoleteDep removing npmlog@4.1.2 from the tree as its been replaced by a newer version or is no longer required
4015 silly removeObsoleteDep removing are-we-there-yet@1.1.5 from the tree as its been replaced by a newer version or is no longer required
4016 silly removeObsoleteDep removing delegates@1.0.0 from the tree as its been replaced by a newer version or is no longer required
4017 silly removeObsoleteDep removing readable-stream@2.3.6 from the tree as its been replaced by a newer version or is no longer required
4018 silly removeObsoleteDep removing core-util-is@1.0.2 from the tree as its been replaced by a newer version or is no longer required
4019 silly removeObsoleteDep removing inherits@2.0.3 from the tree as its been replaced by a newer version or is no longer required
4020 silly removeObsoleteDep removing isarray@1.0.0 from the tree as its been replaced by a newer version or is no longer required
4021 silly removeObsoleteDep removing process-nextick-args@2.0.0 from the tree as its been replaced by a newer version or is no longer required
4022 silly removeObsoleteDep removing safe-buffer@5.1.2 from the tree as its been replaced by a newer version or is no longer required
4023 silly removeObsoleteDep removing string_decoder@1.1.1 from the tree as its been replaced by a newer version or is no longer required
4024 silly removeObsoleteDep removing util-deprecate@1.0.2 from the tree as its been replaced by a newer version or is no longer required
4025 silly removeObsoleteDep removing console-control-strings@1.1.0 from the tree as its been replaced by a newer version or is no longer required
4026 silly removeObsoleteDep removing gauge@2.7.4 from the tree as its been replaced by a newer version or is no longer required
4027 silly removeObsoleteDep removing aproba@1.2.0 from the tree as its been replaced by a newer version or is no longer required
4028 silly removeObsoleteDep removing has-unicode@2.0.1 from the tree as its been replaced by a newer version or is no longer required
4029 silly removeObsoleteDep removing object-assign@4.1.1 from the tree as its been replaced by a newer version or is no longer required
4030 silly removeObsoleteDep removing signal-exit@3.0.1 from the tree as its been replaced by a newer version or is no longer required
4031 silly removeObsoleteDep removing string-width@1.0.2 from the tree as its been replaced by a newer version or is no longer required
4032 silly removeObsoleteDep removing code-point-at@1.1.0 from the tree as its been replaced by a newer version or is no longer required
4033 silly removeObsoleteDep removing is-fullwidth-code-point@1.0.0 from the tree as its been replaced by a newer version or is no longer required
4034 silly removeObsoleteDep removing number-is-nan@1.0.1 from the tree as its been replaced by a newer version or is no longer required
4035 silly removeObsoleteDep removing strip-ansi@3.0.1 from the tree as its been replaced by a newer version or is no longer required
4036 silly removeObsoleteDep removing ansi-regex@2.1.1 from the tree as its been replaced by a newer version or is no longer required
4037 silly removeObsoleteDep removing wide-align@1.1.3 from the tree as its been replaced by a newer version or is no longer required
4038 silly removeObsoleteDep removing set-blocking@2.0.0 from the tree as its been replaced by a newer version or is no longer required
4039 silly removeObsoleteDep removing rc@1.2.8 from the tree as its been replaced by a newer version or is no longer required
4040 silly removeObsoleteDep removing deep-extend@0.6.0 from the tree as its been replaced by a newer version or is no longer required
4041 silly removeObsoleteDep removing ini@1.3.5 from the tree as its been replaced by a newer version or is no longer required
4042 silly removeObsoleteDep removing minimist@1.2.0 from the tree as its been replaced by a newer version or is no longer required
4043 silly removeObsoleteDep removing strip-json-comments@2.0.1 from the tree as its been replaced by a newer version or is no longer required
4044 silly removeObsoleteDep removing rimraf@2.6.2 from the tree as its been replaced by a newer version or is no longer required
4045 silly removeObsoleteDep removing glob@7.1.3 from the tree as its been replaced by a newer version or is no longer required
4046 silly removeObsoleteDep removing fs.realpath@1.0.0 from the tree as its been replaced by a newer version or is no longer required
4047 silly removeObsoleteDep removing inflight@1.0.6 from the tree as its been replaced by a newer version or is no longer required
4048 silly removeObsoleteDep removing once@1.4.0 from the tree as its been replaced by a newer version or is no longer required
4049 silly removeObsoleteDep removing wrappy@1.0.2 from the tree as its been replaced by a newer version or is no longer required
4050 silly removeObsoleteDep removing path-is-absolute@1.0.1 from the tree as its been replaced by a newer version or is no longer required
4051 silly removeObsoleteDep removing semver@5.6.0 from the tree as its been replaced by a newer version or is no longer required
4052 silly removeObsoleteDep removing tar@4.4.8 from the tree as its been replaced by a newer version or is no longer required
4053 silly removeObsoleteDep removing chownr@1.1.1 from the tree as its been replaced by a newer version or is no longer required
4054 silly removeObsoleteDep removing fs-minipass@1.2.5 from the tree as its been replaced by a newer version or is no longer required
4055 silly removeObsoleteDep removing minipass@2.3.5 from the tree as its been replaced by a newer version or is no longer required
4056 silly removeObsoleteDep removing yallist@3.0.3 from the tree as its been replaced by a newer version or is no longer required
4057 silly removeObsoleteDep removing minizlib@1.2.1 from the tree as its been replaced by a newer version or is no longer required
4058 silly removeObsoleteDep removing protobufjs@5.0.3 from the tree as its been replaced by a newer version or is no longer required
4059 silly removeObsoleteDep removing ascli@1.0.1 from the tree as its been replaced by a newer version or is no longer required
4060 silly removeObsoleteDep removing colour@0.7.1 from the tree as its been replaced by a newer version or is no longer required
4061 silly removeObsoleteDep removing optjs@3.2.2 from the tree as its been replaced by a newer version or is no longer required
4062 silly removeObsoleteDep removing bytebuffer@5.0.1 from the tree as its been replaced by a newer version or is no longer required
4063 silly removeObsoleteDep removing long@3.2.0 from the tree as its been replaced by a newer version or is no longer required
4064 silly removeObsoleteDep removing glob@7.1.4 from the tree as its been replaced by a newer version or is no longer required
4065 silly removeObsoleteDep removing fs.realpath@1.0.0 from the tree as its been replaced by a newer version or is no longer required
4066 silly removeObsoleteDep removing inflight@1.0.6 from the tree as its been replaced by a newer version or is no longer required
4067 silly removeObsoleteDep removing once@1.4.0 from the tree as its been replaced by a newer version or is no longer required
4068 silly removeObsoleteDep removing wrappy@1.0.2 from the tree as its been replaced by a newer version or is no longer required
4069 silly removeObsoleteDep removing minimatch@3.0.4 from the tree as its been replaced by a newer version or is no longer required
4070 silly removeObsoleteDep removing brace-expansion@1.1.11 from the tree as its been replaced by a newer version or is no longer required
4071 silly removeObsoleteDep removing balanced-match@1.0.0 from the tree as its been replaced by a newer version or is no longer required
4072 silly removeObsoleteDep removing concat-map@0.0.1 from the tree as its been replaced by a newer version or is no longer required
4073 silly removeObsoleteDep removing path-is-absolute@1.0.1 from the tree as its been replaced by a newer version or is no longer required
4074 silly removeObsoleteDep removing yargs@3.32.0 from the tree as its been replaced by a newer version or is no longer required
4075 silly removeObsoleteDep removing camelcase@2.1.1 from the tree as its been replaced by a newer version or is no longer required
4076 silly removeObsoleteDep removing cliui@3.2.0 from the tree as its been replaced by a newer version or is no longer required
4077 silly removeObsoleteDep removing string-width@1.0.2 from the tree as its been replaced by a newer version or is no longer required
4078 silly removeObsoleteDep removing code-point-at@1.1.0 from the tree as its been replaced by a newer version or is no longer required
4079 silly removeObsoleteDep removing is-fullwidth-code-point@1.0.0 from the tree as its been replaced by a newer version or is no longer required
4080 silly removeObsoleteDep removing number-is-nan@1.0.1 from the tree as its been replaced by a newer version or is no longer required
4081 silly removeObsoleteDep removing strip-ansi@3.0.1 from the tree as its been replaced by a newer version or is no longer required
4082 silly removeObsoleteDep removing ansi-regex@2.1.1 from the tree as its been replaced by a newer version or is no longer required
4083 silly removeObsoleteDep removing wrap-ansi@2.1.0 from the tree as its been replaced by a newer version or is no longer required
4084 silly removeObsoleteDep removing decamelize@1.2.0 from the tree as its been replaced by a newer version or is no longer required
4085 silly removeObsoleteDep removing os-locale@1.4.0 from the tree as its been replaced by a newer version or is no longer required
4086 silly removeObsoleteDep removing lcid@1.0.0 from the tree as its been replaced by a newer version or is no longer required
4087 silly removeObsoleteDep removing invert-kv@1.0.0 from the tree as its been replaced by a newer version or is no longer required
4088 silly removeObsoleteDep removing window-size@0.1.4 from the tree as its been replaced by a newer version or is no longer required
4089 silly removeObsoleteDep removing y18n@3.2.1 from the tree as its been replaced by a newer version or is no longer required
4090 timing stage:rollbackFailedOptional Completed in 1ms
4091 timing stage:runTopLevelLifecycles Completed in 1696ms
4092 silly saveTree test45@0.0.1
4092 silly saveTree ├─┬ @types/chai-as-promised@7.1.0
4092 silly saveTree │ └── @types/chai@4.1.7
4092 silly saveTree ├── @types/chai@4.1.7
4092 silly saveTree ├── @types/mocha@5.2.6
4092 silly saveTree ├─┬ @types/winston@2.4.4
4092 silly saveTree │ └─┬ winston@3.2.1
4092 silly saveTree │   ├─┬ async@2.6.2
4092 silly saveTree │   │ └── lodash@4.17.11
4092 silly saveTree │   ├─┬ diagnostics@1.1.1
4092 silly saveTree │   │ ├─┬ colorspace@1.1.2
4092 silly saveTree │   │ │ ├─┬ color@3.0.0
4092 silly saveTree │   │ │ │ ├─┬ color-convert@1.9.3
4092 silly saveTree │   │ │ │ │ └── color-name@1.1.3
4092 silly saveTree │   │ │ │ └─┬ color-string@1.5.3
4092 silly saveTree │   │ │ │   └─┬ simple-swizzle@0.2.2
4092 silly saveTree │   │ │ │     └── is-arrayish@0.3.2
4092 silly saveTree │   │ │ └── text-hex@1.0.0
4092 silly saveTree │   │ ├─┬ enabled@1.0.2
4092 silly saveTree │   │ │ └── env-variable@0.0.5
4092 silly saveTree │   │ └─┬ kuler@1.0.1
4092 silly saveTree │   │   └── colornames@1.1.1
4092 silly saveTree │   ├── is-stream@1.1.0
4092 silly saveTree │   ├─┬ logform@2.1.2
4092 silly saveTree │   │ ├── colors@1.3.3
4092 silly saveTree │   │ ├── fast-safe-stringify@2.0.6
4092 silly saveTree │   │ ├── fecha@2.3.3
4092 silly saveTree │   │ ├── ms@2.1.1
4092 silly saveTree │   │ └── triple-beam@1.3.0
4092 silly saveTree │   ├── one-time@0.0.4
4092 silly saveTree │   ├─┬ readable-stream@3.3.0
4092 silly saveTree │   │ ├── inherits@2.0.3
4092 silly saveTree │   │ ├─┬ string_decoder@1.2.0
4092 silly saveTree │   │ │ └── safe-buffer@5.1.2
4092 silly saveTree │   │ └── util-deprecate@1.0.2
4092 silly saveTree │   ├── stack-trace@0.0.10
4092 silly saveTree │   ├── triple-beam@1.3.0
4092 silly saveTree │   └─┬ winston-transport@4.3.0
4092 silly saveTree │     └─┬ readable-stream@2.3.6
4092 silly saveTree │       ├── core-util-is@1.0.2
4092 silly saveTree │       ├── isarray@1.0.0
4092 silly saveTree │       ├── process-nextick-args@2.0.0
4092 silly saveTree │       └── string_decoder@1.1.1
4092 silly saveTree ├─┬ fabric-contract-api@1.4.1
4092 silly saveTree │ ├── get-params@0.1.2
4092 silly saveTree │ └── reflect-metadata@0.1.13
4092 silly saveTree └── winston@3.2.1
4093 verbose stack ZlibError: zlib: unexpected end of file
4093 verbose stack     at Zlib.(anonymous function).onerror (/home/blockchain/.nvm/versions/node/v8.15.0/lib/node_modules/npm/node_modules/minizlib/index.js:131:21)
4093 verbose stack     at Unzip.write (/home/blockchain/.nvm/versions/node/v8.15.0/lib/node_modules/npm/node_modules/minizlib/index.js:255:31)
4093 verbose stack     at Unzip.flush (/home/blockchain/.nvm/versions/node/v8.15.0/lib/node_modules/npm/node_modules/minizlib/index.js:222:10)
4093 verbose stack     at Unzip.end (/home/blockchain/.nvm/versions/node/v8.15.0/lib/node_modules/npm/node_modules/minizlib/index.js:229:10)
4093 verbose stack     at Unpack.end (/home/blockchain/.nvm/versions/node/v8.15.0/lib/node_modules/npm/node_modules/tar/lib/parse.js:415:21)
4093 verbose stack     at PassThrough.onend (_stream_readable.js:595:10)
4093 verbose stack     at Object.onceWrapper (events.js:313:30)
4093 verbose stack     at emitNone (events.js:111:20)
4093 verbose stack     at PassThrough.emit (events.js:208:7)
4093 verbose stack     at endReadableNT (_stream_readable.js:1064:12)
4093 verbose stack     at _combinedTickCallback (internal/process/next_tick.js:139:11)
4093 verbose stack     at process._tickCallback (internal/process/next_tick.js:181:9)
4094 verbose cwd /home/blockchain/workspace/test45
4095 verbose Linux 4.4.0-131-generic
4096 verbose argv "/home/blockchain/.nvm/versions/node/v8.15.0/bin/node" "/home/blockchain/.nvm/versions/node/v8.15.0/bin/npm" "install" "grpc@1.17.0-pre1" "--ignore-scripts"
4097 verbose node v8.15.0
4098 verbose npm  v6.4.1
4099 error code Z_BUF_ERROR
4100 error errno -5
4101 error zlib: unexpected end of file
4102 verbose exit [ -5, true ]

**Comment by mbwhite** [comment]
I've never seen this before;  and couldn't think of anything.. but just spotted.

2 info using npm@6.4.1
3 info using node@v8.15.0

Normally the combination would be node@8 and npm@5   node 10 would usually bring in the later npm version... wonder if that could be it..

**Comment by m-g-k** [comment]
Thanks for the tip @mbwhite and thanks for the help @cazfletch. It turns out that I had a corrupted npm cache and clearing that has fixed the problem and the dependencies are automatically installed again, hooray! :-)

Incase anyone else ever gets a similar issue, the command to clear the npm cache that I used was:

npm cache --force clean
