### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by aakzubaidi** [IBM-Blockchain/blockchain-vscode-extension#960]
- Issue Type: `Performance`
- Extension Name: `ibm-blockchain-platform`
- Extension Version: `1.0.0`
- OS Version: `Darwin x64 18.5.0`
- VSCode version: `1.33.1`

:warning: Make sure to **attach** this file from your *home*-directory:
[IBMBlockchain.ibm-blockchain-platform-unresponsive.cpuprofile.txt](https://github.com/IBM-Blockchain/blockchain-vscode-extension/files/3169815/IBMBlockchain.ibm-blockchain-platform-unresponsive.cpuprofile.txt)

:warning:`/Users/aliaalzubaidi/IBMBlockchain.ibm-blockchain-platform-unresponsive.cpuprofile.txt`

Find more details here: https://github.com/Microsoft/vscode/wiki/Explain:-extension-causes-high-cpu-load

**Comment by cazfletch** [comment]
Hi @aakzubaidi what were you doing when this happened?

**Comment by m-g-k** [comment]
The most likely reason is that the fabric sdk is doing a cpu intensive or a lengthy operation underneath the plugin which is causing VS Code to throw this alert. Therefore switching to a language server would probably help this type of issue long term as we would then be in our own process and cannot interfere with other extensions. See this link on the benefits of language servers:

https://code.visualstudio.com/api/language-extensions/language-server-extension-guide

**Comment by m-g-k** [comment]
So, looking at the perf data, if I'm reading it correctly, it looks like the "gatewayExplorer.js" is involved on the largest wait chain of over 5 seconds, during activation. It then goes on to call the FabricRuntime.js on the same chain (out of shot): 

![image](https://user-images.githubusercontent.com/11261488/57630958-7c273800-7596-11e9-9e48-9cc7c2a60ac4.png)

**Comment by cazfletch** [comment]
closing
