### ISSUE TITLE
Exporting the identities from the wallet

### ISSUE THREAD

**Issue by damir-bajramovic** [IBM-Blockchain/blockchain-vscode-extension#961]
Ever since I've received the latest extension update, I can't export the administrator identity from the local wallet of my application. Prior to the update, whenever I exported the connection profile, I would also get the administrator certificate, private and public key - things I need to register new users programmatically and invoke the transactions from my NODE.js applications. I don't want to do that from the command line... 

I am bashing my head for quite a few days now and can't get around it. Please, can you help me with my issue?

**Comment by davidkel** [comment]
As a workaround you can point your wallet in your code to the wallet(s) managed by the VS Code extension. The wallets can be found at $HOME/.fabric-vscode on Linux. Hopefully in similar type of locations for windows/mac

**Comment by heatherlp** [comment]
Hi @damir-bajramovic - would the following issue solve this for you?
https://github.com/IBM-Blockchain/blockchain-vscode-extension/issues/659

**Comment by damir-bajramovic** [comment]
> Hi @damir-bajramovic - would the following issue solve this for you?
> #659

YES! Please. I don't know how is it not possible right now... I did it the other day in the most simplest of manners.

**Comment by heatherlp** [comment]
@damir-bajramovic check out `Export Wallet` in version 1.0.1 and let me know if that covers what you need 👍

**Comment by cazfletch** [comment]
closing as no response
