### ISSUE TITLE
Error when instantiating contract

### ISSUE THREAD

**Issue by Moni-Haimovich** [IBM-Blockchain/blockchain-vscode-extension#962]
This issue started after the last VSC blockchain extension update.
When trying to instantiate a contract on my local fabric ops I'm getting the following error:

[5/13/2019 11:41:53 AM] [INFO] Starting IBM Blockchain Platform Extension
[5/13/2019 11:41:53 AM] [INFO] Migrating local runtime manager
[5/13/2019 11:41:53 AM] [INFO] Initializing local runtime manager
[5/13/2019 11:41:54 AM] [INFO] Registering commands
[5/13/2019 11:41:54 AM] [INFO] IBM Blockchain Platform Extension activated
[5/13/2019 11:42:03 AM] [INFO] instantiateSmartContract
[5/13/2019 11:42:39 AM] [ERROR] Error instantiating smart contract: Error: error starting container: error starting container: Failed to generate platform-specific docker build: Error returned from build: 1 "
> @ampretia/x509@0.4.0 install /chaincode/output/node_modules/@ampretia/x509
> node-gyp rebuild

gyp WARN install got an error, rolling back install
gyp ERR! configure error 
gyp ERR! stack Error: 403 response downloading https://nodejs.org/download/release/v8.11.3/node-v8.11.3-headers.tar.gz
gyp ERR! stack     at Request.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/install.js:210:14)
gyp ERR! stack     at emitOne (events.js:121:20)
gyp ERR! stack     at Request.emit (events.js:211:7)
gyp ERR! stack     at Request.onRequestResponse (/usr/local/lib/node_modules/npm/node_modules/request/request.js:1068:10)
gyp ERR! stack     at emitOne (events.js:116:13)
gyp ERR! stack     at ClientRequest.emit (events.js:211:7)
gyp ERR! stack     at HTTPParser.parserOnIncomingClient (_http_client.js:543:21)
gyp ERR! stack     at HTTPParser.parserOnHeadersComplete (_http_common.js:112:17)
gyp ERR! stack     at TLSSocket.socketOnData (_http_client.js:440:20)
gyp ERR! stack     at emitOne (events.js:116:13)
gyp ERR! System Linux 4.15.0-47-generic
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /chaincode/output/node_modules/@ampretia/x509
gyp ERR! node -v v8.11.3
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok 
npm WARN invioupapercontract@1.0.4 No repository field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @ampretia/x509@0.4.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the @ampretia/x509@0.4.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2019-05-13T08_42_38_254Z-debug.log
"

**Comment by davidkel** [comment]
@Moni-Haimovich The error is saying that the chaincode builder container is unable to contact and download this resource  https://nodejs.org/download/release/v8.11.3/node-v8.11.3-headers.tar.gz
It could be due to networking issues or the nodejs.org server being down temporarily. It could also be a problem with docker itself. If you are running on windows or mac then docker runs a hidden linux VM to run the containers and it could be an issue with that VM

**Comment by Moni-Haimovich** [comment]
@davidkel Thank you for your quick response.
I don't know why it's looking for v8.11.3 (which is not available any more).I'm using v10.15. Any thoughts why it's looking for this old version?

**Comment by davidkel** [comment]
@Moni-Haimovich Fabric 1.4.1 runs node.js chaincode using v8.11.3.

**Comment by Moni-Haimovich** [comment]
@davidkel I'm able to access and download the 8.11.3 headers manually - so I guess it's not a network problem or nodejs.org server issue.
I'm running on ubuntu - so I'm not sure it's a docker issue. The strange thing is that everything worked fine until yesterday.
Any idea?

**Comment by davidkel** [comment]
@Moni-Haimovich It could still be a docker problem.
1. first spin up a chaincode image builder container
`docker run -it hyperledger/fabric-ccenv /bin/bash`
you will get a prompt such as `root@0485d39cae54:/#`
2. on that prompt try the following commands
`node -v` (should be v8.11.3)
`curl -O https://nodejs.org/download/release/v8.11.3/node-v8.11.3-headers.tar.gz`
` tar -xvf https://nodejs.org/download/release/v8.11.3/node-v8.11.3-headers.tar.gz`
if the tar outputs a load of files then it worked. If it fails then
`cat node-v8.11.3-headers.tar.gz`
To look at the output from the curl file.

**Comment by Moni-Haimovich** [comment]
@davidkel
root@67045e0c36df:/# tar -xvf https://nodejs.org/download/release/v8.11.3/node-v8.11.3-headers.tar.gz
tar: Cannot connect to https: resolve failed
root@67045e0c36df:/# cat node-v8.11.3-headers.tar.gz
<!DOCTYPE html>



 <html class="no-js" lang="en-US"> 
<head>
<title>Attention Required! | Cloudflare</title>
<meta name="captcha-bypass" id="captcha-bypass" />
<meta charset="UTF-8" />
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
<meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1" />
<meta name="robots" content="noindex, nofollow" />
<meta name="viewport" content="width=device-width,initial-scale=1,maximum-scale=1" />
<link rel="stylesheet" id="cf_styles-css" href="/cdn-cgi/styles/cf.errors.css" type="text/css" media="screen,projection" />

<style type="text/css">body{margin:0;padding:0}</style>


<script type="text/javascript" src="/cdn-cgi/scripts/zepto.min.js"></script>
<script type="text/javascript" src="/cdn-cgi/scripts/cf.common.js"></script>




</head>
<body>
  <div id="cf-wrapper">
    <div class="cf-alert cf-alert-error cf-cookie-error" id="cookie-alert" data-translate="enable_cookies">Please enable cookies.</div>
    <div id="cf-error-details" class="cf-error-details-wrapper">
      <div class="cf-wrapper cf-header cf-error-overview">
        <h1 data-translate="challenge_headline">One more step</h1>
        <h2 class="cf-subheadline"><span data-translate="complete_sec_check">Please complete the security check to access</span> nodejs.org</h2>
      </div>
      
      <div class="cf-section cf-highlight cf-captcha-container">
        <div class="cf-wrapper">
          <div class="cf-columns two">
            <div class="cf-column">
            
              <div class="cf-highlight-inverse cf-form-stacked">
                <form class="challenge-form" id="challenge-form" action="/cdn-cgi/l/chk_captcha" method="get">
  <input type="hidden" name="s" value="41ffafc33a1082daed504fed7b166ad658ae0899-1557747985-1800-ASUTyhx3RSu8OUsMp1weK4bvBOjaYGk+zEUeqwYArvsPkPMCRxmHCQQCiM8/6F5IMSdMOAx/LSP3aUzzO3RuVZjR1t+nTzvB0FriEhiLmm/kJ0c6rIc6QZyoWq2OlcVi2XpZ4gb2fmdH77b3dkrKG598eBatKFD35LXvkgvfgSloB/CI/nYD550zFlfYmcGNOw=="></input>
  <script type="text/javascript" src="/cdn-cgi/scripts/cf.challenge.js" data-type="normal"  data-ray="4d64644bab9e6b95" async data-sitekey="6LfBixYUAAAAABhdHynFUIMA_sa4s-XsJvnjtgB0"></script>
  <div class="g-recaptcha"></div>
  <noscript id="cf-captcha-bookmark" class="cf-captcha-info">
    <div><div style="width: 302px">
      <div>
        <iframe src="https://www.google.com/recaptcha/api/fallback?k=6LfBixYUAAAAABhdHynFUIMA_sa4s-XsJvnjtgB0" frameborder="0" scrolling="no" style="width: 302px; height:422px; border-style: none;"></iframe>
      </div>
      <div style="width: 300px; border-style: none; bottom: 12px; left: 25px; margin: 0px; padding: 0px; right: 25px; background: #f9f9f9; border: 1px solid #c1c1c1; border-radius: 3px;">
        <textarea id="g-recaptcha-response" name="g-recaptcha-response" class="g-recaptcha-response" style="width: 250px; height: 40px; border: 1px solid #c1c1c1; margin: 10px 25px; padding: 0px; resize: none;"></textarea>
        <input type="submit" value="Submit"></input>
      </div>
    </div></div>
  </noscript>
</form>

                
              </div>
            </div>

            <div class="cf-column">
              <div class="cf-screenshot-container">
              
                <span class="cf-no-screenshot"></span>
              
              </div>
            </div>
          </div>
        </div>
      </div>

      <div class="cf-section cf-wrapper">
        <div class="cf-columns two">
          <div class="cf-column">
            <h2 data-translate="why_captcha_headline">Why do I have to complete a CAPTCHA?</h2>
            
            <p data-translate="why_captcha_detail">Completing the CAPTCHA proves you are a human and gives you temporary access to the web property.</p>
          </div>

          <div class="cf-column">
            <h2 data-translate="resolve_captcha_headline">What can I do to prevent this in the future?</h2>
            

            <p data-translate="resolve_captcha_antivirus">If you are on a personal connection, like at home, you can run an anti-virus scan on your device to make sure it is not infected with malware.</p>

            <p data-translate="resolve_captcha_network">If you are at an office or shared network, you can ask the network administrator to run a scan across the network looking for misconfigured or infected devices.</p>
            
          </div>
        </div>
      </div>
      

      <div class="cf-error-footer cf-wrapper">
  <p>
    <span class="cf-footer-item">Cloudflare Ray ID: <strong>4d64644bab9e6b95</strong></span>
    <span class="cf-footer-separator">&bull;</span>
    <span class="cf-footer-item"><span>Your IP</span>: 216.72.34.217</span>
    <span class="cf-footer-separator">&bull;</span>
    <span class="cf-footer-item"><span>Performance &amp; security by</span> <a href="https://www.cloudflare.com/5xx-error-landing?utm_source=error_footer" id="brand_link" target="_blank">Cloudflare</a></span>
    
  </p>
</div>


    </div>
  </div>

  <script type="text/javascript">
  window._cf_translation = {};
  
  
</script>

</body>
</html>

**Comment by davidkel** [comment]
@Moni-Haimovich Sorry I got the tar command slightly wrong, I have corrected it however there is no need for you to run it. It looks like when your container tries to access the node.js website it's being blocked with a request for you to complete a CAPTCHA. Not sure who is generating that request though, might be something to do with the network you are on.

**Comment by Moni-Haimovich** [comment]
@davidkel
root@67045e0c36df:/# tar -xvf https://nodejs.org/download/release/v8.11.3/node-v8.11.3-headers.tar.gz
tar: Cannot connect to https: resolve failed
root@67045e0c36df:/# cat node-v8.11.3-headers.tar.gz
<!DOCTYPE html>



 <html class="no-js" lang="en-US"> 
<head>
<title>Attention Required! | Cloudflare</title>
<meta name="captcha-bypass" id="captcha-bypass" />
<meta charset="UTF-8" />
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
<meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1" />
<meta name="robots" content="noindex, nofollow" />
<meta name="viewport" content="width=device-width,initial-scale=1,maximum-scale=1" />
<link rel="stylesheet" id="cf_styles-css" href="/cdn-cgi/styles/cf.errors.css" type="text/css" media="screen,projection" />

<style type="text/css">body{margin:0;padding:0}</style>


<script type="text/javascript" src="/cdn-cgi/scripts/zepto.min.js"></script>
<script type="text/javascript" src="/cdn-cgi/scripts/cf.common.js"></script>




</head>
<body>
  <div id="cf-wrapper">
    <div class="cf-alert cf-alert-error cf-cookie-error" id="cookie-alert" data-translate="enable_cookies">Please enable cookies.</div>
    <div id="cf-error-details" class="cf-error-details-wrapper">
      <div class="cf-wrapper cf-header cf-error-overview">
        <h1 data-translate="challenge_headline">One more step</h1>
        <h2 class="cf-subheadline"><span data-translate="complete_sec_check">Please complete the security check to access</span> nodejs.org</h2>
      </div>
      
      <div class="cf-section cf-highlight cf-captcha-container">
        <div class="cf-wrapper">
          <div class="cf-columns two">
            <div class="cf-column">
            
              <div class="cf-highlight-inverse cf-form-stacked">
                <form class="challenge-form" id="challenge-form" action="/cdn-cgi/l/chk_captcha" method="get">
  <input type="hidden" name="s" value="41ffafc33a1082daed504fed7b166ad658ae0899-1557747985-1800-ASUTyhx3RSu8OUsMp1weK4bvBOjaYGk+zEUeqwYArvsPkPMCRxmHCQQCiM8/6F5IMSdMOAx/LSP3aUzzO3RuVZjR1t+nTzvB0FriEhiLmm/kJ0c6rIc6QZyoWq2OlcVi2XpZ4gb2fmdH77b3dkrKG598eBatKFD35LXvkgvfgSloB/CI/nYD550zFlfYmcGNOw=="></input>
  <script type="text/javascript" src="/cdn-cgi/scripts/cf.challenge.js" data-type="normal"  data-ray="4d64644bab9e6b95" async data-sitekey="6LfBixYUAAAAABhdHynFUIMA_sa4s-XsJvnjtgB0"></script>
  <div class="g-recaptcha"></div>
  <noscript id="cf-captcha-bookmark" class="cf-captcha-info">
    <div><div style="width: 302px">
      <div>
        <iframe src="https://www.google.com/recaptcha/api/fallback?k=6LfBixYUAAAAABhdHynFUIMA_sa4s-XsJvnjtgB0" frameborder="0" scrolling="no" style="width: 302px; height:422px; border-style: none;"></iframe>
      </div>
      <div style="width: 300px; border-style: none; bottom: 12px; left: 25px; margin: 0px; padding: 0px; right: 25px; background: #f9f9f9; border: 1px solid #c1c1c1; border-radius: 3px;">
        <textarea id="g-recaptcha-response" name="g-recaptcha-response" class="g-recaptcha-response" style="width: 250px; height: 40px; border: 1px solid #c1c1c1; margin: 10px 25px; padding: 0px; resize: none;"></textarea>
        <input type="submit" value="Submit"></input>
      </div>
    </div></div>
  </noscript>
</form>

                
              </div>
            </div>

            <div class="cf-column">
              <div class="cf-screenshot-container">
              
                <span class="cf-no-screenshot"></span>
              
              </div>
            </div>
          </div>
        </div>
      </div>

      <div class="cf-section cf-wrapper">
        <div class="cf-columns two">
          <div class="cf-column">
            <h2 data-translate="why_captcha_headline">Why do I have to complete a CAPTCHA?</h2>
            
            <p data-translate="why_captcha_detail">Completing the CAPTCHA proves you are a human and gives you temporary access to the web property.</p>
          </div>

          <div class="cf-column">
            <h2 data-translate="resolve_captcha_headline">What can I do to prevent this in the future?</h2>
            

            <p data-translate="resolve_captcha_antivirus">If you are on a personal connection, like at home, you can run an anti-virus scan on your device to make sure it is not infected with malware.</p>

            <p data-translate="resolve_captcha_network">If you are at an office or shared network, you can ask the network administrator to run a scan across the network looking for misconfigured or infected devices.</p>
            
          </div>
        </div>
      </div>
      

      <div class="cf-error-footer cf-wrapper">
  <p>
    <span class="cf-footer-item">Cloudflare Ray ID: <strong>4d64644bab9e6b95</strong></span>
    <span class="cf-footer-separator">&bull;</span>
    <span class="cf-footer-item"><span>Your IP</span>: 216.72.34.217</span>
    <span class="cf-footer-separator">&bull;</span>
    <span class="cf-footer-item"><span>Performance &amp; security by</span> <a href="https://www.cloudflare.com/5xx-error-landing?utm_source=error_footer" id="brand_link" target="_blank">Cloudflare</a></span>
    
  </p>
</div>


    </div>
  </div>

  <script type="text/javascript">
  window._cf_translation = {};
  
  
</script>

</body>
</html>

**Comment by Moni-Haimovich** [comment]
Thank you it was a network issue
