### ISSUE TITLE
Provide a dropdown for non local fabric wallets for MSPids when adding identities

### ISSUE THREAD

**Issue by davidkel** [IBM-Blockchain/blockchain-vscode-extension#966]
For non local fabric wallets when adding identities when asked for MSPid it should present a dropdown with all the mspids defined in the non-local connection profiles added to the fabric-gateways but also allow the ability for users to enter a completely different mspid. 
This differs from the local_wallet version where it won't make sense to allow the user to enter their own as the local_fabric wallet is only used with the local_fabric provided by the extension and thus will know all the organisations available to that network.

**Comment by EdMoffatt** [comment]
Adding this to the design list for this sprint
