### ISSUE TITLE
As a first time user I'd like help with installing extension prerequisites

### ISSUE THREAD

**Issue by heatherlp** [IBM-Blockchain/blockchain-vscode-extension#967]
Notes here on what this could mean:
- People can get too far without having them all in place, or can get really stuck if they install it and can’t compile gRPC. It seems like it’s difficult to resolve the problem if gRPC fails, you fix the problem, it doesn’t automatically resolve in the IDE. You also need to reinstall the extension.
We should also try to see if we can require grpc at startup and assume we need to rebuild if it won’t load

- We also need to support Node 12

- A windows guy just got stuck with a 32 bit VSCode with a 64 bit Node and a 64 bit grpc and there was no hints as to what the problem was

**Comment by heatherlp** [comment]
I've just done a quick test with node 12 and v1.0.0, instantiating and debugging on a newly created smart contract project so I don't think much (if any) work is needed to support it

**Comment by Jakeeyturner** [comment]
[Prerequisites Hi-Fi.zip](https://github.com/IBM-Blockchain/blockchain-vscode-extension/files/3321208/Prerequisites.Hi-Fi.zip)
