### ISSUE TITLE
Stop users from including a space in smart contract project name

### ISSUE THREAD

**Issue by heatherlp** [IBM-Blockchain/blockchain-vscode-extension#968]
npm install fails if user includes space in smart contract project name

**Comment by Jakeeyturner** [comment]
When packaging a smart contract with the name `1.0.1contract` I get:

```Invalid smart contract name '1.0.1contract'. Smart contract names must only consist of alphanumerics, '_', and '-'```.

This might as well be covered in PR #987 as well!

**Comment by heatherlp** [comment]
I think we definitely need to be smarter about this - the user could select any folder, including `Downloads` or `My Documents` and then they'd have smart contracts named to match.
