### ISSUE TITLE
Errors at end of first tutorial

### ISSUE THREAD

**Issue by EdMoffatt** [IBM-Blockchain/blockchain-vscode-extension#969]
As spotted by John Swanson, tutorial 1 has some repeat steps and confusion in the last bit (my fault for didgily merging some change sets!).  The last bit should be...

...
3. First, we will create an asset.  Right-click on createMyAsset and select Submit Transaction. You will be asked to provide arguments for the transaction: try `["001", "a juicy delicious asset"]` (or whatever key and value you like, but make sure you remember the key you use!).

> Pro Tip: Arguments are submitted as JSON, so make sure you type the inputs exactly as shown, so that you're submitting an array of 2 strings as required by this transaction!

> Command Palette alternative: Submit Transaction

4. You will then be asked to set the transient data for the transaction. Don't worry about that for now we will cover it in a later tutorial. For now just hit Enter.

5. Next, submit updateMyAsset in a similar way. This time, for the arguments, provide the same key and a different value e.g. `["001", "a tremendously delicious asset"]`. So, now the value of key 001 on our ledger should be "a tremendously delicious asset". Lets check that by reading the value back...

6. readMyAsset is for reading from rather than writing to the ledger...
...

I'll do a change for this, just raising it here so I don't forget!

**Comment by cazfletch** [comment]
done so closing
