### ISSUE TITLE
The extension does not generate functional tests in Windows. 

### ISSUE THREAD

**Issue by fdiazluque** [IBM-Blockchain/blockchain-vscode-extension#975]
The extension does not generate functional tests in Windows. 

## Description
I am using this extension on a Windows 10 Enterprise. I can package, install, instantiate, eval and commit transactions without problems, but I can not generate the functional tests from the gateway menu.
## Steps

1. Extension option: "Create a Smart Contract Project", option "typescript"
2. Extension option: "Package a Smart Contract Project"
3. Install and instantiate the smart contract
4. Under gateway menu, over the smart contract, I click on "Generate Tests for Smart Contract", I select Javascript or Javascript, but I only get this message in the Output tab:
```
[15/5/2019 13:09:20] [INFO] testSmartContractCommand
```

## Your Environment
* IBM Blockchain Platform Extension Version: 1.0.0
* Visual Studio Code version: 1.33.1
* Environment name and version (Node.js v8.11.1, npm v6.5.0):
* Operating System and version: Windows Pro Enterprise
* Link to your project: The typescript example project generated by the extension.

**Comment by heatherlp** [comment]
I have a theory about line: https://github.com/IBM-Blockchain/blockchain-vscode-extension/blob/master/client/src/commands/testSmartContractCommand.ts#L128

Gonna generate a sandbox and hoping @mbwhite will test it for me

**Comment by heatherlp** [comment]
Still waiting on some Windows resource from Fyre before I can test this .vsix

**Comment by heatherlp** [comment]
Hi @fdiazluque apologies it has taken me so long to make progress with this - can you just confirm you still can't generate tests on v1.0.3 - there have been changes to the generating smart contract tests code since v1.0.0.

**Comment by heatherlp** [comment]
Unassigning - @fdiazluque let us know if you still hit this problem on a later build

**Comment by lquintai** [comment]
This issue has been fixed as part of other deliveries.

Successfully created and ran functional tests for:
- TypeScript contract - TypeScript functional tests
- TypeScript contract - JavaScript functional tests
- Java contract - Java functional tests

Software versions:
- Windows 10 Enterprise
- VSCode 1.40.2
- IBM Blockchain Platform Extension 1.0.16
- Node.js 8.16.1
- npm 6.4.1
- Docker 19.3.4
- Docker Composer 1.24.1
- C++ Build Tools 5.2.2
- Java OpenJDK 8 1.8.0
